
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/zy.media.min.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/zy.media.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">


<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<title>课程包详情</title>
<style>
    body{
        padding-bottom: 120px;
    }

.playvideo{padding-top: auto;z-index: 99;position: relative;}
    .zy_media{z-index: 99}




</style>
<html>
<body>

    <!-- 遮罩层 -->
    <div class="bgb"></div>
    <div class="playvideo" style="height:56vw">
    <div class="promote_play">
        <span class="promote_left"></span>
        <span class="promote_text">推广赚学费</span>
        <span class="promote_img">
            <img src="<?php echo ROOT_PATH;?>webStyle/images/promote.png" alt="" alt="">
        </span>
    </div>
    <div class="real_play">
        <!-- <div></div> -->
    </div>
    <div class="fake_play">
        
    </div>
    <div class="fake_play_ios">
         
    </div>
    <?php if (isset($data['details_image']) && $data['details_image']){?>
    <img class="cover_play" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
    <img class="cover_img" src="<?php echo ROOT_PATH.UPLOAD_PATH.$data['details_image'];?>" alt="">
    <?php }?>
    <img class="cover_load" src="<?php echo ROOT_PATH;?>webStyle/images/londing.gif" alt="">
    <div class="real_play_black"></div>     
    <div class="zy_media">
     <video style="height:56vw"   autoplay="autoplay" id="videoID" x5-video-player-fullscreen="true" poster=""    >
            <source src="<?php echo $data['play_path']?>" type="video/mp4">
          您的浏览器不支持HTML5视频
     </video> 
    </div>
<div id="modelView">&nbsp;</div>
    </div>

    <div class="run">
        <span><span class="label"><?php echo $data['category']['name']?></span></span>
        <span><?php echo $data['title']?></span>
        <?php if(isset($data['collect']) && $data['collect'] != 1){?>
           <span class="collected" id ="collected">收藏 </span>
        <?php }else{?>
           <span class="collect" id ="collected">已收藏 </span>
        <?php }?>
    </div>
      
    <div class="price">
        <?php if($data['sell_type'] == 1){?>
            <?php if($data['price'] != '0.00' && $data['original_price'] != '0.00'){?>
                <span class=" font_size16 mr10">￥<?php echo $data['price']?></span>
                <span class="font_color_055773">(会员￥<?php echo $data['original_price']?>)</span>
            <?php }else{?>
                <span class=" font_size16 mr10">￥<?php echo $data['price']?></span>
                <span class="font_color_055773">(会员免费)</span>
            <?php }?>
        <?php }else{?>
            <span class=" font_size16 mr10">仅限会员</span>
            <span class="font_color_055773">(会员￥<?php echo $data['original_price']?>)</span>
        <?php }?>
          <span class="fr mr10">
            <span class="font_color_055773"><?php echo $data['study_num']?></span><span>人在学</span>
        </span>
    </div>
    <?php if(isset($data['order_audio']) && $data['order_audio']){?>
        <div class="other_content">
            <div class="title">
                此课程包还包含以下内容
            </div>
           
            <div class="voice_curriculums_list pack_up1" id="video_curriculums_list">
                <ul>
                    <?php foreach ($data['order_audio'] as $v){?>
                        <li>
                            <a href="<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'details'))?>?id=<?php echo $v['id']?>,1&type=1">
                                <div  class="cover">
                                    <img class="video_image" src="<?php echo $v['img_path']?>" alt="">
                                    <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                                </div>
                                <div class="content">
                                    <div><?php echo $v['title']?></div>
                                    <div class="teacher_name"><?php echo $v['teacher']['name']?></div>
                                    <div class="information2">
                                        <div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span><?php echo $v['audio_length']?></span></div>
                                        <div class="counting"><span class="font_color_055773"><?php echo $v['study_num']?></span><span>人在学</span></div>
                                    </div>
                                </div>
                                <div  class="more">
                                    <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                                </div>
                            </a>
                        </li>
                    <?php }?>
                </ul>
                <a style="display:none;" href="javascript:showAll();" class="oc_details border_bottom_black"><span>全部</span><img src="<?php echo ROOT_PATH;?>webStyle/images/open_details.png" alt=""></a>
            </div>
            
        </div>
    <?php }?>
    <?php if($data['alike_category']){?>
        <div class="other_content  border_bottom_gray">
            <div class="title">
                其他课程
            </div>
            <div class="voice_curriculums_list pack_up2" id="video_curriculums_list">
                <ul>
                <?php foreach ($data['alike_category'] as $v){?>
                    <li>  
                    <a href="<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'details'))?>?id=<?php echo $v['id']?>,2&type=2"> 
                        <div  class="cover">
                            <img class="video_image" src="<?php echo $v['img_path']?>" alt="">
                            <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                        </div>
                        <div class="content">
                                <div><?php echo $v['title']?></div>
                                <div class="teacher_name"><?php echo ""//$v['teacher_name']['name']?></div>
                                <div class="information">
                                    <div class="sum">总共<?php echo $v['audios_num']?>个视频</div>
                                    <div class="counting"><span class="font_color_055773"><?php echo $v['study_num']?></span><span>人在学</span></div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                <?php }?>
                </ul>
                <a style="display:none;" href="javascript:showAll();" class="oc_details border_bottom_black"><span>全部</span><img src="<?php echo ROOT_PATH;?>webStyle/images/open_details.png" alt=""></a>
            </div>
        </div>
    <?php }?>
    <div class="other_information">
        <div class="select_top">
            <a href="javascript:(0);" onclick="" class="select_on">留言</a>
            <a href="javascript:(0);">详情</a>
            
        </div>
        <section class="select_none">
             <div class="comment">
                 <ul>
                </ul>
                <div class="import_question">
                    <form method='post' action="#">
                        <input type="hidden" id="id" name="id" value="<?php echo $data['id']?>"/>
                        <input type="hidden" id="user_id" name="user_id" value="<?php echo $user_id?>"/>
                        <input type="hidden" name="type" value="<?php echo $type?>"/>
                        <textarea id="content" class="content" name="content" placeholder="自古评论出高手，说说你的看法..."></textarea>
                        <button id="butn">提交留言</button>
                    </form>                
                </div>
            </div>  
            <div class="introduce" style="display:none"><div><?php echo $data['audios_synopsis']?></div></div>
         
        </section>
    </div>   
    <footer class="audio_footer">
        <ul>
            <li><a href="javascript:(0);" onclick="present_window()"><p>送给好友</p></a></li>
            <?php if($data['equality'] == 1){?>
                <li  id="overBuy"><a href="javascript:(0);" onclick="" class="received"><p><imgclass="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt="">已购买</p></a></li>
            <?php }else{?>
                <?php if($_SESSION['is_vip'] == 1){?>
                    <li  id="buyNow"><a href="javascript:(0);" onclick="payOrderSubmit(1)"><p>立即购买</p></a></li>
                <?php }else{?>
                    <li  id="buyNow"><a href="javascript:(0);" onclick="buyNow()"><p>立即购买</p></a></li>
                <?php }?>
                
                <li style="display:none" id="overBuy"  style="display:none"><a href="javascript:(0);" onclick="" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt="">已购买</p></a></li>
            <?php }?>
          
               
        </ul>
    </footer>

	<!-- 余额支付 -->
	<div class="member_pay">
		<div class="title">
            支付
            <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
        </div>
        <div>
        	<ul>
        		<li>
        			<div id="order_com">订单支付价</div>
        			<div>￥<span id="orderPay">9.90</span></div>
        		</li>
        		<a href="<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'wallet'));?>">
        			<li>
        			<div id="user_money">用户余额</div>
        			<div>￥<span id="residueMoney"><?php echo $data['amount']?></span></div>
        			<div><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div>
        		</li>
        		</a>
        		
        		<li>
        			<div>支付后余额</div>
        			<div class="font_color_055773">￥<span id="orderMessage">9.90</span></div>
        		</li>
        		<li>
        			<button id="butMessage">确认支付</button>
        			<!-- <button>去充值</button> -->
        		</li>
        	</ul>
        </div>
	</div>
	
	
	<!-- 订单支付 -->
	<div class="common_pay">
		<div class="title">
            支付
            <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
        </div>
        <div>
        	<ul class="pay_select">
        		<li class="pay_select_on" id=1>
        			<div>会员价</div>
        			<div>￥<?php echo $data['original_price'];?></div>
        		</li>
        		<?php if($data['sell_type'] == 1 && $_SESSION['is_vip'] == 2){?>
            	      <li id=2>
            			<div>普通价</div>
            			<div>￥<?php echo $data['price'];?></div>
            		  </li>
        	    <?php }else{?>
                    <div>
                        <div>普通价</div>
                        <div>本课程为核心课程,仅对会员开放</div>
                    </div>         
                <?php }?>     
        	</ul>
        	<div class="pay_select_content">
        		<ul>
    			   <?php if($_SESSION['is_vip'] == 2 && $data['vip_price'] > $data['original_price']){?>
        			    <li class="explain">
            				<div class="font_color_055773">说明：支付<?php echo $data['vip_price']?>元成为会员后,可按会员价<?php echo $data['original_price'];?>元购买本课程</div>
            			</li>
        			   <li>
            				<div>加入会员</div>
            				<div class="">￥<span class="payNowPriceone font_color_055773"><?php echo $data['vip_price'];?></span></div>
        				</li>
    				<?php }else{?>
        				<li>
            				<div>订单金额</div>
            				<div class="">￥<span class="payNowPriceone font_color_055773"><?php echo $data['original_price']?></span></div>
        				</li>	
    				<?php }?>
        		</ul>
        		<ul style="display:none">
        			<li class="explain">
        				<div class="font_color_055773">说明：最核心的课程、导师沙龙面对面、会员优惠价等权益，非会员无法享受</div>
        			
        			</li>
        			<li>
        				<div>订单金额</div>
        				<div class="">￥<span class="payNowPricetwo font_color_055773"><?php echo $data['price']?></span></div>
        			</li>
        		</ul>
        	</div>
        </div>
        <ul class="operation">
            <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
            <li><a href="javascript:(0);" class="affirm" onclick="payOrderSubmit(1)"><p>支付订单</p></a></li>
        </ul>
    
	</div>
	
	<!-- 赠送支付 -->
        	<div class="common_present_pay">
        	<div class="title">
                支付
                <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
            </div>
            <div>
            	<ul class="pay_select_2">
            		<li class="pay_select_on_2" id=5>
            			<div>会员价</div>
            			<div>￥<span id="present_price"></span></div>
            		</li>
                    <div>
                        <div>普通价</div>
                        <div>本课程为核心课程,仅对会员开放</div>
                    </div>         
            	</ul>
            	<div class="pay_select_content_present">
            		<ul>
        			  
            		</ul>
            	</div>
            </div>
            <ul class="operation">
                <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
                <li><a href="javascript:(0);" class="affirm" onclick="payOrderSubmit(2,10)"><p>支付订单</p></a></li>
            </ul>
        
        </div>

	<!-- 赠送-->
	<div class="present_window" > 
        <div class="title">
            赠送课程
            <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
        </div>
        <ul class="present_detail">
            <li>
                <div>赠送人数</div>
                <div class="quantity">
                    <span class="minus">-</span><span><input type="text" id="edit_num"  value="1"></span><span class="add">+</span>
                </div>
            </li>
            <li>
                <div>课程打包</div>
                <?php if($_SESSION['is_vip'] == 1){?>
                    <div id="price">￥<span><?php echo $data['original_price'];?></span></div>
                <?php }else{?>
                        <?php if($data['sell_type'] == 1){?>
                            <div id="price">￥<span><?php echo $data['price'];?></span></div>
                        <?php }else{?>
                            <div id="price">￥<span><?php echo $data['original_price'];?></span></div>
                        <?php }?>
                <?php }?>
            </li>
            <li>
                <div>订单总价</div>
                <?php if($_SESSION['is_vip'] == 1){?>
                    <div id="total_price" class="font_color_055773">￥<span><?php echo $data['original_price'];?></span></div>
                <?php }else{?>
                        <?php if($data['sell_type'] == 1){?>
                            <div id="total_price" class="font_color_055773">￥<span><?php echo $data['price'];?></span></div>
                        <?php }else{?>
                            <div id="total_price" class="font_color_055773">￥<span><?php echo $data['original_price'];?></span></div>
                        <?php }?>
                <?php }?>
            </li>
        </ul>
        <div>
            <ul class="operation">
                <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
                <?php if($_SESSION['is_vip'] == 2 && $data['sell_type'] == 2){?>
                    <li><a href="javascript:(0);" class="affirm" onclick="buyNow(5)"><p>支付订单</p></a></li>
                <?php }else{?>
                    <li><a href="javascript:(0);" class="affirm" onclick="payOrderSubmit(2)"><p>支付订单</p></a></li>
                <?php }?>
            </ul>
        </div>
    </div>
    <!-- 完善资料 -->
        <div class="perfect_data">
        	<div class="title">
        		可试听,请完善资料
                 <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
        	</div>
        		<ul class="present_detail">
                    <li>
                        <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                    </li>
                    <li>
                        <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="javascript:(0);" class="gain_verification">获取验证码</a></div>
        
        
                    </li>
                    <a href="javascript:(0);" id="showPicker">
                        <li class="select">
                            <div>职位：
                            <span id='position' position_id="<?php echo $user['current_position_id'] ? $user['current_position_id'] : 0?>">
                              <?php echo isset($user['position_name']) && $user['position_name'] ? $user['position_name'] : ""?>
                            </span></div>
                        </li>
                    </a>
                    <li class="select">
                        <div>地区：<input class="weui_input" type="text" value="<?php echo $user['region'] ? $user['region'] : '广东省 广州市';?>" id='region' style="text-align:right"/></div>
                    </li>
                </ul>
                <div>
                <ul class="operation">
        
                    <li><a href="javascript:(0);" class="affirms"><p>完成</p></a></li>
                </ul>
        		</div>
        </div>



         <!-- 验证码错误 -->
        <div class="verification_wrong" >

        <div>您输入的验证码有误！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 verification_wrong_close"><p>确认</p></a></li>
              
            </ul>
        </div>
    </div>
    
        <!-- 验证码错误 -->
        <div class="captcha_wrong" >
        <div id="comment">请输入正确的手机号！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 captcha_wrong_close"><p>确认</p></a></li>
              
            </ul>
        </div>
    </div>
    


    
    <!-- 支付成功分享 -->
    <div class="pay_success" id="pay_success" >
    <div class="title"><img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt=""></div>
        <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
        <div>支付成功</div>
        <a href="<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecord'));?>">分享赠送链接</a>
    </div>
    <!-- 支付成功 -->
    <div class="one_pay_success" id="one_pay_success" >
    <div class="title"><img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt=""></div>
        <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
        <div>支付成功</div>

    </div>
         <!-- 5/18非会员支付弹窗 -->
         
    <div class="newcommon_pay">
        <div class="title">支付<img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt=""></div>
         <?php if($data['sell_type'] == 2 || ($data['price'] != '0.00' && $data['original_price'] != '0.00')){?>
            <div class="mt20">成为会员,可按<span class="font_color_055773" id="vip_pay_price"><?php echo $data['original_price']?></span>元购买</div>
            <input type="hidden" class="vip_pay_price" value="<?php echo $data['original_price'];?>"/>
        <?php }else {?>
            <div class="mt20">成为会员,可<span class="font_color_055773 ">免费</span>学习本课程</div>
        <?php }?>
        <div class="operation">
            <?php if($data['sell_type'] == 1){?>
                <a href="javascript:void(0);" id="become_no_vip" onclick="becomeMember(1,3)">非会员付<span id="no_vip_pay_price"><?php echo $data['price'];?></span>元</a>
                <input type="hidden" class="no_vip_pay_price" value="<?php echo $data['price'];?>"/>
            <?php }else{?>
                <a href="javascript:void(0);">该课程仅限会员</a>
            <?php }?>
            <a href="javascript:void(0);" class="become" id="become_vip" onclick="becomeMember(2,3)">成为会员</a>
        </div>
    </div>   
</body>   
</html>
<style>

</style>
<script>
commentList(<?php echo $data['id']?>,'1','2');
sessionStorage.setItem('url_audio_list', 2);
var goback ="<?php echo $goback?>"
if(goback != 0){
	$(function(){  
		pushHistory();
	    window.addEventListener("popstate", function(e) {
	    	var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'index'))?>";
	    	location.href = url;
	    }, false); 
	});
}
//资料完善
$("#region").cityPicker({
	   title: "选择省市",
	   showDistrict: false,
	 });  
$("#region").cityPicker({
	   title: "选择省市",
	   showDistrict: false,
	 });   
var is_perfect = '<?php echo $is_perfect?>';
var API_URL = '<?php echo API_URL?>';

var position = '<?php echo  isset($user['position']) && $user['position'] ? $user['position'] : ""?>'
var content = '<?php echo isset($user['position_id']) && $user['position_id'] ? $user['position_id'] : "";?>';
	if(position){
		position = JSON.parse(position);	
	}
	if(content){
		content = JSON.parse(content);	
	}

	$('#showPicker').on('click', function () {
	    weui.picker(position, {
            id: '#showPicker',
            defaultValue: [6],        
	        onChange: function (result) {
	        	$(".picker_title").html("选择职位");            	
	        },
	        onConfirm: function (result) {
	           var text = result[0];
	           $("#position").html(content[text]);
	           $("#position").attr('position_id',text);
	        }
	    });
	});

 $('.affirms').click(function(){
		var mobile = $('#mobile').val();
		var captcha = $('#captcha').val();
//	 	var region_id = $('#region').attr('region_id');
		var region_id = $("#region").val();
		var position_id = $('#position').attr('position_id');
		if(!mobile){
			$('.captcha_wrong').show()
		    return false;
		}else{
		    if(!isMobile(mobile)){
		    	$('.captcha_wrong').show()
			    return false;
			}
		}
		if(!captcha){
			$("#comment").html('请输入短信验证码!');
			$('.captcha_wrong').show()
		    return false;
		}
		if(position_id == 0){
			$("#comment").html('请选择职位！');
			$('.captcha_wrong').show()
		    return false;
		}
		if(!region_id){
			$("#comment").html('请选择地区！');
			$('.captcha_wrong').show()
		    return false;
		}

		checkCaptcha();
	});

	var flat = true;
	$(".gain_verification").on("click",function(){
		var mobile = $('#mobile').val();
		if(!isMobile(mobile))
		{
// 		    alert('请输入正确的手机号码');
			$('.captcha_wrong').show()
		    return false;
		}
//		sendCaptcha();
//		return false;
		if(flat){
	    	sendCaptcha();
	    	flat = false;
	        var setTime;
	        var time=60;
	        $(".gain_verification").text('60s');
            $(".gain_verification").css("background-color","#cccccc");
	        setTime=setInterval(function(){
	            if(time<=0){
	            	flat = true;
	                clearInterval(setTime);
	                 $(".gain_verification").text("获取验证码");
	                $(".gain_verification").css("background-color","#d7000f");
	                return false;
	            }
	            time--;
	            $(".gain_verification").text(time+'s');
// 	            $(".gain_verification").css("background-color","#cccccc");
	        },1000);
	    }
	})

function sendCaptcha()
{
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
// 	    alert('请输入正确的手机号码');
		$('.captcha_wrong').show()
	    return false;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
		//$('#captcha').val(data.q.code);
// 			var time=60;
// 	        setTime=setInterval(function(){
// 	            if(time<=0){
// 	            	flat = true;
// 	                clearInterval(setTime);
// 	                 $(".gain_verification").text("获取验证码");
// 	                $(".gain_verification").css("background-color","#d7000f");
// 	                return false;
// 	            }
// 	            time--;
// 	            $(".gain_verification").text(time+'s');
// 	            $(".gain_verification").css("background-color","#cccccc");
// 	        },1000);
		}
		else
		{
			flat = true;
			$("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}

function checkCaptcha(){
	var code = $('#captcha').val();
	if(!code){
	    alert("请输入验证码");
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 2;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
		json.q.mobile = $('#mobile').val();
		json.q.w = new Object();
		json.q.w.code = code;
		json.json = JSON.stringify(json);
		$.post(API_URL,json,function(data)
		{
			if(data.q.s == 0)
			{
				var mobile = $('#mobile').val();
//	 			var region_id = $('#region').attr('region_id');
				var region_id = $("#region").val()
				var position_id = $('#position').attr('position_id');
				$.post("<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ajaxUpdateUserInfo'));?>",{mobile : mobile,position_id:position_id,region_id:region_id},function(result){
				if(result.code == 200){
					$('.perfect_data').hide();
				    $('.bgb').hide();
// 				    location.reload();
// 				    window.location.href=window.location.href+"?id="+10000*Math.random()+"&type="+1;
// 				    window.location.href=window.location.href+"&type="+1;
				    window.location.href=window.location.href+"&go_type="+1+"&num="+10000*Math.random();
				}else{
				    alert(result.message);
				}
			},'json');
		}else{
		    $("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}	  




$(".pack_up1>ul li").hide();
$(".pack_up1>ul li:nth-child(1)").show();
$(".pack_up1>ul li:nth-child(2)").show();
if($(".pack_up1>ul li").length>2){
    $(".pack_up1 .oc_details").css("display","block");
}
var textFlag = 0;
    function showAll(){
        if(textFlag == 0){
            $(".pack_up1>ul li").show();
            $(".pack_up1 .oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/close_details.png');
           
        

            textFlag = 1
   
        }else{
            $(".pack_up1>ul li").hide();
            $(".pack_up1>ul li:nth-child(1)").show();
            $(".pack_up1>ul li:nth-child(2)").show();
            $(".pack_up1 .oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/open_details.png');
    

            textFlag = 0

        }

    }

$(".pack_up2>ul li").hide();
$(".pack_up2>ul li:nth-child(1)").show();
$(".pack_up2>ul li:nth-child(2)").show();
if($(".pack_up2>ul li").length>2){
    $(".pack_up2 .oc_details").css("display","block");
}
var textFlag2 = 0;
    function showAll2(){
        if(textFlag == 0){
            $(".pack_up2>ul li").show();
            $(".pack_up2 .oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/close_details.png');
           
        

            textFlag2 = 1
   
        }else{
            $(".pack_up2>ul li").hide();
            $(".pack_up2>ul li:nth-child(1)").show();
            $(".pack_up2>ul li:nth-child(2)").show();
            $(".pack_up2 .oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/open_details.png');
    

            textFlag2 = 0

        }

    }

//送给好友
present_window = function(){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
    $(".present_window").show();
    $(".bgb").show();
}

function buyNow(type){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	$('.bgb').show();	
	
	if(type == 5){
		 $('.present_window').hide();
		 $(".common_present_pay").show()
		 var li = "";
		 var li2 = "";
		 var vip_price = "<?php echo $data['vip_price']?>";
		 var total_price = $("#total_price>span").html();
		 var price = $("#price>span").html();
		 var sx_price = vip_price-price;
		 li += "<li class='explain'><div class='font_color_055773'>说明：支付"+vip_price+"元成为会员后,可按会员价"+price+"元购买本课程</div></li>";
		 li += "<li><div>加入会员</div><div class=''>￥<span class='payNowPriceone'>"+vip_price+"</span></div></li>";
		 //li2 += "<li class='explain'><div class='font_color_055773'>说明：支付"+vip_price+"元成为会员后,可按会员价"+price+"元购买本课程,之后会员余额为"+sx_price+"元</div></li>";
		 li2 += "<li><div>订单金额</div><div class=''>￥<span class='payNowPriceone'>"+total_price+"</span></div></li>";
		 $(".common_present_pay .pay_select_content_present>ul>li").remove();
		 $("#present_price").html(total_price);
		 
		 if(parseInt(total_price) < parseInt(vip_price)){
			 $(".common_present_pay .pay_select_content_present>ul").append(li);
		 }else{
			 $(".common_present_pay .pay_select_content_present>ul").append(li2);
		 }
		 $(".common_present_pay .operation .affirm").attr('onclick','payOrderSubmit(2,10)');
	}else{
// 		$('.common_pay').show();
		$('#no_vip_pay_price').html($('.no_vip_pay_price').val());
		$('#vip_pay_price').html($('.vip_pay_price').val());
		$("#become_no_vip").attr('onclick','becomeMember(1,3)'); //余额支付
		$("#become_vip").attr('onclick','becomeMember(2,3)'); //余额支付
		$('.newcommon_pay').show();
        $('.newcommon_pay .operation a').removeClass("become");
        $('.newcommon_pay .operation a:last-child').addClass("become");
	}
}

var recharge_url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'rechargeIndex'));?>";
//支付
var is_vip = "<?php echo $_SESSION['is_vip']?>";
function payOrderSubmit(pay_type,pay_cour){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	if(!pay_cour){
		pay_cour = 1;
	}
	 $('.common_pay').hide();
	 $(".present_window").hide();
	 $('.member_pay').show();
	 $(".common_present_pay").hide();
	 $('.bgb').show();
	var residueMoney = $('#residueMoney').html();
	if(pay_type == 2){
		if(pay_cour == 10){
			$('#orderPay').html($(".pay_select_content_present .payNowPriceone").html());
		}else{
			$('#orderPay').html($("#total_price>span").html());
		}
		var order_pay = $('#orderPay').html();
		if(is_vip == 2){
			//非会员
			$('#no_vip_pay_price').html($('.no_vip_pay_price').val());
			$('#vip_pay_price').html($('.vip_pay_price').val());
			$('.member_pay').hide();
			$('.newcommon_pay').show();
            $('.newcommon_pay .operation a').removeClass("become");
            $('.newcommon_pay .operation a:last-child').addClass("become");
			var num = $("#edit_num").val();
			$('#no_vip_pay_price').html(order_pay);
			$('#vip_pay_price').html(parseFloat($('#vip_pay_price').html()*num).toFixed(2));
			//新支付单个文件购买
			$("#become_no_vip").attr('onclick','becomeMember(1,2)'); //成为会员
			$("#become_vip").attr('onclick','becomeMember(2,2)'); //余额支付
		}else{
			if(residueMoney-order_pay >= 0){
				$("#orderMessage").html(parseFloat(residueMoney-order_pay).toFixed(2));
				$("#butMessage").html('确认支付');
				$("#butMessage").attr('onclick','orderSubmit(2,2)'); //余额支付
			}else{
				$("#orderMessage").html('余额不足');
				$("#butMessage").html('微信支付');
				$("#butMessage").removeAttr('onclick'); 
				//$("#butMessage").html('<a class="go_recharge" href='+recharge_url+'>去充值</a>');
//	 			$("#butMessage").attr('onclick','orderSubmit(2,1)'); //微信支付
				$("#butMessage").attr('onclick','becomeMember(1,4,2)'); //微信支付
			
			}
		}
	}else{
		var select_id = $(".pay_select_on").attr('id');
	    if(select_id == 1){
	    	$('#order_com').html('会员优惠价');
	    	$('#user_money').html('会员余额');
	    }
		if(select_id == 1){
			var price = $(".payNowPriceone").html();
		}else{
			var price = $(".payNowPricetwo").html();
		}
		$('#orderPay').html(price);
		if(residueMoney-price >= 0){
			var vip = "<?php echo $_SESSION['is_vip']?>";
			var o_price = "<?php echo $data['original_price'];?>";
			var num1 = (residueMoney-price)*1;
			var num2 = (residueMoney-o_price)*1;
			if(select_id == 1 && vip == 2){
				$("#orderMessage").html(parseFloat(num1+num2).toFixed(2));
			}else{
				$("#orderMessage").html(parseFloat(num1).toFixed(2));
			}		
			$("#butMessage").html('确认支付');	
			$("#butMessage").attr('onclick','orderSubmit(1,2,'+select_id+')'); //余额支付
		}else{
			$("#orderMessage").html('余额不足');
			$("#butMessage").removeAttr('onclick');
			//$("#butMessage").html('<a class="go_recharge" href='+recharge_url+'>去充值</a>');
			$("#butMessage").html('微信支付');
			$("#butMessage").attr('onclick','becomeMember(1,4,3)'); //微信支付
		
		}
	}
}

function becomeMember(id,payment,types){
	if(!types){
		types = 0
	}
	var audio_id = "<?php echo isset($data["id"]) ? $data["id"] : 0?>";
	var user_id = $("#user_id").val();
	if(!audio_id){
		alert("购买失败！");
		return false;
	}
	if(id == 2){
		//成为会员 
		var pay_price = $("#vip_pay_price").html() ? $("#vip_pay_price").html() : 0;
		if(payment == 1){
			//单买单个课程
			var obj = {pay_price:pay_price,pay_type:1,number:1,genre:1,audio_type:2,audio_id:audio_id,transfer_way:2,user_id:user_id};
		}else if(payment == 2){
			//赠送单个课程
			var obj = {pay_price:pay_price,pay_type:2,number:$("#edit_num").val(),genre:2,audio_type:4,audio_id:audio_id,transfer_way:2,user_id:user_id};
		}else if(payment == 3){
			//课程包购买
			//var pay_price = $("#courses_vip_pay_price").html() ? $("#courses_vip_pay_price").html() : 0;
			var obj = {pay_price:pay_price,pay_type:1,number:1,genre:2,audio_type:4,audio_id:audio_id,transfer_way:2,user_id:user_id};
		}
		var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxRecharge'));?>";
	}else{
		if(payment == 4){
			var pay_price = $("#orderPay").html() ? $("#orderPay").html() : 0;
			payment = types;
		}else{
			var pay_price = $("#no_vip_pay_price").html() ? $("#no_vip_pay_price").html() : 0;
		}
		if(parseFloat(residueMoney) > parseFloat(pay_price)){
			//余额支付 调用 audioOrderSubmit
			var url = "<?php echo $this->url('web-common',array('controller' => 'Video','action' => 'audioOrderSubmit'));?>";
			if(payment == 1){
				//余额支付单买单个课程
				var obj = {pay_price:pay_price,pay_type:1,number:1,genre:1,audio_type:2,audio_id:audio_id,transfer_way:2,user_id:user_id};
			}else if(payment == 2){
				//余额支付赠送单个课程
				var obj = {pay_price:pay_price,pay_type:2,number:$("#edit_num").val(),genre:2,audio_type:4,audio_id:audio_id,transfer_way:2,user_id:user_id};
			}else if(payment == 3){
				//余额支付赠送课程包
				var url = "<?php echo $this->url('web-common',array('controller' => 'Video','action' => 'coursesOrderSubmit'));?>";
				var obj = {pay_price:pay_price,pay_type:1,number:1,genre:2,audio_type:4,audio_id:audio_id,transfer_way:2,user_id:user_id};
			}
		}else{
			//微信支付 调用 ajaxWxCoursePay.
			var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxWxCoursePay'));?>";
			if(payment == 1){
				var obj = {pay_price:pay_price,pay_type:1,number:1,genre:1,audio_type:2,audio_id:audio_id,transfer_way:1,user_id:user_id};
			}else if(payment == 2){
				var obj = {pay_price:pay_price,pay_type:2,number:$("#edit_num").val(),genre:2,audio_type:4,audio_id:audio_id,transfer_way:1,user_id:user_id};
			}else if(payment == 3){
				var obj = {pay_price:pay_price,pay_type:1,number:1,genre:2,audio_type:4,audio_id:audio_id,transfer_way:1,user_id:user_id};
			}
			
		}
	}
	$.post(url,{obj:obj,price:pay_price},function(result){
		if(result.code == 200){
			$('.member_pay').hide();
			$('.newcommon_pay').hide();
			$('.bgb').hide();
			if(result.is_debug == 1){
                    if(payment == 1 || payment == 3){
//         				 $('.bgb').show();
        				 $("#one_pay_success").show();
        				 setTimeout("text()",500); 
                    }else{
                    	var url ="<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecordDetail'));?>";
                    	url = url +"?id="+result.giving_log_id;
                    	$("#pay_success > a").attr('href',url);
                    	$("#pay_success").show();
                    	$('.bgb').show();
                    	return false;
                    }
				  
			}else{
				WeixinJSBridge.invoke('getBrandWCPayRequest',result,function(res){
					WeixinJSBridge.log(res.err_msg);
					if (res.err_msg.indexOf("ok") != -1) {
						if(payment == 1 || payment == 3){
							$("#one_pay_success").show();
							setTimeout("text()",500); 
						}else{
							var url ="<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecord'));?>";
// 			    			$("#pay_success > a").attr('href',url);
							$("#pay_success > a").attr('href',url+'?type=video');
			    			$("#pay_success").show();
			    			$('.bgb').show();
			    			return false;
						}
					}
				}
			    );	
			}
		}else{
			alert(result.message);
			return false;
		}
	},'json');
}
//立即购买 取消
$('.common_pay .operation .cancel').on("click",function(){
	$('.bgb').hide();	
	$('.common_pay').hide();
})

$('.close').click(function(){
	$('.bgb').hide();	
	$('.common_pay').hide();
	$('.common_pay').hide();
	$('.member_pay').hide();
    $(".perfect_data").hide();
    $(".one_pay_success").hide();
    $(".pay_success").hide();
    $(".common_present_pay").hide();
    $(".newcommon_pay").hide();
});


$('.verification_wrong_close').click(function(){
    $('.verification_wrong').hide();
    $('.bgb').hide();
})


$('.captcha_wrong_close').click(function(){
    $('.captcha_wrong').hide();
})

//关闭赠送
$(".present_window .title .close").on("click",function(){
    $(".present_window").hide();
    $(".bgb").hide();
})

// 取消赠送
$(".present_window .operation .cancel").on("click",function(){
    $(".present_window").hide();
    $(".bgb").hide();
})

$('.common_present_pay .operation .cancel').on("click",function(){
	$('.bgb').hide();	
	$('.common_present_pay').hide();
})

//会员与非会员切换
$(".common_pay .pay_select li").on("click",function(){
	$(this).addClass('pay_select_on').siblings().removeClass('pay_select_on');
	$('.pay_select_content>ul').hide();
		$('.pay_select_content>ul').eq($(this).index()).show();
})

// 购买数量加减
$(".present_detail .quantity .add").on("click",function(){
    $(".present_detail .quantity input").val(parseInt($(".present_detail .quantity input").val()) + 1);
    $("#total_price>span").html(parseFloat($("#price>span").html()*$(".present_detail .quantity input").val()).toFixed(2));
})
$(".present_detail .quantity .minus").on("click",function(){
    if($(".present_detail .quantity input").val()>=2){
        $(".present_detail .quantity input").val(parseInt($(".present_detail .quantity input").val()) - 1);
        $("#total_price>span").html(parseFloat($("#price>span").html()*$(".present_detail .quantity input").val()).toFixed(2));
    }
})

$("#edit_num").keyup(function(){
	if($("#edit_num").val() > 0){
		$("#total_price>span").html(parseFloat($("#price>span").html()*$("#edit_num").val()).toFixed(2));
	}	
});

$("#total_price>span").html(parseFloat($("#price>span").html()*$("#edit_num").val()).toFixed(2));


var id = "<?php echo $data['id']?>";
var pay_video = true;
function orderSubmit(pay_type,transfer_way,select_id){
	if(!select_id){
		select_id = 0;
	}
	if(!pay_video){
		return false;
	}
	pay_video = false;
	var price = $("#orderPay").html();
	if(pay_type == 2){
		//赠送
		var num = $("#edit_num").val();
	}else{
		//单买
		var num = 1;
		var original_price = "<?php echo $data['original_price'];?>";
	}
	var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'coursesOrderSubmit'));?>";
	$.post(url,{pay_type:pay_type,id:id,price:price,num:num,transfer_way:transfer_way,select_id:select_id,original_price:original_price},function(result){
	if(result.code == 200){
		  pay_video = true;
        	if(result.transfer_way == 2){
//         		alert('支付成功');
        		$('.bgb').hide();	
    			$('.common_pay').hide();
    			$('.member_pay').hide();
    			if(pay_type == 2){
    				var url ="<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecordDetail'));?>";
        			url = url +"?id="+result.giving_log_id;
        			$("#pay_success > a").attr('href',url);
        			$("#pay_success").show();
        			return false;
    			}else{
    				$("#buyNow").hide();
 				    $("#overBuy").show();
 				    $("#one_pay_success").show();
                    $(".bgb").show();
  				   setTimeout("text()",500); 
    			}
        	}
    	}else{
    		alert(result.message);
    		return false;
    	}
    },'json');
}


function text(){
	$('#one_pay_success').hide();
    $(".bgb").hide();
// 	location.reload();
    window.location.href=window.location.href;
}
//提交评论
$("#butn").click(function(){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	var content = $("#content").val();
	var id = $("#id").val();
	var user_id = $("#user_id").val();
	if(content){
		var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'coursesCommentSubmit'));?>";
		$.post(url,{content:content,id:id,user_id:user_id},function(result){
			if(result.code != 200){
				alert(result.message);
				return false;
			}else{
				 var dom = $(".comment ul:first");
				 var li = '';
				 li += '<li>';
				 li += '<div class="title">'
			     li += '<div class="head_portrait_auto"><img src="'+result.user.head_icon+'" alt=""></div>';
				 li += '<span>'+result.user.name+'</span></div>';
				 li += '<div class="content">';
				 li +=  content;
				 li += '</div>';
				 li += '<div class="under">';
				 li += '<span class="time">'+result.user.time+'</span>';
				 li += '<span class="operation"><a href="javascript:(0);" class="reply">回复</a> <a href="javascript:;" onclick = getPraise('+result.user.comment_id+','+ $('#user_id').val()+'); href="" class="like">&nbsp;</a></span>';
				 li += '</div><ul></ul></li>';
				 dom.prepend(li);
				 commentList(id,1,2);
				 $("#content").val('');
			}
            setTimeout('head_portrait()',300);
		},'json');
		return false;
	}else{
		alert("内容不能为空");
		return false;
	}
});




var finished = false;
var page = 1;
function commentList(id,type,num){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     
	 var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxgetCommentList'))?>";
	 $.post(url,{page:page,id:id,num:num},function(data) {
		 if (data.length > 0) {  
			 var dom = $(".comment ul:first");
			 var li = '';
			 if(type == 1){
				 $(".comment ul li").remove();
             }  
			 $.each(data,function(i,v){
				 if(v.praise == 1){
					 class_name = 'like_on';
				 }else{
					 class_name = 'like';
				 }
				 var li = '';
				 li += '<li style="position:relative">';
				 if(v.is_top == 1){
					 li += '<div class="stick">置顶</div>';
				 }
				 li += '<div class="title">'
			     li += '<div class="head_portrait_auto"><img src="'+v.user_head_icon+'" alt=""></div>';
				 li += '<span>'+v.user_name+'</span></div>';
				 if(v.son_com.length > 0){
				    li += '<div class="content" style="color:#d7000f">';
				 }else{
				    li += '<div class="content">';
				 }
				 li +=  v.content;
				 li += '</div>';
				 li += '<div class="under">';
				 li += '<span class="time">'+v.timestamp+'</span>';
				 li += '<input type="hidden" class="par_id" name="par_id" value="'+v.id+'">';
				 li += '<span class="operation">';
				 if(v.user_id == <?php echo $user_id?>){
					 li += '<a href="javascript:(0);" class="empty"  id="'+v.id+'" name="1">删除</a>';
				 }else{
					 li += '<a href="javascript:(0);" class="reply">回复</a>';
				 }
				 
				 li += '<span><a href="javascript:;" onclick = getPraise('+v.id +','+ $('#user_id').val()+'); class="'+class_name+'">&nbsp;</a></span></span>';
				 li += '</div><ul>';
				 if(v.son_com.length > 0){
					 $.each(v.son_com,function(m,n){
						 if(n.praise == 1){
							 class_name = 'like_on';
						 }else{
							 class_name = 'like';
						 }
						 if(n.user_img > 0){
							var img_path = '<?php echo ROOT_PATH.UPLOAD_PATH."/";?>';
							img_path += n.user_img_path;
						 }else{
							 var img_path = n.user_head_icon;
						 }
						 li += '<li class="comment_list_in">';
						 li += '<div class="title"><div class="head_portrait_auto"><img src="'+img_path +'" alt=""></div><span>'+n.user_name+'</span></div>'
					     li += '<div class="content">'+n.content+'</div>';
						 li += '<div class="under"><span class="time"><span>'+n.timestamp+'</span></span>';
						 li += '<span class="operation">';
						 if(n.user_id == <?php echo $user_id?> && n.user_type != 2){
							 li += '<a href="javascript:(0);" class="empty" id="'+n.id+'" name="2">删除</a>';
						 }
						 li += '<span><a href="javascript:;" onclick = getPraise('+n.id +','+ $('#user_id').val()+'); class="'+class_name+'">&nbsp;</a></span></span>';
					 });
				 }				 
				 li += '</ul></li>';
				 dom.append(li);
				 setTimeout('head_portrait()',300);
			 });
			 $(".comment ul li .operation span a").unbind("click").on("click",function(){
				class_names = $(this).attr("class");
			 	 if(class_names == 'like'){
			 		 $(this).attr("class","like_on");
			 	 }else{
			 		 $(this).attr("class","like");
			 	 }
			 });
			 var num = 0;
			 $(".comment ul li .operation>a").unbind("click").on("click",function(){ 
				 if($(this).html() == '回复'){
					 $('.reply_on').attr("class","reply");
					 $(this).attr("class","reply_on");
					 var num = $(this).parents().prev('.par_id').val();
					 $(this).attr('name','comment');
					 if($('.abcde').attr('name') == num){
						 $(this).parents('li').next('li').remove();
						 $(this).attr("class","reply");
					 }else{
						 $('.abcde').remove();						 
						 $(this).parents('li').after('<li class="abcde" name='+num+'><div class="import_question"><input type="hidden" id="id" name="id" value="'+$(this).parents().prev('.par_id').val()+'"> <input type="hidden" id="par_user_id" name="user_id" value="'+$('#user_id').val()+'"> <input type="hidden" name="type" value="1"> <textarea id="reply_content" class="content" name="reply_content" placeholder=""></textarea><button onclick="reply_but()">提交回复</button></div></li>'); 
					 }
				 }else if($(this).html() == '删除'){		
					 var id = $(this).attr('id');
					 var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxDeleteCoursesComment'))?>";
					 $.post(url,{id:id},function(result) {
					 });
					 if($(this).attr('name') == "1"){
						 $(this).parents('li').remove();
					 }else{
						 $(this).parents('.comment_list_in').remove();
					 } 
				 }
			 });
			 finished = false;
             page++;
		 }
	 },'json');
}

//提交回复
function reply_but(){
	var id = $('.abcde').attr('name');
	var user_id = $('#par_user_id').val();
	var content = $('#reply_content').val();
	if(!content){
		alert('回复留言内容不能为空');
		return false;
	}
	 var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxReplyCoursesComment'))?>";
	 $.post(url,{id:id,user_id:user_id,content:content},function(result) {
		if(result.code != 200){
			alert(result.message);
			return false;
		}else{
			 var dom = $('.abcde').prev('li').children('.under').next('ul');
			 var li = '';
			 li += '<li class="comment_list_in">';
			 li += '<div class="title"><div class="head_portrait_auto"><img src="'+result.user.head_icon+'" alt=""></div><span>'+result.user.name+'</span></div>'
		     li += '<div class="content">'+result.str+'</div>';
			 li += '<div class="under"><span class="time"><span>2016-12-20</span></span>';
			 li += '<span class="operation"><a href="javascript:(0);" onclick=deleteReply('+result.user.comment_id+',this) id="'+result.user.comment_id+'" class="empty">删除</a>';
			 li += '<a href="javascript:;" class="like" onclick=getPraise('+result.user.comment_id +','+ $('#user_id').val()+',this);>&nbsp;</a></span></div></li>';
			 dom.append(li);
			 $('.abcde').prev('li').children('.content').attr('style','color:#d7000f');
			 $('.reply_on').attr("class","reply");
		     $('.abcde').remove();
		}

// 		 $(".comment ul li .operation>a").unbind("click").on("click",function(){ 
// 			 console.log($(this).html());
// 			 if($(this).html() == '回复'){
// 				 $('.reply_on').attr("class","reply");
// 				 $(this).attr("class","reply_on");
// 				 var num = $(this).parents().prev('.par_id').val();
// 				 $(this).attr('name','comment');
// 				 if($('.abcde').attr('name') == num){
// 					 $(this).parents('li').next('li').remove();
// 					 $(this).attr("class","reply");
// 				 }else{
// 					 $('.abcde').remove();
// 					 $(this).parents('li').after('<li class="abcde" name='+num+'><div class="import_question"><input type="hidden" id="id" name="id" value="'+$(this).parents().prev('.par_id').val()+'"> <input type="hidden" id="par_user_id" name="user_id" value="'+$('#user_id').val()+'"> <input type="hidden" name="type" value="1"> <textarea id="reply_content" class="content" name="reply_content" placeholder="点击输入您的评论"></textarea><button onclick="reply_but()">提交评论</button></div></li>'); 
// 				 }
// 			 }else if($(this).html() == '删除'){		
// 				 var id = $(this).attr('id');
				// var url = "<?php //echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxDeleteComment'))?>";
// 				 $.post(url,{id:id},function(result) {
// 				 });
// 				 if($(this).attr('name') == "1"){
// 					 $(this).parents('li').remove();
// 				 }else{
// 					 $(this).parents('.comment_list_in').remove();
// 				 }
// 			 }else{
// 				 if($(this).attr('class') == 'like_on'){
// 					 $(this).attr('class','like');
// 				 }else{
// 					 $(this).attr('class','like_on');
// 				 }
				 
// 			 }
// 		 });
        setTimeout('head_portrait()',10);
	 },'json');
	return false;
}


function deleteReply(id,dom){
	 var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxDeleteComment'))?>";
	 $.post(url,{id:id},function(result) {
	 });
	 if($(dom).attr('name') == "1"){
		 $(dom).parents('li').remove();
	 }else{
		 $(dom).parents('.comment_list_in').remove();
	 }
}


function getPraise(parId,user_id,dom){
	 if($(dom).attr('class') == 'like_on'){
		 $(dom).attr('class','like');
	 }else{
		 $(dom).attr('class','like_on');
	 }
	var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxgetPraise'))?>";
	$.post(url,{parId:parId,user_id:user_id},function(data) {
	});
}


function loadmore(obj){    
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	commentList(id,2,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});


$(".other_information .select_top a").click(function(){
        $(this).addClass('select_on').siblings().removeClass('select_on');
        $('.select_none>div').hide();
        $('.select_none>div').eq($(this).index()).show()
    })

zymedia('video',{preload: 'auto'});
var screenheight = window.screen.height/2;

var videoheight = $(".zy_media").height()/2;
var padding_top = screenheight-videoheight;

$("#modelView").css({"margin-top":-1*(padding_top+$(".zy_media").height())});


var id = "<?php echo $data['id']?>";
var user_id = "<?php echo $user_id?>";
var type = "<?php echo $type?>";
var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxAddCollect'))?>";
$("#collected").click(function(){
	var collect_video_type = type == 1 ? 2 : 4;
    $.post(url,{id:id,user_id:user_id,type:collect_video_type},function(result) {
        if(result.code == 200 && result.num == 1){
            //添加
        	$("#collected").attr('class','collect');
        	$("#collected").html('已收藏');
        }else{
            //取消
        	$("#collected").attr('class','collected');
        	$("#collected").html('收藏');
        }
   },'json');
});


var video = $('#videoID').get(0);
video.addEventListener('timeupdate', function (e) {
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    setTimeout("video.pause()",10); 
	    return false;
	}
    setTimeout("$('#videoID').show();",1000);
});


$('.fake_play_ios').click(function(){
    $('#videoID')[0].play();
    setTimeout("$('.cover_img').hide();$('.cover_play').hide();",300);
    
})


$('.real_play').click(function(){     
    $('#videoID')[0].play();
    setTimeout("$('.cover_img').hide();$('.cover_play').hide();",300);
});


var coverSrc = $(".cover_img").attr("src")
if(coverSrc==""){
    $(".cover_img").hide();
    $(".cover_play").hide();
}



$(".newcommon_pay .operation a").on("click",function(){
    $(this).siblings().removeClass("become").end().addClass("become");
})
$(".newcommon_pay_two .operation a").on("click",function(){
    $(this).siblings().removeClass("become").end().addClass("become");
})


$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".buyAset,.member_pay,.present_window,.pay_share,.pay_success,.common_pay").css({"top":"56vw ","margin-top":"0 "})
        $('#videoID').hide();
        $('.real_play').show();
        $('.real_play_black').show();
        $(".perfect_data").css("bottom","20%");
        $(".zy_media .zy_controls").hide();
    }
    else if(/iphone/.test(ua)){
        $(".perfect_data").css("top","50%");
        
            $('.fake_play_ios').show();

        
        $(".zy_media .zy_controls").hide();


    }
    else{
        $(".perfect_data").css("top","50%");
        
            $('.fake_play_ios').show();

       
        $('.fake_play_ios').click(function(){
            $('.fake_play_ios').hide();
            $('.details_banner .tips, .playvideo .tips').hide();
            $('.zy_playpause_btn').removeClass('zy_play').addClass('zy_pause');
        })
        $(".zy_media .zy_controls").show();

    }

}); 

if(is_perfect <= 0){
	$('.fake_play').show();
}

$('.fake_play').click(function(){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
});

//推荐跳转
$('.promote_play').on('click', function() {
    location.href = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ishare'))?>"
})

//分享设置
wx.ready(function(){
	 shareData = {title: '<?php echo $data['title']?>',desc:'<?php echo $data['prise'];?>',imgUrl: '<?php echo 'https://' . $_SERVER['HTTP_HOST'] .'/'.UPLOAD_PATH.$data['cour_img'];?>'};
	 share(shareData);
});
</script>