<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<title>视频课程</title>
<style>
    body{
        padding-bottom: 56px;
    }
    .return_home{
           display:none;
    }
</style>
<html>
<body>
    <div class="londing_gif1" >
        <img src="<?php echo ROOT_PATH;?>webStyle/images/londing.gif" alt="">
    </div>
    <div class="bgb"></div>
    <div class="voice_details">
        <div class="select_top">
            <?php foreach ($data as $k => $v){?>
                <a href="javascript:;" id="<?php echo  $v['id']?>" onclick="getCategory(<?php echo $v['id']?>,2);" <?php if($k==0){?>class="select_on"<?php }?> class=""><?php echo $v['name'];?></a>
            <?php }?>
        </div>
        <a class="goto_search" href="<?php echo $this->url('web-common',array('controller' => 'search','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/seek.png" alt="">更多品牌智慧</a>
        <div class="classify" id="classifys">
            <!-- <div> -->
            <!-- </div> -->
        </div>
        <div class="curriculums_table television">课程列表</div>
        <div class="voice_curriculums_list" id="video_curriculums_list">
            <ul>
               
            </ul>
        </div>
    </div>
    <!-- 完善资料 -->
    <div class="perfect_data">
    	<div class="title">
    		可试听,请完善资料
    	</div>
    		<ul class="present_detail">
                <li>
                    <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                </li>
                <li>
                    <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="javascript:(0);" class="gain_verification">获取验证码</a></div>


                </li>
                <li class="select">
                    <a href="javascript:(0);" id="showPicker">
                    <div>职位：
                    <span id='position' position_id="<?php echo $user['current_position_id'] ? $user['current_position_id'] : 0?>">
                      <?php echo $user['position_name']?>
                    </span></div></a>
                </li>
                <li class="select">
                    <div>地区：<input class="weui_input" type="text" value="<?php echo $user['region'] ? $user['region'] : '广东省 广州市';?>" id='region' style="text-align:right"/></div>
                </li>
            </ul>
            <div>
            <ul class="operation">

                <li><a href="javascript:(0);" class="affirm"><p>完成</p></a></li>
            </ul>
    		</div>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'index','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/home.png" alt=""><p>首页</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/voice.png" alt=""><p>音频</p></a></li>
            <li class=""><a href="javascript:(0);"><img src="<?php echo ROOT_PATH;?>webStyle/images/video_on.png" alt=""><p class="select_on">视频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/mine.png" alt=""><p>我的</p></a></li>
        </ul> 
    </footer>
</body>   
</html>
<script>
var url_id = 0;
var url_list = sessionStorage.getItem('url_list');
var two_type = sessionStorage.getItem('two_type');
var one_type = sessionStorage.getItem('one_type');
var url_name = "<?php echo $url_name?>";
// console.log(url_name);
if(url_list == 2){
	 $('.voice_details .select_on').attr('class','');
	 $('.voice_details #'+one_type).attr('class','select_on');
	 url_name = "";
}

if(url_name){
	$(".voice_details .select_top a").each(function(){
	    if($(this).html() == url_name){
		     url_id = $(this).attr('id');
	    	 $('.voice_details .select_on').attr('class','');
	    	 $('.voice_details #'+url_id).attr('class','select_on');
	    }
	});
}




$("#region").cityPicker({
   title: "选择省市",
   showDistrict: false,
 }); 
var is_perfect = '<?php echo $is_perfect?>';
var API_URL = '<?php echo API_URL?>';

// document.ready = function () {
// 	if(is_perfect <= 0){
// 	    $('.perfect_data').show();
// 	    $('.bgb').show();
// 	}
// }
var position = '<?php echo  isset($user['position']) && $user['position'] ? $user['position'] : ""?>'
var content = '<?php echo isset($user['position_id']) && $user['position_id'] ? $user['position_id'] : "";?>';
position = JSON.parse(position);
content = JSON.parse(content);
$('#showPicker').on('click', function () {
    weui.picker(position, {
        onChange: function (result) {
        	$(".picker_title").html("选择职位");            	
        },
        onConfirm: function (result) {
           var text = result[0];
           $("#position").html(content[text]);
           $("#position").attr('position_id',text);
        }
    });
});

$('.affirm').click(function(){
	var mobile = $('#mobile').val();
	var captcha = $('#captcha').val();
// 	var region_id = $('#region').attr('region_id');
	var region_id = $("#region").val();
	var position_id = $('#position').attr('position_id');
	if(!mobile){
	    alert('请输入手机号码！');
	    return false;
	}else{
	    if(!isMobile(mobile)){
	        alert('手机号码格式不正确！');
	        return false;
		}
	}
	if(!captcha){
		alert('请输入手机验证码！');
		 return false;
	}
	if(!position_id){
		alert('请选择职位！');
		 return false;
	}
	if(!region_id){
		alert('请选择地区！');
		 return false;
	}

	checkCaptcha();
});

var flat = true;
$(".gain_verification").on("click",function(){
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return false;
	}
	if(flat){
    	sendCaptcha();
    	flat = false;
        var setTime;
        var time=60;
        setTime=setInterval(function(){
            if(time<=0){
            	flat = true;
                clearInterval(setTime);
                 $(".gain_verification").text("获取验证码");
                $(".gain_verification").css("background-color","#d7000f");
                return false;
            }
            time--;
            $(".gain_verification").text(time+'s');
            $(".gain_verification").css("background-color","#cccccc");
        },1000);
    }
})

function sendCaptcha()
{
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
		}
		else
		{
			alert(data.q.d);
		}
	},"json");
}

function checkCaptcha(){
	var code = $('#captcha').val();
	if(!code){
	    alert("请输入验证码");
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 2;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.q.w = new Object();
	json.q.w.code = code;
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
			var mobile = $('#mobile').val();
// 			var region_id = $('#region').attr('region_id');
			var region_id = $("#region").val();
			var position_id = $('#position').attr('position_id');
			$.post("<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ajaxUpdateUserInfo'));?>",{mobile : mobile,position_id:position_id,region_id:region_id},function(result){
				if(result.code == 200){
					$('.perfect_data').hide();
				    $('.bgb').hide();
				}else{
				    alert(result.message);
				}
			},'json');
		}else{
		    alert(data.q.d);
		}
	},"json");
}

$(".select_top a").on("click",function(){
	$(this).siblings().removeClass("select_on").end().addClass("select_on");
});

var id = $(".select_top a")[0].id;
if(url_name && url_id){
	getCategory(url_id);
}else if(url_list == 2){
	getCategory(one_type);
}else{
	getCategory(id);
}

function getCategory(id,number_type){
	if(!number_type){
		number_type = 1
	}
    $(".londing_gif1").show();
	$.post("<?php echo $this->url('web-common',array('controller' => 'Video','action' => 'getCategory'));?>",{id : id},function(result){
		$(".classify").html('');
		$(".classify").append("<span class='select_on' id="+0+" onclick='getDataList("+id+','+0+','+1+")'>全部</span>");
		$.each(result,function(i,v){
		     $(".classify").append("<span id="+v.id+" onclick='getDataList("+id+','+v.id+','+1+")'>"+v.name+"</span>");
		});
		$("#classifys span").on("click",function(){
			$(this).siblings().removeClass("select_on").end().addClass("select_on");
		});

	   if(number_type == 2){
		   url_list = 0;
	   }
       if(url_list == 2){
    	   getDataList(one_type,two_type,1);
    	   $('#classifys .select_on').attr('class','');
    	   $('#classifys #'+two_type).attr('class','select_on');
//     	   console.log(one_type);
//     	   console.log(two_type);
       }else{
    	   getDataList(id,0,1);
       }
      
	},'json');
	
}

var finished = false;
var page = 1;
// getDataList(id,0);
function getDataList(sid,pid,type){
	sessionStorage.setItem('one_type', sid);
	sessionStorage.setItem('two_type', pid);
     if (finished && type == 2) {
         console.log(1);
         return false;
     }
     $('.londing_gif1').show();
     if(type == 1){
    	 page = 1;
     }
     finished = true;
    console.log(1);
     var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxgetDataList'))?>";
     $.post(url,{page:page,oid:sid,tid:pid},function(data) {
         var dom = $("#video_curriculums_list ul");
         var li = '';
         $('.londing_gif1').hide();
         if (data.length > 0) {            
             if (data.length > 0) {
                 $.each(data,function(i,v){
                    var play_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/player.png';
                    var detail_img = "<?php echo ROOT_PATH;?>webStyle/images/gray_more.png";
                     if(v.type == 2){
                         var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'details'))?>";
                         var image = "<?php echo ROOT_PATH.UPLOAD_PATH."/";?>"+v.image_path;
                         var ids = [v.id,2];
                         li += '<li>';
                         li += '<a href='+url+'?id='+ids+'&type='+2+'>';
                         li += '<div class="cover"><img class="video_image" src="'+image+'" alt="">';
                         li += '<img class="player" src="'+play_img+'" alt="">';
                         li += '</div>';
                         
                         li += '<div class="content">';
                         li += '<div>'+v.title+'</div>';
                         //li += '<div class="teacher_name">'+v.teacher_name+'</div>';
                         li += '<div class="information">';
                         li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
                         li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
                         li += '</div></div>';
                         li += '<div class="more">';
                         li += '<img src="'+detail_img+'" alt="">';
                         li += '</div></a></li>';
                     }else{
                    	 var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'details'))?>";
                    	 var time_img = '<?php echo ROOT_PATH;?>webStyle/images/clock.png';
                         var image = "<?php echo ROOT_PATH.UPLOAD_PATH."/";?>"+v.image_path;
                         var ids = [v.id,1];
                         li += '<li>';
                         li += '<a href='+url+'?id='+ids+'&type='+1+'>';
                         li += '<div class="cover"><img class="video_image" src="'+image+'" alt="">';
                         li += '<img class="player" src="'+play_img+'" alt="">';
                         li += '</div>';
                         
                         li += '<div class="content">';
                         li += '<div>'+v.title+'</div>';
                         li += '<div class="teacher_name">'+v.teacher_name;
                         if(v.count != "0%"){
                             if(v.count != "100%"){
                            	 li += '<span class="ml40"><span>已播</span><span class=" font_color_055773">'+v.count+'</span></span>';
                             }else{
                            	 li += '<span class="ml40 ">已学完</span>';
                             }
                         }
                         li += '</div>'
                         li += '<div class="information2">';
                         if(v.price == '仅限会员'){
                        	 li += '<div><span class="font_color_055773">'+v.price+'</span></div>';
                         }else{
                        	 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
                         }
                         li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
                         li += '</div></div>';
                         li += '<div class="more">';
                         li += '<img src="'+detail_img+'" alt="">';
                         li += '</div></a></li>';
                     }
                 });
                 if(type == 1){
                	 $('#video_curriculums_list ul li').remove();
                 }  
                 $("#video_curriculums_list ul").append(li);
                 finished = false;
                 page ++;
             }
         }
         else {
             if(type == 1){
            	 $('#video_curriculums_list ul li').remove();
             }         	
         }
         $(".londing_gif1").hide();
     },'json')
}

function loadmore(obj){    
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=120) {
        //console.log(scrollHeight - scrollTop - windowHeight);
    	sid = $(".select_top .select_on")[0].id;
    	pid = $("#classifys .select_on")[0].id
    	getDataList(sid,pid,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});


$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".home_footer ul li img").css({"margin-bottom":"4px"})
    }

}); 




window.onload=function(){
    $(".londing_gif1").show();
    // alert(1);
}
</script>