<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<!--省市区json文件-->
<script src="<?php echo $this->basePath() . '/adminStyle/js/jq_area.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/adminStyle/js/region.js'?>"  type="text/javascript"></script>

<style>
    .controls span {
        color: red;
    }

    .controls input {
        height: 25px;
    }
    .form-horizontal>div{
        margin-left: 20px !important;
    }
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>

<div class="page-header">
    <h1>
        用户详情
    </h1>
</div>
<form class="form-horizontal" role="form" method="post" id="form">
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right" style="font-size:20px;font-weight: bold">基本信息</label>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 昵称：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->nick_name?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 真实姓名：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->real_name?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 手机号码：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->mobile?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right" > 性别：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->sex?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 个性签名：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->description?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 注册时间：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->timestamp?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 最后登陆时间：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $userInfo->last_login_time?></span>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 用户地址：</label>
        <div class="col-sm-9" id="element_id">
            <span id="location">
            <select id="provinceId" name="province_id" style="width: 100px;border-radius:10px;" disabled></select>
            <select id="cityId" name="city_id" style="width: 100px;border-radius:10px;" disabled></select>
            <select id="countyId" name="county_id" style="width: 100px;border-radius:10px;" disabled></select>
            </span>
            <input type="text" name="street" value="<?php echo $userInfo->street?>" placeholder="填入详细街道信息" disabled/>
        </div>
    </div>

    <div class="form-group">

        <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 用户头像：</label>
        <div class="col-sm-9">
            <div class="mot_tright" id="img_div">
<!--                <input id="one_img_upload" type="file"/>-->
                <div id="res_img">
                    <?php if(isset($userInfo['head_filename'])){?>
                        <div id="img_url" class="outdiv">
                            <img src="<?php echo UPLOADFILIS_ROOT.$userInfo['head_path'].$userInfo['head_filename'] ?>"  width = '100px'>
                            <div id='near_img' onmouseout='del3(this)' onclick='$("#res_img").html("")' class='innerdiv'>删除</div>
                            <input value="<?php echo $userInfo['head_image_id']?>" name='image_id' type='hidden'>
                        </div>
                    <?php }?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">

        <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 用户背景图片：</label>
        <div class="col-sm-9">
            <div class="mot_tright" id="img_div2">
<!--                <input id="one_img_upload2" type="file"/>-->
                <div id="res_img2">
                    <?php if(isset($userInfo['back_filename'])){?>
                        <div id="img_url" class="outdiv">
                            <img src="<?php echo UPLOADFILIS_ROOT.$userInfo['back_path'].$userInfo['back_filename'] ?>"  width = '100px'>
                            <div id='near_img' onmouseout='del3(this)' onclick='$("#res_img2").html("")' class='innerdiv'>删除</div>
                            <input value="<?php echo $userInfo['back_image_id']?>" name='image_id2' type='hidden'>
                        </div>
                    <?php }?>
                </div>
            </div>
        </div>
    </div>

    <!--<div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <input type="hidden" name="id" value="<?php echo $Info->id?>">
            <button class="btn btn-info" type="submit" id="submit">
                <i class="ace-icon fa fa-check bigger-110"></i>
                保存
            </button>
            <a class="btn" onclick="window.history.back()">
                <i class="ace-icon fa fa-undo bigger-110"></i>
                取消
                <a/>
        </div>
    </div>-->
</form>

<script>
    $("#location").area({
        provinceId:"#provinceId",cityId:"#cityId",countyId:"#countyId",
        cache: region,
        p_id:<?php echo isset($region[0]['region']['id']) ? $region[0]['region']['id'] : '440000'?>,
        ci_id:<?php echo isset($region[1]['region']['id']) ? $region[1]['region']['id'] : '440100'?>,
        co_id:<?php echo isset($region[2]['region']['id']) ? $region[2]['region']['id'] : '440103'?>,
    });
</script>