<style>
	.controls>label {
		padding-top : 5px;
	}
	.l-n {
		list-style-type: none;
	}
	.fl {
		float: left;
	}
	.m-t-10 {
		margin-top: 10px;
	}
	.fr {
		float: right;
	}
	.form-horizontal .control-label {
		width: 80px;
		text-align: left;
		margin-left: 40px;
	}
	.form-horizontal .controls {
		margin-left: 140px;
	}
	.del-btn {
		height: 46px;
		width: 150px !important;
		border: 1px solid #43a1da;
		background: #fff;
		border-radius: 3px;
	}
	
	.reward-sum{
		padding: 0 10px;
		margin:10px 0;
	}
	.reward-review {
		padding: 12px;
		margin-top: 18px;
		background-color: #f5f5f5;
		border: 1px solid #e5e5e5;
	}
	.stop-text {
		display: inline-block;
		border: 2px solid red;
		width: 70px;
		height: 19.4px;
		text-align: center;
		line-height: 19.4px;
		color: red;
		margin-left: 20px;
	}
	.start-text {
		display: inline-block;
		border: 2px solid green;
		width: 70px;
		height: 19.4px;
		text-align: center;
		line-height: 19.4px;
		color: green;
		margin-left: 20px;
	}
</style>
<div id="content" class="span10">
	<div>
		<ul class="breadcrumb">
			  <li><span>用户管理</span><span class="divider">/</span></li>
			<li>
				<a href="<?php echo $this->url( 'admin', array('controller' => 'User'));?>">用户列表</a>
				<span class="divider">/</span>
			</li>
			<li>
				<a href="#">用户详情</a>
			</li>
		</ul>
	</div>
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
				<form action="" method="post" class="form-horizontal">
					<fieldset>
						<legend class="lg_title">
							<span>用户信息：</span>
						</legend>
						<section style="position: relative; overflow: hidden;">
							<div style="float: left;">
								<div class="control-group">
									<label class="control-label">用户名：</label>
									<div class="controls">
										<label style="display: inline-block;"><?php echo $data['name'];?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">职务：</label>
									<div class="controls">
										<label><?php echo $data['p_name']?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">性别：</label>
									<div class="controls">
										<label><?php echo $data['sex']==1?'男':'女';?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">手机号码：</label>
									<div class="controls">
										<label><?php echo $data['mobile']?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">所在地区：</label>
									<div class="controls">
										<label><?php echo  $data['region']?$data['region']:'';//中国-广东省-广州市?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">是否会员：</label>
									<div class="controls">
										<label><?php echo  $data['member_time'] > date('Y-m-d H:i',time()) ? '是（'.date('Y-m-d',strtotime($data['member_time'])).'到期）':'不是';?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">钱包余额：</label>
									<div class="controls">
										<label><?php echo $data['amount'].'元'?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">消费总额：</label>
									<div class="controls">
										<label><?php echo $data['consumption'].'元'?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">注册时间：</label>
									<div class="controls">
										<label><?php echo $data['timestamp']?></label>
									</div>
								</div>
									<div class="control-group">
									<label class="control-label">推荐人数：</label>
									<div class="controls">
										<label><?php echo $data['stair_num']?></label>
									</div>
								</div>
									<div class="control-group">
									<label class="control-label">个性签名：</label>
									<div class="controls">
										<label><?php echo $data['signature']?></label>
									</div>
								</div>
						
							</div>
							<div style="position: absolute;top: 0;right: 75px;">
								<img style="width:150px;height: 150px; " src="<?php echo $data['img_path']?$this->basePath(). '/'.UPLOAD_PATH.$data['img_path'] :$data['head_icon'];?>">
							</div>
						</section>	
						<legend class="lg_title">
						 <span>Ta的课程：</span>
						</legend>
<!-- 	列表 -->
		                <div id="course_list"></div>
<!-- 列表 -->
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//var rewardList_url = '<?php //echo $this->url('admin',array('controller'=>'User','action'=>'getUserCourseList','id'=>$id));?>';//page;+'/p'+1
var loadmore_type = 1;
function getRewardList(page,type) {
	var rewardList_url = '<?php echo $this->url('admin',array('controller'=>'User','action'=>'getUserCourseList','id'=>$data['id']));?>'+'/p'+page;//page;+'/p'+1
	  if (rewardList_url) {
	    $.post(rewardList_url, {page:page,id:<?php echo $data?$data['id']:0;?>,type:type},function (data) {
//	    	console.log(data);return;
// 	    	rewardTemplate(data, 'reward_list');
// 	    	rewardTemplate2(data,'reward_page');
	    $('#course_list').html('');//清空
        $("#course_list").append(data)
	    },"html");
	  }
	}
	
function rewardList(page,type){
// 	 $('#reward_page').html('');//清空
	  getRewardList(page,type);
}
$(document).ready(function(){
	  // 1打赏；
	  if (loadmore_type == 1) {
		  getRewardList(1,0);
	  }
	});
</script>