<!-- 	列表 -->
	<div class="btn-group pull-right">
          <div class="pull-left ml8" >
                <div class="" style="display:inline-block;">
                 <span>课程类型：</span>
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 114px;">
       <!-- 		<i class="icon-user"></i> -->
    				<span class="hidden-phone"><?php echo $where['type']?($where['type']==1 ? '音频课程' : '视频课程'):'全部课程类型' ?></span>
    				<span class="caret"></span>
    			</a>
    			<ul class="dropdown-menu">
    			<li><a href="javascript:rewardList(1,0);">全部课程</a></li>
    					<li class="divider"></li>
    				<li><a href="javascript:rewardList(1,1);">音频课程</a></li>
    					<li class="divider"></li>
    				<li>
    					<a href="javascript:rewardList(1,2);">视频课程</a>
    				</li>
    			</ul>
    			</div>
		</div>   
	</div>

	<div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>课程类型</th>
                <th>课程名称</th>
                <th>课程导师</th>
                <th>获得时间</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th><?php echo$v['type']==1?'音频':'视频' ;?></th>
                <td><?php echo $v['title'];?></td>
                <td><?php echo $v['t_name'];?></td>
                <td><?php echo $v['timestamp'];?></td>
            </tr>
            <?php }?>
            </tbody>
        </table>
        <div class="page-control">
        <div class="pagination pagination-centered">
        <?php  if($page_info['pagesInRange']){if($page_info['previous']){?>
		       <ul><li class="disabled"><a>首页</a></li><li class="disabled"><a>上一页</a></li>
		   <?php }else{?> 
		    	<ul><li><a href="javascript:rewardList(1,<?php echo $where['type']?>);">首页</a></li><li><a href="javascript:rewardList(<?php echo $page_info['page_1'].','.$where['type'];?>);">上一页</a>
		    <?php }foreach ($page_info['pagesInRange'] as $i=>$val){if($val==$page_info['page']){?>
			    		 <li class="active"><a><?php echo $val;?></a></li>
	    	 <?php }else{?> 
			    		 <li><a href="javascript:rewardList(<?php echo $val.','.$where['type'];?>);"><?php echo $val;?></a></li>
			    <?php }}if($page_info['net']){?>
		        <ul><li class="disabled"><a>下一页</a></li><li class="disabled"><a>尾页</a></li>
		 <?php }else{?> 
		    	<ul><li><a href="javascript:rewardList(<?php echo $page_info['page_2'].','.$where['type'];?>);">下一页</a></li><li><a href="javascript:rewardList(<?php echo $page_info['total'].','.$where['type'];?>);">尾页</a></li>
		    <?php }}?>
        <?php // echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
       </div>
    </div>
      <!--/span-->
</div>
</div>
<!-- 列表 -->
	