<!-- <script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script> 
<script src="<?php echo $this->basePath();?>/jedate/jedate.js"></script>-->
<?php  $arr = $condition['where'];?>
<style>
.select {
    border:1px solid #ccc;
    border-radius: 3px;
    width:115px;
}
</style>
<ul class="breadcrumb">
    <li><span>用户管理</span><span class="divider">/</span></li>
    <li> <a href="#">用户列表</a></li>
</ul>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        
        <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'User', 'action' => 'index'));?>">
<!--             
            <div class="pull-left ml8" style="margin-left:30px;">
                <a href="<?php echo $this->url('admin', array('controller' =>'User', 'action' => 'add'));?>" class="btn btn-info">新增专家</a>
           </div>
   -->         
         <div class="pull-left ml8" style="margin-left:30px;">
               <span class="l_f">
                 <a href="<?php echo $this->url('admin',array('controller' => 'User', 'action'=>'getExcel')).'?'.http_build_query($arr);?>"  class="btn btn-purple btn-primary btn-sm">导出excel</a>
               </span>
          </div>
          
            <div class="pull-right">
         
               <div class="pull-left ml8" style="position: relative">
            <input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入用户名、手机号" value="<?php echo $arr['keyword']?>">
            <i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
            </div>
            <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin-left:15px">
                  <select name="cid" size="1" class="select">
                    <option value="0" >全部职务</option>
                    <?php if($position){foreach ($position as $v){?>
                    <option value="<?php echo $v['id']?>" <?php echo $arr['cid']==$v['id']?'selected="selected"':''?>><?php echo $v['name']?></option>
                    <?php }}?>
                  </select>
            </div>
        </div>
        <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin-left:15px">
                  <select name="sex" size="1" class="select">
                    <option value="0" >全部性别</option>
                    <option value="1" <?php echo $arr['sex']==1?'selected="selected"':''?>>男</option>
                    <option value="2" <?php echo $arr['sex']==2?'selected="selected"':''?>>女</option>
                  </select>
            </div>
        </div>
           <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px;">
                  <select name="status" size="1" class="select">
                    <option value="0" >全部账号状态</option>
                    <option value="1" <?php echo $arr['status']==1?'selected="selected"':''?>>正常</option>
                    <option value="2" <?php echo $arr['status']==2?'selected="selected"':''?>>禁用</option>
                  </select>
            </div>
        </div>
        <div class="pull-left ml8" >
            <button type="submit" class="btn btn-info submit">搜索</button>
        </div>
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>头像</th>
                <th>用户名</th>
                <th>手机号码</th>
                <th>性别</th>
                <th>职务</th>
                <th>消费总额(元)</th>
                <th>注册时间</th>
                <th>帐号状态</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th>
                    <img src="<?php echo $v['img_path']?($this->basepath().'/'.UPLOAD_PATH.'thumb/640X640X4/'.$v['img_path']):$v['head_icon']?>" width="100" height="100">
                </th>
                <th><?php echo$v['name'] ;?></th>
                <td><?php echo $v['mobile'];?></td>
                <td><?php echo $v['sex']==1?'男':'女';?></td>
                <td><?php echo $v['p_name'];?></td>
                <td><?php echo $v['consumption'];?></td>
                <td><?php echo $v['timestamp'];?></td>
                <td id="statusDesc<?php echo $v['id'];?>"><?php echo $v['status']==1?'正常':'禁用';?></td>
                <td>
                 <input type="button" id="statusSwitch<?php echo $v['id']?>" onclick="statusSwitch('<?php echo $v['id']?>')"  class="btn <?php echo $v['status'] == 1 ? 'btn-warning' : 'btn-success';?>" value="<?php echo $v['status'] == 1 ? '禁用' : '启用';?>" status="<?php echo $v['status'];?>" />
                     <a href="<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'details', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
                </td>
            </tr>
            <?php }?>
            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'Social', 'action' => 'delete'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
			<input type="hidden" name="id" value="" id ="social_id">
			<input type="hidden" name="remark" id ="remark2">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
			<input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
		</div>
	</form>
</div>

<script src="<?php echo $this->basepath()?>/adminStyle/js/custom_common.js"></script>
<script type="text/javascript">
var statusSwitchUrl = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'ajaxDelete'));?>';
</script>

<script type="text/javascript">
function ajaxDelete(id,type){
	var url = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'ajaxDelete'));?>';
	$.post(url,{id:id,type:type},function(data){
	    if(data.code==200){
		    if(type ==1){//启用
		    	$('#id-'+id).html('禁用');
		    	$('#id-'+id).attr('onclick','ajaxDelete('+id+',2)');
		    	$('#id-'+id).attr('class','btn btn-warning');
		    }else{
		    	$('#id-'+id).html('启用');
		    	$('#id-'+id).attr('onclick','ajaxDelete('+id+',1)');
		    	$('#id-'+id).attr('class','btn btn-success');
		    }
		    return;
	    }
	    alert(data.message);return;
	},'json');
}
function deleteSocial(id){
	 $('#social_id').val(id);
// 	$('#remark3').val(remark);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>