<div class="page-header">
    <h1>
        用户管理
    </h1>
</div>
<div class="page-header">
    <form action="<?php echo $this->url('admin-user', ['action' => 'index']) ?>">
<!--        <a href="javascript:downloadUser();" class="btn btn-xs btn-primary">导出用户</a>-->
        <div style="float: right">
            用户状态：
            <select name="status" id="status">
                <?php foreach ($statusArr as $k=>$v) { ?>
                    <option value="<?php echo $k ?>" <?php if ($status == $k) echo 'selected'; ?>><?php echo $v ?></option>
                <?php } ?>
            </select>
            <select name="type"  id='type'>
                <option value="0">全部</option>
                <option value="1" <?php if ($type == 1) echo 'selected'; ?>>手机号</option>
                <option value="2" <?php if ($type == 2) echo 'selected'; ?>>昵称</option>
            </select>
            <input type="text" id="keyword" name="keyword" value="<?php echo $keyword; ?>" placeholder="请输入搜索内容">
            <button class="btn btn-xs btn-primary" type="submit">搜索</button>
        </div>
    </form>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>昵称</th>
                <th>真实姓名</th>
                <th>手机号码</th>
                <th>地址</th>
                <th>注册日期</th>
                <th>最后登录时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody id="data">
            <?php foreach ($list as $v) { ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('admin-user', ['action' => 'details', 'id' => $v->id]) ?>"><?php echo $v->nick_name ?></a>
                    </td>
                    <td><?php echo $v->real_name ?></td>
                    <td><?php echo $v->mobile ?></td>
                    <td><?php echo $v->address ?></td>
                    <td><?php echo $v->timestamp ?></td>
                    <td><?php echo $v->last_login_time ?></td>
                    <td><span class="label <?php echo $v->status == 1 ? 'label-success' : 'label-danger'?>"><?php echo $statusArr[$v->status] ?></span></td>
                    <td>
                        <div class="hidden-sm hidden-xs action-buttons">
                            <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-user', ['action' => 'details', 'id' => $v->id]) ?>">查看</a>
                            <input type="hidden" name="id" value="<?php echo $v->id;?>">
                            <?php if ($v->status == 1) { ?>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认禁用该用户吗？',changeUserStatus,'',this)">禁用</a>
                            <?php } else { ?>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认启用该用户吗？',changeUserStatus,'',this)">启用</a>
                            <?php } ?>
                        </div>
                        <div class="hidden-md hidden-lg">
                            <div class="inline pos-rel">
                                <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                    <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                </button>

                                <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                    <li>
                                        <?php if ($v->status == 1) { ?>
                                        <a onclick="confirm_handle('确认禁用该用户吗？',changeUserStatus,'',this)" class="tooltip-success" data-rel="tooltip" title="禁用">
                                            <span class="red">
                                                禁用
                                            </span>
                                        </a>
                                        <?php } else { ?>
                                            <a onclick="confirm_handle('确认启用该用户吗？',changeUserStatus,'',this)" class="tooltip-success" data-rel="tooltip" title="启用">
                                            <span class="red">
                                                启用
                                            </span>
                                        </a>
                                        <?php } ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php } ?>

        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-user', 'condition' => $condition)); ?>
    </div>
</div>
<script>
    //禁用启用用户帐号
    function changeUserStatus(obj) {
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('admin-user', ['action' => 'changeStatus']) ?>",
            data: {"id": id},
            dataType: "JSON",
            async: false,
            success: function (data) {
                if(data.s){
                    showMessage('操作失败！',2);
                }else{
                    showMessage('操作成功！',1);
                    location.reload();
                }
            },
            error: function (res) {
                console.log(res,'error');
            }
        });
    }
    //function downloadUser() {
    //    var length = $('#data').find('tr').length;
    //    if(length <= 0){
    //        showMessage('暂无数据可导！',0);
    //        return false;
    //    }
    //    var url = '<?php //echo $this->url('admin-user', array('action' => 'dumpExcel')); ?>//' + '?type=' + $('#type').val() + '&keyword=' + $('#keyword').val() + '&grade=' + $('#grade').val();
    //    window.location.href = url;
    //}
</script>
