<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<!--富文本编辑器-->
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/themes/default/default.css'?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.css'?>" media="screen" rel="stylesheet" type="text/css">

<script src="<?php echo $this->basePath() . '/plugins/kindeditor/kindeditor-all.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/lang/zh-CN.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.js'?>"  type="text/javascript"></script>

<style>
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>
<div class="page-header">
    <h1>
        资讯详情
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" role="form" action="<?php echo $this->url('admin-article', ['action'=>'details']) ?>" method="post">
        <input value="<?php echo $info->id?>" name="id" type="hidden">
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 标题：</label>

            <div class="col-sm-9">
                <input type="text" name="title" required id="form-field-1" placeholder="标题" value="<?php echo $info->title?>" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 概述：</label>

            <div class="col-sm-9">
                <textarea rows="8" cols="60" name="abstract"><?php echo $info->abstract?></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 分类：</label>

            <div class="col-sm-9">
                <select name="category_id" class="col-xs-10 col-sm-5">
                    <?php if(!$category_list){?>
                        <option value="0">请先添加资讯分类</option>
                    <?php }else{?>
                    <option value="0">请选择分类</option>
                    <?php foreach ($category_list as $v) {?>
                        <option value="<?php echo $v->id?>" <?php echo $v->id == $info->category_id?"selected":""?>><?php echo $v->name?></option>
                    <?php }}?>
                </select>
            </div>
        </div>

        <!-- 一次上传多张图片插件 -->
        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 资讯封面：</label>
            <div class="col-sm-9">
                <div class="mot_tright" id="img_div">
                    <input id="one_img_upload" type="file"/>
                    <div id="res_img">
                        <img style="width: 280px;height:210px;" src="<?php echo UPLOADFILIS_ROOT.$info->path.$info->filename?>">
                        <input value="<?php echo $info->image_id?>" name="image_id" type="hidden">
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1-1">资讯正文：</label>

            <div class="col-sm-9">
                <textarea name="content" style="width:80%;height:600px;visibility:hidden;"><?php echo $info->content?></textarea>
            </div>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a href="javascript:history.back(-1);" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
<script>
    var editor;
    KindEditor.ready(function(K) {
         editor = K.create('textarea[name="content"]', {
             afterBlur: function () { this.sync(); }
        });
    });
    $('form').submit(function (e) {
        ajaxForm(e);
    });
</script>
