<div class="page-header">
    <h1>
        资讯列表
    </h1>
</div>

<div class="page-header">
    <a href="<?php echo $this->url('admin-article', ['action' => 'articleAdd']) ?>" class="btn btn-xs btn-primary">发布资讯</a>
    <form action="<?php echo $this->url('admin-article', ['action' => 'index']) ?>">
    <!--        <a href="javascript:downloadUser();" class="btn btn-xs btn-primary">导出用户</a>-->
        <div style="float: right">
            资讯分类：
            <select name="category_id">
                <option value="0">全部</option>
                <?php foreach ($categoryList as $v) { ?>
                    <option value="<?php echo $v->id ?>" <?php if ($category_id == $v->id) echo 'selected'; ?>><?php echo $v->name ?></option>
                <?php } ?>
            </select>
            搜索：
            <input type="text" name="keyword" value="<?php echo $keyword; ?>" placeholder="请输入关键字">
            <button class="btn btn-xs btn-primary" type="submit">搜索</button>
        </div>
    </form>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>封面图</th>
                <th>标题</th>
                <th>概述</th>
                <th>分类</th>
                <th>阅读量</th>
                <th>发布人</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <input type="hidden" name="id<?php echo $k ?>" value="<?php echo $v->id ?>">
                        <td><?php echo $v->id?></td>
                        <td><img width="50" height="50" src="<?php echo '/uploadfiles/' . $v->path . $v->filename ?>"></td>
                        <td style="width:20%"><?php echo $v->title ?></td>
                        <td style="width:25%"><p style="display: -webkit-box;-webkit-box-orient: vertical;-webkit-line-clamp: 3;overflow: hidden;"><?php echo $v->abstract?></p></td>
                        <td><?php echo $v->category_name ?></td>
                        <td><?php echo $v->read_num ?></td>
                        <td><?php echo $v->admin_name ?></td>
                        <td>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-article', ['action' => 'details', 'id' => $v->id]) ?>">编辑</a>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认删除这条资讯吗？', del, '', this)">
                                    删除
                                </a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto" aria-expanded="false">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                        <li>
                                            <a href="<?php echo $this->url('admin-article', ['action' => 'details', 'id' => $v->id]) ?>" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="blue">
																				编辑
																			</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认删除这条资讯吗？', del, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="red">
																				删除
																			</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-article', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>

<script type="text/javascript">
    //单个删除
    function del(obj){
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url:  "<?php echo $this->url('admin-article', ['action' => 'del']) ?>",
            data: {"id":id} ,
            success:  function (msg) {
                layer.close(index);
                if(msg.s){
                    showMessage('删除失败', 0);
                }
                else if(msg.s == 0){
                    showMessage('删除成功', 1);
                    $(obj).parents('tr').remove();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }
</script>