<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/jedate.css" />
<script src="<?php echo $this->basePath();?>/js/jedate.min.js"></script>
<script src="<?php echo $this->basePath();?>/js/jeDate.setting.js"></script>
<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<!--富文本编辑器-->
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/themes/default/default.css'?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.css'?>" media="screen" rel="stylesheet" type="text/css">

<script src="<?php echo $this->basePath() . '/plugins/kindeditor/kindeditor-all.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/lang/zh-CN.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.js'?>"  type="text/javascript"></script>

<style>
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>
<div class="page-header">
    <h1>
        广告管理
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" role="form" action="<?php echo $this->url('admin-business', ['action'=>'adsAdd']) ?>" method="post">
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 广告名称：</label>

            <div class="col-sm-9">
                <input type="text" name="name" required id="form-field-1" placeholder="广告名称" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 排序序号：</label>

            <div class="col-sm-9">
                <input type="number" name="sort" min="1" required id="form-field-1" placeholder="排序序号" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right">开始时间：</label>

            <div class="col-sm-9">
                <div class="layui-input-inline">
                    <input type="text" name="start_time" readonly required class="form-control" id="start_time" maxlength="50" style="height: 30px;">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right">结束时间：</label>

            <div class="col-sm-9">
                <div class="layui-input-inline">
                    <input type="text" name="end_time" readonly  required class="form-control" id="end_time" maxlength="50" style="height: 30px;">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1-1">廣告位：</label>

            <div class="col-sm-9">
                <select name="position" id="position" lay-verify="">
                    <option value="1">首页</option>
                    <option value="2">視頻首页</option>
                    <option value="3">音頻首页</option>
                </select>
            </div>
        </div>
        <!-- 一次上传多张图片插件 -->
        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 广告图片：</label>
            <div class="col-sm-9">
                <div class="mot_tright" id="img_div">
                    <input id="one_img_upload" type="file"/>
                    <div id="res_img"></div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right"> 跳转类型：</label>

            <div class="col-sm-9">
                <select name="type" style="width: 25%;height: 38px" onchange="changeRunType(this)">
                    <option value="3">图文消息</option>
                    <option value="4">自定义链接</option>
                </select>
            </div>
        </div>
        <div class="form-group" id="runType1">
            <label class="col-sm-1 control-label " for="form-field-1-1">广告内容：</label>

            <div class="col-sm-9">
                <textarea name="content" style="width:80%;height:600px;visibility:hidden;"></textarea>
            </div>
        </div>
        <div class="form-group" id="runType2" style="display: none">
            <label class="col-sm-1 control-label no-padding-right"> 自定义链接：</label>
            <div class="col-sm-9">
                <input type="text" name="link" placeholder="链接地址" style="width:310px;" class="col-xs-10 col-sm-5">
                <span style="margin-left: 10px;">请输入带有https的链接地址</span>
            </div>

        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a href="javascript:history.back(-1);" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
</div>
</div>



<script>
    var editor;
    KindEditor.ready(function(K) {
         editor = K.create('textarea[name="content"]', {
             afterBlur: function () { this.sync(); }
        });
    });

    //选择类型
    function changeRunType(obj){
        if($(obj).val()==3){
            $('#runType1').show();
            $('#runType2').hide();
        }else if($(obj).val()==4){
            $('#runType1').hide();
            $('#runType2').show();
        }
    }

    var type = $('select[name="type"] option:selected').val();
    if(type == 3){
        $('#runType1').show();
        $('#runType2').hide();
    }
    else if(type == 4){
        $('#runType1').hide();
        $('#runType2').show();
    }
</script>

<script type="text/javascript">
    $('form').submit(function (e) {
        if(!dateValidate()){
            return false;
        }
        if(!$('input[name="image_id"]').val()){
          showMessage('必须选择图片', 0);
          return false;
        }
        if($('select[name="type"]').val() == 3){
            if(!$('textarea[name="content"]').val()){
                showMessage('图文详情不能为空', 0);
                return false;
            }
        }
        else if($('select[name="type"]').val() == 4){
            if(!$('input[name="link"]').val()){
                showMessage('自定义链接不能为空', 0);
                return false;
            }
            if(!/^https?:\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?$/.test($('input[name="link"]').val())){
                showMessage('自定义链接不合法', 0);
                return false;
            }
        }
        ajaxForm(e);
    });
</script>
