<div class="page-header">
    <h1>
        广告管理
    </h1>
</div>
<div class="page-header">
    <form action="<?php echo $this->url('admin-business', ['action' => 'adsList']) ?>"  method="get">
        <a href="<?php echo $this->url('admin-business', ['action' => 'adsAdd']) ?>" class="btn btn-xs btn-primary">新增广告</a>
        <div style="float: right">
            <button type="button" style="margin-right:50px;" class="btn btn-xs btn-info" onclick="saveSort()">保存排序</button>
            廣告位：
            <select name="position">
                <?php foreach ($positions as $k=>$v){?>
                <option value="<?php echo $k?>" <?php if(isset($where['position']) && $where['position'] == $k) echo 'selected' ?>><?php echo $v?></option>
                <?php }?>
            </select>
            <button class="btn btn-xs btn-primary" type="submit" name="submit">搜索</button>
        </div>
    </form>
</div>

<!-- PAGE CONTENT BEGINS -->
<!--<div class="table-header" style="margin-top: 20px;">
    导航管理
</div>-->

<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>广告位</th>
                <th>广告名称</th>
                <th>开始时间</th>
                <th>结束时间</th>
                <th>排序</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <input type="hidden" name="id<?php echo $k ?>" value="<?php echo $v->id ?>">
                        <td>
                            <?php echo $v->id ?>
                        </td>
                        <td><?php echo $positions[$v->position]?></td>
                        <td><?php echo $v->name ?></td>
                        <td><?php echo $v->start_time ?></td>
                        <td><?php echo $v->end_time ?></td>
                        <td><input data-id="<?php echo $v->id?>" class="sort" style="width: 80px;" type="number" value="<?php echo $v->sort ?>"/></td>
                        <td>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-business', ['action' => 'adsEdit', 'id' => $v->id]) ?>">编辑</a>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认删除这个广告吗？', del, '', this)">
                                    删除
                                </a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto" aria-expanded="false">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close"><li>
                                            <a href="<?php echo $this->url('admin-business', ['action' => 'adsEdit', 'advert_id' => $v->id]) ?>" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="blue">
																				编辑
																			</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认删除这个广告吗？', del, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="red">
																				删除
																			</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-business', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>

<script type="text/javascript">
    //单个删除
    function del(obj){
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url:  "<?php echo $this->url('admin-business', ['action' => 'adsDel']) ?>",
            data: {"id":id} ,
            success:  function (msg) {
                layer.close(index);
                if(msg.s){
                    showMessage('删除失败', 0);
                }else{
                    showMessage('删除成功', 1);
                    $(obj).parents('tr').remove();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }

    function saveSort(){
        var sortObject = {};
        $.each($('.sort'),function(i,v){
            var sort_value = v.value;
            var id = $(this).attr('data-id');
            sortObject[id] = sort_value;
        });
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url:  "<?php echo $this->url('admin-business', ['action' => 'saveAdsSort']) ?>",
            data: {sortObject: sortObject},
            success:  function (data) {
                layer.close(index);
                if(data.s){
                    showMessage(data.d, 0);
                }else{
                    showMessage(data.d, 1);
                    location.reload();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }
</script>

