<div class="page-header">
    <h1>
        导航管理
    </h1>
</div>

<div class="page-header">
    <a href="<?php echo $this->url('admin-business', ['action' => 'navigationAdd']) ?>" class="btn btn-xs btn-primary">新增导航</a>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>板块名称</th>
                <th>图标</th>
                <th>导航名称</th>
                <th>跳转类型</th>
                <th>外部链接</th>
                <th>排序序号</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <input type="hidden" name="id<?php echo $k ?>" value="<?php echo $v->id ?>">
                        <td>
                            <?php
                            if ($v->type == 1) {
                                echo '首页';
                            } else if ($v->type == 2) {
                                echo '商城首页';
                            } else if ($v->type == 3) {
                                echo '服务首页';
                            } else if ($v->type == 4) {
                                echo '门店首页';
                            }
                            ?>
                        </td>
                        <td><img width="50" height="50" src="<?php echo '/uploadfiles/' . $v->path . $v->filename ?>"></td>
                        <td><?php echo $v->name ?></td>
                        <td>
                            <?php
                            if ($v->from_type == 1) {
                                echo '外部链接';
                            } else if ($v->from_type == 2) {
                                echo '视频';
                            } else if ($v->from_type == 3) {
                                echo '音频';
                            } else if ($v->from_type == 4) {
                                echo '资讯';
                            }
                            ?>
                        </td>
                        <td><?php echo $v->link ?></td>
                        <td><?php echo $v->sort ?></td>
                        <td>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-business', ['action' => 'navigationDetails', 'id' => $v->id]) ?>">编辑</a>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认删除这个导航吗？', del, '', this)">
                                    删除
                                </a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto" aria-expanded="false">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close"><li>
                                            <a href="<?php echo $this->url('admin-business', ['action' => 'navigationDetails', 'navigation_id' => $v->id]) ?>" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="blue">
																				编辑
																			</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认删除这个导航吗？', del, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="red">
																				删除
																			</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-business', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>

<script type="text/javascript">
    //单个删除
    function del(obj){
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',

            url:  "<?php echo $this->url('admin-business', ['action' => 'navigationDel']) ?>",

            data: {"id":id} ,

            success:  function (msg) {
                layer.close(index);
                if(msg.s){
                    showMessage('删除失败', 0);
                }
                else if(msg.s == 0){
                    showMessage('删除成功', 1);
                    $(obj).parents('tr').remove();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }
</script>