<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<style>
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>
<div class="page-header">
    <h1>
        导航管理
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" role="form" action="<?php echo $this->url('admin-business', ['action'=>'navigationDetails', 'id'=>$navigation_info->id]) ?>" method="post">
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 导航名称：</label>

            <div class="col-sm-9">
                <input type="text" name="name" value="<?php echo $navigation_info->name ?>" required id="form-field-1" placeholder="导航名称" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <!--<div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1-1">板块名称：</label>

            <div class="col-sm-9">
                <select name="type" lay-verify="">
                    <option value="1" <?php if($navigation_info->type == 1) echo 'selected'; ?>>首页</option>
                    <option value="2" <?php if($navigation_info->type == 2) echo 'selected'; ?>>商城首页</option>
                    <option value="4" <?php if($navigation_info->type == 4) echo 'selected'; ?>>门店首页</option>
                    <option value="3" <?php if($navigation_info->type == 3) echo 'selected'; ?>>服务首页</option>
                </select>
            </div>
        </div>-->
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1">跳转链接：</label>

            <div class="col-sm-9">
                <input type="url" value="<?php echo $navigation_info->link ?>" name="link" required id="form-field-1" placeholder="" class="col-xs-10 col-sm-5">
                <label class="col-sm-1 control-label " for="form-field-1" style="width:200px;">请输入带有https的链接地址</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 排序序号：</label>

            <div class="col-sm-9">
                <input type="number" min="1" value="<?php echo $navigation_info->sort ?>" name="sort" required id="form-field-1" placeholder="排序序号" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <!-- 一次上传多张图片插件 -->
        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 导航图标：</label>
            <div class="col-sm-9">
                <div class="mot_tright" id="img_div">
                    <input id="one_img_upload" type="text"/>
                    <div id="res_img">
                        <?php if(isset($navigation_info['filename'])){?>
                            <div id="img_url" class="outdiv">
                                <img src="<?php echo '/uploadfiles/'.$navigation_info->path.$navigation_info->filename ?>" onmouseover='del1(this)'  width = '100px'>
                                <div id='near_img' onmouseout='del3(this)' onclick='$("#res_img").html("")' class='innerdiv'>删除</div>
                                <input value="<?php echo $navigation_info['icon']?>" name='image_id' type='hidden'>
                            </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a href="javascript:history.back(-1);" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
</div>
</div>




<script type="text/javascript">

    $('form').on('submit', function (e) {
        ajaxForm(e);
    });

</script>