<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<style>
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>
<div class="page-header">
    <h1>
        导航管理
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" role="form" action="<?php echo $this->url('admin-business', ['action'=>'navigationDetails', 'id'=>$navigation_info->id]) ?>" method="post">
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 导航名称：</label>

            <div class="col-sm-9">
                <input type="text" name="name" value="<?php echo $navigation_info->name ?>" required id="form-field-1" placeholder="导航名称" class="col-xs-10 col-sm-5">
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 排序序号：</label>

            <div class="col-sm-9">
                <input type="number" min="1" value="<?php echo $navigation_info->sort ?>" name="sort" required id="form-field-1" placeholder="排序序号" class="col-xs-10 col-sm-3">
            </div>
        </div>

        <!--<div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1-1">板块名称：</label>

            <div class="col-sm-9">
                <select name="type" lay-verify="">
                    <option value="1" <?php if($navigation_info->type == 1) echo 'selected'; ?>>首页</option>
                    <option value="2" <?php if($navigation_info->type == 2) echo 'selected'; ?>>商城首页</option>
                    <option value="4" <?php if($navigation_info->type == 4) echo 'selected'; ?>>门店首页</option>
                    <option value="3" <?php if($navigation_info->type == 3) echo 'selected'; ?>>服务首页</option>
                </select>
            </div>
        </div>-->
        <!-- 一次上传多张图片插件 -->
        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 导航图标：</label>
            <div class="col-sm-9">
                <div class="mot_tright" id="img_div">
                    <input id="one_img_upload" type="text"/>
                    <div id="res_img">
                        <?php if(isset($navigation_info['filename'])){?>
                            <div id="img_url" class="outdiv">
                                <img src="<?php echo '/uploadfiles/'.$navigation_info->path.$navigation_info->filename ?>" onmouseover='del1(this)'  width = '100px'>
                                <div id='near_img' onmouseout='del3(this)' onclick='$("#res_img").html("")' class='innerdiv'>删除</div>
                                <input value="<?php echo $navigation_info['icon']?>" name='image_id' type='hidden'>
                            </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 跳转类型：</label>
            <div class="col-sm-9">
                <select id="from_type" name="from_type" onchange="selectSource(this)">
                    <option value="1" <?php echo $navigation_info->from_type==1?"selected":""?>>外部链接</option>
                    <option value="2" <?php echo $navigation_info->from_type==2?"selected":""?>>视频</option>
                    <option value="3" <?php echo $navigation_info->from_type==3?"selected":""?>>音频</option>
                    <option value="4" <?php echo $navigation_info->from_type==4?"selected":""?>>资讯</option>
                </select>
            </div>
        </div>

        <div class="form-group" id="link" style="<?php echo $navigation_info->from_type == 1?"display:block":"display:none"?>">
            <label class="col-sm-1 control-label " for="form-field-1">跳转链接：</label>

            <div class="col-sm-9">
                <input type="url" value="<?php echo $navigation_info->link ?>" name="link" id="form-field-1" placeholder="" class="col-xs-10 col-sm-3">
                <label class="col-sm-1 control-label " for="form-field-1" style="width:200px;">请输入带有http|https的链接地址</label>
            </div>
        </div>

        <div style="<?php echo $navigation_info->from_type == 1?"display:none":"display:block"?>" id="local_source">
            <div class="form-group">
                <label class="col-sm-1 control-label">搜索：</label>

                <div class="col-sm-9">
                    <input type="text" id="search_key" placeholder="请先搜索，再选择来源" class="col-xs-10 col-sm-3">
                    &nbsp;&nbsp;<input type="button" class="btn btn-sm btn-info" value="搜索" onclick="searchSource()">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-1 control-label">来源</label>

                <div class="col-sm-9">
                    <select name="from_id" id="from_id">
                        <?php if(!$source){?>
                        <option value="0">数据不存在</option>
                        <?php }else{ ?>
                        <option value="<?php echo $source['id']?>"><?php echo $source['name']?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
        </div>

        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a href="javascript:history.back(-1);" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
</div>
</div>




<script type="text/javascript">

    $('form').on('submit', function (e) {
        ajaxForm(e);
    });

    function selectSource(obj){
        var from_type = $(obj).val();
        if(from_type == 1){
            $('#link').show();
            $('#local_source').hide();
        }else{
            $('#local_source').show();
            $('#link').hide();
        }
    }

    function searchSource(){
        var search_key = $('#search_key').val();
        var from_type = $('#from_type').val();
        if(!search_key){
            showMessage('请输入搜索关键字',0);return;
        }
        $.post(
            "<?php echo $this->url('admin-business', ['action'=>'searchList']) ?>",
            {from_type:from_type,search_key:search_key},
            function(data){
                $('#from_id').empty();
                var html = '';
                if(data.length > 0){
                    html = '<option value="0">请选择</option>';
                    $.each(data,function(i,v){
                        html += '<option value="'+v.id+'">'+v.name+'</option>'
                    });
                }else{
                    html = '<option value="0">数据不存在</option>';
                }
                $('#from_id').append(html);
            },'json'
        );
    }

</script>