<div class="page-header">
    <h1>
        举报列表
    </h1>
</div>

<div class="page-header">
    <form action="<?php echo $this->url('admin-business', ['action' => 'reportList']) ?>">
        <div style="float: right">
            分类：
            <select name="category_id">
                <option value="0">全部</option>
                <?php foreach ($categoryList as $v) { ?>
                    <option value="<?php echo $v->id ?>" <?php if ($category_id == $v->id) echo 'selected'; ?>><?php echo $v->name ?></option>
                <?php } ?>
            </select>
            举报对象类型：
            <select name="type">
                <option value="0">全部</option>
                <option value="1" <?php if ($type == 1) echo 'selected'; ?>>微博</option>
                <option value="2" <?php if ($type == 2) echo 'selected'; ?>>评论</option>
            </select>
            <button class="btn btn-xs btn-primary" type="submit">搜索</button>
        </div>
    </form>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>举报对象</th>
                <th>举报分类</th>
                <th>举报对象类型</th>
                <th>举报补充内容</th>
                <th>用户昵称</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <td><?php echo $v->obj_name?></td>
                        <td><?php echo $v->category_name ?></td>
                        <td><?php echo $v->type==1?"微博":"评论" ?></td>
                        <td><?php echo $v->content ?></td>
                        <td><?php echo $v->nick_name ?></td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-business', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>