<script src="<?php echo $this->basePath()?>/adminStyle/js/upload/jquery.uploadify.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath()?>/adminStyle/js/upload/uploadify.css">
<div id="content">
	<div>
		<ul class="breadcrumb">
			  <li><span>集团会员</span></li>
		</ul>
	</div>
	<div class="row-fluid sortable">
		<div class="box span12">
		    <div class="pannel">
               <div class="row" style="margin:15px;">
                  <div class="pull-right">
                   <div class="pull-left ml8" style="margin-left:30px;">
                       <span class="l_f">
                         <a href="<?php echo $this->url('admin',array('controller' => 'GroupMember', 'action'=>'getExcel'));?>"  class="btn btn-purple btn-primary btn-sm">下载导入模板</a>
                       </span>
                   </div>
                   <div class="pull-left ml8" style="margin-left:30px;">
                       <span class="l_f">
                         <a href="<?php echo $this->url('admin',array('controller' => 'GroupMember', 'action'=>'index2'));?>"  class="btn btn-purple btn-primary btn-sm">查看导入历史</a>
                       </span>
                   </div>
                </div>
            </div>
        </div>
		<div class="box-content" style="height: 675px;">
		        <form class="form-horizontal" method="post" action="<?php echo $this->url('admin', array('controller' =>'GroupMember', 'action' => 'addExcel'));?>">
				     <div class="ml8" style="margin-left:43.5%;height: 200px;margin-top: 60px;">
                       <span class="l_f2">
									<input id="file_success" name="images" type="hidden" >
									<input id="file_order" name="order" type="hidden" >
									<input id="file_upload2" name="file_upload" type="button" multiple="true" hidden>
 <!--                       <input type="button" value="导入集团用户表格" class="btn btn-purple btn-primary btn-sm" onclick="showFileUpload()"/>
 <!--                       <input id="file" name="file" type="file" style="display: none;" hidden onclick="showFileUpload2()"> 
                        <input type="file" name="file" id="file" /> 
                            <br />
                            <input type="submit" name="submit" value="Submit" />
<!--                         multiple="true"  -->
                       </span>
                   </div>
               </form>
                <div class="ml8 span" style="margin-left:30px;">
                       <legend class="lg_title">
							<span>导入说明：</span>
						</legend>
						<span>1、导入前请检查表格内容是否正确。</span><br/>
						<span>2、导入表格后，对应的用户即可成为会员。</span><br/>
						<span>3、会员期限与付费开通的相同。</span><br/>
						<span>4、导入的用户必须要事先注册觉鸟学堂公众号并绑定手机号码，否则无法生效。</span><br/>
               </div>
		</div>
	</div>
  </div>
</div>
<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#file_upload2').uploadify({
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'id' : '0',
			},
			'swf'      : '<?php echo $this->basePath()?>/adminStyle/js/upload/uploadify.swf',
				'uploader' : '<?php  echo $this->url('admin',array('controller'=>'GroupMember','action'=>'addExcel'));?>',//'<?php //echo $this->basePath()?>/adminStyle/js/upload/uploadify.php'
				'onUploadSuccess' : function (file, data, response) {
					data = JSON.parse(data);
					if (response) {
						alert(data.message);return;
						if(data.code == 200){
							window.location.href='<?php echo $this->url('admin',array('controller'=>'GroupMember','action'=>'index2'))?>'; 
						}
                    }
		    },
	    });
	});
</script>
<style>
.uploader{
display: none;
}
.span span{
    color: #222222;
}
.l_f2 input{
    width: 137px;
    height: 60px;
    line-height: 60px;
}
.span span{
    font-size: 14px;
    line-height: 2em;
}
</style>