<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>导师详情</title>
<style>
    .apostrophe .more{
        display: none;
        position: absolute;
        right: 2px;
        top: 21px;
        z-index: 10;
    }
</style>
<html>
<body>
    <div class="londing_gif" >
        <img src="<?php echo ROOT_PATH;?>webStyle/images/londing.gif" alt="">
    </div>
    <div class="tutor_details">
        <div class="banner">
            <img src="<?php echo $data['head_icon']?>" alt="">
        </div>
        <div class="tutor_information">
            <div class="tutor_title"><?php echo $data['title']?></div>
            <div>总播放量：<?php echo $data['play_num']?></div>
            <?php if(isset($data['subscription']) && $data['subscription']){?>
                <div class="attention_volume up"><?php echo "已关注"?>(<?php echo $data['subscription_num']?>)</div>
            <?php }else{?>
                <div class="attention_volume on"><?php echo "关注"?>(<?php echo $data['subscription_num']?>)</div>
            <?php }?>
            
            <div class="detailed_information apostrophe"><?php echo $data['synopsis']?><span class="more">...</span></div>
            <a style="display:none" href="javascript:showAll();" class="oc_details"><img src="<?php echo ROOT_PATH;?>webStyle/images/open_details.png" alt=""></a>
        </div>
        <div class="select_top">
            <a href="javascript:(0);" class="select_on" onclick="getTutorCoursesList(4,1)">视频课程</a>
            <a href="javascript:(0);"  onclick="getTutorCoursesList(3,1)">音频课程</a>
        </div>
        <section>
            <div class="voice_curriculums_list" id="video_curriculums_list">
                <ul>
                
                </ul>
            </div>
            <div class="voice_curriculums_list" id="audio_curriculums_list"  style="display:none">
                <ul>
                
                </ul>
            </div>
            
        </section>
        <input type="hidden" class="play" id="contrllor">
        <audio id="audio" -webkit-playsinline webkit-playsinline>
                <source src="" />
        </audio>
    </div>
</body>   
</html>
<script>
var pause_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/audio_pause_white.png';
var play_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/player.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'audio', 'action' => 'ajaxAddStudyNum'));?>";
var teacher_id = '<?php echo $data['id']?>';
var user_id = '<?php echo $user_id?>';
var finished = false;
var page = 1;
var current_audio_id = 0;
getTutorCoursesList(4);
function getTutorCoursesList(audio_type,load_more){
	 if (finished && load_more == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(load_more == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxGetTutorCourseList'))?>";
     $.post(url,{teacher_id:teacher_id,audio_type:audio_type,page:page},function(data){
    		$('.londing_gif').hide();
             var list = data.list;
             if(audio_type == 3){
            	 var num = 1;
             }else{
            	 var num = 2;
             }
  	    	 if(data.code == 200){       
                  if (list.length > 0) {
                	    var li = '';
              			$.each(list,function(i,v){
              				if(v.type == 3 || v.type == 4){
              					li += '<li>';
              				    if(v.type == 3){
              				        var url = "<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'details'));?>";
              				        url = url+'?id='+[v.audio_id,2]+'&type='+2;
              				    }else{
                  				    var url = "<?php echo $this->url('web-common',array('controller' => 'video','action' => 'details'));?>";
                  			        url = url +'?id='+[v.audio_id,2]+'&type='+2;
              				    }
              					li += '<a href="'+url+'">';
              					li += '<div class="cover">';
              					if(num == 1){
              						li += '<img src="'+v.img+'" alt="">';
              					}else{
              						li += ' <img class="video_image" src="'+v.img+'" alt="">';
              					}
              					li += '<img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">';
              					li += '</div><div class="content"><div>'+v.audio_name+'</div>';
              					li += '<div class="information">';
                                li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
                                li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
                                li += '</div></div>';
              					li += '</a>';
              					li += '</li>'; 
              				}else if(v.type == 1 || v.type == 2){                     
              					li += '<li>';
              					if(v.type == 1){
              				        var url = "<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'details'));?>";
              				        url = url+'?id='+[v.audio_id,1]+'&type='+1;;
              				    }else{
                  				    var url = "<?php echo $this->url('web-common',array('controller' => 'video','action' => 'details'));?>";
                  			        url = url +'?id='+[v.audio_id,1]+'&type='+1;;
              				    }
              					li += '<a href="'+url+'">';
              					li += '<div  class="cover">';
              					if(num == 1){
              						li += '<img src="'+v.img+'" alt="">';
              					}else{
              						li += '<img class="video_image" src="'+v.img+'" alt="">';
              					}
              					li += '<img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">';
              					li += '</div>';
              					li += '<div class="content">';
              					li += '<div>'+v.audio_name+'</div>';
                                li += '<div class="teacher_name">'+v.teacher_name;
                                if(v.count != "0%"){
                                    if(v.count != "100%"){
                                   	 li += '<span class="ml40"><span>已播</span><span class=" font_color_055773">'+v.count+'</span></span>';
                                    }else{
                                   	 li += '<span class="ml40 ">已学完</span>';
                                    }
                                }
                                li += '</div>'
                                li += '<div class="information2">';
                                if(v.price == '仅限会员'){
                               	 li += '<div><span class="font_color_055773">'+v.price+'</span></div>';
                                }else{
                               	 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
                                }
                                li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
              					li += '</div></div>';
              					li += '<div  class="more"><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div></a>';
              					li += '</li>';
              				}					
              			});	
//               	 		console.log(li);
                          if(load_more == 1){
    	                      if(audio_type == 3){
    	                    	  $('#audio_curriculums_list ul li').remove();
    			              }else{
    			            	  $('#video_curriculums_list ul li').remove();
    				          }
                          }
                          if(audio_type == 3){
                        	  $("#audio_curriculums_list ul").append(li);
    		              }else{
    		            	  $("#video_curriculums_list ul").append(li);
    			          }  
                          finished = false;
	                      page ++;
	                  }else{
	                	  if(load_more == 1 || !load_more){
	                		  if(audio_type == 3){
		                    	  $('#audio_curriculums_list ul li').remove();
		                    	  if($('#audio_curriculums_list ul li').length <= 0){
			                		  $('#audio_curriculums_list ul div').remove();
				                	  $("#audio_curriculums_list ul").append('<div style="text-align: center;margin-top:40px;">暂无课程</div>');
				                  }
				              }else{
				            	  $('#video_curriculums_list ul li').remove();
			                	  if($('#video_curriculums_list ul li').length <= 0){
			                		  $('#video_curriculums_list ul div').remove();
				                	  $("#video_curriculums_list ul").append('<div style="text-align: center;margin-top:40px;">暂无课程</div>');
				                  }
					          }
    	                  }       	  
    	              }
	              }
	              else {
	                  if(load_more == 1){
	                	  if(audio_type == 3){
	                    	  $('#audio_curriculums_list ul li').remove();
			              }else{
			            	  $('#video_curriculums_list ul li').remove();
				          }
	                  }
	              }
     },'json');
}

function play_audio(src,obj){
	var new_audio_id = $(obj).attr('audio_id');
	$('.player').attr('src',play_img);
    if(src){
    	var audio = document.getElementById("audio");
    	if(new_audio_id != current_audio_id){
    		audio.src = src;
    		current_audio_id = new_audio_id;
    		$("#contrllor").addClass("play")
        }
    	audio.loop = false; //歌曲循环
    	if ($("#contrllor").hasClass("play")) {
    		$("#contrllor").addClass("pause").removeClass("play");
    		audio.play();//开始播放
    		$(obj).attr('src',pause_img);
        }
    	else
    	{
    		$("#contrllor").addClass("play").removeClass("pause");
    	    audio.pause();
    	    $(obj).attr('src',play_img);
        }

    	play_num_deal(current_audio_id);//播放量处理
    }
}

$(".attention_volume").click(function(){
	var attention_url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxAttention'))?>";
    $.post(attention_url,{teacher_id:teacher_id,user_id:user_id},function(result) {
        if(result.code == 200 && result.num == 1){
            //添加
//         	$(".attention_volume").attr('class','collect');
        	$(".attention_volume").html('已关注('+result.subscription_num+')');
          $(".attention_volume").addClass('up').removeClass('on');
        }else{
            //取消
//         	$(".attention_volume").attr('class','collected');
        	$(".attention_volume").html('关注('+result.subscription_num+')');
          $(".attention_volume").addClass('on').removeClass('up');
        }
   },'json');
});

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
        var audio_html = $('.select_on').html();
        if(audio_html == '视频课程'){
        	audio_type = 4;
        }else{
        	audio_type = 3;
        }
    	getTutorCoursesList(audio_type,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});

$(".tutor_details .select_top a").click(function(){
        $(this).addClass('select_on').siblings().removeClass('select_on');
        $('section >div').hide();
        $('section >div').eq($(this).index()).show()
    })

if( $(".detailed_information").height()>40){
    $(".oc_details").css("display","block");
    $(".apostrophe").css({"height":"40px","overflow":"hidden"});
    $(".apostrophe .more").css("display","block");


}
var textFlag = 0;
    function showAll(){
        if(textFlag == 0){
            $(".detailed_information").css('height','auto');
            $(".oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/close_details.png');
           $(".apostrophe .more").css("display","none");
            $(".detailed_information"). removeClass("apostrophe");

            textFlag = 1
        }else{
            $(".detailed_information").css('height','40px');
            $(".oc_details img").attr('src','<?php echo ROOT_PATH;?>webStyle/images/open_details.png');
            $(".detailed_information").addClass("apostrophe");
            $(".apostrophe .more").css("display","block");

            textFlag = 0
        }

    }





$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".attention_volume").css("padding-top","2px")
    }

}); 

wx.ready(function(){
	 shareData = {title: '<?php echo $data['name']?>',desc: '<?php echo $data['synopsis'];?>',imgUrl: '<?php echo 'https://' . $_SERVER['HTTP_HOST'] .($data['head_icon'] ? $data['head_icon'] : "");?>'};
	 share(shareData);
});
</script>