<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>订阅记录</title>
<style>
    body{
        margin-bottom: 5px;
    }
</style>
<html>
<body>
    <div class="tutor_list teacher_list" id="tutor_list">
        <ul>
        
        </ul>
    </div>
    <div class="unrecorded">
        <img src="<?php echo ROOT_PATH;?>webStyle/images/no_subscriptionTutorList.png" alt="">
        <div>还没有订阅的记录</div>
    </div>
</body>   
</html>
<script>
var finished = false;
var page = 1;
getSubscriptionTutorList();
function getSubscriptionTutorList(type){
	 if (finished && type == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(!type){
    	 type = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxGetSubscriptionTutorList'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
    		 $('.londing_gif').hide();
  	    	 if(data.code == 200){
  	  	    	  var list = data.list;
  	    		  var dom = $("#tutor_list ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  url = '<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'details'));?>'
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         li += '<a href="'+url+'?id='+v.id+'">';
	                         li += '<img src="'+v.head_icon+'" alt="">';
	                         li += '<div class="">'+v.name+'：'+v.signature+'</div>';
	                         // li += '<div class="tutor_profile">';
	                         // li += '<span class="video_view">'+v.play_num+'</span>';
	                         // li += '<span class="date_updated">'+v.timestamp+'</span>';
	                         // li += '</div>';
	                         li += '</a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#tutor_list ul li').remove();
	                      }  
	                      $("#tutor_list ul").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#tutor_list ul li').remove();
    	                  }
    	                  if($("#tutor_list ul li").length <= 0){
    	                	  $('.unrecorded').show();
    	                  }
	                	
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#tutor_list ul li').remove();
	                  }
	              }
     },'json');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getSubscriptionTutorList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});

//wx.ready(function(){
//   shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php //echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>//webStyle/images/nightbird_log.png'};
//   share(shareData);
//});
</script>