<?php //var_dump($position);exit;?>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.config.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.all.min.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 8px;
}
.row input, .row select {
    margin-bottom:0px;
}
.controls label{
   margin-top:5px
}
</style>
<ul class="breadcrumb">
    <li><span>意见反馈</span><span class="divider">/</span></li>
    <li> <a href="#">意见列表</a></li>
</ul>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        <form method="get" action="">
		      <div class="pull-left ml8">
					<span style="margin-left:20px;">反馈日期：</span>
					<input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $condition['where']['start'] ? $condition['where']['start'] : '';?>">&nbsp;至&nbsp;
					<input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $condition['where']['end'] ? $condition['where']['end'] : '';?>">
				</div>
				<div class="pull-left ml8" style="position: relative">
					<input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入用户名" value="<?php echo $condition['where']['keyword'] ? $condition['where']['keyword']:'';?>">
					<i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
				</div>
				
			<div class="pull-right">
				<div class="pull-left">
        			<label>
        				<select name="status" class="input-medium select select-radius" style="border-radius: 4px;margin-left: 10px;">
            				<option value="0">全部回复状态</option>
        				    <option value="2" <?php echo  $condition['where']['status']== 2?'selected="selected"':''?>>未回复</option>
        				    <option value="1" <?php echo  $condition['where']['status']== 1?'selected="selected"':''?>>已回复</option>
        				</select>
        			</label>
        		</div>
				<div class="pull-left ml8" >
					<button type="submit" class="btn btn-info submit">搜索</button>
				</div>
			</div>
        </form>
        <div class="clearfix"> </div>
    </div>
</div>
<br/>
<div class="bs-example4" data-example-id="simple-responsive-table">
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
				<tr>
					<th style="width: 10%">反馈时间</th>
					<th>用户名</th>
					<th>职务</th>
					<th style="width: 55%">反馈内容</th>
					<th style="width: 6%">回复状态</th>
					<th style="width: 8%">操作</th>
				</tr>
            </thead>
			<tbody>
            <?php foreach($list as $k=>$v){?>
				<tr>
					<th><?php echo $v['timestamp'] ;?></th>
					<td><?php echo $v['name'];?></td>
					<td><?php echo $v['z_name'];?></td>
					<td style="text-align: left;"><?php echo $v['content'];?></td>
					<td><?php echo $v['reply_status']==1?'已回复':'未回复';?></td>
					<td>
					  <?php if($v['reply_status']==2){?>
						<input type="button" class="btn btn-danger btn-sm"  onclick="submitDelete(<?php echo $v['id'];?>)" value="回复" />
						<?php }?>
 					</td>
				</tr>
            <?php }?>
            </tbody>
        </table>
    </div>
</div>
<div class="page-control">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
</div>
</div>

<div class="modal hide" id="myModal"  style="top: 30%;left: 40%;width:700px;">
	<form action="<?php echo $this->url('admin', array('controller' => 'Feedback', 'action' => 'details2','id'=>1));?>" method="post" id="abolish-family" class="form-horizontal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">建议反馈</h3>
		</div>
	    <div class="">
            <div class="bootbox-body">
						<div style="float: left;width: 100%;">
							<div class="control-group">
    							<label class="control-label">反馈时间：</label>
    							<div class="controls">
    								<label id="com_time"></label>
    							</div>
							</div>
							<div class="control-group">
    							<label class="control-label">用户名：</label>
    							<div class="controls">
    								<label  id="com_name"></label>
    							</div>
							</div>
							<div class="control-group">
								<label class="control-label">职务：</label>
								<div class="controls">
									<label id="com_type"></label>
								</div>
							</div>
							<div class="control-group" style="width:93%;">
								<label class="control-label">反馈内容：</label>
								<div class="controls" >
									<label id="com_content"></label>
								</div>
							</div>
                  <div class="control-group">
                      <label class="control-label">回复内容</label>
        			  <div class="controls">
                         <TEXTAREA id="cc1"  rows="5" name="content" id="contents" style="width: 90%;" placeholder="请输入回复内容" ></TEXTAREA>
                     </div>
    	    	</div>		
           </div>
        </div>
		<div class="modal-footer">
			<input type="hidden" name="id" value="" id ="shop_id">
			<input type="hidden" name="ajax" value="2017" >
			<a href="#" class="btn" data-dismiss="modal">取消</a>
			<input type="submit" name="s" class="btn btn-primary"   value="确定">
		</div>
	</form>
</div>
<script>
function submitDelete(id){
   var url = '<?php echo $this->url('admin', array('controller' => 'Feedback', 'action' => 'details2'));?>'+'/i'+id;
   $.post(url,{},function(data){
	    if(data.code != 200){
		    alert(data.msg);	return;
	    }else{
		    item = data.info;
		    $('#com_time').text(item.timestamp);
		    $('#com_name').text(item.name);
		    $('#com_type').text(item.z_name);
		    $('#com_content').text(item.content);
		    $('#shop_id').val(id);
		    $('#myModal').modal('show');
	    }
	   },'json');
}

var ue1 = UE.getEditor('cc1', {
	"initialFrameWidth" : "100%",
	"initialFrameHeight" : 200,
// 	"maximumWords" : 8000,
	toolbars: [[
	            'fullscreen', 'source', '|', 'undo', 'redo', '|',
	            'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'superscript', 'subscript', 'removeformat', 'formatmatch', 'autotypeset', 'blockquote', 'pasteplain', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'selectall', 'cleardoc', '|',
	        ]]
});
</script>
