<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>详情</title>
<style>
    body{
        padding-bottom: 90px;
        /*background-color: #f0f0f5; */
    }

</style>
<html>
<body>
    <div class="message_details">
        <div class="message_title">
             <?php echo $data['title'];?>
        </div>
        <div class="message_content">
            <div><?php echo $data['content'];?></div>
        </div>
    </div>
</body>   
</html>
<script>

</script>