<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>首页</title>
<style>
    body{
        padding-bottom: 60px;
    }
</style>
<html>
<body>
    <audio id="audio" -webkit-playsinline webkit-playsinline>
            <source src="" />
    </audio>
    <div id="banner">
        <div class="bd sl">
            <div class="tempWrap" style="overflow:hidden; position:relative;"><ul style="width: 1500px; position: relative; overflow: hidden; padding: 0px; margin: 0px; transition-duration: 200ms; transform: translate(0px, 0px) translateZ(0px);">
            <?php if($ads){?>
            <?php foreach ($ads as $v){?>
                <li style="display: table-cell; vertical-align: top; width: 375px;"><a href="<?php echo $v['link']?>"><img src="<?php echo ROOT_PATH.UPLOAD_PATH.$v['image'];?>" alt=""></a></li>
            <?php }?>
            <?php }?>
            </ul></div>
        </div>
        <div class="hd">
            <ul style="margin-left: 154.5px;"><li class="on">1</li><li class="">2</li><li class="">3</li><li class="">4</li></ul>
        </div> 
    </div>
    <?php if($link_array){?>
        <div class="select_home">
            <a href="<?php echo $link_array[0]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['0'];?>" alt="">
                <div><?php echo $name_array['0']?></div>
            </a>
            <a href="<?php echo $link_array[1]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['1'];?>" alt="">
                <div><?php echo $name_array['1']?></div>
            </a>
            <a href="<?php echo $link_array[2]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['2'];?>" alt="">
                <div><?php echo $name_array['2']?></div>
            </a>
            <a href="<?php echo $link_array[3]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['3'];?>" alt="">
                <div><?php echo $name_array['3']?></div>
            </a>
        </div>
    <?php }?>
    <?php if($first_name){?>
        <a class="repast_free" href="<?php echo $this->url('web-common',array('controller' => 'video','action' => 'freeVideoList'))?>"><?php echo $first_name?></a>
    <?php }?>
    <?php if($four_free_audios){?>
    <div class="repast_voice" id="repast_voice">
        <ul>
            <?php foreach ($four_free_audios as $v){?>
            <li <?php if($v['is_today']){?>class="new"<?php }?>>
                <a class="audio<?php echo $v['id']?>" href="javascript:void(0)" id="<?php echo $v['id']?>" src="<?php echo $v['full_path']?>"><?php echo $v['teacher_name']?>：<?php echo $v['title']?><?php echo $v['title']?><?php echo $v['title']?><?php echo $v['title']?></a><img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:20px;">
            </li>
            <?php }?>
        </ul>
        <img id="contrllor" audio_id="0" class="voice_play play" src="<?php echo ROOT_PATH;?>webStyle/images/player_blue.png" alt="">
    </div>
    <?php }?>
    <?php if($second_name){?>
        <a class="repast_free" href="<?php echo $this->url('web-common',array('controller' => 'tutor','action' => 'index'))?>"><?php echo $second_name?></a>
    <?php }?>
    <div class="teacher_list" id="teacher_list">
        <ul>   
                
        </ul>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href="javascript:void(0);"><img src="<?php echo ROOT_PATH;?>webStyle/images/home_on.png" alt=""><p class="select_on">首页</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/voice.png" alt=""><p>音频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'video','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/video.png" alt=""><p>视频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/mine.png" alt=""><p>我的</p></a></li>
        </ul> 
    </footer>
</body>   
</html>
<script>
var play_img = '<?php echo ROOT_PATH;?>webStyle/images/player_blue.png';
var pause_img = '<?php echo ROOT_PATH;?>webStyle/images/audio_pause.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'ajaxAddStudyNum'));?>";
var finished = false;
var page = 1;
var current_audio_id = 0;
getTutorList();
adList();
function getTutorList(type = 1){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxGetTutorList'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
  	    	 if(data.code == 200){
  	  	    	  var list = data.list;
  	    		  var dom = $("#teacher_list ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  url = '<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'details'));?>'
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         li += '<a href="'+url+'?id='+v.id+'">';
	                         li += '<img src="'+v.head_icon+'" alt="">';
	                         li += '<div>'+v.name+'：'+v.signature+'</div>';
	                         li += '</a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#teacher_list ul li').remove();
	                      }  
	                      $("#teacher_list ul").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#teacher_list ul li').remove();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#teacher_list ul li').remove();
	                  }
	              }
     },'json');
}

$('#repast_voice a').on('click',function(){
	var src = $(this).attr('src');
	var audio = document.getElementById("audio");
	$('#repast_voice a').removeClass('first_voice');
	$(this).addClass('first_voice');
	audio.src = src;

	var new_audio_id = $(this).attr('id');
	$("#contrllor").attr("audio_id",new_audio_id);
	if(audio.src != src || new_audio_id != current_audio_id){
		audio.src = src;
		current_audio_id = new_audio_id;
		$("#contrllor").addClass("play")
    }
	audio.loop = false; //歌曲循环
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
    }else{
    	$("#contrllor").addClass("play").removeClass("pause");
    	$("#contrllor").attr('src',play_img);
    	audio.pause();//开始播放
    	$('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

$("#contrllor").click(function(){
	var audio = document.getElementById("audio");
	var audio_id = $("#contrllor").attr('audio_id');
	if(audio_id == '0'){
		audio.src = '<?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['full_path'] : ""?>';
		$('#repast_voice a:first').addClass('first_voice');
		current_audio_id = <?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['id'] : 0?>;
		$("#contrllor").attr('audio_id',current_audio_id);
	}
	
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
		$("#"+audio_id).addClass('first_voice');
    }
	else
	{
		$("#contrllor").addClass("play").removeClass("pause");
	    audio.pause();
	    $("#contrllor").attr('src',play_img);
	    $('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

// 图片轮播
function adList(){
   TouchSlide({slideCell:"#banner",
               titCell:".hd ul",
               mainCell:'.bd ul',
               effect:'left',
               autoPlay:true,
               autoPage:true
        });           
   $('.hd ul').css('margin-left',($('.hd').width()-$('.hd ul').width())/2+'px');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getTutorList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});


    var t=$(".repast_voice ul").height()/2;
    $(".repast_voice ul").css("margin-top",-t)
</script>