<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>首页</title>
<style>
    body{
        padding-bottom: 60px;
    }
</style>
</html>
<body rlt="1">
    <div class="bgb"></div>
    <audio id="audio" -webkit-playsinline="" webkit-playsinline="">
            <source src="">
    </audio>
    <div id="banner">
        <div class="bd sl">
            <div class="tempWrap" style="overflow:hidden; position:relative;"><div class="tempWrap" style="overflow:hidden; position:relative;"><ul style="width: 1600px; position: relative; overflow: hidden; padding: 0px; margin: 0px; transition-duration: 200ms; transform: translate(-1280px, 0px) translateZ(0px);">
                <li style="display: table-cell; vertical-align: top; width: 320px;"><a href="<?php echo $url;?>"><img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image;?>" alt=""></a></li>
<!--                  
                <li style="display: table-cell; vertical-align: top; width: 320px;"><a href="/nightbird/public/web/audio/details/t2/i11"><img src="/nightbird/public/uploadfiles/201704/01/172800_2040.png" alt=""></a></li>
                <li style="display: table-cell; vertical-align: top; width: 320px;"><a href="/nightbird/public/web/index/articleDetails/i6"><img src="/nightbird/public/uploadfiles/201704/01/173458_1940.png" alt=""></a></li>
                <li style="display: table-cell; vertical-align: top; width: 320px;"><a href="/nightbird/public/web/video/details/t1?id=3"><img src="/nightbird/public/uploadfiles/201704/01/144352_7440.jpg" alt=""></a></li>
                <li style="display: table-cell; vertical-align: top; width: 320px;"><a href="http://www.sina.com"><img src="/nightbird/public/uploadfiles/201704/01/173916_6860.jpg" alt=""></a></li>
-->
            </ul></div></div>
        </div>
        <div class="hd">
            <ul style="margin-left: 120px;"><li class="">1</li><li class="">2</li><li class="">3</li><li class="">4</li><li class="on">5</li></ul>
        </div> 
    </div>
            <div class="select_home">
            <a href="">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115149_3800.jpg" alt="">
                <div>觉察自己2</div>
            </a>
            <a href="">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/122215_7350.jpg" alt="">
                <div>餐饮锦囊</div>
            </a>
            <a href="">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115219_9280.jpg" alt="">
                <div>老板秘籍</div>
            </a>
            <a href="">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115156_1950.jpg" alt="">
                <div>平凡之路</div>
            </a>
        </div>
                <a class="repast_free" href="">餐饮知识</a>
            <div class="repast_voice" id="repast_voice">
        <ul style="margin-top: -68px;">
                        <li>
                <a class="audio18" href="" id="18" >曹格：u</a><img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:20px;">
            </li>
                        <li>
                <a class="audio17" href="" id="17" >陈整：get out</a><img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:20px;">
            </li>
                        <li>
                <a class="audio16" href="" id="16" >汪含：have no words</a><img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:20px;">
            </li>
                        <li>
                <a class="audio15" href="" id="15" >陈整：hush</a><img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:20px;">
            </li>
                    </ul>
        <img id="contrllor" audio_id="0" class="voice_play play" src="<?php echo ROOT_PATH;?>webStyle/images/player_blue.png" alt="">
    </div>
                <a class="repast_free" href="">餐饮课堂</a>
        <div class="teacher_list" id="teacher_list">
        <ul>   
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115156_1950.jpg" alt=""><div>王八：学习是人生的一种高度，我们应该时刻朝着这种高度网上攀岩</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/142726_1780.jpg" alt=""><div>土匪：学习让人的高度更加高不可攀</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115149_3800.jpg" alt=""><div>美老师：我就是美</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/141927_6780.png" alt=""><div>李毛：让优秀成为一种习惯</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/141916_4860.jpg" alt=""><div>曹格：学习是一种态度，一直优秀下去</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/142338_6200.jpg" alt=""><div>汪含：美丽是人生的一种境界。我学习我美丽</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/142233_1150.jpg" alt=""><div>陈整：学武苦海，态度决定一切</div></a></li>
        <li><a href=""><img src="<?php echo ROOT_PATH.UPLOAD_PATH;?>201704/01/115224_7330.jpg" alt=""><div>董老师：懵懵懂懂，一生就是一脸萌逼。所以说学习很重要</div></a></li></ul>
    </div>
    <div class="perfect_data">
    	<div class="title">
    		可试听,请完善资料
    	</div>
    		<ul class="present_detail">
                <li>
                    <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                </li>
                <li>
                    <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="" class="gain_verification">获取验证码</a></div>


                </li>
                <li class="select">
                    <a href="" id="showPicker">
                    <div>职位：
                    <span id="position" position_id="6">
                      洗碗工                    </span></div></a>
                </li>
                <li class="select">
                    <a href=""><div>地区：<input class="weui-input" id="region" region_id="230400" type="text" value="黑龙江省 鹤岗市" readonly=""></div></a>
                </li>
            </ul>
            <div>
            <ul class="operation">

                <li><a href="" class="affirm"><p>完成</p></a></li>
            </ul>
    		</div>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href=""><img src="<?php echo ROOT_PATH;?>webStyle/images/home_on.png" alt=""><p class="select_on">首页</p></a></li>
            <li class=""><a href=""><img src="<?php echo ROOT_PATH;?>webStyle/images/voice.png" alt=""><p>音频</p></a></li>
            <li class=""><a href=""><img src="<?php echo ROOT_PATH;?>webStyle/images/video.png" alt=""><p>视频</p></a></li>
            <li class=""><a href=""><img src="<?php echo ROOT_PATH;?>webStyle/images/mine.png" alt=""><p>我的</p></a></li>
        </ul> 
    </footer>

</body> 
<script>
var play_img = '<?php echo ROOT_PATH;?>webStyle/images/player_blue.png';
var pause_img = '<?php echo ROOT_PATH;?>webStyle/images/audio_pause.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'ajaxAddStudyNum'));?>";
var finished = false;
var page = 1;
var current_audio_id = 0;
getTutorList();
adList();
function getTutorList(type = 1){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxGetTutorList'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
  	    	 if(data.code == 200){
  	  	    	  var list = data.list;
  	    		  var dom = $("#teacher_list ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  url = '<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'details'));?>'
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         li += '<a href="'+url+'?id='+v.id+'">';
	                         li += '<img src="'+v.head_icon+'" alt="">';
	                         li += '<div>'+v.name+'：'+v.signature+'</div>';
	                         li += '</a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#teacher_list ul li').remove();
	                      }  
	                      $("#teacher_list ul").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#teacher_list ul li').remove();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#teacher_list ul li').remove();
	                  }
	              }
     },'json');
}

$('#repast_voice a').on('click',function(){
	var src = $(this).attr('src');
	var audio = document.getElementById("audio");
	$('#repast_voice a').removeClass('first_voice');
	$(this).addClass('first_voice');
	audio.src = src;

	var new_audio_id = $(this).attr('id');
	$("#contrllor").attr("audio_id",new_audio_id);
	if(audio.src != src || new_audio_id != current_audio_id){
		audio.src = src;
		current_audio_id = new_audio_id;
		$("#contrllor").addClass("play")
    }
	audio.loop = false; //歌曲循环
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
    }else{
    	$("#contrllor").addClass("play").removeClass("pause");
    	$("#contrllor").attr('src',play_img);
    	audio.pause();//开始播放
    	$('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

$("#contrllor").click(function(){
	var audio = document.getElementById("audio");
	var audio_id = $("#contrllor").attr('audio_id');
	if(audio_id == '0'){
		audio.src = '<?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['full_path'] : ""?>';
		$('#repast_voice a:first').addClass('first_voice');
		current_audio_id = <?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['id'] : 0?>;
		$("#contrllor").attr('audio_id',current_audio_id);
	}
	
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
		$("#"+audio_id).addClass('first_voice');
    }
	else
	{
		$("#contrllor").addClass("play").removeClass("pause");
	    audio.pause();
	    $("#contrllor").attr('src',play_img);
	    $('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

// 图片轮播
function adList(){
   TouchSlide({slideCell:"#banner",
               titCell:".hd ul",
               mainCell:'.bd ul',
               effect:'left',
               autoPlay:true,
               autoPage:true
        });           
   $('.hd ul').css('margin-left',($('.hd').width()-$('.hd ul').width())/2+'px');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getTutorList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});


    var t=$(".repast_voice ul").height()/2;
    $(".repast_voice ul").css("margin-top",-t)
</script>