<?php
if (!array_key_exists('action_list', $_SESSION)) {
    $_SESSION['action_list'] = 'all';
}
$menu = array(
    array(
        'name' => '首页',
//        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_index', explode('|', $_SESSION['action_list'])) ? true : false,
        'authority' => true,
        'icon' => 'fa fa-home',
        'sub' => array(
            array(
                'route' => $this->url('admin', array('action' => 'index')),
                'name' => '数据统计', 'other' => '',
//                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_index_index', explode('|', $_SESSION['action_list'])) ? true : false
                'authority' => true
            ),
        )
    ),

    array(
        'name' => '用户管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_user', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-users',
        'sub' => array(
            array(
                'route' => $this->url('admin-user', array('action' => 'index')),
                'name' => '用户列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_user_index', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '运营管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-cogs',
        'sub' => array(
            array(
                'route' => $this->url('admin-business', array('action' => 'adsList')),
                'name' => '广告列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business_adsList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-business', array('action' => 'navigation')),
                'name' => '导航列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business_navigation', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-business', array('action' => 'mobileAppealList')),
                'name' => '手机申诉列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business_mobileAppealList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-business', array('action' => 'reportList')),
                'name' => '举报列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business_reportList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-business', array('action' => 'poster')),
                'name' => '平台海报', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_business_poster', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '视频管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_video', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-desktop',
        'sub' => array(
            array(
                'route' => $this->url('admin-video', array('action' => 'index')),
                'name' => '视频列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_video_index', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-video', array('action' => 'videoCategoryList')),
                'name' => '视频分类', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_video_categoryList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '音频管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_audio', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-microphone',
        'sub' => array(
            array(
                'route' => $this->url('admin-audio', array('action' => 'index')),
                'name' => '音频列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_audio_index', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-audio', array('action' => 'audioCategoryList')),
                'name' => '音频分类', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_audio_categoryList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '微博管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_microblog', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-pencil-square-o',
        'sub' => array(
            array(
                'route' => $this->url('admin-microblog', array('action' => 'index')),
                'name' => '微博列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_microblog_index', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '资讯管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_article', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-list-alt',
        'sub' => array(
            array(
                'route' => $this->url('admin-article', array('action' => 'index')),
                'name' => '资讯列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_article_index', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-article', array('action' => 'articleCategoryList')),
                'name' => '资讯分类列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_article_categoryList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
        )
    ),

    array(
        'name' => '评论管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_comment', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'fa fa-list',
        'sub' => array(
            array(
                'route' => $this->url('admin-comment', array('action' => 'index')),
                'name' => '评论列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_comment_index', explode('|', $_SESSION['action_list'])) ? true : false
            )
        )
    ),

    array(
        'name' => '财务管理',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_finance', explode('|', $_SESSION['action_list'])) ? true : false,
        'icon' => 'glyphicon glyphicon-bed',
        'sub' => array(
            array(
                'route' => $this->url('admin-finance', array('action' => 'index')),
                'name' => '财务列表', 'other' => '',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_finance_index', explode('|', $_SESSION['action_list'])) ? true : false
            )
        )
    ),

    array(
        'name' => '平台管理',
        'icon' => 'fa fa-tachometer',
        'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting', explode('|', $_SESSION['action_list'])) ? true : false,
        'sub' => array(
            array(
                'route' => $this->url('admin-setting', array('action' => 'adminList')),
                'name' => '管理员管理',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting_adminList', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-setting', array('action' => 'adminCategory')),
                'name' => '职务管理',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting_adminCategory', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-setting',['action'=>'agreement']),
                'name' => '协议管理',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting_agreement', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-setting',['action'=>'privacyAgreement']),
                'name' => '隐私协议',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting_privacyAgreement', explode('|', $_SESSION['action_list'])) ? true : false
            ),
            array(
                'route' => $this->url('admin-setting',['action'=>'reportCategoryList']),
                'name' => '举报类型设置',
                'authority' => ($_SESSION['action_list'] == 'all') || in_array('admin_setting_reportCategoryList', explode('|', $_SESSION['action_list'])) ? true : false
            )
        )
    )
);
?>
<?php
$url = $_SERVER['REQUEST_URI'];
$navigate_arr = [
    '/index' => ['/index' => '数据统计'],

    '/user' => ['/user' => '用户列表', '/user/adetails' => '用户详情'],

    '/business' => ['/business' => '广告管理', '/business/aadsEdit' => '编辑广告', '/business/aadsAdd' => '添加广告'],

    '/business/anavigation' => ['/business/anavigation'=>'导航列表','/business/anavigationDetails' => '编辑导航', '/business/anavigationAdd' => '新增导航'],

    '/business/amobileAppealList' => ['/business/amobileAppealList' => '手机申诉管理'],

    '/business/areportList' => ['/business/areportList' => '举报列表'],

    '/business/aposter' => ['/business/aposter' => '平台海报'],

    '/video' => ['/video' => '视频列表', '/video/avideoAdd' => '视频添加', '/video/avideoDetails' => '视频详情'],

    '/video/avideoCategoryList' => ['/video/avideoCategoryList' => '视频分类管理'],

    '/audio' => ['/audio' => '音频列表', '/audio/aaudioAdd' => '音频添加', '/audio/aaudioDetails' => '音频详情'],

    '/audio/aaudioCategoryList' => ['/audio/aaudioCategoryList' => '音频分类管理'],

    '/microblog' => ['/microblog' => '微博管理', '/microblog/amicroblogDetails' => '音频详情'],

    '/article' => ['/article' => '资讯管理', '/article/aarticleAdd' => '添加资讯','/article/adetails' => '资讯详情'],

    '/article/aarticleCategoryList' => ['/article/aarticleCategoryList' => '资讯分类管理'],

    '/comment' => ['/comment' => '评论管理'],

    '/finance' => ['/finance' => '财务管理'],

    '/setting' => ['/setting' => '管理员管理', '/setting/aaddAdmin' => '新增管理员','/setting/aviewAdmin' => '编辑管理员'],

    '/setting/aadminCategory' => ['/setting/aadminCategory' => '职务管理', '/setting/aaddRole' => '新增职务','/setting/aviewRole' => '编辑职务'],

    '/setting/asensitiveWord' => ['/setting/asensitiveWord' => '敏感词管理'],

    '/setting/aagreement'=>['/setting/aagreement'=>'协议管理'],

    '/setting/aprivacyAgreement'=>['/setting/aprivacyAgreement'=>'隐私协议'],

    '/setting/areportCategoryList' => ['/setting/areportCategoryList'=>'举报类型管理']

];
function array_remove(&$arr, $offset)
{
    array_splice($arr, $offset, 1);
}
$arr = array_keys($navigate_arr);
if (strpos($url, '?')) {
    $url = substr($url, 0, strpos($url, '?'));
}
$url_arr = explode('/', $url);
$active = '';
$navigate = '';
$url_header = '';
$active_header = '';
$index = array_search('index.php',$url_arr);
if($index){
    array_remove($url_arr,$index);
    $active_header .= '/index.php';
    $url_header .= '/index.php';
}
$module = array_search('admin',$url_arr);
if($module){
    array_remove($url_arr,$module);
    $active_header .= '/admin';
    $url_header .= '/admin';
}
$url = implode('/', $url_arr);
if (in_array($url, $arr)) {
    $navigate = '<li class="active1">' . $navigate_arr[$url][$url] . '</li>';
    $active = $active_header.$url;
} else {
    foreach ($navigate_arr as $k1 => $v1) {
        foreach ($v1 as $k2 => $v2) {
            $arr1 = explode('/', $url);
            $arr2 = explode('/', $k2);
            if (isset($arr2[2]) && isset($arr1[2]) && $arr2[2] == $arr1[2] && $arr2[1] == $arr1[1]) {
                $navigate = '<li class="active1"><a href="' .$url_header. $k1 . '">' . $v1[$k1] . '</a></li>' . '<li class="active1">' . $v1[$k2] . '</li>';
                $active = $active_header.$k1;
            } else if (isset($arr2[1]) && $arr2[1] == $arr1[1] && !isset($arr2[2])) {
                $navigate = '<li class="active1"><a href="' .$url_header. $k1 . '">' . $v1[$k1] . '</a></li>' . '<li class="active1">' . $v1[$k2] . '</li>';
                $active = $active_header.$k1;
            }
        }
    }
}
?>


<div id="navbar" class="navbar navbar-default          ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
            <a href="<?php echo $this->url('admin', ['action' => 'index']) ?>" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    爱侗乡平台管理
                </small>
            </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="/adminStyle/images/avatars/user.jpg" alt="Jason's Photo"/>
                        <span class="user-info">
                            <small>Welcome,</small>
                            <?php echo array_key_exists('admin_name', $_SESSION) ? $_SESSION['admin_name'] : '未登录' ?>
                        </span>

                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="<?php echo $this->url('admin', ['action' => 'changePassword']) ?>">
                                <i class="ace-icon fa fa-cog"></i>
                                修改密码
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="<?php echo $this->url('admin', ['action' => 'logout']) ?>">
                                <i class="ace-icon fa fa-power-off"></i>
                                退出登录
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>


<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>

    <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
        <script type="text/javascript">
            try {
                ace.settings.loadState('sidebar')
            } catch (e) {
            }
        </script>

        <ul class="nav nav-list">
            <?php foreach ($menu as $main_menu) : ?>
                <?php if ($main_menu['authority']) { ?>
                    <li class="">
                        <a href="" class="dropdown-toggle">
                            <i class="menu-icon <?php echo $main_menu['icon'] ?>"></i>
                            <span class="menu-text"><?php echo $main_menu['name'] ?></span>
                            <b class="arrow fa fa-angle-down"></b>
                        </a>

                        <b class="arrow"></b>

                        <ul class="submenu">
                            <?php foreach ($main_menu['sub'] as $drop_menu) : ?>
                                <?php if ($drop_menu['authority']) { ?>
                                    <li class="">
                                        <a href="<?php echo $drop_menu['route'] ?>">
                                            <i class="menu-icon fa fa-caret-right"></i>
                                            <span class="menu-content"><?php echo $drop_menu['name'] ?></span>
                                        </a>

                                        <b class="arrow"></b>
                                    </li>
                                <?php } ?>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php } ?>
            <?php endforeach; ?>
        </ul>
        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
<!--                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="<?php echo $this->url('admin', ['action' => 'index']) ?>">Home</a>
                    </li>-->
                    <?php echo $navigate ?>
                </ul><!-- /.breadcrumb -->
            </div>

            <div class="page-content">

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->

                        <?php echo $this->main; ?>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->

    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
                <span class="bigger-120">
                    <span class="blue bolder">爱侗乡</span>
                    &copy; 2017
                </span>
            </div>
        </div>
    </div>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->
<script>
    var active = '<?php echo $active ?>';
    var nav_a = $(".nav li a");
    nav_a.each(function () {
        var href = $(this).attr("href");
        if (active == href) {
            $(this).parents("ul").parent("li").addClass("active open");
            $(this).parent("li").addClass("active");
        }
    });
</script>


