<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>详情</title>
<style>
    body{
        padding-bottom: 90px;
        /*background-color: #f0f0f5; */
        max-width:100vw;
        overflow: hidden;
    }

</style>
<html>
<body>
    <div class="message_details">
        <div class="message_title">
             <?php echo $data['title'];?>
        </div>
        <div class="message_content">
            <div><?php echo $data['content'];?></div>
        </div>
    </div>
</body>   
</html>
<script>
//wx.ready(function(){
//     shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php //echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>//webStyle/images/nightbird_log.png'};
//     share(shareData);
//});
</script>