<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/home.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/swiper.min.css">
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/swiper.min.js"></script>
<title>一起聚餐</title>
<style>
    body{
        padding-bottom: 60px;
    }
/*    .londing_gif{
	       display:none;
    }*/
    .return_home{
        display:none;
    }

    .swiper-container {
        width: 100%;
        height: 34vw;
        border-bottom: 1px solid #d8d8d8;
    }
    .swiper-wrapper{
        margin-top: 2vw;
        height:30vw;
    }
    .swiper-slide {
        /*text-align: center;*/
        font-size: 18px;
        background: #fff;
        width: 30vw!important;
        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }
    .swiper-slide a{
        display: block;
        height: 100%;
        width: 100%;
        text-align: center;
    }
    .swiper-slide img{
        width:94%;
        height:94%;
        margin-top: 3%;

    }
    .swiper-wrapper .swiper-slide:first-child{
        padding-left: 1.8vw;
    }
</style>
<html>
<body>

    <div class="bgb"></div>
    <audio id="audio" -webkit-playsinline webkit-playsinline>
            <source src="" />
    </audio>
    <div id="banner">
        <div class="bd sl">
            <div class="tempWrap" style="overflow:hidden; position:relative;"><ul style="width: 1500px; position: relative; overflow: hidden; padding: 0px; margin: 0px; transition-duration: 200ms; transform: translate(0px, 0px) translateZ(0px);">
            <?php if($ads){?>
            <?php foreach ($ads as $v){?>
                <li style="display: table-cell; vertical-align: top; width: 375px;"><a href="<?php echo $v['link']?>"><img src="<?php echo ROOT_PATH.UPLOAD_PATH.$v['image'];?>" alt=""></a></li>
            <?php }?>
            <?php }?>
            </ul></div>
        </div>
        <div class="hd">
            <ul style="margin-left: 154.5px;"><li class="on">1</li><li class="">2</li><li class="">3</li><li class="">4</li></ul>
        </div> 
    </div>
    <?php if($link_array){?>
        <div class="select_home">
            <a href="<?php echo $link_array[0]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['0']['path'];?>" alt="">
                <div><?php echo $name_array['0']?></div>
            </a>
            <a href="<?php echo $link_array[1]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['1']['path'];?>" alt="">
                <div><?php echo $name_array['1']?></div>
            </a>
            <a href="<?php echo $link_array[2]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['2']['path'];?>" alt="">
                <div><?php echo $name_array['2']?></div>
            </a>
            <a href="<?php echo $link_array[3]?>">
                <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$image_array['3']['path'];?>" alt="">
                <div><?php echo $name_array['3']?></div>
            </a>
        </div>
    <?php }?>
    <?php if($first_name){?>
        <a class="repast_free" href="<?php echo $first_url_link?>"><?php echo $first_name?></a>
    <?php }?>
    
    <?php if($today_ads){?>
    <div class="swiper-container swiper-container-horizontal">
        <div class="swiper-wrapper" style="">
        <?php foreach ($today_ads as $v){?>
            <div class="swiper-slide"><a href="<?php echo $v['link']?>"><img src="<?php echo ROOT_PATH.UPLOAD_PATH.$v['image'];?>" alt=""></a></div>
        <?php }?>
        </div>
    </div>
    <?php }?>

    <?php if($four_free_audios){?>
    <div class="repast_voice" id="repast_voice">
        <ul>
            <?php foreach ($four_free_audios as $v){?>
            <li style="overflow:hidden">
                <a style="float:left" class="audio<?php echo $v['id']?>" href="javascript:void(0)" id="<?php echo $v['id']?>" src="<?php echo $v['full_path']?>">
                    <?php if($v['setting_hide'] == 2){?>
                        <?php echo $v['teacher_name']?>：
                    <?php }?>
                    <?php echo $v['title']?>
                </a>
                <?php if($v['is_new'] == 1){?>
                    <img src="<?php echo ROOT_PATH;?>webStyle/images/new_voice.png" alt="" style="width:7%;float:left;margin-top:4px;">
                <?php }?>
            </li>
            <?php }?>
        </ul>
        <img id="contrllor" audio_id="0" class="voice_play play" src="<?php echo ROOT_PATH;?>webStyle/images/player_blue1.png" alt="">
    </div>
    <?php }?>
    <?php if($second_name){?>
        <a class="become_member" href="<?php echo $second_url_link?>"><?php echo $second_name?></a>
        <!-- <a class="become_member" href="<?php echo $second_url_link?>">成为会员：￥299开始学习</a> -->
    <?php }?>
    <div class="teacher_list" id="teacher_list">
        <ul>   
                
        </ul>
    </div>
    <div class="perfect_data">
    	<div class="title">
    		可试听,请完善资料
            <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
    	</div>
    		<ul class="present_detail">
                <li>
                    <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                </li>
                <li>
                    <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="javascript:(0);" class="gain_verification">获取验证码</a></div>


                </li>
                <a href="javascript:(0);" id="showPicker">
                    <li class="select">
                        <div>职位：
                        <span id='position' position_id="<?php echo $user['current_position_id'] ? $user['current_position_id'] : 0?>">
                          <?php echo isset($user['position_name']) && $user['position_name'] ? $user['position_name'] : ""?>
                        </span></div>
                    </li>
                </a>
                <li class="select">
                    <div>地区：<input class="weui_input" type="text" value="<?php echo $user['region'] ? $user['region'] : '广东省 广州市';?>" id='region' style="text-align:right"/></div>
                </li>
            </ul>
            <div>
            <ul class="operation">

                <li><a href="javascript:(0);" class="affirm"><p>完成</p></a></li>
            </ul>
    		</div>
    </div>
    <!-- 验证码错误 -->
    <div class="verification_wrong" >
        <div>您输入的验证码有误！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 verification_wrong_close"><p>确认</p></a></li>
              
            </ul>
        </div>
    </div>
    <!-- 验证码错误 -->
    <div class="captcha_wrong" >
        <div id="comment">请输入正确的手机号！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 captcha_wrong_close"><p>确认</p></a></li>
            </ul>
        </div>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href="javascript:void(0);"><img src="<?php echo ROOT_PATH;?>webStyle/images/home_on.png" alt=""><span class="select_on">首页</span></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/voice.png" alt=""><span>音频</span></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'video','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/video.png" alt=""><span>视频</span></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/mine.png" alt=""><span>我的</span></a></li>
        </ul> 
    </footer>
</body>   
</html>
<script>

$(function(){
    pushHistory();
    window.addEventListener("popstate", function(e) {
         WeixinJSBridge.call('closeWindow');
    }, false); 
});


sessionStorage.setItem('url_list', 0);
sessionStorage.setItem('url_audio_list', 0);
$("#region").cityPicker({
   title: "选择省市",
   showDistrict: false,
 });   
var is_perfect = '<?php echo $is_perfect?>';
var API_URL = '<?php echo API_URL?>';

var position = '<?php echo  isset($user['position']) && $user['position'] ? $user['position'] : ""?>'
var content = '<?php echo isset($user['position_id']) && $user['position_id'] ? $user['position_id'] : "";?>';
if(position){
	position = JSON.parse(position);	
}
if(content){
	content = JSON.parse(content);	
}

$('#showPicker').on('click', function () {
    weui.picker(position, {
        id: '#showPicker',
        defaultValue:[6],
        onChange: function (result) {
        	$(".picker_title").html("选择职位");            	
        },
        onConfirm: function (result) {
           var text = result[0];
           $("#position").html(content[text]);
           $("#position").attr('position_id',text);
        }
    });
});

$('.affirm').click(function(){
	var mobile = $('#mobile').val();
	var captcha = $('#captcha').val();
// 	var region_id = $('#region').attr('region_id');
	var region_id = $("#region").val();
	var position_id = $('#position').attr('position_id');
	if(!mobile){
		$('.captcha_wrong').show()
	    return false;
	}else{
	    if(!isMobile(mobile)){
	    	$('.captcha_wrong').show()
		    return false;
		}
	}
	if(!captcha){
		$("#comment").html('请输入短信验证码!');
		$('.captcha_wrong').show()
	    return false;
	}
	if(position_id == 0){
		$("#comment").html('请选择职位！');
		$('.captcha_wrong').show()
	    return false;
	}
	if(!region_id){
		$("#comment").html('请选择地区！');
		$('.captcha_wrong').show()
	    return false;
	}

	checkCaptcha();
});

var flat = true;
$(".gain_verification").on("click",function(){
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
// 	    alert('请输入正确的手机号码');
// 	    return false;
		$('.captcha_wrong').show()
	    return false;
	}
	if(flat){
    	sendCaptcha();
    	flat = false;
       var setTime;
       var time=60;
       $(".gain_verification").text('60s');
       $(".gain_verification").css("background-color","#cccccc");
        setTime=setInterval(function(){
            if(time<=0){
            	flat = true;
                clearInterval(setTime);
                 $(".gain_verification").text("获取验证码");
                $(".gain_verification").css("background-color","#d7000f");
                return false;
            }
            time--;
            $(".gain_verification").text(time+'s');
//             $(".gain_verification").css("background-color","#cccccc");
        },1000);
    }
})

function sendCaptcha()
{
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
// 	    alert('请输入正确的手机号码');
// 	    return false;
		$('.captcha_wrong').show()
	    return false;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
// 			var time=60;
// 	        setTime=setInterval(function(){
// 	            if(time<=0){
// 	            	flat = true;
// 	                clearInterval(setTime);
// 	                 $(".gain_verification").text("获取验证码");
// 	                $(".gain_verification").css("background-color","#d7000f");
// 	                return false;
// 	            }
// 	            time--;
// 	            $(".gain_verification").text(time+'s');
// 	            $(".gain_verification").css("background-color","#cccccc");
// 	        },1000);
		}
		else
		{
// 			alert(data.q.d);
			flat = true;
			$("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}

function checkCaptcha(){
	var code = $('#captcha').val();
	if(!code){
		$("#comment").html('请输入验证码！');
		$('.captcha_wrong').show()
	    return false;
	}
	var json = GetJson('SMSCode');
	json.q.a = 2;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.q.w = new Object();
	json.q.w.code = code;
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
			var mobile = $('#mobile').val();
// 			var region_id = $('#region').attr('region_id');
			var region_id = $("#region").val()
			var position_id = $('#position').attr('position_id');
			$.post("<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ajaxUpdateUserInfo'));?>",{mobile : mobile,position_id:position_id,region_id:region_id},function(result){
				if(result.code == 200){
					$('.perfect_data').hide();
				    $('.bgb').hide();
// 				    location.reload(true);
				    window.location.href=window.location.href+"?id="+10000*Math.random();
				}else{
				    alert(result.message);
				}
			},'json');
		}else{
			$("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}

$('.close').click(function(){
    $('.bgb').hide();   
    $(".perfect_data").hide();
});
$('.captcha_wrong_close').click(function(){
    $('.captcha_wrong').hide();
})


var play_img = '<?php echo ROOT_PATH;?>webStyle/images/player_blue1.png';
var pause_img = '<?php echo ROOT_PATH;?>webStyle/images/audio_pause1.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'ajaxAddStudyNum'));?>";
var finished = false;
var page = 1;
var current_audio_id = 0;
getTutorList();
adList();
function getTutorList(type){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'ajaxGetTutorList'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
  	    	 if(data.code == 200){
  	  	    	  var list = data.list;
  	    		  var dom = $("#teacher_list ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  url = '<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'details'));?>'
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         li += '<a href="'+url+'?id='+v.id+'">';
	                         li += '<img src="'+v.head_icon+'" alt="">';
	                         li += '<div>'+v.name+'：'+v.signature+'</div>';
	                         li += '</a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#teacher_list ul li').remove();
	                      }  
	                      $("#teacher_list ul").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#teacher_list ul li').remove();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#teacher_list ul li').remove();
	                  }
	              }
     },'json');
}

$('#repast_voice a').on('click',function(){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	var src = $(this).attr('src');
	var audio = document.getElementById("audio");

	$('#repast_voice a').removeClass('first_voice');
	$(this).addClass('first_voice');
	audio.src = src;

	var new_audio_id = $(this).attr('id');
	$("#contrllor").attr("audio_id",new_audio_id);
	if(audio.src != src || new_audio_id != current_audio_id){
		audio.src = src;
		current_audio_id = new_audio_id;
		$("#contrllor").addClass("play")
    }
	audio.loop = false; //歌曲循环
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
         $('.londing_gif').show();
    }else{
    	$("#contrllor").addClass("play").removeClass("pause");
    	$("#contrllor").attr('src',play_img);
    	audio.pause();//开始播放
    	$('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

$("#contrllor").click(function(){
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	var audio = document.getElementById("audio");
	var audio_id = $("#contrllor").attr('audio_id');
	
	if(audio_id == '0'){
		audio.src = '<?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['full_path'] : ""?>';
		$('#repast_voice a:first').addClass('first_voice');
		current_audio_id = <?php echo isset($four_free_audios[0]) ? $four_free_audios[0]['id'] : 0?>;
		$("#contrllor").attr('audio_id',current_audio_id);
	}
	
	if ($("#contrllor").hasClass("play")) {
		$("#contrllor").addClass("pause").removeClass("play");
		audio.play();//开始播放
		$("#contrllor").attr('src',pause_img);
		$("#"+audio_id).addClass('first_voice');
        $('.londing_gif').show();
    }
	else
	{
		$("#contrllor").addClass("play").removeClass("pause");
	    audio.pause();
	    $("#contrllor").attr('src',play_img);
	    $('#repast_voice a').removeClass('first_voice');
    }
	play_num_deal(current_audio_id);//播放量处理
});

var real_time;
audio.addEventListener("loadeddata", //歌曲一经完整的加载完毕( 也可以写成上面提到的那些事件类型)
    function() {
       var time = setInterval(function() {
        	var audio = document.getElementById("audio");
            var currentTime = audio.currentTime;
            if(real_time < currentTime){
                $('.londing_gif').hide();
            }/* else{
            	clearInterval(time);
            } */
            real_time = audio.currentTime;
        }, 1000);
}, false);



// 图片轮播
function adList(){
   TouchSlide({slideCell:"#banner",
               titCell:".hd ul",
               mainCell:'.bd ul',
               effect:'left',
               autoPlay:true,
               autoPage:true,
               interTime: <?php echo $adsTime;?>
        });           
   $('.hd ul').css('margin-left',($('.hd').width()-$('.hd ul').width())/2+'px');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getTutorList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});


    var t=$(".repast_voice ul").height()/2+15;
    $(".repast_voice ul").css("margin-top",-t)



$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".home_footer ul li img").css({"margin-bottom":"4px"})
        $(".perfect_data").css("bottom","20%");
    }
    else{
        $(".perfect_data").css("top","50%");
    }

}); 

if($('.swiper-wrapper').children().length>3){
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        // slidesPerView: 3,
        paginationClickable: true,
        slidesPerView: 'auto',
        // spaceBetween: 30
        // spaceBetween: 10,
        // slidesOffsetBefore : 10
    });

}



//
//wx.ready(function(){
//  	 shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php //echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>//webStyle/images/nightbird_log.png'};
//   	 share(shareData);
//});




</script>