<br>
<div class="pannel-body">
    <div class="pannel">
        <div class="pannel">
            <div class="row">
                <div class="pull-left ml8" style="margin-left:30px;">
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'grade'));?>" class="btn btn-primary">+新增</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th colspan="2">推荐人数范围</th>
                        <th>一级佣金(元)</th>
                        <th>二级佣金(元)</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($list as $k=>$v){?>
                        <tr id="item<?php echo $v['id']?>">
                            <td><?php echo $v['start']?></td>
                            <td><?php echo $v['end']?></td>
                            <td><?php echo $v['stair_brokerage']?></td>
                            <td><?php echo $v['second_brokerage']?></td>
                            <td><input class="btn btn-danger" type="button" onclick="deleteModal('<?php echo $v['id'];?>')" value="删除" /></td>
                        </tr>
                    <?php }?>
                    </tbody>
                </table>
                <div class="modal hide" id="myModal" style="width: 300px">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h3 id="titles" style="text-align: center">确定删除该分销等级</h3>
                    </div>
                    <div class="modal-footer">
                        <input type="hidden" name="id" value="" id="social_id">
                        <a href="#" class="btn" data-dismiss="modal">取消</a>
                        <input type="button" name="s" class="btn btn-primary"
                               onclick="submitDelete()" value="确定">
                    </div>
                </div>
                <div class="page-control">
                    <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function deleteModal(id){
        $('#social_id').val(id);
        $('#myModal').modal('show');
    }

    function submitDelete() {
        var url = '<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'deleteAwardAjax'))?>';
        var id = $('#social_id').val();
        $.post(url, {id: id}, function (data) {
            $('#item' + id).remove();
            $('#myModal').modal('hide');
        }, 'json');
    }
</script>