<br>
<div class="pannel-body">
    <div class="pannel">
        <div class="pannel">
            <div class="row">
                <div class="pull-left ml8" style="margin-left:30px;">
                    <a href="<?php echo $this->url('admin',array('controller' => 'System', 'action'=>'getExcel'));?>"  class="btn btn-purple btn-primary btn-sm">导出excel</a>
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'poster'));?>" class="btn btn-primary">分销设置</a>
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'award'));?>" class="btn btn-primary">分销奖励等级设置</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>用户名</th>
                        <th>手机号码</th>
                        <th>上线用户名</th>
                        <th>上线手机号码</th>
                        <th>一级下线数</th>
                        <th>一级佣金</th>
                        <th>二级下线数</th>
                        <th>二级佣金</th>
                        <th>佣金合计</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($list as $k=>$v){?>
                        <tr>
                            <td><?php echo $v['name'];?></td>
                            <td><?php echo $v['mobile'];?></td>
                            <td><?php echo $v['first_name'];?></td>
                            <td><?php echo $v['first_mobile'];?></td>
                            <td><?php echo $v['stair_num'];?></td>
                            <td><?php echo $v['stair_brokerage'];?></td>
                            <td><?php echo $v['second_num'];?></td>
                            <td><?php echo $v['second_brokerage'];?></td>
                            <td><?php echo $v['stair_brokerage'] + $v['second_brokerage'];?></td>
                        </tr>
                    <?php }?>
                    </tbody>
                </table>
                <div class="page-control">
                    <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
                </div>
            </div>
        </div>
    </div>
</div>
