<link rel="stylesheet" href="<?php echo $this->basePath();?>/adminStyle/css/iframe.css">
<script src="<?php echo $this->basepath();?>/adminStyle/js/jquery.colorbox.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/adminStyle/dropzone/dropzone.css" />
<script type="text/javascript" src="<?php echo $this->basePath()?>/adminStyle/dropzone/dropzone.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script>
<script src="<?php echo $this->basePath();?>/adminStyle/template/upload/ajaxfileupload.js"></script>

<script src="<?php echo $this->basePath();?>/ueditor/ueditor.config.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.all.min.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<style>
    .ace-thumbnails {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    .uploader{
        display: none;
    }
    .ace-thumbnails li{
        float: left;
        margin-left: 50px;
    }
    .ace-thumbnails{
        margin-left: 110px;
    }
    #mybigdropzone{
        margin-top: 10px;
    }
    #mydropzone{
        margin-top: 10px;
    }
        /*清除浮动代码*/
    .clearfloat{clear:both}
</style>
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            <legend class="lg_title">
                <span>分销设置：</span>
            </legend>
            <form id="submitForm" class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <label class="col-md-2 control-label">是否开启分销：</label>
                    <div class="col-md-8">
                        <input class="re-redio" name="is_open" type="radio" <?php if(isset($info) && $info['is_open'] == 1){echo 'checked'; };?> value="1"/> 是
                        <input class="re-redio" name="is_open" type="radio" <?php if(isset($info) && $info['is_open'] == 2){echo 'checked'; };?> value="2"/> 否
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">启用几级分销：</label>
                    <div class="col-md-8">
                        <input class="re-redio" name="rank" type="radio" <?php if(isset($info) && $info['rank'] == 1){echo 'checked'; };?> value="1"/> 一级
                        <input class="re-redio" name="rank" type="radio" <?php if(isset($info) && $info['rank'] == 2){echo 'checked'; };?>  value="2"/> 二级
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">分享按钮名称：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" name="button_name" id="button_name" value="<?php echo isset($info['button_name']) && $info['button_name'] ? $info['button_name'] : '';?>" />
                        <br/><span></span></div>
                    </div>
                </div>

                <div class="control-group">
                    <label class="col-md-2 control-label">佣金说明：</label>
                    <div class="col-md-8">
                        <div><textarea name="explain" id="explain" placeholder="请输入佣金说明" style="margin-left:140px;"><?php echo isset($info['explain']) && $info['explain'] ? $info['explain'] : '';?></textarea></div>
                    </div>
                </div>

                <div class="control-group">
                    <label class="col-md-2 control-label">分销规则：</label>
                    <div class="col-md-8">
                        <div><textarea name="rule" id="rule" placeholder="请输入分销规则" style="margin-left:140px;"><?php echo isset($info['rule']) && $info['rule'] ? $info['rule'] : '';?></textarea></div>
                    </div>
                </div>

                <div class="control-group">
                    <label class="col-md-2 control-label">分享主标题：</label>
                    <div class="col-md-8">
                        <div>
                            <textarea name="heading" id="heading" style="resize:none; width:80%;height:55px;"><?php echo isset($info['heading']) && $info['heading'] ? $info['heading'] : '';?></textarea>
                        </div>
                    </div>
                    <br>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">分享副标题：</label>
                    <div class="col-md-8">
                        <div>
                            <textarea name="subheading" id="subheading" style="resize:none; width:80%;height:55px;"><?php echo isset($info['subheading']) && $info['subheading'] ? $info['subheading'] : '';?></textarea>
                        </div>
                    </div>
                    <br>
                </div>
                <div>
                    <label class="control-label">分享图标：</label>
                    <div class="controls portraits">
                        <div style="border: 2px solid #ccc; width: 80px">
                            <img class="show_img" id="img_1" width="80" height="80" border="1" src="<?php echo  $this->basePath().(isset($info['img_path']) && $info['img_path'] ? '/'.UPLOAD_PATH.$info['img_path'] :'/images/portrait.png');?>" alt="">
                        </div>
                        <br><span>（注：像素80x80或者宽高比与此相同）</span>
                        <div style="display: none;">
                            <input type="hidden" id="img_id_1" name="img_id_1" value="<?php if(isset($info['img_id']) && $info['img_id']){echo $info['img_id'];} ?>" />
                            <input id="img_path_1" type="hidden" name="img_path_1" value="<?php if(isset($info['img_path']) && $info['img_path']){echo $info['img_path'];} ?>"/>
                            <input class="img" type="file" id="img1" name="Filedata[]" onchange="return ajaxFileUpload('1');"/>
                        </div>
                    </div>
                </div>
                <br>

                <div class="control-group">
                    <label class="col-md-2 control-label">分享打开页面内容：</label>
                    <div class="col-md-8">
                        <div><textarea name="content" id="editor" placeholder="请输入分享打开页面内容" style="margin-left:140px;"><?php echo isset($info['content']) && $info['content'] ? $info['content'] : '';?></textarea></div>
                    </div>
                </div>
                <br>
            	<div class="control-group">
                    <div class="control-group">
                        <label class="col-md-2 control-label">分销海报大图片：</label>
                        <div style="margin-top:6px; "><span  style="color: red;" >像素474*842或宽高比与此相同</span></div>
                    </div>
                    <div class="col-md-8">
                        <div class="article_list">
                            <div id="big_img" class="dataTables_wrapper form-inline no-footer">
                                <div>
                                    <ul class="ace-thumbnails " id="big" style="border: 0; width: 100%;">
                                        <?php $i = 0;if(isset($info['big_img']) && $info['big_img']){foreach ($info['big_img'] as $k=>$v){;?>
                                            <li  id="xpic<?php echo $k;?>" data-rel="colorbox" class="cboxElement">
                                                <a href="javascript:void(0)" onclick="delImg(<?php echo $k;?>,'xpic')">
                                                    <div class="imagestyle">
                                                        <img src="<?php echo $this->basepath() . '/'  . UPLOAD_PATH .  $v;?>" style="width: 125px; height: 188px;">
                                                    </div>
                                                    </a>
                                                    <div class="tools tools-bottom" style="width: 125px;">
                                                        <input name="big_img_ids[]" type="hidden" value="<?php echo $k;?>">
                                                        <input name="bit_paths[]" type="hidden" value="<?php echo $v;?>">
                                                         <i class="ace-icon fa fa-times red"></i>
                                                    </div>
                                                </a>
                                            </li>
                                        <?php }}?>
                                    </ul>
                                    <div class="clearfloat"></div>
                                </div>
                                <div id="mybigdropzone"  class="dropzone dz-clickable" style="padding: 21px 0;<?php echo $i >= 6?'display: none;':''; ?>">
                                    <div class="dz-default dz-message">
                                        <span>请添加请分享海报大图片</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="control-group">
                        <label class="col-md-2 control-label">分销海报小图片：</label>
                        <div style="margin-top:6px; "><span  style="color: red;" >像素122*122或宽高比与此相同</span></div>
                    </div>
                    <div class="col-md-8">
                        <div class="article_list">
                            <div id="small_img" class="dataTables_wrapper form-inline no-footer">
                                <div>
                                    <ul class="ace-thumbnails " id="small" style="border: 0; width: 100%;">
                                        <?php $i = 0;if(isset($info['small_img']) && $info['small_img']){foreach ($info['small_img'] as $k=>$v){$i++;?>
                                            <li id="spic<?php echo $k;?>" data-rel="colorbox" class="cboxElement">
                                                <a href="javascript:void(0)" onclick="delImg(<?php echo $k;?>,'spic')">
                                                    <div class="imagestyle">
                                                        <img style="width:120px;height:120px;"  src="<?php echo $this->basepath() . '/'  . UPLOAD_PATH .  $v;?>" style="width: 125px; height: 188px;">
                                                    </div>
                                                    <div class="tools tools-bottom" style="width: 125px;">
                                                        <input name="small_img_ids[]" type="hidden" value="<?php echo $k;?>">
                                                        <input name="small_paths[]" type="hidden" value="<?php echo $v;?>">
                                                         <i class="ace-icon fa fa-times red"></i>
                                                    </div>
                                                </a>
                                            </li>
                                        <?php }}?>
                                    </ul>
                                    <div class="clearfloat"></div>
                                </div>
                                <div id="mydropzone"  class="dropzone dz-clickable" style="padding: 21px 0;<?php echo $i >= 6?'display: none;':''; ?>">
                                    <div class="dz-default dz-message">
                                        <span>请添加请分享海报小图片</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="control-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-8">
                            <input type="hidden" value="<?php echo isset($info) ? $info['id'] : 0;?>" name="id" />
                            <input type="hidden" value="03" name="ajax" />
                            <input type="button" class="btn btn-large btn-primary" id="ap" value="保存" onclick="save()"/>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('controller' => 'common', 'action'=>'uploadImage'));?>';//图片上传地址
    $(".show_img").click(function () {
        $(this).parent().parent().find(".img").click();
    })
</script>
<script>
    function save(){
        if(!$('#button_name').val()){
            alert('请填写分享按钮名称');
            return false;
        }
        if(!$('#heading').val()){
            alert('请填写分享主标题');
            return false;
        }
        if(!$('#subheading').val()){
            alert('请填写分享副标题');
            return false;
        }
        if(!$('#img_id_1').val()){
            alert('请选择分享图标');
            return false;
        }
        $("form").submit();
        return false;
    }
    var sum = 5 - $("#big_img  li").length;
    var small_sum = 5 - $("#small_img li").length;
    var url = "<?php echo $this->url('admin', array('controller' => 'common', 'action' => 'uploadImage'));?>";
    uploadImage(sum,url,'mybigdropzone');
    uploadImage2(small_sum,url,'mydropzone');
    showImageAdd('xpic');
    showImageAdd('spic');
    var mybigDropzone;
    var mydropzone;
    //删除图片
    function delImg(imgId,type){
        $('#'+type+imgId).remove();
        if(type == 'xpic'){
            sum = Number(sum)  + 1;
            mybigDropzone.options.maxFiles = sum;
        }else{
            small_sum = Number(small_sum)  + 1;
            mydropzone.options.maxFiles = small_sum;
        }
        showImageAdd(type);
    }

    function showImageAdd(type) {
        // 活动说明页多图上传按钮隐藏与显示
        if(type == 'xpic'){
            if ($("#big_img  li").length >= 5) {
                $("#mybigdropzone").hide();
            }
            else {
                $("#mybigdropzone").show();
            }
        }else{
            if ($("#small_img  li").length >= 5) {
                $("#mydropzone").hide();
            }
            else {
                $("#mydropzone").show();
            }
        }

    }
    //dropzone上传图片
    function uploadImage(sum,url,word){
        mybigDropzone = new Dropzone("div#"+word, {
            url: url,
            paramName: "Filedata",
            maxFilesize: 5, // MB
            maxFiles: sum,//数量
            acceptedFiles: ".jpg,.png,.gif,.jpeg",
            addRemoveLinks:true,
            dictRemoveFile:'取消',
            dictDefaultMessage: "请添加分享海报图片",
            init:function(){
                this.on("addedfile", function(file) {

                });
                this.on("queuecomplete",function(file) {

                });
                this.on("removedfile",function(file){
                    //删除时触发的方法
                    var imgid = file.imgid;
                    $("#pic"+imgid).remove();
                });
                this.on("success", function(file,jsonDate) {
                    var jsonObj = JSON.parse( jsonDate );
                    file.imgid = jsonObj.imgid;
                    file.path = jsonObj.path1;
                    var dropHtml = file.previewTemplate.innerHTML;
                    var dropsrc = $(dropHtml).find('img').attr('src');
                    var imgid = jsonObj.imgid;
                    var path = jsonObj.path1;
                    var basepath = "<?php echo $this->basePath().'/uploadfiles/';?>";
                    var picpath = basepath + path;
                    var template = '<li id="pic'+ imgid +'" style="border:0;"><a href="javascript:void(0)"><div class="imagestyle"><img src="'+ dropsrc +'" style="width:125px;height:188px;"/></div></a><div><input name="big_img_ids[]" type="hidden" value="'+ imgid +'"><input name="bit_paths[]" type="hidden" value="'+ path +'"></div></li>';
                    $('#big').append(template);
                });
            }
        });
    }

    //dropzone上传图片
    function uploadImage2(sum,url,word){
        mydropzone = new Dropzone("div#"+word, {
            url: url,
            paramName: "Filedata",
            maxFilesize: 5, // MB
            maxFiles: sum,//数量
            acceptedFiles: ".jpg,.png,.gif,.jpeg",
            addRemoveLinks:true,
            dictRemoveFile:'取消',
            dictDefaultMessage: "请添加分享海报图片",
            init:function(){
                this.on("addedfile", function(file) {

                });
                this.on("queuecomplete",function(file) {

                });
                this.on("removedfile",function(file){
                    //删除时触发的方法
                    var imgid = file.imgid;
                    $("#pic"+imgid).remove();
                });
                this.on("success", function(file,jsonDate) {
                    var jsonObj = JSON.parse( jsonDate );
                    file.imgid = jsonObj.imgid;
                    file.path = jsonObj.path1;
                    var dropHtml = file.previewTemplate.innerHTML;
                    var dropsrc = $(dropHtml).find('img').attr('src');
                    var imgid = jsonObj.imgid;
                    var path = jsonObj.path1;
                    var basepath = "<?php echo $this->basePath().'/uploadfiles/';?>";
                    var picpath = basepath + path;
                    var template = '<li id="pic'+ imgid +'" style="border:0;"><a href="javascript:;" data-rel="colorbox"><div class="imagestyle"><img src="'+ dropsrc +'" style="width:120px;height:120px;"/></div></a><div><input name="small_img_ids[]" + type="hidden" value="'+ imgid +'"><input name="small_paths[]" type="hidden" value="'+ path +'"></div></li>';
                    $('#small').append(template);
                });
            }
        });
    }

    var ue = UE.getEditor('editor', {
        "initialFrameWidth" : "87%",
        "initialFrameHeight" : 400,
        "maximumWords" : 8000,
    });

    var ue = UE.getEditor('explain', {
        "initialFrameWidth" : "87%",
        "initialFrameHeight" : 400,
        "maximumWords" : 400,
        toolbars: [
            ['fullscreen', 'source', 'undo', 'redo', 'bold', 'italic', 'underline', 'strikethrough', '|', 'forecolor', 'backcolor', 'selectall', 'cleardoc','|', 'justifyleft', 'justifyright', 'justifycenter', 'justifyjustify',]
        ]
    });

    var ue = UE.getEditor('rule', {
        "initialFrameWidth" : "87%",
        "initialFrameHeight" : 400,
        "maximumWords" : 400,
        toolbars: [
            ['fullscreen', 'source', 'undo', 'redo', 'bold', 'italic', 'underline', 'strikethrough', '|', 'forecolor', 'backcolor', 'selectall', 'cleardoc','|', 'justifyleft', 'justifyright', 'justifycenter', 'justifyjustify',]
        ]
    });
</script>
