<link href="<?php echo $this->basePath() . '/css/uploadifive.css'?>" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->basePath() . '/js/jquery.uploadifive.min.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/js/uploadifive.single.js'?>"  type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/cos-js-sdk-v4-master/dist/cos-js-sdk-v4.js'?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/cos-js-sdk-v4-master/demo/crypto.js'?>"></script>

<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('action'=>'getAdminFile')) ;?>';
</script>

<!--富文本编辑器-->
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/themes/default/default.css'?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.css'?>" media="screen" rel="stylesheet" type="text/css">

<script src="<?php echo $this->basePath() . '/plugins/kindeditor/kindeditor-all.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/lang/zh-CN.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.js'?>"  type="text/javascript"></script>

<style>
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
    .video-upload{
        margin-top: 10px;
        display:block;
        width:45px;
    }
</style>
<div class="page-header">
    <h1>
        视频添加
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" role="form" action="<?php echo $this->url('admin-video', ['action'=>'videoAdd']) ?>" method="post">
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 视频名称：</label>

            <div class="col-sm-9">
                <input type="text" name="name" required id="form-field-1" placeholder="视频名称" class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1"> 视频分类：</label>

            <div class="col-sm-9">
                <select name="category_id" class="col-xs-10 col-sm-5">
                    <?php if(!$category_list){?>
                        <option value="0">请先添加视频分类</option>
                    <?php }else{?>
                    <option value="0">请选择分类</option>
                    <?php foreach ($category_list as $v) {?>
                        <option value="<?php echo $v->id?>"><?php echo $v->name?></option>
                    <?php }}?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right">视频收费：</label>

            <div class="col-sm-9">
                <input type="radio" name="pay_type" value="1" class="ace" checked onclick="showPriceDiv()"/>
                <span class="lbl">免费</span>
                <input type="radio" name="pay_type" value="2" class="ace" onclick="showPriceDiv()"/>
                <span class="lbl">收费</span>
            </div>
        </div>
        <div class="form-group" style="display: none" id="price">
            <label class="col-sm-1 control-label no-padding-right">视频价格：</label>

            <div class="col-sm-9">
                <div class="layui-input-inline">
                    <input type="text" name="price" class="form-control" style="height: 30px;">
                </div>
            </div>
        </div>
        <!-- 一次上传多张图片插件 -->
        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 视频封面：</label>
            <div class="col-sm-9">
                <div class="mot_tright" id="img_div">
                    <input id="one_img_upload" type="file"/>
                    <div id="res_img"></div>
                </div>
            </div>
        </div>

        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 完整视频：</label>
            <div class="col-sm-9">
                <div class="mot_tright">
                    <input type="file"/>
                    <input type="hidden" id="full_path" name="full_path"  />
                    <input type="hidden" id="audio_length" name="audio_length">
                    <div class="col-sm-3" style="background-color: #cccccc;padding:0px;margin-top:5px;"></div><br/>
                    <a class="btn btn-xs btn-info video-upload">上传</a>
                </div>
            </div>
        </div>

        <div class="form-group">

            <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 试播视频：</label>
            <div class="col-sm-9">
                <div class="mot_tright">
                    <input type="file"/>
                    <input type="hidden" id="auditions_path" name="auditions_path"  />
                    <input type="hidden" id="auditions_length" name="auditions_length">
                    <div class="col-sm-3" style="background-color: #cccccc;padding:0px;margin-top:5px;"></div><br/>
                    <a class="btn btn-xs btn-info video-upload">上传</a>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-1 control-label " for="form-field-1-1">视频介绍：</label>

            <div class="col-sm-9">
                <textarea name="description" style="width:80%;height:600px;visibility:hidden;"></textarea>
            </div>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a href="javascript:history.back(-1);" class="btn" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
<script>
    jQuery(function($) {
        //腾讯云 获取签名
        var url = '<?php echo $this->url('admin-cos', ['action' => 'getSign'])?>';
        var bucket = '<?php echo $bucket?>';
        var region = '<?php echo $region?>';
        var appid = '<?php echo $appid?>';
        var cos = new CosCloud({
            appid:appid,
            bucket: bucket,//bucketName 必填参数
            region: region,//地域信息 必填参数 华南地区填gz 华东填sh 华北填tj
            getAppSign: function (callback) {//获取签名 必填参数
                $.get(url,{},function(data){
                    console.log(data);
                    var sign = data.sign;
                    callback(encodeURIComponent(sign));
                },'json');
            },
        });

        var successCallBack = function (result) {
            var a = JSON.stringify(result);
            console.log(result);
            //$("#result").val(JSON.stringify(result));
            layer.msg('上传成功');
            //加入到隐藏input
            var data = result.data ?  result.data.access_url : "";
            $('#video_src').val(data);
            //加入到隐藏video标签
            $('#for_video_length').attr('src',data);
        };
        // var myVid=document.getElementById("for_video_length");
        // myVid.ondurationchange=function(){
        //     $('#video_length').val( $('#for_video_length')[0].duration);
        // }



        var errorCallBack = function (result) {
            result = result || {};
            //$("#result").val(result.responseText || 'error');
            console.log(result.responseText);
            $('#progress span').remove();
            layer.msg('上传失败');
        };

        var progressCallBack = function(curr){
            //$("#result").val('uploading... curr progress is '+curr);
            $('#progress span').css('width',(curr*100)+'%');
            console.log(curr);
        };

        $('.video-upload').on('click',function(){
            var file_obj = $(this).parents('.mot_tright').find('input[type="file"]');
            var files = file_obj.prop('files');
            console.log(files);
            var file_name = files[0].name;
            console.log(file_name);
            var timestamp = Date.parse(new Date());
            //var path = '/video/'+timestamp+'/'+file_name;
            var path = '/video/'+timestamp+file_name;
            //console.log(files);
            //50M 52428800
            // if(files[0].type != 'video/mp4'){
            //     layer.msg('请选择mp4文件');
            //     return false;
            // }
            if(files[0].size > 52428800){
                layer.msg('文件大小不能超过50M');
                return false;
            }
            $('#size').val(files[0].size);
            $('#filename').val(file_name);
            console.log('开始上传...');
            //console.log(path);

            //开始上传
            cos.sliceUploadFile(successCallBack, errorCallBack, progressCallBack,bucket,path,files[0],0);
            var progress = $(this).parents('.mot_tright').find('.progress');
            progress.html('');
            progress.html('<span class="progress_bar">&nbsp;</span>');
        });

    });
</script>


<script>
    var editor;
    KindEditor.ready(function(K) {
         editor = K.create('textarea[name="description"]', {
             afterBlur: function () { this.sync(); }
        });
    });

    function showPriceDiv(){
        $.each($('input[name="pay_type"]'),function(){
            var checked = $(this).prop("checked");
            if(checked){
                var pay_type = $(this).val();
                if(pay_type == 2){
                    $('#price').show();
                }else{
                    $('#price').hide();
                }
            }
        });
    }
</script>

<script type="text/javascript">
    $('form').submit(function (e) {
        if(!dateValidate()){
            return false;
        }
        if(!$('input[name="image_id"]').val()){
          showMessage('必须选择图片', 0);
          return false;
        }
        if($('select[name="type"]').val() == 3){
            if(!$('textarea[name="content"]').val()){
                showMessage('图文详情不能为空', 0);
                return false;
            }
        }
        else if($('select[name="type"]').val() == 4){
            if(!$('input[name="link"]').val()){
                showMessage('自定义链接不能为空', 0);
                return false;
            }
            if(!/^https?:\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?$/.test($('input[name="link"]').val())){
                showMessage('自定义链接不合法', 0);
                return false;
            }
        }
        ajaxForm(e);
    });
</script>
