
<div id="content" class="span10">
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
				<form action="" method="post" class="form-horizontal" id="submitForm">
					<fieldset>
						<legend class="lg_title">
							<span>系统设置-新增版块：</span>
						</legend>
						<section style="overflow: hidden;">
							<div style="float: left;">
								<div class="control-group">
									<label class="control-label">版块名称：</label>
									<div class="controls">
										<input name="name" id="name" required="required"class="input-xlarge" type="text" value=""
											placeholder="请输入版块名称"><br><span>请设置一级版块,建议4个字内</span>
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label">所属分类：</label>
									<div class="controls">
									    <select name="type" id="type">
                                            <option value="0" id="select-type">请选择分类</option> 
                                            <?php foreach ($category_list as $k=>$v){ ?>
                                                <option value="<?php echo  $k;?>"><?php echo $v;?></option>
                                            <?php }?>
                                         </select>
                                    </div>
								</div>
								<div class="control-group">
									<label class="control-label">排序序号：</label>
									<div class="controls">
										<input name="sort" id="sort" required="required" maxlength="11"
											class="input-xlarge" type="text"
											placeholder="请输入排序序号">
											<br><span>排序越小，位置越前</span>
									</div>
								</div>
							</div>
							
						</section>
						<div class="control-group">
							<label class="control-label" for="focusedInput"></label>
							<div class="controls" style="margin-top: 10px;">
								<div class="controls" style="margin-top: 10px;">
									<input name="sb" class="btn btn-large btn-primary" type="submit" id="submit-button"
										value="保存" />
									<input class="btn btn-large btn-primary resetHref" type="reset" value="取消" />
									
								</div>
							</div>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(".resetHref").click(function(){
    location.href = '<?php echo $this->url('admin',array('controller'=>'System','action'=>'category'));?>';
});
$("#submit-button").click(function(){
    var sort = $("#sort").val();
    var name = $("#name").val();
    var type = $("#type").val();
    console.log(type);
    if(!name){
    	alert('版块名称不能为空'); // message.js
    	return false;
    }
    if(type == 0){
    	alert('请选择分类'); // message.js
    	return false;
    }
    if(!sort){
    	alert('排序序号不能为空'); // message.js
    	return false;
    } 
    $("#submitForm").submit();
 });
	
</script>
