<link rel="stylesheet" href="<?php echo $this->basePath();?>/adminStyle/css/iframe.css">
<style>
    .iphone-iframe .iphone-bg {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/device-sprite.png");
    }
    .iphone-bg-header {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/status-bar.png");
    }
</style>
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            <legend class="lg_title">
                <span>活动设置：</span>
            </legend>
            <form id="submitForm" class="form-horizontal" method="post" action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addMarketing'));?>">
                <div class="control-group">
                    <label class="col-md-2 control-label">奖励金额：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" maxlength="3"  name="price" id="price"  onkeyup="value=value.replace(/[^\d]/g,'')"/>  &nbsp;&nbsp;&nbsp;&nbsp;元
                        <br/><span>用户在领取后，钱包将充值入对应的金额</span></div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">会员天数：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" name="days" maxlength="3" id="days"  onkeyup="value=value.replace(/[^\d]/g,'')"/>  &nbsp;&nbsp;&nbsp;&nbsp;天
                        <br/><span>用户在领取后，会员有效期将在原有基础上增加</span></div>
                    </div>
                </div>
                  <div class="control-group">
                    <label class="col-md-2 control-label">有效期：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" id="putaway_time3" name="time"/></div>
                   </div>
                 </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">生成数量：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" maxlength="4" name="number" id="number"  onkeyup="value=value.replace(/[^\d]/g,'')"/>  &nbsp;&nbsp;&nbsp;&nbsp;份</div>
                    </div>
                </div>
			     <div class="control-group">
                    <label class="col-md-2 control-label">备注说明：</label>
                    <div class="col-md-8">
                       <div class="controls"><textarea name="content" id="status" style="resize:none;width:60%;height:55px;"onkeydown='countChar("status","counter");' 
                    onkeyup='countChar("status","counter");'></textarea>
                    <span class="wordwrap tr" style="width: 40px;"><i id="counter"></i></span></div>
                    </div>
                    <br>
                </div>
              
                <div class="control-group">
                    <label class="col-md-2 control-label"></label>
                    <div class="col-md-8">
                          <input type="hidden" value="03" name="ajax" />
                          <input type="button" class="btn btn-large btn-primary" id="ap" value="生成二维码" onclick="save()"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
<?php if(isset($info) && $info){?>
countChar("status","counter");
<?php }?>
    function countChar(textareaName,spanName)
    {
        document.getElementById(spanName).innerHTML = document.getElementById(textareaName).value.length;
    }
function save(){
	var url = '';
	var form = $("#submitForm");
	form.attr("action", url);
	form.removeAttr("target");//消除target(打开方式)
	form.submit();
}

function preview() {
	var url = '<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'memberPreview'));?>';
	//$("#editor").val(UE.getEditor('editor').getContent());
	var form = $("#submitForm");
	form.attr("action", url);
	form.attr("target", "previewIframe");
	form.submit();
}
$('.iphone-iframe').css({
    'width':$(window).width()+'px',
    'height':$(window).height()+'px'
});
$('.iphone-bg').css({
    'top':($(window).height()-$('.iphone-bg').height())/2+'px',
    'left':($(window).width()-$('.iphone-bg').width())/2+'px'
});
$('#ap1').click(function(){
    $('.iphone-iframe').toggle();
});
$('.iphone-btn').click(function() {
    $('.iphone-iframe').toggle();
});
</script>
<script>
// //上传封面
var upload_url = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'uploadImage'));?>'; // uploadImage.js
$("#show_image_1").click(function(){
  $("#uploadImage").click();
});
</script>
