<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="pannel">
        <div class="row">
            <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'roleList'));?>">
                <div class="pull-left ml8" style="margin-left:30px;">
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'adminDetails'));?>" class="btn btn-primary">+新增管理员</a>
                </div>
                <div class="pull-right">
                	<div class="pull-left ml8" style="position: relative">
                        <input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="输入姓名、手机号码" value="<?php echo isset($keyword) ? $keyword:'';?>">
                        <i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
                    </div>
                    <div class="pull-left ml8" >
                        <span style="margin-left:20px;">角色：</span>
                        <div class="btn-group marginTB-xs" style="display:inline-block;margin-left: 15px;">
                            <select class="select-top"  name="cid" size="1" id="select">
                            	<option value="0" <?php echo $cid==0?'selected="selected"':''?>>全部</option>
                                <?php foreach ($role_list as $v){ ?>
                                    <option value="<?php echo  $v['id'];?>" <?php echo $cid==$v['id']?'selected="selected"':'';?>><?php echo $v['name'];?></option>
                                <?php }?>
                    		</select>
                    	</div>
                    </div>
                    <div class="pull-left ml8" >
                        <span style="margin-left:20px;">账号状态：</span>
                        <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px;">
                            <select class="select-top" name="types" size="1" id="select">
                            	<option value="0" <?php echo $types==0?'selected="selected"':''?>>全部</option>
                                <option value="1" <?php echo $types==1?'selected="selected"':''?>>正常</option>
                                <option value="2" <?php echo $types==2?'selected="selected"':''?>>禁用</option>
            				</select>
            			</div>
            		</div>
            		<div class="pull-left ml8" >
            			<button type="submit" class="btn btn-info submit">搜索</button>
            		</div>
            	</div>
            </form>
        </div>
    </div>
</div>
<div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>头像</th>
                    <th>姓名</th>
                    <th>登录账号</th>
                    <th>职务</th>
                    <th>手机号码</th>
                    <th>最近登录时间</th>
                    <th>账号状态</th>
                    <th>操作</th>
                </tr>
                </thead>
             <tbody>
                <?php foreach($list as $k=>$v){?>
                <tr>
                     <td><img width="40" height="40" src="<?php echo  $this->basePath().(isset($v['image']) && $v['image'] ? '/'.UPLOAD_PATH.$v['image'] :'/images/portrait.png');?>" alt=""></td>
                     <td><?php echo $v['name'];?></td>
                     <td><?php echo $v['login_name'];?></td>
                     <td><?php echo $v['admin_type'];?></td>
                     <td><?php echo $v['mobile'];?></td>
                     <td><?php echo $v['last_login_time'];?></td>
                     <td><?php echo $v['status'] == 1 ? "正常" : "禁用";?></td>
                    <td>
        			<?php if($v['admin_manage'] == 'all'){?>
    					<a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'adminDetails', 'id' => $v['id'], 'cid' => 1));?>" class="btn btn-info">查看</a>
    					<?php }else{
    					if($v['status']==1){?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDelete', 'id' => $v['id'],'types'=>2));?>" class="btn btn-warning">禁用</a>
    					<?php }else{?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDelete', 'id' => $v['id'],'types'=>1));?>" class="btn btn-success ">启用</a>
    					<?php }?>
    					<a onclick="deleteWallet(<?php echo $v['id']?>)" class="btn">删除</a>
    					 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'adminDetails', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
					 <?php }?>
                    </td>
                </tr>
                <?php }?>
    
                </tbody>
            </table>
            <div class="page-control">
            <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
           </div>
        </div>
     </div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDeleteAdmin'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>