<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="pannel">
        <div class="row">
            <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'category'));?>">
                <div class="pull-left ml8" style="margin-left:30px;">
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'addCategory'));?>" class="btn btn-primary">+新增一级版块</a>
                </div>
                <div class="pull-right">
                	
                    <div class="pull-left ml8" >
                        <span style="margin-left:20px;">分类：</span>
                        <div class="btn-group marginTB-xs" style="display:inline-block;margin-left: 15px;">
                            <select class="select-top"  name="cid" size="1" id="select">
                            	<option value="0" <?php echo $cid==0?'selected="selected"':''?>>全部</option>
                                <?php foreach ($category_list as $k => $v){ ?>
                                    <option value="<?php echo  $k;?>" <?php echo $cid==$k?'selected="selected"':'';?>><?php echo $v;?></option>
                                <?php }?>
                    		</select>
                    	</div>
                    </div>
            		<div class="pull-left ml8" >
            			<button type="submit" class="btn btn-info submit">搜索</button>
            		</div>
            	</div>
            </form>
        </div>
    </div>
</div>
<div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>排序序号</th>
                    <th>版块名称</th>
                    <th>分类</th>
                    <th>子板块数</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
             <tbody>
                <?php foreach($list as $k=>$v){?>
                <tr>
                     <td><?php echo $v['sort'];?></td>
                     <td><?php echo $v['name'];?></td>
                     <td><?php echo $category_list[$v['type']];?></td>
                     <td><?php echo $v['number'];?></td>
                     <td><?php echo $v['status'] == 1 ? "正常" : "禁用";?></td>
                    <td>
    					<?php
    					if($v['status']==1){?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'categoryDelete', 'id' => $v['id'],'types'=>2));?>" class="btn btn-warning">禁用</a>
    					<?php }else{?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'categoryDelete', 'id' => $v['id'],'types'=>1));?>" class="btn btn-success ">启用</a>
    					<?php }?>
    					<a onclick="deleteWallet(<?php echo $v['id']?>)" class="btn">删除</a>
    					<a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'categoryDetails', 'id' => $v['id']));?>" class="btn btn-info">编辑</a>
                    </td>
                </tr>
                <?php }?>
    
                </tbody>
            </table>
            <div class="page-control">
            <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
           </div>
        </div>
     </div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDeleteCategory'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>