
<div id="content" class="span10">
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
				<form action="" method="post" class="form-horizontal" id="submitForm">
					<fieldset>
						<legend class="lg_title">
							<span>系统设置-版块详情：</span>
						</legend>
						<legend class="lg_title">
							<span>一级版块信息：</span>
						</legend>
						<section style="overflow: hidden;">
						     <input type="hidden" name="id" value="<?php echo $cate_list['id'];?>"/>
							<div style="float: left;">
								<div class="control-group">
									<label class="control-label">版块名称：</label>
									<div class="controls">
										<input name="name" id="name" required="required"class="input-xlarge" type="text" value="<?php echo $cate_list['name'];?>"
											placeholder="请输入版块名称"><br><span>请设置一级版块,建议4个字内</span>
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label">所属分类：</label>
									<div class="controls">
									    <select name="type" id="type">
                                            <option value="0" id="select-type">请选择分类</option> 
                                            <?php foreach ($category_list as $k=>$v){ ?>
                                                <option value="<?php echo  $k;?>" <?php if($cate_list){ echo $cate_list['type'] == $k ?'selected="selected"':'';}?>><?php echo $v;?></option>
                                            <?php }?>
                                         </select>
                                    </div>
								</div>
								<div class="control-group">
									<label class="control-label">排序序号：</label>
									<div class="controls">
										<input name="sort" id="sort" required="required" maxlength="11"
											class="input-xlarge" type="text" value="<?php echo $cate_list['sort'];?>"
											placeholder="请输入排序序号">
											<br><span>排序越小，位置越前</span>
									</div>
								</div>
							</div>
							
						</section>
						<legend class="lg_title">
							<span>二级版块信息：</span>
						</legend>
			<div class="pannel">
            <div class="row">
                    <form class="form-horizontal" method="post" action="">
                      <div class="pull-left ml8" style="margin-left:30px;">
                            <a href="#" id="addUserJob" class="btn btn-info">+新增子版块</a>
                       </div>
                    <div class="pull-right">
               
                    </div>
                    </form>
            </div>
            <div class="row-fluid sortable">
                <div class="box span12">
                    <div class="box-content">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>子版块名称</th>
                                <th>状态</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                         <tbody>
                            <?php foreach($list as $k=>$v){?>
                            <tr>
                                <td id="o_sort" abbr="<?php echo $v['id']?>"><?php echo$v['sort'];?></td>
                                <td id="o_name"><?php echo $v['name'];?></td>
                                <td id="o_status"><?php echo $v['status'] == 1 ? "正常" : "禁用" ;?></td>
                                <td>
                                     <?php if($v['status']==1){?>
                						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'categoryDelete', 'id' => $v['id'],'types'=>2,'cid' => '1','pid' => $cate_list['id']));?>" class="btn btn-warning">禁用</a>
                					<?php }else{?>
                						 <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'categoryDelete', 'id' => $v['id'],'types'=>1,'cid' => '1','pid' => $cate_list['id']));?>" class="btn btn-success ">启用</a>
                					<?php }?>
                                     <a onclick="deleteWallet(<?php echo $v['id'];?>)" class="btn btn-warning">删除</a>
                                     <a href="#"  class="btn btn-info" >编辑</a>
                                </td>
                            </tr>
                            <?php }?>
                
                            </tbody>
                        </table>
                            <div class="page-control">
                            <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
                           </div>
                    </div>
                </div>
            </div>
            <div class="control-group">
				<label class="control-label" for="focusedInput"></label>
				<div class="controls" style="margin-top: 10px;">
					<div class="controls" style="margin-top: 10px;">
						<input name="sb" class="btn btn-large btn-primary" type="submit" id="submit-button"
							value="保存" />
						<input class="btn btn-large btn-primary resetHref" type="reset" value="取消" />
						
					</div>
				</div>
			</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDeleteCategory','cid' => '1','pid' => $cate_list['id']));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
//	$('#myModal').modal('hide');
  $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
$(".resetHref").click(function(){
    location.href = '<?php echo $this->url('admin',array('controller'=>'System','action'=>'category'));?>';
});
$("#submit-button").click(function(){
    var sort = $("#sort").val();
    var name = $("#name").val();
    var type = $("#type").val();
    console.log(type);
    if(!name){
    	alert('版块名称不能为空'); // message.js
    	return false;
    }
    if(type == 0){
    	alert('请选择分类'); // message.js
    	return false;
    }
    if(!sort){
    	alert('排序序号不能为空'); // message.js
    	return false;
    } 
    $("#submitForm").submit();
 });
$("#addUserJob").click(function() {
    $(".table-bordered tbody").append('<tr><td><input type="text" name="sort_num" id="sort_num"/></td><td><input type="text" name="name" id="con"/></td><td><input type="text" name="status" placeholder="1为正常 2为禁用" id="status"/></td><td><a onclick="ensure()" class="btn btn-warning">确定</a> <a href="#" onclick="abolish()" class="btn btn-info">取消</a></td></tr>');
});
function abolish(){
	$(".table-bordered tbody tr:last").remove();
}
function ensure(){
	var sort = $("#sort_num").val();
	var name = $("#con").val();
	var status = $("#status").val();
	if(!sort){
		alert("排序不能为空");
		return false;
	}else if(!name){
		alert("子版块名称不能为空");
		return false;
	}else if(!status){
		alert("子版块状态不能为空");
		return false;
	}else{
		var id = "<?php echo $cate_list['id'];?>";
		var url = "<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addTwoCategory'));?>";
		$.post(url,{sort:sort,name:name,status:status,parid:id},function(data){
  			alert(data.message);
  			if(data.code == 200){
  				window.location.reload();
  			}
  		},'json');
	}
}
$(function(){
    $(".table-bordered tbody tr .btn-info").click(function() {
        str = $(this).html() == "编辑" ? "确定":"编辑";  
        if($(this).html() == "确定"){
        	var sort = $(".o_sort").val();
        	var name = $(".o_name").val();
        	var status = $(".o_status").val();
        	if(!sort){
        		alert("排序不能为空");
        		return false;
        	}else if(!name){
        		alert("子版块名称不能为空");
        		return false;
        	}else if(!status){
        		alert("子版块状态不能为空");
        		return false;
        	}else{
        		var id = $(".o_sort").attr("alt");
        		var url = "<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addTwoCategory'));?>";
        		$.post(url,{sort:sort,name:name,status:status,id:id},function(data){
          			alert(data.message);
          			if(data.code == 200){
          				window.location.reload();
          			}
          		},'json');
        	}
        }
        $(this).html(str);  

        $(this).parent().siblings("td").each(function() {
            obj_text = $(this).find("input:text");
            if(!obj_text.length)
                $(this).html("<input type='text'  alt='"+obj_text.context.abbr+"' class='"+obj_text.context.id+"'   name='"+obj_text.context.id+"' value='"+$(this).text()+"'>");
            else   // 如果已经存在文本框，则将其显示为文本框修改的值
                $(this).html(obj_text.val()); 
        });
        if($(".o_status").val() == "正常"){
        	$(".o_status").val(1)
        }else{
        	$(".o_status").val(2)
        }
//         console.log();

    });

});
</script>
