<link rel="stylesheet" href="<?php echo $this->basePath();?>/adminStyle/css/iframe.css">
<style>
    .iphone-iframe .iphone-bg {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/device-sprite.png");
    }
    .iphone-bg-header {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/status-bar.png");
    }
</style>
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            <legend class="lg_title">
                <span>活动设置：</span>
            </legend>
            <form id="submitForm" class="form-horizontal" method="post" action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'packQrcode'));?>">
                <input type="hidden" name="id" value="<?php echo $info?$info['id']:0;?>"/>
                <div class="control-group">
                    <label class="col-md-2 control-label">奖励金额：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" name="price" id="price"  value="<?php echo $info?$info['price']:'';?>" disabled="true"/>  &nbsp;&nbsp;&nbsp;&nbsp;元
                        <br/><span>用户在领取后，钱包将充值入对应的金额</span></div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">会员天数：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" name="days" id="days"  value="<?php echo $info?$info['day']:'';?>" disabled="true"/>  &nbsp;&nbsp;&nbsp;&nbsp;天
                        <br/><span>用户在领取后，会员有效期将在原有基础上增加</span></div>
                    </div>
                </div>
                  <div class="control-group">
                    <label class="col-md-2 control-label">有效期：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" id="putaway_time3" name="time"  value="<?php echo $info?$info['effective_time']:'';?>" disabled="true" /></div>
                   </div>
                 </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">生成数量：</label>
                    <div class="col-md-8">
                        <div class="controls"><input required="required" type="text" name="number" id="number"  disabled="true" value="<?php echo $info?$info['num']:'';?>"/>  &nbsp;&nbsp;&nbsp;&nbsp;份</div>
                    </div>
                </div>
			     <div class="control-group">
                    <label class="col-md-2 control-label">备注说明：</label>
                    <div class="col-md-8">
                       <div  class="controls"><textarea name="content" id="status" style="resize:none;width:60%;height:55px;"onkeydown='countChar("status","counter");' 
                    onkeyup='countChar("status","counter");'  disabled="true"><?php echo $info?$info['remark']:'';?></textarea>
                    <span class="wordwrap tr" style="width: 40px;"><i id="counter"></i></span> <br/><br/><span>共：<?php echo $info?$info['num']:'';?> 份，已领取：<?php echo $info?$info['used_num']:'';?> 份，未领取：<?php echo $info?$info['num'] - $info['used_num']:'';?> 份</span></div>
                    </div>
                    <br>
                </div>
              
                <div class="control-group">
                    <label class="col-md-2 control-label"></label>
                    <div class="col-md-8">
                          <input type="hidden" value="03" name="ajax" />
                          <input type="submit" class="btn btn-large btn-primary" id="ap" value="打包下载二维码" "/>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
<?php if(isset($info) && $info){?>
countChar("status","counter");
<?php }?>

function countChar(textareaName,spanName)
{
    document.getElementById(spanName).innerHTML = document.getElementById(textareaName).value.length;
}

//function save(id){//Pack and download the qr code
//	var url = '<?php //echo $this->url('admin', array('controller' => 'System', 'action' => 'packQrcode'));?>//';
//	$.post(url,{id:id},function(data){
//
//		},'json');
//
//}
</script>
