<script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script>
<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 8px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        <form method="get" action="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'userHelp'.($type==2?2:''),'types'=>$type)) ;?>">
			<div class="pull-left ml8" style="margin-left:30px;">
				<a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'helpDetails','types'=>$type));?>" class="btn btn-primary"><?php echo $type == 1 ? "+新增用户帮助" : "+新增功能介绍"?></a>
			</div>
			<div class="pull-right">
				<div class="pull-left ml8">
					<span style="margin-left:20px;">修改日期：</span>
					<input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $start ? $start : '';?>">&nbsp;至&nbsp;
					<input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $end ? $end : '';?>">
				</div>

				<div class="pull-left ml8" style="position: relative">
					<input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入标题" value="<?php echo $keyword ? $keyword:'';?>">
					<i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
				</div>
				<div class="pull-left ml8" >
					<button type="submit" class="btn btn-info submit">搜索</button>
				</div>
			</div>
        </form>
        <div class="clearfix"> </div>
    </div>
</div>
<br/>
<div class="bs-example4" data-example-id="simple-responsive-table">
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
				<tr>
					<th>排序序号</th>
					<th>帮助标题</th>
					<th>修改时间</th>
					<th>发送人</th>
					<th>操作</th>
				</tr>
            </thead>
			<tbody>
            <?php foreach($list as $k=>$v){?>
				<tr>
					<th><?php echo $v['sort'] ;?></th>
					<td style="text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $v['title'];?></td>
					<td><?php echo $v['timestamp_update'];?></td>
					<td><?php echo $v['admin_name'].'/'.$v['a_name'];?></td>
					<td>
						<input type="button" value="删除" class="btn btn-warning" onclick="systemDelete(<?php echo $v['id'];?>)"/>
						<a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'helpDetails', 'id' => $v['id'],'types'=>$type));?>" class="btn btn-info">查看</a>
					</td>
				</tr>
            <?php }?>
            </tbody>
        </table>
    </div>
</div>
<div class="page-control">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
</div>

</div>

<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDeleteHelp'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
			<input type="hidden" name="id" value="" id ="social_id">
			<input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function systemDelete(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>

