<script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script>
<script src="<?php echo $this->basePath() ?>/adminStyle/template/upload/ajaxfileupload.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.config.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.all.min.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath();?>/adminStyle/css/iframe.css">
<script type="text/javascript">
    var uploader = '<?php echo $this->url('admin',array('controller' => 'common', 'action'=>'uploadImage'));?>';//图片上传地址
</script>
<style>
    .iphone-iframe .iphone-bg {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/device-sprite.png");
    }
    .iphone-bg-header {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/status-bar.png");
    }
</style>
<br>
<div class="row-fluid">
	<div class="box span12">
		<div class="box-content">
			<legend class="lg_title">
			    <?php if($type == 1){?>
				    <span><?php echo $help ? '用户帮助详情' : '新增用户帮助';?>：</span>
				<?php }else{?>
				    <span><?php echo $help ? '功能介绍详情' : '新增功能详情';?>：</span>
				<?php }?>
			</legend>
			<form class="form-horizontal" method="post" action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'helpDetails','types' => $type));?>" id="submitForm" enctype="multipart/form-data">
				<div class="control-group">
					<label class="col-md-2 control-label">帮助标题：</label>
					<div class="col-md-8">
						<div><input type="text" value="<?php echo $help ? $help['title'] : '';?>" name="title" required="required" id="title" placeholder="请输入帮助标题" /></div>
					</div>
				</div>
				
				<div class="control-group">
					<label class="col-md-2 control-label">排序序号：</label>
					<div class="col-md-8">
						<div><input type="number" value="<?php echo $help ? $help['sort'] : '1';?>" min="1" name="sort" required="required" id="sort" placeholder="请输入排序序号" /></div>
					</div>
				</div>
				
				<div class="control-group">
					<label class="col-md-2 control-label">帮助内容：</label>
					<div class="col-md-8">
					   <!--  <div><textarea id="cc" name="content" placeholder="请输入帮助内容"><?php echo $help ? $help['content'] : '';?></textarea></div> -->
					   <div><textarea name="content" id="editor" placeholder="请输入帮助内容" style="margin-left:140px;"><?php echo $help ? $help['content'] : '';?></textarea></div>
					</div>
				</div>
				<?php if($help){?>
				<br/>
				<div class="control-group">
					<label class="col-md-2 control-label">修改时间：</label>
					<div class="col-md-8">
						<div><?php echo $help['timestamp_update'];?></div>
					</div>
				</div>
				
				<div class="control-group">
					<label class="col-md-2 control-label">发布人：</label>
					<div class="col-md-8">
						<div><?php echo $help['sender'];?></div>
					</div>
				</div>
                <?php }?>
				<div class="control-group">
					<label class="col-md-2 control-label"></label>
					<div class="col-md-8">
					    <input name="id"  type="hidden" value="<?php echo $help ? $help['id'] : 0; ?>" />
					    <input class="btn btn-large btn-primary" type="button" id="submit-button" value="保存" />
					    <?php if(!$help){?>
					    <button type="button" class="btn btn-large btn-primary" id="ap1" onclick="preview()">预览</button>
					    <?php }?>
						<input class="btn btn-large btn-primary resetHref" onclick="history.go(-1)" type="reset" value="取消" />
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="iphone-iframe" style="display: none;">
    <div class="zzc"></div>
    <div class="iphone-bg">
        <div class="iphone-bg-header"></div>
        <p class="iphone-btn">关闭预览</p>
        <iframe id="previewIframe" name="previewIframe" frameborder="0" scrolling="auto" src=""></iframe>
    </div>
</div>
<script type="text/javascript">
var ue = UE.getEditor('editor', {
	"initialFrameWidth" : "90%",
	"initialFrameHeight" : 400,
	"maximumWords" : 8000,
});

</script>
<script>
// KindEditor.ready(function(K) {
//         window.editor = K.create('#cc');
//     });

//$("#forUpload").click(function(){
        //$(".file").click();
    //});

$("#submit-button").click(function(){
    var sort = $("#sort").val();
    var title = $("#title").val();
    var t= "^[.\0-9]+$";
    var content = UE.getEditor('editor').getContent();
    if(!title){
    	alert("请输入帮助标题!");
    	return false;
    }
    if(sort.search(t)==-1){
    	alert('排序序号请输入数字'); // message.js
    	return false;
    }

    if(!content){
    	alert("请输入帮助内容!");
    	return false;
    }
	var url = '';
	var form = $("#submitForm");
	form.attr("action", url);
	form.removeAttr("target");
	form.submit();
    
//     $("#submitForm").submit();
 });

// $(".resetHref").click(function(){
 //   location.href = '<?php //echo $this->url('admin',array('controller'=>'System','action'=>'userHelp'));?>';
// });
    function preview() {
    	var url = '<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'articleDetails'));?>';
    	//$("#editor").val(UE.getEditor('editor').getContent());
    	var form = $("#submitForm");
    	form.attr("action", url);
    	form.attr("target", "previewIframe");
    	form.submit();
    }
   
</script>
<script>
    $('.iphone-iframe').css({
        'width':$(window).width()+'px',
        'height':$(window).height()+'px'
    });
    $('.iphone-bg').css({
        'top':($(window).height()-$('.iphone-bg').height())/2+'px',
        'left':($(window).width()-$('.iphone-bg').width())/2+'px'
    });
    $('#ap1').click(function(){
        $('.iphone-iframe').toggle();
    });
    $('.iphone-btn').click(function() {
        $('.iphone-iframe').toggle();
    });
</script>
