<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="pannel">
        <div class="row">
            <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'marketing'));?>">
                <div class="pull-left ml8" style="margin-left:30px;">
                    <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'addMarketing'));?>" class="btn btn-primary">+新增活动</a>
                </div>
                <div class="pull-right">
            	</div>
            </form>
        </div>
    </div>
</div>
<div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>生成时间</th>
                    <th>奖励金额</th>
                    <th>会员天数</th>
                    <th>数量</th>
                    <th>剩余数量</th>
                    <th>有效期</th>
                    <th>操作</th>
                </tr>
                </thead>
             <tbody>
                <?php foreach($list as $k=>$v){?>
                <tr>
                     <td><?php echo $v['timestamp'];?></td>
                     <td><?php echo $v['price'];?></td>
                     <td><?php echo $v['day'];?></td>
                     <td><?php echo $v['num'];?></td>
                     <td><?php echo $v['num']-$v['used_num'];?></td>
                     <td><?php echo $v['effective_time'];?></td>
                    <td>
    					<a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'getMarketing', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
                    </td>
                </tr>
                <?php }?>
                </tbody>
            </table>
            <div class="page-control">
            <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
           </div>
        </div>
     </div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'ajaxDeleteCategory'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>