<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        
        <form class="form-horizontal" method="post" action="">
          <div class="pull-left ml8" style="margin-left:30px;">
                <a href="<?php echo $this->url('admin', array('controller' =>'System', 'action' => 'roleDetail'));?>" class="btn btn-primary">+新增角色</a>
           </div>
        <div class="pull-right">
   
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>角色名称</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th><?php echo$v['id'];?></th>
                 <td><?php echo $v['name'];?></td>
                <td>
                <?php if($v['manage'] !='all'){?>
                      <a onclick="deleteWallet(<?php echo $v['id'];?>)" class="btn btn-warning">删除</a>
               <?php }?>
                     <a href="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'roleDetail', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
                </td>
            </tr>
            <?php }?>

            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'roleDelete'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>