<style type="text/css">
	.form-horizontal .control-label {
		text-align: left;
	}
	.control-group-border {
		border-bottom: 1px solid #ccc;
	}
	.control-label>img {
		margin: 0 10px;
		width: 18px;
		height: 18px;
		border: none;
		vertical-align: bottom;
	}
</style>
<br>
<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-content">
			<form class="form-horizontal" method="post" action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addRole'));?>">
				<fieldset>
<!-- 					<legend>平台管理-角色管理-新增角色</legend> -->
					<div class="control-group">
						<label class="control-label" style="font-weight:bold;font-size:16px;">角色信息</label>
					</div>
					<div class="control-group">
						<label class="control-label">角色名称：</label>
						<div class="controls">
							<span class="message"></span>
							<input name="name" class="input-xlarge name" type="text" value="<?php echo $info ? $info['name'] : '';?>" onchange="checkAdmin('name', this);" placeholder="请输入角色名称" >
							<span style="color: red;" class="message"></span>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label" style="font-weight:bold;font-size:16px;">权限信息：</label>
					</div>
					<div class="control-group">
						<label class="control-label">请选择角色权限</label>
					</div>
						<?php foreach ($roleList as $k=>$v) {?>
						<div class="control-group control-group-border">
							<label class="control-label"><i class="icon-home"></i><?php echo $k?>：</label>
							<div class="controls">
							     <input class="input-xlarge input-xlarge-all" type="checkbox" value=""<?php  if($authority == 'all'){echo 'checked="checked"';}?> /><span style="margin-right: 40px;vertical-align: sub;">全选</span>
<!-- 							     <div> -->
        							     <?php foreach ($v as $key => $val) {?>
        							    <input name="manage[<?php echo $key?>]"   class="input-xlarge input-xlarge-branch" type="checkbox" value="<?php echo $val?>" <?php  if($authority == 'all' || isset($authority[$key])){echo 'checked="checked"';}?> /><span style="margin-right: 40px;vertical-align: sub;"><?php echo $key?></span>
        							    <?php }?>
<!-- 							    </div> -->
							</div>
						</div>
						<?php }?>
    					<div class="form-actions">					   
    						<input type="hidden" name="id" id="rank_id" value="<?php echo $info ? $info['id'] : '';?>" >      	
    						<input type="button" class="btn btn-success sub" value="保存"/>
    						<input type="button" class="btn btn-success resetHref" value="取消" />
    						
    					</div>
					<?php //}?>
				</fieldset>
			</form>
		</div>
	</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'roleDelete'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
			<input type="hidden" name="id" value="" id ="social_id">
			<input type="hidden" name="type" value="1">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
			<input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
</script>
<script>
$(".resetHref").click(function(){
    location.href = '<?php echo $this->url('admin',array('controller'=>'System','action'=>'role'));?>';
});

$('.sub').click(function (){
     if($('.message').html() != ''){
    	   alert($('.message').html());
    	   return false;
     }
     if(!$('.name').val()){
    	 alert('角色名称不能空');
    	 return false;
     }
     if($("input:checked").length<1){
    	    alert('请选择权限！');
    	    return false;
     }
	$('.form-horizontal').submit();
});
function checkAdmin(type, dom) {
	if (! dom) {
		return 0;
	}
	var url = '<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'checkRole', 'id' => $info ? $info['id'] : 0));?>';
   if(dom.value){
    	$.post(url, {type:type, name:dom.value},function (result) {
    		if (result.code != 200) {
    			if (type == 'name') {
    				$(dom).next().html(result.message);
    			}
    		}
    		else {
    			$(dom).next().html('');
    		}
    	}, "json");
   }
}
</script>

<script>
	$(function(){
		$(".input-xlarge-all").bind("click", function () {
			var bing = $(this);
			var kk = bing.parents('.checker').siblings('.checker').find('input');
			if (bing.is(":checked")){
				for(var i=0;i<kk.length;i++){
					var item = $(kk[i]);
					item.attr("checked","checked");
					item.parent().addClass("checked");
				};
			}else{
				for(var i=0;i<kk.length;i++){
					var item = $(kk[i]);
					item.removeAttr("checked");
					item.parent().removeClass("checked");
				}
			};
		});
		$(".input-xlarge-branch").bind("click",function(){
			var bing = $(this);
			var kk = bing.parents('.checker').siblings('.checker').find('.input-xlarge-all');
			if(bing.is(":checked")==false){
				bing.removeAttr("checked");
				kk.removeAttr("checked");
				kk.parent().removeClass("checked");
			}else if(bing.is(":checked")==true){
				bing.attr("checked","checked");
				var jj = 0;
				var gg = bing.parents('.checker').siblings('.checker').find('.input-xlarge-branch');
				for(var i=0;i<gg.length;i++){
					var item = $(gg[i]);
					if(item.is(":checked")==false){
						jj = 1;
					};
				};
				if(jj == 0){
					kk.attr("checked","checked");
					kk.parent().addClass("checked");
				};
			};
		});
	});
</script>

