<script src="<?php echo $this->basePath() ?>/js/thescript.js"></script>
<script src="<?php echo $this->basePath() ?>/js/ajaxfileupload.js"></script>
<script src="<?php echo $this->basePath() ?>/js/date/jedate.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/mobileBUGFix.mini.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/uploadImage.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/exif.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.config.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/ueditor.all.min.js"></script>
<script src="<?php echo $this->basePath();?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<link href="<?php echo $this->basePath() . '/js/date/skin/jedate.css'?>" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="<?php echo $this->basePath();?>/adminStyle/css/iframe.css">
<style>
    .iphone-iframe .iphone-bg {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/device-sprite.png");
    }
    .iphone-bg-header {
        background-image: url("<?php echo $this->basePath();?>/adminStyle/images/status-bar.png");
    }
</style>
<!-- <ul class="breadcrumb"> -->
<!--     <li><span>系统通知</span></li> -->
<!--     <li><span>/</span></li>
    <li><?php //echo $info?'编辑':'新增';?></li>
<!-- </ul> -->
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            <legend class="lg_title">
                <span><?php echo $info?'编辑':'新增';?>通知信息：</span>
            </legend>
            <form id="submitForm" class="form-horizontal" method="post" action="">
                <div class="control-group">
                    <label class="col-md-2 control-label">通知标题：</label>
                    <div class="col-md-8">
                        <input type="text" value="<?php echo $info ? $info['title'] : '';?>" name="title" id="title2"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">通知对象：</label>
                    <div class="col-md-8">
                        <div>
                        	<select name="position"  id="position">
                        	   <option value="0" >全部</option>
                              <?php foreach ($position as $k=>$v){?>
            				   <option value="<?php echo $k;?>" <?php echo $info && $info['position'] == $k?'selected="selected"':''?>><?php echo $v['name'];?></option>
    				          <?php }?>
            				</select>
                      </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="col-md-2 control-label">发送时间：</label>
                    <div class="col-md-8">
                        <div><input required="required" type="text" name="send_time" id="start_time" value="<?php echo $info ? $info['send_time'] : date('Y-m-d H:i:00');?>" /></div>
                    </div>
                </div>
            	<div>
				    <label class="control-label">通知封面：</label>
					<div class="controls portraits">
						<div style="border: 2px solid #ccc; width: 200px">
							<img id="show_image_1" width="250" height="125 border="1" src="<?php echo isset($info['image']) ? $this->basePath().'/'.UPLOAD_PATH.$info['image'] : $this->basePath().'/adminStyle/img/home-made.png';?>" alt="">
							<!-- 图片路径是否正确? -->
						</div>
						<br><span>(注：像素654*280或宽高比与此相同)</span>
						<div style="display: none;">
							<input type="hidden" id="img_id_1" name="img_id" value="" />
							<input id="imgPath" type="hidden" name="image" value="<?php echo isset($info['image']) ? $info['image'] : '' ?>"/>
							<input type="file" accept="" id="uploadImage"
								capture="camera" onchange="selectFileImage(this);" hidden />
						</div>
					</div>
			     </div>
			     
<!--               <div id="Material_1" class="classMaterial hide"> -->
               <div class="control-group">
		            <label class="control-label">通知概要：</label>
					<div class=" portraits" style="margin-left:140px">
					    <div><textarea  name="outline" id="outline" rows="5" style="width: 90%;" placeholder=""><?php echo $info ? $info['outline'] : "";?></textarea></div>
					    <br><span>请输入系统通知的消息概要，建议50字内</span>
					</div>
			     </div>
<!--             </div> -->
            
                <div class="control-group">
                    <label class="col-md-2 control-label">跳转类型：</label>
                    <div class="col-md-8">
                        <div>
                        	<select name="type"  id="ads_type" onchange="showMaterialBox(this,0,0)">
                        	<?php foreach ($jump as $k=>$v){?>
            				   <option value="<?php echo $k;?>" <?php echo $info && $info['type'] == $k?'selected="selected"':''?>><?php echo $v;?></option>
            				  <?php }?>
            				</select>
                      </div>
                    </div>
                </div>

            <div id="Material_1" class="classMaterial  <?php echo $info && $info['type']==1?'':'hide'?>">
               <div class="control-group">
		            <label class="control-label">通知详情：</label>
					<div class=" portraits" style="margin-left:140px">
					    <div><textarea id="cc1" name="content" rows="20" style="width: 90%;" placeholder=""><?php echo $info ? $info['content'] : "";?></textarea></div>
					</div>
			     </div>
            </div>
            <div id="Material_2" class="classMaterial <?php echo $info && in_array($info['type'], array('2','3','4','5'))?'':'hide'?>">
                <div class="control-group">
                    <label class="col-md-2 control-label titles">选择物料：</label>
                    <div class="col-md-8">
<!--                     onchange="showMaterial(this.value)" -->
                        <div><select required="required" name="audio_id" class="contents"><option value="0"></option>
                        </select></div>
                    </div>
                </div>
            </div>
            <div id="Material_6" class="classMaterial <?php echo $info && $info['type']==6 ?'':'hide'?>">
                <div class="control-group">
                    <label class="col-md-2 control-label">链接地址：</label>
                    <div class="col-md-8">
                        <div><input type="text" name="link" id="link" value="<?php echo $info?$info['link']:''?>" /></div>
                    </div>
                </div>
            </div>
                <div class="control-group">
                    <label class="col-md-2 control-label"></label>
                    <div class="col-md-8">
                        <input type="hidden" value="<?php echo $info ? $info['id'] : 0;?>" name="id" />
                          <input type="hidden" value="2017" name="ajax" />
<!--                           onclick="save()" -->
                          <input type="button" class="btn btn-large btn-primary" id="submit-button" value="保存" />
                           <?php if(!$info){?>
					    <button type="button" class="btn btn-large btn-primary" id="ap1" onclick="preview()">预览</button>
					    <?php }?>
                        <input class="btn btn-large btn-primary resetHref" type="reset" value="取消"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="iphone-iframe" style="display: none;">
    <div class="zzc"></div>
    <div class="iphone-bg">
        <div class="iphone-bg-header"></div>
        <p class="iphone-btn">关闭预览</p>
        <iframe id="previewIframe" name="previewIframe" frameborder="0" scrolling="auto" src=""></iframe>
    </div>
</div>
<script>
//提交表单
$("#submit-button").click(function(){
    var title = $("#title2").val();
    var start_time = $("#start_time").val();
    var position = $("#position").val();
//     var img_id_1 = $("#imgPath").val();
    var ads_type = $("#ads_type").val();
    var outline = $('#outline').val();
	var cc1 =  UE.getEditor('cc1').hasContents();
// 	console.log(cc1);return;
	var audio_id = $('.contents').val();
	var link = $('#link').val();
    if(!title){
    	alert('通知标题不能为空！');
    	return false;
    }else if(!start_time){
    	alert('发送时间不能为空！');
    	return false;
    }else if(!position){
    	alert('通知对象不能为空！');
    	return false;
    }/*else if(!img_id_1){
    	alert('通知封面不能为空！');
    	return false;
    } */else if(!outline){
    	alert('通知概要不能为空！');
    	return false;
    }else if(ads_type ==1){
   	    if(!cc1){
	    	alert('通知详情不能为空！');
	    	return false;
	    }
    }else if(ads_type ==2){
    	if(!audio_id){
        	alert('选择音频不能为空！');
        	return false;
        }
    }else if(ads_type ==3){
    	if(!audio_id){
        	alert('选择视频不能为空！');
        	return false;
        }
    }else if(ads_type ==4){
    	if(!audio_id){
        	alert('选择音频包不能为空！');
        	return false;
        }
    }else if(ads_type ==5){
    	if(!audio_id){
        	alert('选择视频包不能为空！');
        	return false;
        }
    }else if(ads_type ==6){
    	if(!link){
        	alert('链接地址不能为空！');
        	return false;
        }
    }
	var url = '';
	var form = $("#submitForm");
	form.attr("action", url);
	form.removeAttr("target");//消除target(打开方式)
	form.submit();
//     $('#submitForm').from();
 });
function save(){
	var url = '';
	var form = $("#submitForm");
	form.attr("action", url);
	form.removeAttr("target");//消除target(打开方式)
	form.submit();
}

function preview() {
	var url = '<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'articleDetails'));?>';
	//$("#editor").val(UE.getEditor('editor').getContent());
	var form = $("#submitForm");
	form.attr("action", url);
	form.attr("target", "previewIframe");
	form.submit();
}
$('.iphone-iframe').css({
    'width':$(window).width()+'px',
    'height':$(window).height()+'px'
});
$('.iphone-bg').css({
    'top':($(window).height()-$('.iphone-bg').height())/2+'px',
    'left':($(window).width()-$('.iphone-bg').width())/2+'px'
});
$('#ap1').click(function(){
    $('.iphone-iframe').toggle();
});
$('.iphone-btn').click(function() {
    $('.iphone-iframe').toggle();
});
</script>
<script>
//上传封面
var upload_url = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'uploadImage'));?>'; // uploadImage.js
$("#show_image_1").click(function(){
  $("#uploadImage").click();
});
//编辑框
    var ue1 = UE.getEditor('cc1', {
    	"initialFrameWidth" : "100%",
    	"initialFrameHeight" : 200,
    	"maximumWords" : 8000,
    });
<?php if ($info) {?>
showMaterialBox(null,<?php echo ($info['type']?$info['type']:1).','.($info['audio_id']?$info['audio_id']:0);?>);
<?php }else{?>
showMaterialBox(null,1,0);
<?php }?>
function showMaterialBox(btn,type,id){
	if(!type){
      type = $(btn).val();
	}
      if(type>=2 && type<=5){
          var url = '<?php echo $this->url('admin',array('controller'=>'Ads','action'=>'ajaxFindList'));?>';
          $('.contents').html('');
           $.post(url,{type:type,ajax:27,id:id},function(data){
        	    if(data.status != 0){
                     alert(data.msg);return;
        	    }else{
        	    	 $('.contents').append(data.content);
        	    }
        	  },'json');
          if(type == 2){
              $('.titles').text('选择音频：');
          }else if(type == 3){
        	  $('.titles').text('选择视频：');
          }else if(type == 4){
        	  $('.titles').text('选择音频包：');
          }else if(type == 5){
        	  $('.titles').text('选择视频包：');
          }
          type = 2;
      }
      $(".classMaterial").hide();
 	 $("#Material_"+ type ).show();
}
</script>
<script>
//var loading_img = '<?php echo $this->basepath() . '/adminStyle/img/loading.gif'?>';
// $("#forUpload").click(function(){
//     $(".file").click();
// });
</script>
<script>
     var start = {
        dateCell: '#start_time',
        format:"YYYY-MM-DD hh:mm",
        minDate: '2013-01-01 00:00',
        festival:true,
        //maxDate: jeDate.now(0),
        isTime: true,
        choosefun: function(datas){
            end.minDate = datas;
        }
    };
    var end = {
        dateCell: '#end_time',
        minDate: '2013-01-01 00:00',
        festival:true,
        format:"YYYY-MM-DD hh:mm",
        isTime: true,
        choosefun: function(datas){
            start.maxDate = datas;
        }
    };
    jeDate(start);
    jeDate(end);

</script>