<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        
        <form class="form-horizontal" method="post" action="">
          <div class="pull-left ml8" style="margin-left:30px;">
                <a href="#" id="addUserJob" class="btn btn-primary">+新增职位</a>
           </div>
        <div class="pull-right">
   
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>职位名称</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th id="<?php echo $v['id'];?>"><?php echo$v['id'];?></th>
                <td id="<?php echo $v['id'];?>"><?php echo $v['name'];?></td>
                <td>
                     <a onclick="deleteWallet(<?php echo $v['id'];?>)" class="btn btn-warning">删除</a>
                     <a href="#"  class="btn btn-info" >编辑</a>
                </td>
            </tr>
            <?php }?>

            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'userJobDelete'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script type="text/javascript">
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
$("#addUserJob").click(function() {
    $(".table-bordered tbody").append('<tr><td></td><td><input type="text" name="content" id="content"/></td><td><a onclick="ensure()" class="btn btn-warning">确定</a> <a href="#" onclick="abolish()" class="btn btn-info">取消</a></td></tr>');
});
function abolish(){
	$(".table-bordered tbody tr:last").remove();
}
function ensure(){
	var content = $("#content").val();
	if(!content){
		alert("职位名称不能为空");
		return false;
	}else{
		var url = "<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addUserJob'));?>";
		$.post(url,{content:content},function(data){
  			alert(data.message);
  			if(data.code == 200){
  				window.location.reload();
  			}
  		},'json');
	}
}
$(function(){
    $(".table-bordered tbody tr .btn-info").click(function() {
        str = $(this).html() == "编辑" ? "确定":"编辑";  
        if($(this).html() == "确定"){
        	var content = $("#content").val();
        	var id = $("#content").prop("name");
        	if(!id){
        		alert("修改失败");
 		    }
        	if(!content){
        		alert("职位名称不能为空");
        	}else{
        		var url = "<?php echo $this->url('admin', array('controller' => 'System', 'action' => 'addUserJob'));?>";
        		$.post(url,{content:content,id:id},function(data){
//           			alert(data.message);
          			if(data.code == 200){
//           				window.location.reload();
          			}
          		},'json');
        	}
        }
        $(this).html(str);  

        $(this).parent().siblings("td").each(function() {
            obj_text = $(this).find("input:text");
            if(!obj_text.length)
                $(this).html("<input type='text' id='content'  name='"+obj_text.context.id+"' value='"+$(this).text()+"'>");

            else   // 如果已经存在文本框，则将其显示为文本框修改的值

                $(this).html(obj_text.val()); 

        });

    });

}); 
</script>