<style>
.submit {
	float: right;
	margin-left: 8px;
}

.ml8 {
	margin-left: 48px;
}

.row input, .row select {
	margin-bottom: 0px;
}
</style>
<br>
<div class="pannel-body">
	<div class="pannel">
		<div class="row">
			<form class="form-horizontal" method="get"
				action="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'coursesList','page'=>1));?>">
				<div class="pull-left ml8" style="margin-left: 30px;">
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'addCoures'));?>"
						class="btn btn-primary">+新增课程包</a>
					<a href="javascript:;"class="btn btn-primary" onclick = "ajaxDeleteData(1)">批量删除</a>
					<a href="javascript:;"class="btn btn-primary" onclick = "ajaxDeleteData(2)">批量下架</a>
				</div>
				<div class="pull-right">
					<div class="pull-left ml8" style="position: relative">
						<input style="width: 160px; padding-left: 25px" name="keyword"
							type="text" class="input-small" placeholder="请输入课程包名称"
							value="<?php echo isset($keyword) ? $keyword:'';?>"> <i
							class="iconfont" style="position: absolute; top: 5px; left: 5px;">&#xe604;</i>
						<span style="margin-left: 20px;">课程包类型：</span> <select
							class="select-top" name="cid" size="1" id="select">
							<option value="0" <?php echo $cid==0?'selected="selected"':''?>>全部</option>
							<option value="3" <?php echo $cid==3?'selected="selected"':''?>>音频</option>
							<option value="4" <?php echo $cid==4?'selected="selected"':''?>>视频</option>
						</select>
						<span style="margin-left: 20px;">售卖类型：</span> <select
							class="select-top" name="num" size="1" id="select">
							<option value="0" <?php echo $num==0?'selected="selected"':''?>>全部</option>
							<option value="1" <?php echo $num==1?'selected="selected"':''?>>普通课程包</option>
							<option value="2" <?php echo $num==2?'selected="selected"':''?>>会员专享包</option>
						</select>
						 <span style="margin-left: 20px;">分类：</span> <select
							class="select-top" name="pid" size="1" id="select">
							<option value="0" <?php echo $pid==0?'selected="selected"':''?>>全部</option>
                        <?php foreach ($data as $v){?>
                            <option value="<?php echo $v['id']?>"
								<?php echo $pid==$v['id']?'selected="selected"':''?>><?php echo $v['name']?></option>
                        <?php }?>
    				</select> <span style="margin-left: 20px;">课程包状态：</span> <select
							class="select-top" name="types" size="1" id="select">
							<option value="0" <?php echo $types==0?'selected="selected"':''?>>全部</option>
							<option value="1" <?php echo $types==1?'selected="selected"':''?>>正常</option>
							<option value="2" <?php echo $types==2?'selected="selected"':''?>>已下架</option>
						</select>
						
						<button type="submit" class="btn btn-info submit">搜索</button>
					</div>
				</div>
			</form>
			<form class="form-horizontal" method="post" action="">
				<div class="pull-right"></div>
			</form>
		</div>
	</div>
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
			 <input type="hidden" value="" name="ids" id="ids"/>
			<table class="table table-bordered">
				<thead>
					<tr>
					    <th class="tal"><label><input type="checkbox" class="ace"><span class="lbl"></span></label></th> 
					    <th>序号</th>
						<th>封面</th>
						<th>标题</th>
						<th>课程包类型</th>
						<th>分类</th>
						<th>售卖类型</th>						
						<th>课程数</th>
						<th>普通课程包价格</th>
						<th>会员专享包价格</th>
						<th>是否推荐(排序)</th>
						<th>课程包状态</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
                <?php foreach($list as $k=>$v){?>
                <tr>
                    <td><input type="checkbox" class="ace" id="<?php echo $v['id']?>"></label></td> 
                    <td><?php echo $v['cour_sort'];?></td>
					<td><img width="40" height="40"
						src="<?php echo  $this->basePath().(isset($v['img_path']) && $v['img_path'] ? '/'.UPLOAD_PATH.$v['img_path'].$v['filename'] :'/images/portrait.png');?>"
						alt=""></td>
					<td><?php echo $v['title'];?></td>
					<td><?php echo $v['type']?$type[$v['type']]:'';?></td>
					<td><?php echo $v['category_name'];?></td>
					<td><?php echo $v['sell_type'] == 1 ? "普通课程包" : "会员专享包";?></td>
					<td><?php echo $v['audios_num'];?></td>
					<td><?php echo $v['price'] ? $v['price'] : "--";?></td>
					<td><?php echo $v['original_price'];?></td>
					<td><?php echo$v['recommend'] == 1 ? '是（'.$v['sort'].'）' : '否（-）';?></td>
					<td><?php echo$v['status'] == 1 ? "正常" : "已下架";?></td>
					<td><a
						href="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'addCoures', 'id' => $v['id']));?>"
						class="btn btn-info">查看</a> <a href="javascript:;"
						class="btn btn-infos">更多</a>
						<div class = "more" style="display: none">
							<ul>
								<a href="<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'index')).'?type='.$v['type'].'&id='. $v['id'];?>" target="_blank" ><div>查看评论</div></a>
								<?php if($v['status'] == 1){?>
								    <a onclick="soldOut(<?php echo $v['id']?>,1)"><div>下架</div></<a>
								<?php }else{?>
								    <a onclick="soldOut(<?php echo $v['id']?>,2)"><div>上架</div></<a>
								 <?php }?>
								<a onclick="deleteWallet(<?php echo $v['id']?>)"><div>删除</div></a>
							</ul>
						</div>
					</td>
				</tr>
                <?php }?>

            </tbody>
				</table>
				<div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
			</div>
			<!--/span-->
		</div>
	</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteCourses'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script>

$('table th input:checkbox').on('click' , function(){
	var ids = '';
    if(this.checked == true){
    	$('.table-bordered tbody input[type=checkbox]').attr('checked','checked');
    	$('.table-bordered tbody input[type=checkbox]').each(function(){
        	ids += $(this).attr('id')+",";
    	})
    }else{
    	$('.table-bordered tbody input[type=checkbox]').removeAttr('checked','checked');
    }
    $("#ids").val(ids);
    $.uniform.update();
});
$('table tbody input:checkbox').on('click' , function(){
	var ids = '';
	$('.table-bordered tbody input[type=checkbox]:checked').each(function(){
    	ids += $(this).attr('id')+",";
	})   
	$("#ids").val(ids)
});
function ajaxDeleteData(type){
	//1 删除  2 下架
	var ids = $("#ids").val();
    if(!ids){
    	alert("请选择课程");
    	return false;
    }
    if(type == 1){
        var str = confirm("确定要批量删除课程包吗？");
     }else{
  	   var str = confirm("确定要批量下架课程包吗？");
     }
	if(str){
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteData','types'=>1));?>";
		 $.post(url,{ids:ids,type:type,audio_type:3},function(result){
				if(result.code == 200){
					alert(result.msg);
					history.go(0);
					return false;
				}else{
					alert(result.msg);
					return false;
				}
		 },'json');
	}
}

								
function soldOut(id,status){
	 if(status == 1){
		 $("#titles").text("你确定要下架吗？");
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteCourses','types'=>1));?>";
	 }else{
		 $("#titles").text("你确定要上架吗？");
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteCourses','types'=>2));?>";
	 }
//	 var url = "<?php //echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteCourses','types'=>1));?>";
	 $('#abolish-family')[0].action = url;
	 $('#social_id').val(id);
// 	 $("#titles").text("你确定要下架吗？")
	 $('#myModal').modal('show');
}
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
$(".table-bordered tbody tr .btn-infos").click(function() {
	if($(this).next().is(':hidden'))
	{
		$(this).next().slideDown('slow');  
       }else{
	    $(this).next().slideUp('slow'); 
    }
});
</script>