<style>
	@media screen and (max-width: 1160px) { 
		.shangjia{
			display: block;
		} 
		.shangjia .ml30{
			margin-left: 0;
		}
	} 
	.homePage_set{
		margin-bottom: 20px;
	}
	.homePage_set select,.homePage_set input{
		margin-bottom: 4px;
	}
	.homePage_set select{
		width: 18%;
	}
	.mr10{
		margin-right: 10px;
	}
	.ml10{
		margin-left: 10px;
	}
	.ml15{
		margin-left: 15px;
	}
	.ml30{
		margin-left: 30px;
	}
	.col_gray{
		color: gray;
	}
	button{
		width: 120px;
		height: 30px;
		border: 1px solid #0099CC;
		border-radius: 2px;
		background-color: #fff;
		margin-right: 10px;
		margin-top: 30px;
	}
	.save{
		background: #0099cc;
		color: #fff;
	}
	div.checker{
		top: 0;
	}
</style>
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            <legend class="lg_title">
                <span>首页设置</span>
            </legend>
            <form action="" method="post">
            	<div class="homePage_set">
					<input type="hidden" name="infos[1][id]" value="<?php echo isset($one_data[0]['id']) ? $one_data[0]['id'] : 0?>"/>
					<input type="hidden" name="infos[1][type]" value="1"/>
            		<span class="mr10">选择音频:</span>
            		<select name="infos[1][audio_id]" id="">
						<?php foreach($data  as $v){?>
							<option <?php if(isset($one_data[0]['audio_id']) && $v['id'] == $one_data[0]['audio_id']){?>selected = "selected"<?php }?> value ="<?php echo $v['id'] ?>"><?php echo $v['title']?></option>
						<?php }?>
            		</select>

            		<span class="ml15">
            			<input name="infos[1][teacher_name_hide]" type="checkbox" <?php if(isset($one_data[0]['hide']) && $one_data[0]['hide'] == 1){?>checked="checked"<?php }?>" value="1"/>
            			<span  class="ml10" >隐藏导师名称</span>
            		</span> 

            		<span class="mr10 ml30">将更新的音频:</span>
					<input type="hidden" name="infos[2][id]" value="<?php echo isset($two_data[0]['id']) ? $two_data[0]['id'] : 0 ?>"/>
					<input type="hidden" name="infos[2][type]" value="2"/>
            		<select name="infos[2][audio_id]" id="">
						<?php foreach($data  as $v){?>
							<option <?php if(isset($two_data[0]['audio_id']) && $v['id'] == $two_data[0]['audio_id']){?>selected = "selected"<?php }?>  value ="<?php echo $v['id'] ?>"><?php echo $v['title']?></option>
						<?php }?>
            		</select>

            		<span class="ml15">
						<input name="infos[2][teacher_name_hide]" type="checkbox" <?php if(isset($two_data[0]['hide']) && $two_data[0]['hide'] == 1){?>checked="checked"<?php }?> value="1" />
            			<span  class="ml10" >隐藏导师名称</span>
            		</span> 


            		<span class="shangjia">
            			<span class="mr10 ml30">上架时间:</span>
                		<input name="infos[2][putaway]"  type="text" id="putaway_time1" class="input-medium"  value="<?php echo isset( $two_data[0]['putaway']) ? $two_data[0]['putaway'] : ""?>">
            		</span>
            	</div>

            	<div class="homePage_set">
					<input type="hidden" name="infos[3][id]" value="<?php echo isset($one_data[1]['id']) ? $one_data[1]['id'] : 0 ?>"/>
					<input type="hidden" name="infos[3][type]" value="1"/>
            		<span class="mr10">选择音频:</span>
            		<select name="infos[3][audio_id]" id="">
						<?php foreach($data  as $v){?>
							<option <?php if(isset($one_data[1]['audio_id']) && $v['id'] == $one_data[1]['audio_id']){?>selected = "selected"<?php }?>  value ="<?php echo $v['id'] ?>"><?php echo $v['title']?></option>
						<?php }?>
            		</select>

            		<span class="ml15">
						<input name="infos[3][teacher_name_hide]" type="checkbox" <?php if(isset($one_data[1]['hide']) && $one_data[1]['hide'] == 1){?>checked="checked"<?php }?> value="1"/>
            			<span  class="ml10" >隐藏导师名称</span>
            		</span> 

            		<span class="mr10 ml30">将更新的音频:</span>
					<input type="hidden" name="infos[4][id]" value="<?php echo isset($two_data[1]['id']) ? $two_data[1]['id'] : 0?>"/>
					<input type="hidden" name="infos[4][type]" value="2"/>
            		<select name="infos[4][audio_id]" id="">
						<?php foreach($data  as $v){?>
							<option <?php if(isset($two_data[1]['audio_id']) && $v['id'] == $two_data[1]['audio_id']){?>selected = "selected"<?php }?>  value ="<?php echo $v['id'] ?>"><?php echo $v['title']?></option>
						<?php }?>
            		</select>

					<span class="ml15">
						<input name="infos[4][teacher_name_hide]" type="checkbox" <?php if(isset($two_data[1]['hide']) && $two_data[1]['hide'] == 1){?>checked="checked"<?php }?> value="1"/>
            			<span  class="ml10" >隐藏导师名称</span>
            		</span> 

            		<span class="shangjia">
            			<span class="mr10 ml30">上架时间:</span>
                		<input name="infos[4][putaway]"  type="text" id="putaway_time2" class="input-medium" value="<?php echo isset($two_data[1]['putaway']) ? $two_data[1]['putaway'] : ""?>">
            		</span>
            	</div>
				<p class="col_gray">用于管理公众号首页的免费音频模块显示的课程</p>
				<input name="sub"  type="submit" class="btn btn-large btn-primary" id="submit-button" value="保存" />
            </form>

        </div>
</div>
<script type="text/javascript">

</script>
