<style>
.submit {
    float: right;
    margin-left: 8px;
}
.ml8 {
    margin-left: 48px;
}
.row input, .row select {
    margin-bottom:0px;
}
</style>
<br>
<div class="pannel-body">
<div class="pannel">
    <div class="row">
        <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'teacherList'));?>">
            <div class="pull-left ml8" style="margin-left:30px;">
                <a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'teacherDetails'));?>" class="btn btn-primary">+觉鸟导师</a>
            </div>
            <div class="pull-right">
            	<div class="pull-left ml8" style="position: relative">
                    <input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入老师名称" value="<?php echo isset($keyword) ? $keyword:'';?>">
                    <i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
                </div>
                <div class="pull-left ml8" >
                    <span style="margin-left:20px;">账号状态：</span>
                    <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px;">
                        <select class="select-top" name="types" size="1" id="select">
                        	<option value="0" <?php echo $types==0?'selected="selected"':''?>>全部</option>
                            <option value="1" <?php echo $types==1?'selected="selected"':''?>>正常</option>
                            <option value="2" <?php echo $types==2?'selected="selected"':''?>>禁用</option>
        				</select>
        			</div>
        		</div>
        		<div class="pull-left ml8" >
        			<button type="submit" class="btn btn-info submit">搜索</button>
        		</div>
        	</div>
        </form>
        <form class="form-horizontal" method="post" action="">
        <div class="pull-right">
   
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>头像</th>
                <th>名称</th>
                <th>导师头衔</th>
                <th>音频课程量</th>
                <th>视频课程量</th>
                <th>关注量</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <td><img width="40" height="40" src="<?php echo  $this->basePath().(isset($v['img_path']) && $v['img_path'] ? '/'.UPLOAD_PATH.$v['img_path'].$v['filename'] :'/images/portrait.png');?>" alt=""></td>
                <td><?php echo $v['name'];?></td>
                <td><?php echo$v['title'];?></td>
                <td><?php echo $v['audio_num'];?></td>
                <td><?php echo$v['video_num'];?></td>
                <td><?php echo $v['subscription_num'];?></td>
                <td><?php echo$v['status'] == 1 ? "正常" : "禁用";?></td>
                <td>
                     	<?php if($v['status']==1){?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDelete', 'id' => $v['id'],'types'=>2));?>" class="btn btn-warning">禁用</a>
    					<?php }else{?>
    						 <a href="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDelete', 'id' => $v['id'],'types'=>1));?>" class="btn btn-success ">启用</a>
    					<?php }?>
                     <a href="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'teacherDetails', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
                </td>
            </tr>
            <?php }?>

            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>