<style>
.submit {
	float: right;
	margin-left: 8px;
}

.ml8 {
	margin-left: 48px;
}

.row input, .row select {
	margin-bottom: 0px;
}
.position_capacity{
	position: relative;
}
.statistics_capacity{
	border: 1px solid #ccc;
	background-color: #fff;
	position: absolute;
	left: 16px;
	top: 30px;
	display: none;
	z-index: 1000;
}
</style>
<br>
<div class="pannel-body">
	<div class="pannel">
		<div class="row">
			<form class="form-horizontal" method="get"
				action="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'videoList'.($type==2?2:''),'a_type' => $type,'page'=>1));?>">
				<div class="pull-left ml8" style="margin-left: 30px;">
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'addVideo','a_type' => $type));?>"
						class="btn btn-primary"><?php if($type == 1){?>+新增音频<?php }else{?>+新增视频<?php }?></a>
					   <a href="javascript:;"class="btn btn-primary" onclick = "ajaxDeleteData(1)">批量删除</a>
					   <a href="javascript:;"class="btn btn-primary" onclick = "ajaxDeleteData(2)">批量下架</a>
				</div>
				<div class="pull-right">
				    <input type="hidden" value="" name="ids" id="ids"/>
					<div class="pull-left ml8" style="position: relative">
						<input style="width: 160px; padding-left: 25px" name="keyword"
							type="text" class="input-small" placeholder="课程名称、课程老师"
							value="<?php echo isset($keyword) ? $keyword:'';?>"> <i
							class="iconfont" style="position: absolute; top: 5px; left: 5px;">&#xe604;</i>
						<span style="margin-left: 20px;">分类：</span> 
						<select class="select-top" name="pid" size="1" id="select">
    							<option value="0" <?php echo $pid==0?'selected="selected"':''?>>全部</option>
                            <?php foreach ($data as $v){?>
                                <option value="<?php echo $v['id']?>"
								<?php echo $pid==$v['id']?'selected="selected"':''?>><?php echo $v['name']?></option>
                            <?php }?>
    				    </select> 
    				    <span style="margin-left: 20px;">售卖类型：</span> 
						<select class="select-top" name="num" size="1" id="select">
							<option value="0" <?php echo $num==0?'selected="selected"':''?>>全部</option>
							<option value="1" <?php echo $num==1?'selected="selected"':''?>>普通课程</option>
							<option value="2" <?php echo $num==2?'selected="selected"':''?>>会员专享</option>
						</select>
						
						<span style="margin-left: 20px;">付费类型：</span> 
						<select class="select-top" name="cid" size="1" id="select">
							<option value="0" <?php echo $cid==0?'selected="selected"':''?>>全部</option>
							<option value="3" <?php echo $cid==3?'selected="selected"':''?>>免费</option>
							<option value="2" <?php echo $cid==2?'selected="selected"':''?>>单卖</option>
							<option value="1" <?php echo $cid==1?'selected="selected"':''?>>课程包</option>
							<option value="4" <?php echo $cid==4?'selected="selected"':''?>>课程包外单卖</option>
						</select>
						
				        <span style="margin-left: 20px;">课程状态：</span> 
				        <select
							class="select-top" name="types" size="1" id="select">
							<option value="0" <?php echo $types==0?'selected="selected"':''?>>全部</option>
							<option value="1" <?php echo $types==1?'selected="selected"':''?>>正常</option>
							<option value="2" <?php echo $types==2?'selected="selected"':''?>>已下架</option>
						</select>
						
						<button type="submit" class="btn btn-info submit">搜索</button>
					</div>
				</div>
			</form>
			<form class="form-horizontal" method="post" action="">
				<div class="pull-right"></div>
			</form>
		</div>
	</div>
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
			<table class="table table-bordered">
				<thead>
					<tr>
					    <th class="tal"><label><input type="checkbox" class="ace"><span class="lbl"></span></label></th> 
					    <th>序号</th>
						<th>封面</th>
						<th>标题</th>
						<th>分类</th>
						<th>老师</th>
						<th>售卖类型</th>
						<th>付费类型</th>
						<th>普通价(元)</th>
						<th>会员价(元)</th>
						<th>所属课程包</th>
						<th>统计</th>
						<th>上架时间</th>
						<th>课程状态</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
				<?php $pay_type = array(1=>'课程包','单卖','免费','课程包外单卖');?>
				<?php $sell_type = array('--','普通课程','会员专享');?>
				<?php $status = array(1=>'正常','已下架','待上架');?>
                <?php foreach($list as $k=>$v){?>
                <tr>
                    <td><input type="checkbox" class="ace" id="<?php echo $v['id']?>"></label></td> 
                    <td><?php echo $v['sort'];?></td>
					<td><img width="40" height="40"
						src="<?php echo  $this->basePath().(isset($v['img_path']) && $v['img_path'] ? '/'.UPLOAD_PATH.$v['img_path'].$v['filename'] :'/images/portrait.png');?>"
						alt=""></td>
					<td><?php echo $v['title'];?></td>
					<td><?php echo $v['category_name'];?></td>
					<td><?php echo $v['teacher_name'];?></td>
					<td><?php echo $sell_type[$v['sell_type']]?></td>
					<td><?php echo $pay_type[$v['pay_type']];?></td>
					<td><?php echo (int)$v['price'] ? $v['price'] : "--";?></td>
					<td><?php echo (int)$v['original_price'] ? $v['original_price'] : '--';?></td>
					<td><?php echo $v['courses_name'] ? $v['courses_name'] : "--";?></td>
					<td class="position_capacity"><div class="statistics" style="cursor: pointer;"><img src="<?php echo $this->basepath().'/adminStyle/images/内容列表icon.png';?>" width="16" height="16" alt=""></div> 
						<div class="statistics_capacity" style="text-align: inherit;min-width:120px;text-align: initial;">
							<div>评论数：<?php echo $v['comment_num']?></div>
							<div>播放量：<?php echo $v['study_num']?></div>
							<div>完播量：<?php echo $v['over_play']?></div>
							<div>完播率：<?php echo ($v['study_num']?round($v['over_play']/$v['study_num']*100,2):0).'%'?></div>
						</div>
					</td>
					<td><?php echo $v['putaway'];?></td>
					<td><?php echo $status[$v['status']];?></td>
					<td>
					<a href="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'addVideo', 'id' => $v['id'],'a_type' => $type));?>"
						class="btn btn-info">查看</a>
						 <a href="javascript:;" class="btn btn-infos">更多</a>
						<div class = "more" style="display: none">
							<ul>
								<a href="<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'index')).'?type='.$v['type'].'&id='. $v['id'];?>" target="_blank" ><div>查看评论</div></a>
								<?php if($v['status'] == 1){?>
								    <a onclick="soldOut(<?php echo $v['id']?>,1)"><div>下架</div></<a>
								<?php }else{?>
								    <a onclick="soldOut(<?php echo $v['id']?>,2)"><div>上架</div></<a>
								 <?php }?>
								<a onclick="deleteWallet(<?php echo $v['id']?>)"><div>删除</div></a>
							</ul>
						</div>
					</td>
				</tr>
                <?php }?>
            </tbody>
				</table>
				<div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
			</div>
			<!--/span-->
		</div>
	</div>
</div>
<div class="modal hide" id="myModal"  style="width:300px">
	<form action="<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteVideo'));?>" method="post" id="abolish-family">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">您确认要删除吗？</h3>
		</div>
		<div class="modal-footer">
		    <input type="hidden" name="id" value="" id ="social_id">
		    <input type="button" name="s" class="btn btn-primary"  onclick="submitDelete()" value="确定">
			<a href="#" class="btn" data-dismiss="modal">取消</a>
		</div>
	</form>
</div>
<script>

$('table th input:checkbox').on('click' , function(){
	var ids = '';
    if(this.checked == true){
    	$('.table-bordered tbody input[type=checkbox]').attr('checked','checked');
    	$('.table-bordered tbody input[type=checkbox]').each(function(){
        	ids += $(this).attr('id')+",";
    	})
    }else{
    	$('.table-bordered tbody input[type=checkbox]').removeAttr('checked','checked');
    }
    $("#ids").val(ids);
    $.uniform.update();
});
$('table tbody input:checkbox').on('click' , function(){
	var ids = '';
	$('.table-bordered tbody input[type=checkbox]:checked').each(function(){
    	ids += $(this).attr('id')+",";
	})   
	$("#ids").val(ids)
});
function ajaxDeleteData(type){
	//1 删除  2 下架
	var ids = $("#ids").val();
    if(!ids){
    	alert("请选择课程");
    	return false;
    }
    if(type == 1){
       var str = confirm("确定要批量删除课程吗？");
    }else{
 	   var str = confirm("确定要批量下架课程吗？");
    }
	if(str){
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteData','types'=>1));?>";
		 $.post(url,{ids:ids,type:type},function(result){
				if(result.code == 200){
					alert(result.msg);
					history.go(0);
					return false;
				}else{
					alert(result.msg);
					return false;
				}
		 },'json');
	}
}

function soldOut(id,status){
	 if(status == 1){
		 $("#titles").text("你确定要下架吗？");
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteVideo','types'=>1));?>";
	 }else{
		 $("#titles").text("你确定要上架吗？");
		 var url = "<?php echo $this->url('admin', array('controller' => 'ContentList', 'action' => 'ajaxDeleteVideo','types'=>2));?>";
	 }
	 $('#abolish-family')[0].action = url;
	 $('#social_id').val(id);
	 $('#myModal').modal('show');
}
function deleteWallet(id){
	 $('#social_id').val(id);
	$('#myModal').modal('show');
}
function submitDelete(){
// 	$('#myModal').modal('hide');
    $('#abolish-family').submit();
	$('#myModal').modal('toggle');
}
$(".table-bordered tbody tr .btn-infos").click(function() {
	if($(this).next().is(':hidden'))
	{
		$(this).next().slideDown('slow');  
       }else{
	    $(this).next().slideUp('slow'); 
    }
});



var textFlag;

	$(".statistics").click(function(){
		if(textFlag==1) {
			$(".statistics_capacity").hide();
			textFlag=0;
		}else{
	
		$(this).next(".statistics_capacity").show();
		textFlag=1;
		

		}
			
		
	})
	



</script>