<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle(PRODUCT_NAME . '管理'. $this->translate('后台'))->setSeparator(' - ')->setAutoEscape(false);?>
    <?php
    
echo $this->headMeta()
        ->appendName('description', 'RemoteSystemsTempFiles')
        ->appendName('author', 'aiitec')?>

    <!-- Le styles -->
    <?php
    
echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/adminStyle/img/favicon.ico'
    ))
        ->appendStylesheet($this->basePath() . '/adminStyle/css/bootstrap-cerulean.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/bootstrap-responsive.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/charisma-app.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery-ui-1.8.21.custom.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/fullcalendar.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/fullcalendar.print.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/chosen.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/uniform.default.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/colorbox.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.cleditor.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.noty.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/noty_theme_default.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/elfinder.min.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/elfinder.theme.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.iphone.toggle.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/opa-icons.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/uploadify.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/base.css')?>

        <!-- The styles -->

<style type="text/css">
body {
    margin: 0;
    padding: 0
}

.sidebar-nav {
    padding: 9px 0;
}
</style>

<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<!-- Scripts -->
    <?php
    
echo $this->headScript()
        ->offsetSetFile(1, $this->basePath() . '/js/html5.js', 'text/javascript', array(
        'conditional' => 'lt IE 9'
    ))
        ->offsetSetFile(2, $this->basePath() . '/adminStyle/js/jquery-1.7.2.min.js')
        ->offsetSetFile(3, $this->basePath() . '/adminStyle/js/jquery.uploadify.js')
        ->offsetSetFile(4, $this->basePath() . '/adminStyle/js/swfobject.js')
        ->offsetSetFile(5, $this->basePath() . '/adminStyle/js/jquery-ui-1.8.21.custom.min.js')
        ->offsetSetFile(6, $this->basePath() . '/adminStyle/js/bootstrap-transition.js')
        ->offsetSetFile(7, $this->basePath() . '/adminStyle/js/bootstrap-alert.js')
        ->offsetSetFile(8, $this->basePath() . '/adminStyle/js/bootstrap-modal.js')
        ->offsetSetFile(9, $this->basePath() . '/adminStyle/js/bootstrap-dropdown.js')
        ->offsetSetFile(10, $this->basePath() . '/adminStyle/js/bootstrap-scrollspy.js')
        ->offsetSetFile(11, $this->basePath() . '/adminStyle/js/bootstrap-tab.js')
        ->offsetSetFile(12, $this->basePath() . '/adminStyle/js/bootstrap-tooltip.js')
        ->offsetSetFile(13, $this->basePath() . '/adminStyle/js/bootstrap-popover.js')
        ->offsetSetFile(14, $this->basePath() . '/adminStyle/js/bootstrap-button.js')
        ->offsetSetFile(15, $this->basePath() . '/adminStyle/js/bootstrap-typeahead.js')
        ->offsetSetFile(16, $this->basePath() . '/adminStyle/js/bootstrap-tour.js')
        ->offsetSetFile(17, $this->basePath() . '/adminStyle/js/jquery.cookie.js')
        ->offsetSetFile(18, $this->basePath() . '/adminStyle/js/fullcalendar.min.js')
        ->offsetSetFile(19, $this->basePath() . '/adminStyle/js/jquery.dataTables.min.js')
        ->offsetSetFile(20, $this->basePath() . '/adminStyle/js/jquery.chosen.min.js')
        ->offsetSetFile(21, $this->basePath() . '/adminStyle/js/jquery.uniform.min.js')
        ->offsetSetFile(22, $this->basePath() . '/adminStyle/js/jquery.colorbox.min.js')
        ->offsetSetFile(23, $this->basePath() . '/adminStyle/js/jquery.cleditor.min.js')
        ->offsetSetFile(24, $this->basePath() . '/adminStyle/js/jquery.noty.js')
        ->offsetSetFile(25, $this->basePath() . '/adminStyle/js/jquery.elfinder.min.js')
        ->offsetSetFile(26, $this->basePath() . '/adminStyle/js/jquery.raty.js')
        ->offsetSetFile(27, $this->basePath() . '/adminStyle/js/jquery.iphone.toggle.js')
        ->offsetSetFile(28, $this->basePath() . '/adminStyle/js/jquery.autogrow-textarea.js')
        ->
    // ->appendFile($this->basePath() . '/adminStyle/js/jquery.uploadify-3.1.min.js')
    offsetSetFile(29, $this->basePath() . '/adminStyle/js/jquery.history.js')
        ->offsetSetFile(30, $this->basePath() . '/adminStyle/js/charisma.js')
        ->
    // 公共js
    offsetSetFile(31, $this->basePath() . '/js/public.js')?>
<?php if(! empty($_SESSION['admin_login_count']) && $_SESSION['admin_login_count'] > 2) {?>
  <script type="text/javascript">
  $(function(){ 
      onvdcodeFocus();
      });
  </script>
<?php }?>
</head>

<body>
    <div class="container-fluid">
        <div class="row-fluid">

            <div class="row-fluid">
                <div class="span12 center login-header">
                    <h2>管理后台登录</h2>
                </div>
                <!--/span-->
            </div>
            <!--/row-->

            <div class="row-fluid">
                <div class="well span5 center login-box">
                    <div class="alert alert-info">请输入您的用户名和密码。</div>
                    <form class="form-horizontal"
                        action="<?php echo $this->url('admin', array('controller' => 'admin', 'action' => 'index'));?>"
                        method="post">
                        <fieldset>
                            <div class="input-prepend" title="Username" data-rel="tooltip">
                                <span class="add-on">
                                    <i class="icon-user"></i>
                                </span>
                                <input autofocus class="input-large span10" style="width:75%" name="username"
                                    id="username" type="text" value="" />
                            </div>
                            <div class="clearfix"></div>

                            <div class="input-prepend" title="Password" data-rel="tooltip">
                                <span class="add-on">
                                    <i class="icon-lock"></i>
                                </span>
                                <input class="input-large span10"  style="width:75%" name="password" id="password"
                                    type="password" value="" />
                            </div>
<?php if(! empty($_SESSION['admin_login_count']) && $_SESSION['admin_login_count'] >= 3) {?>
                            <div class="clearfix"></div>
                            <div class="input-prepend" title="请输入验证码" data-rel="tooltip">
                                <span class="add-on">
                                    <i class="icon-lock"></i>
                                </span>
                                <input type="text" name="code" style="width: 57px;" />
                                <img id="Captcha" src="" onclick="onvdcodeFocus()"
                                    style="cursor: pointer; width:85px;height:28px;">
                            </div>
<?php }?>
                            <div class="clearfix"></div>
                            <p class="center span5">
                                <input type="submit" class="btn btn-primary" name="submit"
                                    value="登录">
                            </p>
                        </fieldset>
                    </form>
                </div>
                <!--/span-->
            </div>
            <!--/row-->
        </div>
        <!--/fluid-row-->

    </div>
    <!--/.fluid-container-->
</body>
</html>
<script language="JavaScript">
    
function onvdcodeFocus()
{
    $.post("<?php echo $this->url('admin',array('controller' => 'common', 'action'=>'generateCaptcha'))?>",
           function(data){                       
             $("#Captcha").attr("src",data);
           });
}
</script>