<div class="page-header">
    <h1>
        微博列表
    </h1>
</div>

<div class="page-header">
    <form action="<?php echo $this->url('admin-microblog', ['action' => 'index']) ?>">
    <!--        <a href="javascript:downloadUser();" class="btn btn-xs btn-primary">导出用户</a>-->
        <div style="float: right">
            状态：
            <select name="display">
                <option value="0">全部</option>
                <option value="1" <?php if ($display == 1) echo 'selected'; ?>>显示</option>
                <option value="2" <?php if ($display == 2) echo 'selected'; ?>>隐藏</option>
            </select>
            搜索：
            <select name="search_type">
                <option value="1">微博内容</option>
                <option value="2" <?php if ($search_type == 2) echo 'selected'; ?>>用户昵称</option>
            </select>
            <input type="text" name="keyword" value="<?php echo $keyword; ?>" placeholder="请输入关键字">
            <button class="btn btn-xs btn-primary" type="submit">搜索</button>
        </div>
    </form>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>内容</th>
                <th>用户昵称</th>
                <th>定位地址</th>
                <th>点赞量</th>
                <th>评论量</th>
                <th>转发量</th>
                <th>显示状态</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <input type="hidden" name="id<?php echo $k ?>" value="<?php echo $v->id ?>">
                        <input type="hidden" name="display<?php echo $k ?>" value="<?php echo $v->display ?>">
                        <td><?php echo $v->id?></td>
                        <td style="width:30%"><p style="display: -webkit-box;-webkit-box-orient: vertical;-webkit-line-clamp: 3;overflow: hidden;"><?php echo $v->content?></p></td>
                        <td><?php echo $v->nick_name ?></td>
                        <td><?php echo $v->address ?></td>
                        <td><?php echo $v->praise_num ?></td>
                        <td><?php echo $v->comment_num ?></td>
                        <td><?php echo $v->repeat_num ?></td>
                        <td>
                            <span class="label <?php echo $v->display==1?"label-success":"label-danger"?>">
                                <?php echo $v->display ==1?"显示":"隐藏"?>
                            </span>
                        </td>
                        <td>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-microblog', ['action' => 'microblogDetails', 'id' => $v->id]) ?>">详情</a>
                                <?php if($v->display ==1){?>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认隐藏这条微博吗？', changeDisplay, '', this)">
                                    隐藏
                                </a>
                                <?php }else{?>
                                    <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认显示这条微博吗？', changeDisplay, '', this)">
                                        显示
                                    </a>
                                <?php }?>
                                <a class="btn btn-xs btn-danger" onclick="confirm_handle('确认删除这条微博吗？', del, '', this)">
                                    删除
                                </a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto" aria-expanded="false">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                        <li>
                                            <a href="<?php echo $this->url('admin-microblog', ['action' => 'microblogDetails', 'id' => $v->id]) ?>" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="blue">
																				详情
																			</span>
                                            </a>
                                        </li>
                                        <li>
                                            <?php if($v->display ==1){?>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认隐藏这条微博吗？', changeDisplay, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="red">
																				隐藏
																			</span>
                                            </a>
                                            <?php }else{?>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认显示这条微博吗？', changeDisplay, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
                                                                        <span class="red">
                                                                            显示
                                                                        </span>
                                            </a>
                                            <?php }?>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" onclick="confirm_handle('确认删除这条微博吗？', del, '', this)" class="tooltip-info" data-rel="tooltip" title="" data-original-title="View">
																			<span class="red">
																				删除
																			</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-microblog', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>

<script type="text/javascript">
    //单个删除
    function del(obj){
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url:  "<?php echo $this->url('admin-microblog', ['action' => 'microblogDel']) ?>",
            data: {"id":id} ,
            success:  function (msg) {
                layer.close(index);
                if(msg.s){
                    showMessage('删除失败', 0);
                }
                else if(msg.s == 0){
                    showMessage('删除成功', 1);
                    $(obj).parents('tr').remove();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }

    function changeDisplay(obj){
        var id = $(obj).parents('tr').find('input[name^="id"]').val();
        var display = $(obj).parents('tr').find('input[name^="display"]').val();
        var index = showLoad();
        //发送ajax请求
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url:  "<?php echo $this->url('admin-microblog', ['action' => 'changeDisplay']) ?>",
            data: {"id":id,"display":display==1?2:1} ,
            success:  function (msg) {
                layer.close(index);
                if(msg.s){
                    showMessage(msg.d, 0);
                }
                else if(msg.s == 0){
                    showMessage(msg.d, 1);
                    location.reload();
                }
            },
            error : function () {
                layer.close(index);
                showMessage('请求异常, 请稍后重试', 0);
            }
        });
    }
</script>