<!--省市区json文件-->
<script src="<?php echo $this->basePath() . '/adminStyle/js/jq_area.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/adminStyle/js/region.js'?>"  type="text/javascript"></script>

<style>
    .controls span {
        color: red;
    }

    .controls input {
        height: 25px;
    }
    .form-horizontal>div{
        margin-left: 20px !important;
    }
    .form-group label{
        text-align: left !important;
        width:110px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>

<div class="page-header">
    <h1>
        微博详情
    </h1>
</div>
<form class="form-horizontal" role="form" method="post" id="form">
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right" style="font-size:20px;font-weight: bold">基本信息</label>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 微博内容：</label>

        <div class="col-sm-9">
            <textarea cols="80" rows="8"><?php echo $info->content?></textarea>
<!--            <span style="height:30px;line-height: 30px;">--><?php //echo $->nick_name?><!--</span>-->
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 用户昵称：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $info->nick_name?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 定位地址：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;"><?php echo $info->address?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right" > 点赞量：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;font-size:20px"><?php echo $info->praise_num?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 评论数：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;font-size:20px"><?php echo $info->comment_num?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 转发数：</label>

        <div class="col-sm-9">
            <span style="height:30px;line-height: 30px;font-size:20px"><?php echo $info->repeat_num?></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label no-padding-right"> 显示状态：</label>

        <div class="col-sm-9">
            <span style="height:23px;line-height: 23px;" class="label <?php echo $info->display==1?'label-success':'label-danger'?>"><?php echo $info->display==1?"显示":"隐藏"?></span>
        </div>
    </div>

<!--    <div class="form-group">-->
<!--        <label class="col-sm-1 control-label no-padding-right"> 用户地址：</label>-->
<!--        <div class="col-sm-9" id="element_id">-->
<!--            <span id="location">-->
<!--            <select id="provinceId" name="province_id" style="width: 100px;border-radius:10px;" disabled></select>-->
<!--            <select id="cityId" name="city_id" style="width: 100px;border-radius:10px;" disabled></select>-->
<!--            <select id="countyId" name="county_id" style="width: 100px;border-radius:10px;" disabled></select>-->
<!--            </span>-->
<!--            <input type="text" name="street" value="--><?php //echo $userInfo->street?><!--" placeholder="填入详细街道信息" disabled/>-->
<!--        </div>-->
<!--    </div>-->

    <?php if($image_list){?>
    <div class="form-group">

        <label class="col-sm-1 control-label no-padding-right" for="form-field-1"> 微博图片：</label>
        <div class="col-sm-9">
            <div class="mot_tright">
                <div>
                    <?php foreach ($image_list as $v) {?>
                        <div style="display: inline-block;">
                            <img src="<?php echo strpos($v['filename'],'http')===false?UPLOADFILIS_ROOT.$v['path'].$v['filename']:$v['filename'] ?>"  width = '100px'>
                        </div>
                    <?php }?>
                </div>
            </div>
        </div>
    </div>
    <?php }?>

    <!--<div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <input type="hidden" name="id" value="<?php echo $Info->id?>">
            <button class="btn btn-info" type="submit" id="submit">
                <i class="ace-icon fa fa-check bigger-110"></i>
                保存
            </button>
            <a class="btn" onclick="window.history.back()">
                <i class="ace-icon fa fa-undo bigger-110"></i>
                取消
                <a/>
        </div>
    </div>-->
</form>

<script>
    //$("#location").area({
    //    provinceId:"#provinceId",cityId:"#cityId",countyId:"#countyId",
    //    cache: region,
    //    p_id:<?php //echo isset($region[0]['region']['id']) ? $region[0]['region']['id'] : '440000'?>//,
    //    ci_id:<?php //echo isset($region[1]['region']['id']) ? $region[1]['region']['id'] : '440100'?>//,
    //    co_id:<?php //echo isset($region[2]['region']['id']) ? $region[2]['region']['id'] : '440103'?>//,
    //});
</script>