<div class="page-header">
    <h1>
        管理员
    </h1>
</div>
<div class="page-header">
    <a href="<?php echo $this->url('admin-setting', array('action' => 'addAdmin')); ?>" class="btn btn-xs btn-primary">新增管理员</a>
</div>


<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>姓名</th>
                <th>登录帐号</th>
                <th>职务</th>
                <th>手机号码</th>
                <th>最近登录时间</th>
                <th>帐号状态</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($list as $v) { ?>
                <tr>
                    <td>
                        <?php echo $v->id ?>
                    </td>
                    <td><?php echo $v->real_name ?></td>
                    <td><?php echo $v->name ?></td>
                    <td><?php echo $v->admin_category_name ?></td>
                    <td><?php echo $v->mobile ?></td>
                    <td><?php echo $v->timestamp ?></td>
                    <td><?php echo ($v->status == 1) ? '正常' : '注销/停用' ?></td>
                    <td>
                        <?php if ($v->super != 2) { ?>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-setting', array('action' => 'viewAdmin', 'id' => $v->id)); ?>">查看</a>
                                <a class="btn btn-xs btn-yellow" href="javascript:confirm_handle('确认启用/禁用该管理员吗？',del,'',{'id':<?php echo $v->id;?>,'type':1});" ><?php echo ($v->status == 1) ? '禁用' : '启用' ?></a>
                                <a class="btn btn-xs btn-danger" href="javascript:confirm_handle('确认删除吗？',del,'',{'id':<?php echo $v->id;?>,'type':2});">删除</a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                        <li>
                                            <a href="<?php echo $this->url('admin-setting', array('action' => 'viewAdmin', 'id' => $v->id)); ?>" class="tooltip-info" data-rel="tooltip" title="查看">
                                                <span class="blue">
                                                    查看
                                                </span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="javascript:confirm_handle('确认启用/禁用该管理员吗？',del,'',{'id':<?php echo $v->id;?>,'type':1});" class="tooltip-success" data-rel="tooltip" title="<?php echo ($v->status == 1) ? '禁用' : '启用' ?>">
                                                <span class="orange">
                                                    <?php echo ($v->status == 1) ? '禁用' : '启用' ?>
                                                </span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="javascript:confirm_handle('确认删除吗？',del,'',{'id':<?php echo $v->id;?>,'type':2});" class="tooltip-error" data-rel="tooltip" title="删除">
                                                <span class="red">
                                                    删除
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>

        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;}?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-setting', 'condition' => $condition)); ?>
    </div>
</div>
<script>
    function del(obj) {
        var type = obj.type;
        var id = obj.id;
        if(type == 1){
            var url = '<?php echo $this->url('admin-setting', ['action' => 'banAdmin']) ?>';
        }else{
            var url = '<?php echo $this->url('admin-setting', ['action' => 'deleteAdmin']) ?>';
        }
        $.ajax({
            type: "POST",
            url: url,
            data: {"id": id},
            dataType: "JSON",
            async: false,
            success: function (data) {
                if(data.s){
                    showMessage('操作失败！',2);
                }else{
                    showMessage('操作成功！',1);
                    location.reload();
                }
            },
            error: function (res) {
                console.log(res,'error');
            }
        });
    }
</script>
