<div class="page-header">
    <h1>
        职务管理
    </h1>
</div>
<div class="page-header">
   <a href="<?php echo $this->url('admin-setting', array('action' => 'addRole')); ?>" class="btn btn-xs btn-primary">新增职务</a>
</div>


<!-- PAGE CONTENT BEGINS -->
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>职务名称</th>
                <th>操作</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($list as $v) { ?>
                <tr>
                    <td><?php echo $v->id ?></td>
                    <td><?php echo $v->name ?></td>
                    <td>
                        <?php if ($v->name != '超级管理员') { ?>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="btn btn-xs btn-danger" href="javascript:confirm_handle('确认删除吗？',del,'',{'id':<?php echo $v->id;?>});" >删除</a>
                                <a class="btn btn-xs btn-primary" href="<?php echo $this->url('admin-setting', ['action' => 'viewRole', 'id' => $v->id]) ?>">查看</a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>

                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                        <li>
                                            <a href="javascript:confirm_handle('确认删除吗？',del,'',{'id':<?php echo $v->id;?>});" class="tooltip-info" data-rel="tooltip" title="删除">
                                                <span class="red">
                                                    删除
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('admin-setting', ['action' => 'viewRole', 'id' => $v->id]) ?>" class="tooltip-error" data-rel="tooltip" title="查看">
                                                <span class="blue">
                                                    查看
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>

        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-setting', 'condition' => $condition)); ?>
    </div>
</div>
<script>
    function del(obj) {
        var id = obj.id;
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('admin-setting', ['action' => 'deleteRole']) ?>",
            data: {"id": id},
            dataType: "JSON",
            async: false,
            success: function (data) {
                if(data.s){
                    showMessage(data.d,0);
                }else{
                    showMessage('操作成功！',1);
                    location.reload();
                }
            },
            error: function (res) {
                console.log(res,'error');
            }
        });
    }
</script>