<!--富文本编辑器-->
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/themes/default/default.css'?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.css'?>" media="screen" rel="stylesheet" type="text/css">

<script src="<?php echo $this->basePath() . '/plugins/kindeditor/kindeditor-all.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/lang/zh-CN.js'?>"  type="text/javascript"></script>
<script src="<?php echo $this->basePath() . '/plugins/kindeditor/plugins/code/prettify.js'?>"  type="text/javascript"></script>
<div class="page-header">
    <h1>
        隐私协议
    </h1>
</div>
<form class="form-horizontal" id="form" method="post" action="">
    <div class="form-group">
        <textarea name="content" style="width:80%;height:600px;visibility:hidden;" id="value"><?php echo $info->value;?></textarea>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <input type="hidden" name="id" value="<?php echo $info->id;?>">
            <input class="btn btn-info" type="submit" name="submit" value="保存">
        </div>
    </div>
</form>
<script>
    $('#form').submit(function (e) {
        ajaxForm(e);
    })
    KindEditor.ready(function(K) {
        var editor1 = K.create('textarea[name="content"]', {
            afterBlur: function(){this.sync();}
        });
    });
</script>