<!-- <script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script>
<script src="<?php echo $this->basePath();?>/jedate/jedate.js"></script>-->
<?php  $arr = $condition['where'];?>
<style>
    .select {
        border:1px solid #ccc;
        border-radius: 3px;
        width:115px;
    }
</style>
<ul class="breadcrumb">
    <li><span>访客记录</span></li>
</ul>
<div class="pannel-body">
    <div class="pannel">
        <div class="row">

            <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>">
                <div class="pull-left ml8" style="margin-left:30px;">
               <!--<span class="l_f">
                 <a href="<?php /*echo $this->url('admin',array('controller' => 'User', 'action'=>'getExcel')).'?'.http_build_query($arr);*/?>"  class="btn btn-purple btn-primary btn-sm">导出excel</a>
               </span>-->
                </div>

                <div class="pull-right">
                    <!--<div class="pull-left ml8" style="position: relative">
                        <input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入用户名、手机号" value="<?php /*echo $arr['keyword']*/?>">
                        <i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
                    </div>-->
                    <div class="pull-left ml8" style="margin-right: 10px;">
                        <span style="margin-left:20px;">查询日期：</span>
                        <input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $start;?>">&nbsp;至&nbsp;
                        <input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $end;?>">
                    </div>
                    <div class="pull-left ml8" >
                        <button type="submit" class="btn btn-info submit">搜索</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>头像</th>
                        <th>昵称</th>
                        <th>手机号码</th>
                        <th>第一次访问时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($list as $k=>$v){?>
                        <tr>
                            <th>
                                <img src="<?php echo $v['img_path']?($this->basepath().'/'.UPLOAD_PATH.'thumb/640X640X4/'.$v['img_path']):$v['head_icon']?>" width="100" height="100">
                            </th>
                            <th><?php echo$v['user_name'] ;?></th>
                            <td><?php echo $v['mobile'];?></td>
                            <td><?php echo $v['date'];?></td>
                        </tr>
                    <?php }?>
                    </tbody>
                </table>
                <div class="page-control">
                    <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basepath()?>/adminStyle/js/custom_common.js"></script>


<script type="text/javascript">


</script>