<!-- <script type="text/javascript" src="<?php echo $this->basePath();?>/adminStyle/template/js/thescript.js"></script>
<script src="<?php echo $this->basePath();?>/jedate/jedate.js"></script>-->
<?php  $arr = $condition['where'];?>
<style>
    .select {
        border:1px solid #ccc;
        border-radius: 3px;
        width:115px;
    }
</style>
<ul class="breadcrumb">
    <li><span>页面浏览详情</span></li>
</ul>
<div class="pannel-body">
    <div class="pannel">
        <div class="row">

            <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>">
                <input type="hidden" value="4" name="type">
                <div class="pull-left ml8" style="margin-left:30px;">
<!--               <span class="l_f">-->
<!--                 <a href="--><?php //echo $this->url('admin',array('controller' => 'User', 'action'=>'getExcel')).'?'.http_build_query($arr);?><!--"  class="btn btn-purple btn-primary btn-sm">导出excel</a>-->
<!--               </span>-->
                </div>

                <div class="pull-right">
                    <div class="pull-left ml8" style="margin-right: 10px;">
                        <span style="margin-left:20px;">查询日期：</span>
                        <input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $start;?>">&nbsp;至&nbsp;
                        <input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $end;?>">
                    </div>
                    <div class="pull-left ml8" >
                        <button type="submit" class="btn btn-info submit">搜索</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>页面名称</th>
                        <th>浏览量</th>
                        <th>统计时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($list as $k=>$v){
                        if($v['page_id'] == 0){
                            $v['name'] = $page_arr[$v['page_type']];
                        }else{
                            if($v['page_type']==5){
                                $v['name'] = $user_arr[$v['page_id']];
                            }else if($v['page_type'] == 4){
                                $v['name'] = '导师详情';
                            }else{
                                $v['name'] = $v['p_name']?$v['p_name']:$v['c_name'];
                            }
                        }
                        ?>

                        <tr>
                            <th><?php echo$v['name'] ;?></th>
                            <td><?php echo $v['value'];?></td>
                            <td><?php echo $v['date'];?></td>
                        </tr>
                    <?php }?>
                    </tbody>
                </table>
                <div class="page-control">
                    <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basepath()?>/adminStyle/js/custom_common.js"></script>


<script type="text/javascript">


</script>