<style>
	.controls>label {
		padding-top : 5px;
	}
	.l-n {
		list-style-type: none;
	}
	.fl {
		float: left;
	}
	.m-t-10 {
		margin-top: 10px;
	}
	.fr {
		float: right;
	}
	.form-horizontal .control-label {
		width: 80px;
		text-align: left;
		margin-left: 40px;
	}
	.form-horizontal .controls {
		margin-left: 140px;
	}
	.del-btn {
		height: 46px;
		width: 150px !important;
		border: 1px solid #43a1da;
		background: #fff;
		border-radius: 3px;
	}
	
	.reward-sum{
		padding: 0 10px;
		margin:10px 0;
	}
	.reward-review {
		padding: 12px;
		margin-top: 18px;
		background-color: #f5f5f5;
		border: 1px solid #e5e5e5;
	}
	.stop-text {
		display: inline-block;
		border: 2px solid red;
		width: 70px;
		height: 19.4px;
		text-align: center;
		line-height: 19.4px;
		color: red;
		margin-left: 20px;
	}
	.start-text {
		display: inline-block;
		border: 2px solid green;
		width: 70px;
		height: 19.4px;
		text-align: center;
		line-height: 19.4px;
		color: green;
		margin-left: 20px;
	}
</style>
<?php   $type_arr = array('1'=>'音频', '2'=>'视频','3'=>'音频包','4'=>'视频包');?>
<div id="content" class="span10">
	<div>
		<ul class="breadcrumb">
			  <li><span>评论管理</span><span class="divider">/</span></li>
			<li>
				<a href="<?php echo $this->url( 'admin', array('controller' => 'Comment'));?>">评论列表</a>
				<span class="divider">/</span>
			</li>
			<li>
				<a href="#">评论详情</a>
			</li>
		</ul>
	</div>
	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">
					<fieldset>
						<legend class="lg_title">
							<span>课程信息：</span>
						</legend>
					<form action="" method="post" class="form-horizontal">
						<section style="position: relative; overflow: hidden;">
							<div style="float: left;width: 100%;">
								<div class="control-group">
									<label class="control-label">课程类型：</label>
									<div class="controls">
										<label style="display: inline-block;"><?php echo $type_arr[$data['type']];?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">课程名称：</label>
									<div class="controls">
										<label><?php echo $data['type']>=2?$data['c_name']:$data['p_name'];?></label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">老师名称：</label>
									<div class="controls">
										<label><?php echo $data['t_name'];?></label>
									</div>
								</div>
								<legend class="lg_title">
        							<span>评论信息：</span>
        						</legend>
								<div class="control-group">
									<label class="control-label">
									       <img src="<?php echo $data['img_path']?($this->basepath().'/'.UPLOAD_PATH.'thumb/640X640X4/'.$data['img_path']):$data['head_icon']?>" width="100" height="100">
									</label>
									<div class="controls">
										<label><?php echo $data['name'];?><div style="float: right;margin-right: 10px;"><?php echo $data['timestamp'];?></div></label>
										<div><?php echo $data['content'];?></div>
										 <TEXTAREA rows="5"  name="content" id="contents" style="width: 98%;" placeholder="回复内容" ></TEXTAREA>
									</div>
								</div>
								<div class="control-group">
                                    <label class="col-md-2 control-label"></label>
                                    <div class="col-md-8 controls">
                                        <input type="hidden" value="<?php echo $data ? $data['id'] : 0;?>" name="id" />
                                          <input type="hidden" value="2017" name="ajax" />
                                        <input type="submit" class="btn btn-large btn-primary" id="ap" value="回复"/>
<!--                                         <input class="btn btn-large btn-primary resetHref" type="reset" value="取消"/> -->
                                    </div>
                                </div>
							</div>
						</section>
						</form>
<!-- 						<legend class="lg_title"> -->
<!-- 						 <span>Ta的课程：</span> -->
<!-- 						</legend> -->
<!-- 	列表 -->
		                <div id="course_list"></div>
<!-- 列表 -->
					</fieldset>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//var rewardList_url = '<?php //echo $this->url('admin',array('controller'=>'User','action'=>'getUserCourseList','id'=>$id));?>';//page;+'/p'+1
var loadmore_type = 1;
function getRewardList(page,type) {
	var rewardList_url = '<?php echo $this->url('admin',array('controller'=>'Comment','action'=>'getCommentReplyList','id'=>$data['id']));?>'+'/p'+page;//page;+'/p'+1
	  if (rewardList_url) {
	    $.post(rewardList_url, {page:page,id:<?php echo $data?$data['id']:0;?>,type:type},function (data) {
//	    	console.log(data);return;
// 	    	rewardTemplate(data, 'reward_list');
// 	    	rewardTemplate2(data,'reward_page');
	    $('#course_list').html('');//清空
        $("#course_list").append(data)
	    },"html");
	  }
	}
	
function rewardList(page,type){
// 	 $('#reward_page').html('');//清空
    getRewardList(page,type);
}
$(document).ready(function(){
    if (loadmore_type == 1) {
      getRewardList(1,0);
    }
});
</script>