<?php  $arr = $condition['where']; $type_arr = array('1'=>'音频', '2'=>'视频','3'=>'音频包','4'=>'视频包');?>
<style>
.select {
    border:1px solid #ccc;
    border-radius: 3px;
    width:115px;
}
.title-top div.con{
/*     border: 1px solid green; */
    width: 12%;
    text-align: center;
    font-size: 22px;
    display: inline-block;
     margin-left:1%;
     margin-right:1%;
/*     margin:0 20%; */
}
.title-top div.margin{
    margin-left:4.5%;
}
</style>

<ul class="breadcrumb">
    <li><span>财务管理</span><span class="divider">/</span></li>
    <li> <a href="#">财务列表</a></li>
</ul>
<div class="pannel-body">
	<div class="box-content">
		<legend class="lg_title">
			<!-- <span>今天实时 （更新时间：<?php //echo date('Y-m-d H:i:s');?>）：</span> -->
		</legend>
		<div class="title-top">
            <div class="con" ><div>￥<?php echo $total['sum']?$total['sum'] : '0.00';?></div><br/><span style=" font-size: 14px;">今日收入（元）</span></div>
            <div class="con" ><div>￥<?php echo $total['today_consumption']?$total['today_consumption'] : '0.00';?></div><br/><span style=" font-size: 14px;">今日消费（元）</span></div>
	      <div class="con " ><div>￥<?php echo $total['sum_total']?$total['sum_total'] : '0.00';?></div><br/><span style=" font-size: 14px;">总收入（元）</span></div>
            <div class="con " ><div>￥<?php echo $total['total_consumption']?$total['total_consumption'] : '0.00';?></div><br/><span style=" font-size: 14px;">总消费（元）</span></div>
            <div class="con " ><div>￥<?php echo $total['sum_total']-$total['total_consumption'];?></div><br/><span style=" font-size: 14px;">待交付总额（元）</span></div>
            <div class="con " ><div>￥<?php echo $total['member_total_income']?$total['member_total_income'] : '0.00';?></div><br/><span style=" font-size: 14px;">会员总收入（元）</span></div>
            <div class="con " ><div>￥<?php echo $total['member_total_consumption']?$total['member_total_consumption'] : '0.00';?></div><br/><span style=" font-size: 14px;">会员总消费（元）</span></div>
		</span>
		<legend class="lg_title" style="margin-top: 27px;">
		</legend>
	</span>
<div class="pannel">
    <div class="row">
        <form class="form-horizontal" method="get" action="<?php echo $this->url('admin',array(
"controller"=>'Order','page'=>1))?>">
            <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px">
                    <select name="income" size="1" class="select">
                        <option value="0" >财务类型</option>
                        <option value="1" <?php echo $arr['income']==1?'selected="selected"':''?>>收入</option>
                        <option value="2" <?php echo $arr['income']==2?'selected="selected"':''?>>消费</option>
                    </select>
                    <select name="vip_pay" size="1" class="select">
                        <option value="0" >用户类型</option>
                        <option value="1" <?php echo $arr['vip_pay']==1?'selected="selected"':''?>>会员</option>
                        <option value="2" <?php echo $arr['vip_pay']==2?'selected="selected"':''?>>非会员</option>
                    </select>
                </div>
            </div>
             <div class="pull-left ml8" style="margin-left:30px;">
               <span class="l_f">
                 <a href="<?php echo $this->url('admin',array('controller' => 'Order', 'action'=>'getExcel')).'?'.http_build_query($arr);?>"  class="btn btn-purple btn-primary btn-sm">导出excel</a>
               </span>
          </div>
            <div class="pull-left ml8" style="margin-left:30px;font-size: 14px;line-height: 30px;">
               <span class="l_f">购买人数：<?php echo isset($total['count'])?$total['count']:'0';?>人</span>
          </div>
          <div class="pull-right">
           <div class="pull-left ml8">
				<span style="margin-left:20px;">修改日期：</span>
				<input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $arr['start'] ? $arr['start'] : '';?>">&nbsp;至&nbsp;
				<input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $arr['end'] ? $arr['end'] : '';?>">
			</div>
        <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px">
                  <select name="type" size="1" class="select">
                    <option value="0" >全部课程类型</option>
                    <option value="1" <?php echo $arr['type']==1?'selected="selected"':''?>>音频</option>
                    <option value="2" <?php echo $arr['type']==2?'selected="selected"':''?>>视频</option>
                     <option value="3" <?php echo $arr['type']==3?'selected="selected"':''?>>音频包</option>
                      <option value="4" <?php echo $arr['type']==4?'selected="selected"':''?>>视频包</option>
                  </select>
            </div>
        </div>
        <div class="pull-left ml8" >
            <button type="submit" class="btn btn-info submit">搜索</button>
        </div>
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>头像</th>
                <th>用户名</th>
                <th>购买类型</th>
                <th>购买内容</th>
                <th>购买数量</th>
                <th>订单总额(元)</th>
                <th>订单时间</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th>
                    <img src="<?php echo $v['img_path']?($this->basepath().'/'.UPLOAD_PATH.'thumb/640X640X4/'.$v['img_path']):$v['head_icon']?>" width="100" height="100">
                </th>
                <th><?php echo$v['name'] ;?></th>
                <?php if($v['type'] == 6){?>
                    <td>佣金充值</td>
                <?php }else if($v['type'] == 5){?>
                    <td>营销活动充值</td>
                <?php }else if($v['type'] == 4){?>
                    <td>集团会员充值</td>
                <?php }else if($v['type'] == 3){?>
                    <td>充值</td>
                <?php }else if($v['type'] == 2 && $v['pay_type'] == 2){?>
                    <td>会员赠送</td>
                <?php }else if($v['genre'] == 1){?>
                    <?php if($v['p_type'] == 1){?>
                        <td>音频</td>
                    <?php }else{?>
                        <td>视频</td>
                    <?php }?>
                <?php }else if($v['genre'] == 2){?>
                    <?php if($v['c_type'] == 3){?>
                        <td>音频包</td>
                    <?php }else{?>
                        <td>视频包</td>
                    <?php }?>
                <?php }?>
               
                <td><?php echo $v['genre']==1?$v['p_name']:$v['c_name'];?></td>
                <td><?php echo $v['number'];?></td>
                <td><?php echo $v['amount'];?></td>
                <td><?php echo $v['timestamp'];?></td>
            </tr>
            <?php }?>
            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>
