<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>关于一起聚餐</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="about_nightbird">
        <img class="logo" src="<?php echo ROOT_PATH;?>webStyle/images/nightbird_log.png" alt="">
        <div>一起聚餐6.2.5</div>
        <div>
            <ul class="mt50 bg_white">
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'userHelp','type' => 2));?>">
                    <li class="go">
                        功能介绍
                    </li>
                </a>
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'userHelp','type' => 1));?>">
                    <li class="go">
                        用户帮助
                    </li>
                </a>
                
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'feedBack'));?>">
                    <li class="go">
                        意见反馈
                    </li>
                </a>
            </ul>
        </div>
    </div>
</body>   
</html>
<script>
//wx.ready(function(){
//	 shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php //echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>//webStyle/images/nightbird_log.png'};
//	 share(shareData);
//});
</script>