<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>账号与安全</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    
    <div class="account_set">
    <p class="mb10">安全</p>
        <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'captcha'));?>?tell=<?php echo $data['mobile'];?>">
            <div class="go">
                手机号
                <span class="phone_number"><?php echo $data['mobile']?></span>
            </div>
        </a>
        <!-- <a href="">
            <div class="go">
                修改密码
            </div>
        </a>
        -->
    </div>

</body>   
</html>
<script>
//wx.ready(function(){
//     shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php //echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>//webStyle/images/nightbird_log.png'};
//     share(shareData);
//});
</script>