<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>设置</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="bgb"></div>
    <div class="account_set">
        <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'accountSafety'));?>">
            <div class="go">
                账号与安全
            </div>
        </a>
        <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'aboutNightBird'));?>">
            <div class="go">
                关于一起聚餐
            </div>
        </a>
        <!-- <a href="javascript:(0);">
            <div class="quit">
                退出登录
            </div>
        </a> -->
    </div>
        <div class="affirm_delete">
        <div class="quit_prompt">退出当前账号不会删除任何历史数据，下次登录依然可以使用本账号。</div>
        <div>
            <ul>
                <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
                <li><a href="javascript:(0);" class="affirm"><p>退出</p></a></li>
            </ul>
        </div>
    </div>
</body>   
</html>
<script>
$(".quit").on('click',function(){
    $(".bgb").show();
    $(".affirm_delete").show();
})
$(".affirm_delete .cancel").on('click',function(){
    $(".bgb").hide();
    $(".affirm_delete").hide();
})
$(".affirm_delete .affirm").on('click',function(){
	var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ajaxLogout'))?>";
	var return_url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'index'))?>?logout=1";
	$.post(url,{},function(data){
	    if(data.code == 200){
	    	window.location.href = return_url;
		}
	    $(".bgb").hide();
        $(".affirm_delete").hide();
		},'json');
})
</script>