<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>购买记录</title>
<style>
    body{
        padding-bottom: 60px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="record">
        <div class="select_top">
            <a href="javascript:(0);" class="select_on">音频课程</a>
            <a href="javascript:(0);">视频课程</a>
        </div>
        <section>
        <!-- 音频 -->
            <div class="voice_curriculums_list">
                <ul>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">

                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
                                <div class="information">
                                    <div class="sum">总共8个音频</div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                                <img class="present_red" src="<?php echo ROOT_PATH;?>webStyle/images/present_red.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
                                <div class="information2">
                                    <div><img src="<?php echo ROOT_PATH;?>webStyle/images/video_view.png" alt=""><span>100.3万</span></div>
                                    <div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span>15:36</span></div>
                                    <div><img src="<?php echo ROOT_PATH;?>webStyle/images/date.png" alt=""><span>03-01</span></div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
                                <div class="information">
                                    <div class="sum">总共8个音频</div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>

                </ul>
                
            </div>            
        <!-- 视频 -->
            <div class="voice_curriculums_list" id="video_curriculums_list" style="display:none">
                <ul>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img class="video_image" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
                                <div class="information">
                                    <div class="sum">总共8个音频</div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img class="video_image" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                                <img class="present_red" src="<?php echo ROOT_PATH;?>webStyle/images/present_red.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
          
                                <div class="information2">
                                    <div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span>15:36</span></div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img class="video_image" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
                                <div class="information">
                                    <div class="sum">总共8个音频</div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img class="video_image" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                                <img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">
                            </div>
                            <div class="content">
                                <div>大商之道-教你如何发展好企业</div>
                                <div class="teacher_name">张老师</div>
          
                                <div class="information2">
                                    <div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span>15:36</span></div>
                                    <div class="counting"><span class="font_color_055773">5.6万</span>人在学</div>
                                </div>
                            </div>
                            <div  class="more">
                                <img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                            </div>
                        </a>
                    </li>
            
                </ul>
            </div>        
        </section>
    </div>
</body>   
</html>
<script>
$(".record .select_top a").click(function(){
        $(this).addClass('select_on').siblings().removeClass('select_on');
        $('section>div').hide();
        $('section>div').eq($(this).index()).show()
    })
</script>