<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>购买记录</title>
<style>
    body{
        padding-bottom: 80px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
<div class="bgb"></div>
    <div class="record">
        <div class="select_top  bg_white">
            <a href="javascript:(0);" class="select_on" onclick="getFavorite(1,1)">音频课程</a>
            <a href="javascript:(0);" onclick="getFavorite(2,1)">视频课程</a>
        </div>
        <section>
            <!-- 音频 -->
            <div class="voice_curriculums_list" id="audio_curriculums_list">
                <ul class="bg_white">
                    
                </ul>
        		<div class="unrecorded">
        			<img src="<?php echo ROOT_PATH;?>webStyle/images/no_buyRecord.png" alt="">
            		<div>还没有购买记录</div>
        		</div>                
            </div>            
            <!-- 视频 -->
            <div class="voice_curriculums_list" id="video_curriculums_list" style="display:none">
                <ul class="bg_white">            
                </ul>
        		<div class="unrecorded">
        			<img src="<?php echo ROOT_PATH;?>webStyle/images/no_buyRecord.png" alt="">
            		<div>还没有购买记录</div>
        		</div>                  
            </div>        
        </section>
    </div>


   
</body>   
</html>
<script>

$(".record .select_top a").click(function(){
    $(this).addClass('select_on').siblings().removeClass('select_on');
    $('section>div').hide();
    $('section>div').eq($(this).index()).show()
})


var finished = false;
var page = 1;
getFavorite(1,1);
function getFavorite(num,type ){
	 if (finished && type == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(type == 1){
    	 page = 1;
     }
     finished = true;
	$.post("<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxGetBuyLog'));?>",{num:num,page:page},function(result){
		 $('.londing_gif').hide();
		if(result.list.length > 0){			
			var li = '';
			var video_dom = $("#video_curriculums_list ul");
			var audio_dom = $("#audio_curriculums_list ul");
			var img_url = "<?php echo ROOT_PATH.UPLOAD_PATH;?>";
			
			$.each(result.list,function(i,v){
				if(v.audio_type == 1 || v.audio_type == 2){                   
					li += '<li>';
					li += '<div class="delete_blue"><img src="<?php echo ROOT_PATH;?>webStyle/images/delete_blue.png" alt=""></div>';
					if(v.audio_type == 1){
				        var url = "<?php echo $this->url('web-common',array('controller' => 'Audio','action' => 'details'));?>";
				        url = url+'?id='+[v.audio_id,1]+'&type=1';
				    }else{
    				    var url = "<?php echo $this->url('web-common',array('controller' => 'video','action' => 'details'));?>";
    			        url = url+'?id='+[v.audio_id,1]+'&type=1';
				    }
					li += '<a href="'+url+'">';
					li += '<div  class="cover">';
					if(num == 1){
						li += '<img src="'+ img_url + '/' +v.img_filename +'" alt="">';
					}else{
						li += '<img class="video_image" src="'+ img_url + v.img_path + v.img_filename +'" alt="">';
					}
					if(v.is_giving == 2){
						li += '<img class="present_red" src="<?php echo ROOT_PATH;?>webStyle/images/present_red.png" alt="">';
					}
					li += '<img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">';
					li += '</div>';
					li += '<div class="content">';
					li += '<div>'+v.title+'</div>';
					li += '<div class="teacher_name">'+v.teacher_name+'</div>';
					li += '<div class="information2">';
					if(num == 2){
						li += '<div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span>'+v.audio_length+'</span></div>';
						li += '<div class="counting"><span class="font_color_055773">'+v.study_num+'</span>人在学</div>';
					}else{
						li += '<div><img src="<?php echo ROOT_PATH;?>webStyle/images/video_view.png" alt=""><span>'+v.study_num+'</span></div>';
						li += '<div><img src="<?php echo ROOT_PATH;?>webStyle/images/clock.png" alt=""><span>'+v.audio_length+'</span></div>';
						li += '<div><img src="<?php echo ROOT_PATH;?>webStyle/images/date.png" alt=""><span>'+v.timestamp+'</span></div>';
					}
// 					if(v.count != "0%"){
//                         if(v.count != "100%"){
//                        	 li += '<span class="ml40"><span>已播</span><span class=" font_color_055773">'+v.count+'</span></span>';
//                         }else{
//                        	 li += '<span class="ml40 ">已学完</span>';
//                         }
//                     }
//                     li += '</div>'
//                     li += '<div class="information2">';
//                     if(v.price == '仅限会员'){
//                    	 li += '<div><span class="font_color_055773">'+v.price+'</span></div>';
//                     }else{
//                    	 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
//                     }
//                     li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
					
					li += '</div></div>';
					li += '<div  class="more"><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div></a>';
					li += '</li>';
				}					
			});	
			if(type == 1){
				$("#video_curriculums_list ul li").remove('li');
				$("#audio_curriculums_list ul li").remove('li');
			}
			if(num == 1){
				audio_dom.append(li);
			}else{
				video_dom.append(li);
			}
			$(".user_footer").show()
			finished = false;
            page++;
		}else{
			if(num == 1){
				if($("#audio_curriculums_list ul li").length <= 0){
					$(".user_footer").hide();
					$("#audio_curriculums_list .unrecorded").show();
				}
			}else{
				if($("#video_curriculums_list ul li").length <= 0){
					$(".user_footer").hide()
					$("#video_curriculums_list .unrecorded").show();
				}
			}
		}
	},'json');
	
}


	
function loadmore(obj){    
	if($('.select_on').html() == '视频课程'){
		var num = 2;
	}else{
		var num = 1;
	}
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getFavorite(num,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});
</script>