<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>手机号</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="captcha">
    <p class="mb10">验证手机号</p>
      
            <div class="captcha_import">
                <span> 短信验证：</span>
               
                <input id="captcha" type="text" placeholder="请输入短信验证码" maxlength="4" oninput="checkInput()">
                <a href="javascript:(0);" class="get_captcha">获取验证码</a>
            </div>
   
        <button id="next" class="cannot_on" onclick="checkCaptcha()">下一步</button>
    </div>
</body>   
</html>
<script>
var API_URL = '<?php echo API_URL?>';
var flat = true;
$(".get_captcha").on("click",function(){
    if(flat){
    	sendCaptcha();
    	flat = false;
        var setTime;
        var time=60;
        $(".get_captcha").text('60s');
        $(".get_captcha").css("background-color","#cccccc");
        setTime=setInterval(function(){
            if(time<=0){
                flat = true;
                clearInterval(setTime);
                $(".get_captcha").text("获取验证码");
                $(".get_captcha").css("background-color","#d7000f");
                return;
            }
            time--;
            $(".get_captcha").text(time+'s');
            // $(".get_captcha").css("background-color","#cccccc");
        },1000);
    }
});

function checkInput(){
	var code = $('#captcha').val();
	if(code){
		$('#next').removeClass('cannot_on').addClass('can_on');
	}else{
		$('#next').removeClass('can_on').addClass('cannot_on');
	}
}

function sendCaptcha()
{
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 2;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = '<?php echo $mobile?>';
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
		}
		else
		{
			alert(data.q.d);
		}
	},"json");
}

function checkCaptcha(){
	if($('#next').hasClass('can_on')){
		var code = $('#captcha').val();
		if(!code){
		    alert("请输入验证码");
		    return;
		}
		var json = GetJson('SMSCode');
		json.q.a = 2;
		json.q.type = 2;
		json.q.userId = '<?php echo $_SESSION['user_id']?>';
		json.q.w = new Object();
		json.q.w.code = code;
		json.json = JSON.stringify(json);
		$.post(API_URL,json,function(data)
		{
			if(data.q.s == 0)
			{
				js_go('<?php echo $this->url('web-common',array('controller' => 'user','action' => 'changeMobile'))?>');
			}else{
			    alert(data.q.d);
			}
		},"json");
	}
}
</script>