<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>绑定新的手机号</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="captcha">
    <p class="mb10">请绑定新的手机号</p>
            <div class="captcha_import">
                <span> 手机号码：</span>
               
                <input id="tell" type="text" placeholder="请输入手机号码" maxlength="11">
                
            </div>
            <div class="captcha_import">
                <span> 短信验证：</span>
               
                <input type="text" id="captcha" placeholder="请输入短信验证码" maxlength="4" oninput="checkInput()">
                <a href="javascript:(0);" class="get_captcha">获取验证码</a>
            </div>
   
        <button class="cannot_on" id="finish" onclick="checkCaptcha()">完成</button>

 
    </div>
</body>   
</html>
<script>
var API_URL = '<?php echo API_URL?>';
var flat = true;
$(".get_captcha").on("click",function(){
	var mobile = $('#tell').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return;
	}
	if(flat){
    	sendCaptcha();
    	flat = false;
        var setTime;
        var time=60;
        setTime=setInterval(function(){
            if(time<=0){
            	flat = true;
                clearInterval(setTime);
                 $(".get_captcha").text("获取验证码");
                $(".get_captcha").css("background-color","#d7000f");
                return;
            }
            time--;
            $(".get_captcha").text(time+'s');
            $(".get_captcha").css("background-color","#cccccc");
        },1000);
    }
})

function checkInput(){
	var code = $('#captcha').val();
	if(code){
		$('#finish').removeClass('cannot_on').addClass('can_on');
	}else{
		$('#finish').removeClass('can_on').addClass('cannot_on');
	}
}

function sendCaptcha()
{
	var mobile = $('#tell').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 3;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#tell').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
		}
		else
		{
			alert(data.q.d);
		}
	},"json");
}

function checkCaptcha(){
	if($('#finish').hasClass('can_on')){
		var code = $('#captcha').val();
		if(!code){
		    alert("请输入验证码");
		    return;
		}
		var json = GetJson('SMSCode');
		json.q.a = 2;
		json.q.type = 3;
		json.q.userId = '<?php echo $_SESSION['user_id']?>';
		json.q.mobile = $('#tell').val();
		json.q.w = new Object();
		json.q.w.code = code;
		json.json = JSON.stringify(json);
		$.post(API_URL,json,function(data)
		{
			if(data.q.s == 0)
			{
				history.go(-2);
			}else{
			    alert(data.q.d);
			}
		},"json");
	}
}  
</script>