<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>课程推荐</title>
<style>
    body{
        padding-bottom: 60px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="record bg_white">
        <div class="select_top">
            <a href="javascript:(0);" class="select_on" onclick="getCoursepack(3)">精彩音频</a>
            <a href="javascript:(0);" onclick="getCoursepack(4)">精彩视频</a>
        </div>
        <section>
        <!-- 音频 -->
            <div class="voice_curriculums_list" id="audio_curriculums_list">
                <div class="voice_title">精彩音频列表</div>
                <ul>
                
                </ul>
            </div>            
        <!-- 视频 -->
            <input type="hidden" class="play" id="contrllor">
            <audio id="audio" -webkit-playsinline webkit-playsinline>
                <source src="" />
            </audio>
            <div class="voice_curriculums_list" id="video_curriculums_list" style="display:none">
                <div class="video_title">精彩视频列表</div>
                <ul>
                
                </ul>
            </div>        
        </section>
    </div>
</body>   
</html>
<script>
var finished = false;
var page = 1;
var pack_type = 3;
var current_audio_id = "0";
var play_img = "<?php echo ROOT_PATH;?>webStyle/images/player.png";
var pause_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/audio_pause_white.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'ajaxAddStudyNum'));?>";
getCoursepack(3);
function getCoursepack(pack_type,type = 1){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     pack_type = pack_type;
     var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ajaxGetCoursepack'))?>";
     $.post(url,
    	 {page:page,pack_type:pack_type},
    	 function(data){
  	    	 if(data.code == 200){
  	  	    	  var list = data.list;
  	    		  var dom = $("#tutor_list ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  audio_url = '<?php echo $this->url('web-common', array('controller' => 'audio', 'action' => 'details','type'=>2));?>';
		                  video_url = '<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'details','type'=>2));?>';
		                  move_img = "<?php echo ROOT_PATH;?>webStyle/images/gray_more.png";
		                  var audio_alias = pack_type == 3 ? "音频" : "视频";
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         if(pack_type == 4){
	                        	 li += '<a href="'+video_url+'?id='+v.id+'">';
		                     }
	                         li += '<div  class="cover">';
	                         if(pack_type == 3){
	                        	 li += '<img src="'+v.head_icon+'" alt="">';
	                        	 li += '<img class="player" audio_id="'+v.first_audio_id+'" onclick="play_audio(\''+v.full_path+'\',this)" src="'+play_img+'" alt="">';
	                        	 
		                     }else{
		                    	 li += '<img class="video_image" src="'+v.head_icon+'" alt="">';
		                    	 li += '<img class="player" src="'+play_img+'" alt="">';
		                    	      
			                 }
	                         li += '</div>';
                        	 if(pack_type == 3){
                     		     li += '<a href="'+audio_url+'?id='+v.id+'">';
	                         }
	                         li += '<div class="content">';
	                         li += '<div>'+v.title+'</div>';
	                         li += '<div class="teacher_name"></div>';
	                         li += '<div class="information">';
	                         li += '<div class="sum">总共'+v.audios_num+'个'+audio_alias+'</div>';
	                         li += '<div class="counting"><span class="font_color_055773">'+v.study_num+'</span>人在学</div>';
	                         li += '</div></div><div  class="more">';
	                         li += '<img src="'+move_img+'" alt="">';
	                         li += '</div></a></li>';
	                      });
	                      if(type == 1){
		                      if(pack_type == 3){
		                    	  $('#audio_curriculums_list ul li').remove();
		                      }else{
		                    	  $('#video_curriculums_list ul li').remove();
		                      }
	                      }  
	                      
	                      if(pack_type == 3){
	                    	  $("#audio_curriculums_list ul").append(li);
	                      }else{
	                    	  $("#video_curriculums_list ul").append(li);
	                      }
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
	                		  if(pack_type == 3){
		                    	  $('#audio_curriculums_list ul li').remove();
		                      }else{
		                    	  $('#video_curriculums_list ul li').remove();
		                      }
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                	  if(pack_type == 3){
	                    	  $('#audio_curriculums_list ul li').remove();
	                      }else{
	                    	  $('#video_curriculums_list ul li').remove();
	                      }
	                  }
	              }
     },'json');
}

function play_audio(src,obj){
	var new_audio_id = $(obj).attr('audio_id');
	$('.player').attr('src',play_img);
    if(src){
    	var audio = document.getElementById("audio");
    	if(audio.src != src || new_audio_id != current_audio_id){
    		audio.src = src;
    		current_audio_id = new_audio_id;
    		$("#contrllor").addClass("play");
        }
    	audio.loop = false; //歌曲循环
    	if ($("#contrllor").hasClass("play")) {
    		$("#contrllor").addClass("pause").removeClass("play");
    		audio.play();//开始播放
    		$(obj).attr('src',pause_img);
        }
    	else
    	{
    		$("#contrllor").addClass("play").removeClass("pause");
    	    audio.pause();
    	    $(obj).attr('src',play_img);
        }

    	play_num_deal(current_audio_id);//播放量处理
    }
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getCoursepack(pack_type,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});

$(".record .select_top a").click(function(){
        $(this).addClass('select_on').siblings().removeClass('select_on');
        $('section>div').hide();
        $('section>div').eq($(this).index()).show()
    })
</script>