<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>我的收藏</title>
<style>
    body{
        padding-bottom: 80px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
<div class="bgb"></div>
    <div class="record">
        <div class="select_top bg_white">
            <a href="javascript:(0);" class="select_on" onclick="getFavorite(1,1)">音频课程</a>
            <a href="javascript:(0);" onclick="getFavorite(2,1)">视频课程</a>
        </div>
        <section>
            <!-- 音频 -->
            <div class="voice_curriculums_list" id="audio_curriculums_list">
                <ul class=" bg_white">
                    
                </ul>
        <div class="unrecorded">
        <img src="<?php echo ROOT_PATH;?>webStyle/images/no_favorite.png" alt="">
            <div>还没有我的收藏</div>
        </div>
            </div>            
            <!-- 视频 -->
            <div class="voice_curriculums_list" id="video_curriculums_list" style="display:none">
                <ul class=" bg_white">            
                </ul>
        <div class="unrecorded">
        <img src="<?php echo ROOT_PATH;?>webStyle/images/no_favorite.png" alt="">
            <div>还没有我的收藏</div>
        </div>
            </div> 

        </section>
    </div>

    <div class="affirm_delete">
        <div>是否要清空所有收藏？</div>
        <div>
            <ul>
                <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
                <li><a href="javascript:(0);" class="affirm" id="affirm"><p>确认</p></a></li>
            </ul>
        </div>
    </div>
    <footer class="user_footer">
            <ul>
                <li><a href="javascript:(0);" class="delete"><p>删除</p></a></li>
                <li><a href="javascript:(0);" class="empty"><p>一键清空</p></a></li>
            </ul>
        </footer>
</body>   
</html>
<script>
var t=1;
$(".record .select_top a").click(function(){
        $(this).addClass('select_on').siblings().removeClass('select_on');
        $('section>div').hide();
        $('section>div').eq($(this).index()).show()
        $(".delete").html('删除');
        t=1;
    })

$(".delete").on('click',function(){
    if(t==1){
        $(".voice_curriculums_list li a").addClass('left50');
        $(".delete_blue").show();
        $(".delete").html("完成");
        t=2;
        $(".delete_blue").on('click',function(){
            $(this).parent().children("a").addClass('left-60');
           
            $(this).hide();
            $(this).parent().children(".ultimately_delete").show();
        })
    }else{

        $(".voice_curriculums_list li a").removeClass('left50');
        $(".delete_blue").hide();
        $(".delete").html("删除");
        $(".voice_curriculums_list li a").removeClass('left-60');
        $(".ultimately_delete").hide();
        t=1
    
    }
}) 

$("#affirm").click(function(){
	var user_id = "<?php echo $user_id;?>"
	if($('.select_on').html() == '视频课程'){
		var num = 2;
	}else{
		var num = 1;
	}
	$.post("<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxDeleteFavoriteAll'));?>",{num:num,user_id:user_id},function(result){
		if(result.code == 200){
			if(num == 1){
				audio_dom = $("#audio_curriculums_list ul").remove();
				$("#audio_curriculums_list .unrecorded").show();
			}else{
				video_dom = $("#video_curriculums_list ul").remove();
				$("#video_curriculums_list .unrecorded").show();
			}
		    $(".bgb").hide();
			$(".affirm_delete").hide();
		}
	},'json');
});

$(".empty").on('click',function(){
    $(".bgb").show();
    $(".affirm_delete").show();
})
$(".affirm_delete .cancel").on('click',function(){
    $(".bgb").hide();
    $(".affirm_delete").hide();
})

var finished = false;
var page = 1;
getFavorite(1,1);
function getFavorite(num,type){
	 if (finished && type == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(type == 1){
    	 page = 1;
     }
     finished = true;
	$.post("<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxGetFavoriteList'));?>",{num:num,page:page},function(result){
		$('.londing_gif').hide();
		if(result.length > 0){
			var li = '';
			var video_dom = $("#video_curriculums_list ul");
			var audio_dom = $("#audio_curriculums_list ul");
			$.each(result,function(i,v){
				if(v.type == 3 || v.type == 4){
					li += '<li>';
					li += '<div class="delete_blue"><img src="<?php echo ROOT_PATH;?>webStyle/images/delete_blue.png" alt=""></div>';
				    if(v.type == 3){
				        var url = "<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'details'));?>";
				        url = url+'?id='+[v.audio_id,2]+'&type=2';
				    }else{
    				    var url = "<?php echo $this->url('web-common',array('controller' => 'video','action' => 'details'));?>";
    			        url = url +'?id='+[v.audio_id,1]+'&type=2';
				    }
					li += '<a href="'+url+'">';
					li += '<div class="cover">';
					if(num == 1){
						li += '<img src="'+v.img+'" alt="">';
					}else{
						li += ' <img class="video_image" src="'+v.img+'" alt="">';
					}
					li += '<img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">';
					li += '</div><div class="content"><div>'+v.audio_name+'</div>';
					li += '<div class="information">';// <div class="sum">总共'+v.audio_num+'个音频</div>';
					 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
					li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
					li += '</div></div><div class="more"><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div>';
					li += '</a>';
					li += '<div class="ultimately_delete" id='+v.id+' onclick=ajaxDelete('+v.id+')>删除</div></li>';
				}else if(v.type == 1 || v.type == 2){                     
					li += '<li>';
					li += '<div class="delete_blue"><img src="<?php echo ROOT_PATH;?>webStyle/images/delete_blue.png" alt=""></div>';
					if(v.type == 1){
				        var url = "<?php echo $this->url('web-common',array('controller' => 'Audio','action' => 'details'));?>";
				        url = url+'?id='+[v.audio_id,1]+'&type=1';
				    }else{
    				    var url = "<?php echo $this->url('web-common',array('controller' => 'video','action' => 'details'));?>";
    			        url = url +'?id='+[v.audio_id,1]+'&type=1';
				    }
					li += '<a href="'+url+'">';
					li += '<div  class="cover">';
					if(num == 1){
						li += '<img src="'+v.img+'" alt="">';
					}else{
						li += '<img class="video_image" src="'+v.img+'" alt="">';
					}
					li += '<img class="player" src="<?php echo ROOT_PATH;?>webStyle/images/player.png" alt="">';
					li += '</div>';
					li += '<div class="content">';
					li += '<div>'+v.audio_name+'</div>';
					li += '<div class="teacher_name">'+v.teacher_name;
					if(v.count != "0%"){
                        if(v.count != "100%"){
                       	 li += '<span class="ml40"><span>已播</span><span class=" font_color_055773">'+v.count+'</span></span>';
                        }else{
                       	 li += '<span class="ml40 ">已学完</span>';
                        }
                    }
                    li += '</div>'
                    li += '<div class="information2">';
                    if(v.price == '仅限会员'){
                   	 li += '<div><span class="font_color_055773">'+v.price+'</span></div>';
                    }else{
                   	 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
                    }
                    li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
					li += '</div></div>';
					li += '<div  class="more"><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div></a>';
					li += '<div class="ultimately_delete" id='+v.id+' onclick=ajaxDelete('+v.id+')> 删除 </div></li>';
				}					
			});	
			if(type == 1){
				$("#video_curriculums_list ul li").remove('li');
				$("#audio_curriculums_list ul li").remove('li');
			}
			if(num == 1){
				audio_dom.append(li);
			}else{
				video_dom.append(li);
			}
			$(".user_footer").show()
			finished = false;
            page++;
		}else{
			if(num == 1){
				if($("#audio_curriculums_list ul li").length <= 0){
					$(".user_footer").hide();
					$("#audio_curriculums_list .unrecorded").show();
				}
			}else{
				if($("#video_curriculums_list ul li").length <= 0){
					$(".user_footer").hide()
					$("#video_curriculums_list .unrecorded").show();
				}
			}
		}
	},'json');
	
}

function ajaxDelete(id){
	$.post("<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxDeleteCollect'));?>",{id:id},function(result){
		if(result.code == 200){
			$('#'+id).parent().remove();
		}
	},'json');
	
}
	
function loadmore(obj){    
	if($('.select_on').html() == '视频课程'){
		var num = 2;
	}else{
		var num = 1;
	}
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getFavorite(num,2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});
</script>