<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>

<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">

<title>意见反馈</title>
<style>
    body{

        background-color: #f0f0f5; 
    }
    
    .signature textarea{
        height: 180px;
    }
    .signature span {
        position: absolute;
        top: 195px;
        right: 2%;
        font-size: 1.2rem;
    }
    .signature span div{
        display: inline;
    }
    #submitOk{
        display: none;
        position: fixed;
        left: 50%;
        top: 140px;
        width: 100px;
        height: 30px;
        margin-left: -50px;
        line-height: 30px;
        text-align: center;
        color: #fff;
        background-color: rgba(0,0,0,0.5);
        border-radius: 5px;
        border: 1px solid #585858;
        animation: myfirst 3s;

    }
    @keyframes myfirst
    {
        0% {opacity:0}
        50% {opacity:1}

    }

</style>
<html>
<body>
    <div class="signature">
        <textarea maxlength="300" placeholder="请输入您对我们的意见....."></textarea>
        <span><div>0</div>/300</span>
        <button id="btn">保存</button>
    </div>
     <div id="submitOk" style="">
        <span>提交成功</span>
    </div>
</body>   
</html>
<script>
    //通知标题
    $(".signature textarea").on("input propertychange",function(){
     var t = $(this).val().length;
        if(t>=300){
            t=300;
        }
        $(".signature span div").text(t);
    })
    $('button').click(function(){
        var content = $(".signature textarea").val();
        var user_id = "<?php echo $user_id;?>";
        if(!content){
            alert('反馈内容不能为空！');
            return false;
        }else{
       	 var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'addFeedBack'))?>";
    	   $.post(url,{content:content,user_id:user_id},function(data) {
    		    if(data.code == 400){
        		    alert(data.message);
    		    }else{
    		    	$("#submitOk").show();
    		    	setTimeout("test()",2000); 
    		    }
     	   },'json');
        }
    });
    function test() 
	{ 
    	history.go(-1);
	} 

</script>