<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>账户明细</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
        position: relative;
    }

</style>
<html>
<body>
    <ul class="transaction" id="transaction">
    </ul>
</body>   
</html>
<script>
var finished = false;
var page = 1;
getFinanceList();
function getFinanceList(type){
	 if (finished && type == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ajaxGetFinance'))?>";
     $.post(url,
    	 {page:page},
    	 function(result){
    		 $('.londing_gif').hide();
  	    	 if(result.code == 200){
  	  	    	  var list = result.data;
	              var li = '';            
	                  if (list.length > 0) {
		                  url = '<?php echo $this->url('web-common', array('controller' => 'tutor', 'action' => 'details'));?>'
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         if(v.type == 1){
                        	     var type = v.title;
                        	     li +='<div><img src="'+v.image_path+'" alt="" /></div>'
		                     }else if(v.type == 2){
		                    	 var type =  v.title;
		                    	 li +='<div><img src="'+v.image_path+'" alt="" /></div>'
			                 }else if(v.type == 3){
			                	 var type = '充值';  
			                	 li +='<div><img src="<?php echo ROOT_PATH;?>webStyle/images/wixin_logo.png" alt="" /></div>'
				             }else if(v.type == 4){
					             if(v.pay_type_menber == 1){
					            	 var type = '购买会员'; 
					             }else{
					            	 var type = '赠送会员'; 
					             }
				            	 li +='<div><img src="<?php echo ROOT_PATH;?>adminStyle/images/logo.png" alt="" /></div>'
				             }else if(v.type == 5){
				            	 var type = '领取会员'; 
				            	 li +='<div><img src="<?php echo ROOT_PATH;?>adminStyle/images/logo.png" alt="" /></div>'
				             }else if(v.type == 6){
								 var type = '集团会员充值';
								 li +='<div><img src="<?php echo ROOT_PATH;?>adminStyle/images/logo.png" alt="" /></div>'
							 }else if(v.type == 7){
								 var type = '营销活动充值';
								 li +='<div><img src="<?php echo ROOT_PATH;?>adminStyle/images/logo.png" alt="" /></div>'
							 }else if(v.type == 8){
								 var type = '佣金充值';
								 li +='<div><img src="<?php echo ROOT_PATH;?>adminStyle/images/logo.png" alt="" /></div>'
							 }
	                         li += '<div>';
	                         
	                         li += '<div class="type">'+type+'</div>';
	                         li += '<div>';
	                         li += '<span>'+v.timestamp+'</span></div></div>';
	                         if(v.type == 3 || v.type == 5  || v.type == 6 || v.type == 7 || v.type == 8){
	                        	 li += '<div class="font_color_055773">+'+v.amount+'</div>';
		                     }else{
		                    	 li += '<div>-'+v.amount+'</div>';
			                 }
	                         li += '</li>';
	                      });
	                      if(type == 1){
	                     	 $('#transaction li').remove();
	                      }  
	                      $("#transaction").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#transaction li').remove();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#transaction li').remove();
	                  }
	              }
     },'json');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getFinanceList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});

</script>
