<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>意见反馈通知</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="system_massage" id="system_massage">
        <ul>
        
        </ul>
    </div>
</body>   
</html>
<script>
var finished = false;
var page = 1;
getFeedbackList();
function getFeedbackList(type = 1){
	 if (finished && type == 2) {
         return false;
     }
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ajaxIdeaFeedback'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
  	    	 if(data.code == 200){
  	  	    	  var list = data.data;
  	    		  var dom = $("#system_massage ul");
	              var li = '';            
	                  if (list.length > 0) {
	                      $.each(list,function(i,v){
	                         li += '<li><a href="javascript:void(0)">';
	                         li += '<div class="massage_title">回复：'+v.content+'</div>';
	                         li += '<div class="massage_time mt10">'+v.timestamp+'</div>';
	                         li += '<div class="mt10">'+v.reply+'</div></a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#system_massage ul li').remove();
	                      }  
	                      $("#system_massage ul").append(li);
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#system_massage ul li').remove();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#system_massage ul li').remove();
	                  }
	              }
     },'json');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getFeedbackList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});
</script>