<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<title>我的</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }
    .return_home{
           display:none;
    }
</style>
<html>
<body>
    <div class="bgb"></div>
    <div class="mine">
            <div class="top">
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'userDetails','id' => $data['id']))?>">
                    <div class="portrait_auto">
                        <img class="portrait" src="<?php echo $is_logout ? "/nightbird/public/images/portrait.png" : $data['head_icon'];?>" alt="">  
                    </div>    
                    <div class="name">
                        <?php if(!$is_logout){?><div><?php echo $data['name']?></div><?php }?>
                        <?php if($data['setup']){?>
                            <div><?php echo $data['setup']?></div>
                        <?php }?>                
                    </div>
                 </a>
                 <?php if(!$is_logout){?>
                
                    <?php if($_SESSION['is_vip'] == 1){?>
                       <a style="color:#fff" href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'member'))?>?id=<?php echo $data['id']?>&type=2">
                            <div class="crown member">会员</div>
                       </a>
                    <?php }else{?>
                       <a style="color:#fff" href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'member'))?>?id=<?php echo $data['id']?>&type=1">
                           <div class="member">成为会员</div>
                       </a>
                    <?php }?>
            
               <?php }?>
                <div class="recommend">
                    <span>
                        <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'coursepack'))?>">课程推荐</a>
                    </span>
                    <span>
                        <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ishare'))?>">赚奖学金</a>
                    </span>
                </div>
            </div>
      
        <div class="mine_options">
            <ul>
                <?php if(!$is_logout){?>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'wallet','type' => 1))?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/wallet.png" alt="">
                        </div>
                        <div>我的钱包<span class="money">￥<?php echo $data['amount']?></span></div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <?php }?>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'wallet','type' => 2))?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/wallet.png" alt="">
                        </div>
                        <div>我的佣金<span class="money">￥<?php echo $data['brokerage']?></span></div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'recommend'))?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/take.png" alt="">
                        </div>
                        <div>我的推荐</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <li style="position:relative;">
                    <a href="<?php echo $this->url('web-common',array('controller' => 'tutor','action' => 'subscriptionTutorList'))?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/take.png" alt="">
                        </div>
                        <div>订阅记录
                            <?php if(isset($user['total']) && $user['subscibe_total']>0){?>
                                <span class="message_quantity"><?php echo $user['subscibe_total'];?></span>
                            <?php }?>
                        </div>
                        <div>
                        
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'buyRecord'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/buy_record.png" alt="">
                        </div>
                        <div>购买记录</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'presentRecord'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/give_record.png" alt="">
                        </div>
                        <div>赠送记录</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'favorite'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/collect.png" alt="">
                        </div>
                        <div>我的收藏</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'watchRecord'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/watch_record.png" alt="">
                        </div>
                        <div>观看记录</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>

            </ul>
            <ul>
                <li style="position:relative;">
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'messageInform'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/message.png" alt="">
                        </div>
                        <div>消息通知
                          <?php if(isset($user['total']) && $user['total'] > 0){?>
                            <span class="message_quantity"><?php echo $user['total'];?></span>
                        <?php }?>
                        
                        </div>
                      
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                        
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'accountSet'));?>">
                        <div>
                            <img class="icon" src="<?php echo ROOT_PATH;?>webStyle/images/set.png" alt="">
                        </div>
                        <div>设置</div>
                        <div>
                            <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt="">
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        
    </div>
    <!-- 完善资料 -->
    <div class="perfect_data">
    	<div class="title">
    		可试听,请完善资料
    	</div>
    		<ul class="present_detail">
                <li>
                    <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                </li>
                <li>
                    <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="javascript:(0);" class="gain_verification">获取验证码</a></div>


                </li>
                <li class="select">
                    <a href="javascript:(0);" id="showPicker">
                    <div>职位：
                    <span id='position' position_id="<?php echo $user['current_position_id'] ? $user['current_position_id'] : 0?>">
                      <?php echo $user['position_name']?>
                    </span></div></a>
                </li>
                 <li class="select">
                    <div>地区：<input class="weui_input" type="text" value="广东省 广州市" id='region' style="text-align:right"/></div>
                </li>
            </ul>
            <div>
            <ul class="operation">

                <li><a href="javascript:(0);" class="affirm"><p>完成</p></a></li>
            </ul>
    		</div>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'index','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/home.png" alt=""><p>首页</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'audio','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/voice.png" alt=""><p>音频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'video','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/video.png" alt=""><p>视频</p></a></li>
            <li class=""><a href="javascript:void(0);"><img src="<?php echo ROOT_PATH;?>webStyle/images/mine_on.png" alt=""><p class="select_on">我的</p></a></li>
        </ul> 
    </footer>
</body>   
</html>
<script>
sessionStorage.setItem('url_list', 0);
sessionStorage.setItem('url_audio_list', 0);
$("#region").cityPicker({
   title: "选择省市",
   showDistrict: false,
 }); 
<?php if(!$is_logout){?>
var is_perfect = '<?php echo $is_perfect?>';
var API_URL = '<?php echo API_URL?>';

document.ready = function () {
// 	if(is_perfect <= 0){
// 	    $('.perfect_data').show();
// 	    $('.bgb').show();
// 	}
}
var position = '<?php echo  isset($user['position']) && $user['position'] ? $user['position'] : ""?>'
var content = '<?php echo isset($user['position_id']) && $user['position_id'] ? $user['position_id'] : "";?>';
position = JSON.parse(position);
content = JSON.parse(content);
$('#showPicker').on('click', function () {
    weui.picker(position, {
        id: '#showPicker',
        defaultValue: [6],        
        onChange: function (result) {
        	$(".picker_title").html("选择职位");            	
        },
        onConfirm: function (result) {
           var text = result[0];
           $("#position").html(content[text]);
           $("#position").attr('position_id',text);
        }
    });
});

$('.affirm').click(function(){
	var mobile = $('#mobile').val();
	var captcha = $('#captcha').val();
// 	var region_id = $('#region').attr('region_id');
	var region_id = $("#region").val();
	var position_id = $('#position').attr('position_id');
	if(!mobile){
	    alert('请输入手机号码！');
	    return false;
	}else{
	    if(!isMobile(mobile)){
	        alert('手机号码格式不正确！');
	        return false;
		}
	}
	if(!captcha){
		alert('请输入手机验证码！');
		 return false;
	}
	if(!position_id){
		alert('请选择职位！');
		 return false;
	}
	if(!region_id){
		alert('请选择地区！');
		 return false;
	}

	checkCaptcha();
});

var flat = true;
$(".gain_verification").on("click",function(){
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return false;
	}
	sendCaptcha();
	return false;
	if(flat){
    	sendCaptcha();
    	flat = false;
        var setTime;
        var time=60;
        setTime=setInterval(function(){
            if(time<=0){
            	flat = true;
                clearInterval(setTime);
                 $(".gain_verification").text("获取验证码");
                $(".gain_verification").css("background-color","#d7000f");
                return false;
            }
            time--;
            $(".gain_verification").text(time+'s');
            $(".gain_verification").css("background-color","#cccccc");
        },1000);
    }
})

function sendCaptcha()
{
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
	    alert('请输入正确的手机号码');
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
			var time=60;
	        setTime=setInterval(function(){
	            if(time<=0){
	            	flat = true;
	                clearInterval(setTime);
	                 $(".gain_verification").text("获取验证码");
	                $(".gain_verification").css("background-color","#d7000f");
	                return false;
	            }
	            time--;
	            $(".gain_verification").text(time+'s');
	            $(".gain_verification").css("background-color","#cccccc");
	        },1000);
		}
		else
		{
			alert(data.q.d);
		}
	},"json");
}

function checkCaptcha(){
	var code = $('#captcha').val();
	if(!code){
	    alert("请输入验证码");
	    return;
	}
	var json = GetJson('SMSCode');
	json.q.a = 2;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.q.w = new Object();
	json.q.w.code = code;
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
			var mobile = $('#mobile').val();
// 			var region_id = $('#region').attr('region_id');
			var region_id = $("#region").val();
			var position_id = $('#position').attr('position_id');
			$.post("<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ajaxUpdateUserInfo'));?>",{mobile : mobile,position_id:position_id,region_id:region_id},function(result){
				if(result.code == 200){
					$('.perfect_data').hide();
				    $('.bgb').hide();
				}else{
				    alert(result.message);
				}
			},'json');
		}else{
		    alert(data.q.d);
		}
	},"json");
}
<?php }?>



$(function(){
    pushHistory();
    window.addEventListener("popstate", function(e) {
        var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'index'))?>";
        location.href = url;
    }, false); 
});




$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".home_footer ul li img").css({"margin-bottom":"4px"})
    }

}); 
</script>