
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>我爱分享</title>
<style>
	body{
		margin: 0;
	}

</style>
<html>
<body>
    <img style="width:100%;height:100%" src="<?php echo $data ? $data['img_path'] : "";?>"/>
</body>   
</html>