<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>一起聚餐会员</title>
<style>
    body{
        /*padding-bottom: 90px;*/
        background-color: #f0f0f5; 
        /*font-size: 1.2rem;*/
    }

</style>

<html>
<body>
        <div class="bgb"></div>
        <div class="member_title">
            <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'member'))?>?id=<?php echo $data['id']?>&type=1" class="interests">会员权益</a>
            <div class="head_portrait">
                <img  src="<?php echo ROOT_PATH;?>webStyle/images/nightbird_log.png" alt="">
            </div>
            
            <div><img class="crown" src="<?php echo ROOT_PATH;?>webStyle/images/crown.png" alt=""><span>你已成为会员</span></div>
        </div>
        <ul class="member_valid_time">
            <li>
                <span>开通时间</span>
                <span><?php echo date('Y-m-d',strtotime($data['user']['open_member_time']))?></span>
            </li>
            <li>
                <span>到期时间</span>
                <span><?php echo date('Y-m-d',strtotime($data['user']['member_time']))?></span>
            </li>
        </ul>
        <div class="member_article">
          <?php echo $data['content'];?>
        </div>
        <footer class="audio_footer">
            <ul>
                <li><a href="javascript:(0);" onclick="present_window(2)"><p>送给好友</p></a></li>

                <li><a href="javascript:(0);" onclick="" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt="">已购买</p></a></li>
            </ul>
        </footer>
         <div class="present_window" style="display:none"> 
            <div class="title">
                赠送会员
                <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
            </div>
            <ul class="present_detail">
                <li>
                    <div>赠送人数</div>
                    <div class="quantity">
                        <span class="minus">-</span><span><input type="text" id="edit_num" value="1"></span><span class="add">+</span>
                    </div>
                </li>
                <li>
                    <div>会员单价</div>
                    <div id="price">￥<span><?php echo $data['price']?></span></div>
                </li>
                <li>
                    <div>订单总价</div>
                    <div class="font_color_055773">￥<span></span></div>
                </li>
            </ul>
            <div>
            <ul class="operation">
                <li><a href="javascript:(0);" class="cancel"><p>取消</p></a></li>
                <li><a href="javascript:(0);" class="affirm" onclick = "member(2)"><p>支付订单</p></a></li>
            </ul>
        </div>
        </div>
       <div class="member_pay">
    		<div class="title">
                支付
            <img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
            </div>
            <div>
            	<ul>
            		<li>
            			<div>订单支付价</div>
            			<div>￥<span id="orderPay">9.90</span></div>
            		</li>
            		<a href="<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'wallet'));?>">
            			<li>
            			<div>用户余额</div>
            			<div>￥<span id="residueMoney"><?php echo $data['user']['amount']-$data['user']['freeze_amount']?></span></div>
            			<div><img src="<?php echo ROOT_PATH;?>webStyle/images/gray_more.png" alt=""></div>
            		</li>
            		</a>
            		
            		<li>
            			<div>支付后余额</div>
            			<div class="font_color_055773">￥<span id="orderMessage">9.90</span></div>
            		</li>
            		<li>
            			<button id="butMessage">确认支付</button>
            			<!-- <button>去充值</button> -->
            		</li>
            	</ul>
            </div>
    	</div>
         <div class="pay_success" >
            <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
            <div>支付成功</div>
            <a href="javascript:;">分享赠送链接</a>
        </div>
</body>   
</html>
<script>
$(function(){
	pushHistory();
    window.addEventListener("popstate", function(e) {
    	var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'index'))?>";
    	location.href = url;
    }, false); 
});
var type = 1;
$('.close').click(function(){
	$('.bgb').hide();	
	$('.common_pay').hide();
	$('.member_pay').hide();
});

var recharge_url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'rechargeIndex'));?>";
// function payOrder(num){
// 	$('.bgb').show();	
// 	$('.common_pay').hide();
// 	$(".present_window").hide();
// 	$('.member_pay').show();
// 	$('#orderPay').html($(".font_color_055773>span").html());
// 	if(num == 1){
// 		$('#orderPay').html($("#price>span").html());
// 	}
// 	var order_pay = $('#orderPay').html();
// 	var residueMoney = $('#residueMoney').html();
// 	if(residueMoney-order_pay >= 0){
// 		$("#orderMessage").html(parseFloat(residueMoney-order_pay).toFixed(2));
// 		$("#butMessage").attr('onclick','member()'); //余额支付
// 	}else{
		
// 		$("#orderMessage").html('余额不足');
// 		$("#butMessage").html('<a  class="go_recharge" href='+recharge_url+'>去充值</a>');
	
// 	}
// }


var sub = true;
function member(pay_type){
	$('#orderPay').html($(".font_color_055773>span").html());
	var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxMember'));?>";
	var price = $('#orderPay').html();
	var num = $("#edit_num").val();

	//用户余额
	var amount = "<?php echo $data['user']['amount']?>";
	var freeze_amount = "<?php echo $data['user']['freeze_amount']?>";
	if(amount - freeze_amount >= price){
		//余额支付
		var pay_ment = 2;
	}else{
		//微信支付
		var pay_ment = 1;
	}
// 	console.log(pay_ment);
// 	return false;
	if(sub){
		sub = false;
	}else{
		return false;
	}
	$.post(url,{price:price,type:type,num:num,pay_ment:pay_ment,pay_type:pay_type},function(result){
		if(result.code == 200){
			sub = true;
			$('.present_window').hide();
			$(".bgb").hide();
			if(result.pay_ment == 2){
// 				$('.member_pay').hide();
				$(".pay_success").show();
				var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecordDetail'));?>";
				$('.pay_success>a').attr('href',url+'?id='+result.giv_id+'&type=member');
			}else{
				WeixinJSBridge.invoke(
						'getBrandWCPayRequest',
						result,
						function(res){
							WeixinJSBridge.log(res.err_msg);
							if (res.err_msg.indexOf("ok") != -1) {
//                                 setTimeout("text()",2000); 
// 								$('.member_pay').hide();
								$(".pay_success").show();
								sub = true;
								var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'presentRecord'));?>";
								$('.pay_success>a').attr('href',url+'?type=member');
							}
						}
					);	
				return false;
			}
		}else{
			alert(result.message);
			sub = true;
			return false;
		}
	},'json');
}

present_window = function(id){
	type = id;
    $(".present_window").show();
    $(".bgb").show();
}

$(".present_window .title .close").on("click",function(){
    $(".present_window").hide();
    $(".bgb").hide();
})
$(".present_window .operation .cancel").on("click",function(){
    $(".present_window").hide();
    $(".bgb").hide();
})

// 购买数量加减
$(".present_detail .quantity .add").on("click",function(){
    $(".present_detail .quantity input").val(parseInt($(".present_detail .quantity input").val()) + 1);
    $(".font_color_055773>span").html($("#price>span").html()*$(".present_detail .quantity input").val());
})
$(".present_detail .quantity .minus").on("click",function(){
    if($(".present_detail .quantity input").val()>=2){
        $(".present_detail .quantity input").val(parseInt($(".present_detail .quantity input").val()) - 1);
        $(".font_color_055773>span").html($("#price>span").html()*$(".present_detail .quantity input").val());
    }
    
})
$("#edit_num").keyup(function(){
	if($("#edit_num").val() > 0){
		$(".font_color_055773>span").html($("#price>span").html()*$("#edit_num").val());
	}	
});

$(".font_color_055773>span").html($("#price>span").html()*$("#edit_num").val());


</script>