<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>消息通知</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="message_inform bg_white" id="message_inform">
        <ul>
        
        </ul>

    </div>
        <div class="unrecorded">
        	<img src="<?php echo ROOT_PATH;?>webStyle/images/no_messageInform.png" alt="">
        	<div>还没有消息通知</div>
    	</div> 
</body>   
</html>
<script>
var finished = false;
var page = 1;
getMessageInfoList();
function getMessageInfoList(type){
	 if (finished && type == 2) {
         return false;
     }
	 $('.londing_gif').show();
     if(type == 1){
    	 page = 1;
     }
     finished = true;
     var url = "<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ajaxGetmessageInform'))?>";
     $.post(url,
    	 {page:page},
    	 function(data){
    		 $('.londing_gif').hide();
  	    	 if(data.code == 200){
  	  	    	  var list = data.data;
  	    		  var dom = $("#message_inform ul");
	              var li = '';            
	                  if (list.length > 0) {
		                  var system_massage_url = '<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'systemMassage'))?>';
		                  var feedback_url = '<?php echo $this->url('web-common', array('controller' => 'user', 'action' => 'ideaFeedback'))?>';
		                  var feedback_url_img = '<?php echo ROOT_PATH;?>webStyle/images/idea_feedback.png';
		                  var system_massage_img = '<?php echo ROOT_PATH;?>webStyle/images/system_massage.png';
		                  
	                      $.each(list,function(i,v){
	                         li += '<li>';
	                         if(v.message_type == 1){
	                        	 li += '<a href="'+system_massage_url+'"><div class="cover">';
	                        	 li += '<img src="'+system_massage_img+'" alt=""></div><div class="content">';
	                        	 li += '<div>系统通知</div>';
		                     }else if(v.message_type == 2){
		                    	 li += '<a href="'+feedback_url+'"><div class="cover">';
		                    	 li += '<img src="'+feedback_url_img+'" alt=""></div><div class="content">';
		                    	 li += '<div>意见反馈通知</div>';
			                 }else{
			                	 li += '<a href="'+v.link+'&pid='+v.id+'&types=subscibe"><div class="cover">';
			                	 li += '<img src="'+v.teacher_img+'" alt=""></div><div class="content">';
			                	 li += '<div>'+v.teacher_name+'</div>';
				             }
	                         li += '<div>'+v.title+'</div></div><div class="message_time">';
	                         li += '<div>'+v.timestamp+'</div>'
	                         if(v.message_type == 1){
		                         if(v.notification_num>0){
		                        	 li += '<div class="message_quantity">'+v.notification_num+'</div>';
		                         }
		                     }else if(v.message_type == 2){
			                     if(v.total > 0){
			                    	 li += '<div class="message_quantity">'+v.total+'</div>';
				                 }
			                 }else if(v.message_type == 3){
				                 if(v.is_new == 2){
				                	 li += '<div class="message_quantity">1</div>';
				                 }
			                 }
	                         li += '</div></a></li>';
	                      });
	                      if(type == 1){
	                     	 $('#message_inform ul li').remove();
	                      }  

                    	  $("#message_inform ul").append(li);
	                      
	                      finished = false;
	                      page ++;
	                  }else{
	                	  if(type == 1){
    	                 	 $('#message_inform ul li').remove();
    	                 	 $('.unrecorded').show();
    	                  }
    	              }
	              }
	              else {
	                  if(type == 1){
	                 	 $('#message_inform ul li').remove();
	                  }
	              }
     },'json');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	getMessageInfoList(2);
    }
};
$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});

    $(".content ").width($(window).width()-150);
    $(".content div:nth-child(2)").width($(window).width()-150);

</script>