<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>通知详情</title>
<style>
    body{
        padding-bottom: 90px;
        /*background-color: #f0f0f5; */
    }

</style>
<html>
<body>
    <div class="message_details">
        <div class="message_title">
            新时代餐饮转型与升级的关键
        </div>
        <div class="message_content">
            <div>去年向市安定KIS放假啊首付款家多撒谎开放建行卡圣诞节后付款的煎熬首付款加啊敦煌石窟方哈桑的开奖号卡萨丁付款哈桑的开放后</div>
            <img class="mt15" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
        </div>
    </div>
</body>   
</html>