<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>首页</title>
<style>
    body{

        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="personal_information">
        <ul>
            <li>
                <a href="">
                    <div>头像</div>
                    <div>
                        <img class="head_portrait" src="<?php echo ROOT_PATH;?>webStyle/images/首页轮播.png" alt="">
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="">
                    <div>昵称</div>
                    <div>
                        静水流深
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:(0);" id="showPicker">
                    <div>职位</div>
                    <div>
                        店长
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="">
                    <div>性别</div>
                    <div>
                        男
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="">
                    <div>地区</div>
                    <div>
                        广东 广州
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="">
                    <div>个性签名</div>
                    <div>
                        模样...
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
        </ul>
    </div>
</body>   
</html>
<script>
    $('#showPicker').on('click', function () {

        weui.picker([{
            label: '服务员',
            value: 0
        }, {
            label: '前台',
            value: 1
        }, {
            label: '厨师',
            value: 2
        },{
            label: '店长',

            value: 3
        }, {
            label: '经理',
            value: 4
        }], {
            onChange: function (result) {
                console.log(result);
            },
            onConfirm: function (result) {
                console.log(result);
            }
        });
    });

</script>