<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>一起聚餐</title>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }
    .voice_curriculums_list li .cover img.video_image {
        width: 85px;
    }
</style>
<html>
<body>
 
   <div id="details_banner">
        <div class="bd sl">
            <div class="tempWrap" style="overflow:hidden; position:relative;"><ul style="width: 1500px; position: relative; overflow: hidden; padding: 0px; margin: 0px; transition-duration: 200ms; transform: translate(0px, 0px) translateZ(0px);">
            <?php if($ads){?>
            <?php foreach ($ads as $v){?>
                <li style="display: table-cell; vertical-align: top; width: 375px;"><a href="<?php echo $v['link']?>"><img src="<?php echo ROOT_PATH.UPLOAD_PATH.$v['image'];?>" alt=""></a></li>
            <?php }?>
            <?php }?>
            </ul></div>
        </div>
        <div class="hd">
            <ul style="margin-left: 154.5px;"><li class="on">1</li><li class="">2</li><li class="">3</li><li class="">4</li></ul>
        </div> 
    </div>
    <div class="present_course_title bg_white">
        会员礼包
    </div>
            <div class="voice_curriculums_list bg_white" id="video_curriculums_list">
                <ul>
                    <li>
                        <a href="">
                            <div  class="cover">
                                <img class="video_image" src="<?php echo ROOT_PATH;?>webStyle/images/nightbird_log.png" alt="">
                                
                            </div>
                            <div class="content">
                                <div>一起聚餐会员卡</div>
                                
                                <div class="information">
                                    <div class="sum font_color_055773 course_price">￥<?php echo $data['price']?></div>
                                    
                                </div>
                            </div>
                            <div  class="more">
                              
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
            
            <div class="present_quantity">共
                <span class="font_color_055773"><?php echo $data['num']?></span>
                份,已领取
                <span class="font_color_055773"><?php echo $data['remain_num']?></span>
                份
            </div>
            <?php if(isset($data['courses_list']) && $data['courses_list']){?>     
                <div class="thank_list bg_white">
                    <ul>
                       <?php foreach ($data['courses_list'] as $v){?>
                            <li>
                                <a>
                                    <div class="cover">
                                        <img src="<?php echo $v['user_img_head_icon'];?>" alt="">
                                    </div>
                                    <div class="content">
                                            <div class="mb10"><?php echo $v['user_name'];?></div>
                                            <div class="font_color_gray">谢谢老板么么哒</div>
        
                                    </div>
                                    <div class="thank_time">
                                        <span class="mr10"><?php echo date('Y-m-d',strtotime($v['timestamp']));?></span>
                                        <span class="mr10"><?php echo date('H:i',strtotime($v['timestamp']));?></span>
                                    </div>
                                </a>
                            </li>
                        <?php }?>
                    </ul>
                </div>
             <?php }?>
     <footer class="audio_footer">
        <ul>
            <?php if($data['user_id'] == $_SESSION['user_id']){?>
                <?php if($data['num']-$data['remain_num'] > 0 && in_array($_SESSION['user_id'],$data['user_ids'])){?>
                   <li><a href="javascript:(0);" onclick="sendFriend()"><p><span>送给好友</span></p></a></li>
                   <li><a href="javascript:(0);" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><span>已领取</span></p></a></li>
                <?php }else if($data['num']-$data['remain_num'] == 0 && in_array($_SESSION['user_id'],$data['user_ids'])){?>
                    <li><a href="javascript:(0);" class="received"><p><span>送给好友</span></p></a></li>
                    <li><a href="javascript:(0);" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><span>已领取</span></p></a></li>
                <?php }else if($data['num']-$data['remain_num'] > 0 && !in_array($_SESSION['user_id'],$data['user_ids'])){?>
                     <li><a href="javascript:(0);" onclick="sendFriend()"><p><span>送给好友</span></p></a></li>
                     <li><a href="javascript:(0);" id="getMyBag"><p><span>领取礼包</span></p></a></li>
                <?php }else{?>
                     <li><a href="javascript:(0);" class="received"><p><span>送给好友</span></p></a></li>
                     <li><a href="javascript:(0);" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><span>礼包已领完</span></p></a></li>
                <?php }?>
             <?php }else{?>
                <?php if($data['num']-$data['remain_num'] > 0 && in_array($_SESSION['user_id'],$data['user_ids'])){?>
                    <li><a href="javascript:(0);" class="received"><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><p><span>已领取</span></p></a></li>
                <?php }else if($data['num']-$data['remain_num'] == 0 && in_array($_SESSION['user_id'],$data['user_ids'])){?>
                    <li><a href="javascript:(0);" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><span>已领取</span></p></a></li>
                <?php }else if($data['num']-$data['remain_num'] > 0 && !in_array($_SESSION['user_id'],$data['user_ids'])){?>
                     <li><a href="javascript:(0);" id="getOrderBag"><p><span>领取礼包</span></p></a></li>
                <?php }else{?>
                     <li><a href="javascript:(0);" class="received"><p><img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt=""><span>礼包已领完</span></p></a></li>
                <?php }?>
            <?php }?>
        </ul>
    </footer>
     <!-- 领取成功 -->
    <div class="get_hint" id="div_sub_ok">
        <div>
            <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
            <div>领取成功，获得了好友赠送的<?php echo $data['price']/$data['num'];?>元余额，并可享受多项会员权益！</div>
        </div>
        <div class="affirm">
            <a href="<?php echo $this->url('web-common',array('controller' => 'index','action' => 'index'));?>" id="sub_ok" onclick="sub_ok()">确认</a>
        </div>
    </div>

    <!-- 点击分享 -->
    <div class="get_hint" id="send_sub_ok">
        <div>
            <img src="<?php echo ROOT_PATH;?>webStyle/images/share_gray.png" alt="">
            <div>点击屏幕右上角“...”选择分享给好友来领取。</div>
        </div>
        <div class="affirm">
            <a href="javascript:(0);" onclick="send_sub_ok()">确认</a>
        </div>
    </div>

</body>   
</html>
<script>
adList();
function adList(){
   TouchSlide({slideCell:"#details_banner",
               titCell:".hd ul",
               mainCell:'.bd ul',
               effect:'left',
               autoPlay:true,
               autoPage:true
        });           
   $('.hd ul').css('margin-left',($('.hd').width()-$('.hd ul').width())/2+'px');
}

var draw = true; 

$("#getMyBag").click(function(){
	if(!draw){
		return false;
	}
	draw = false;
	var user_id = "<?php echo $_SESSION['user_id']?>"; //当前用户
	var get_id = "<?php echo $data['id']?>"; //当前记录id->修改get_course
	var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxGetPresentMbmber'));?>";
	$.post(url,{get_id:get_id,user_id:user_id},function(result){
		if(result.code != 200){
			alert(result.message);
			return false;
		}else{
			$("#getMyBag").addClass('received');
			$("#getMyBag>p>span").html('已领取');
             $("#getMyBag>p>span").before('<img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt="">');
			$('#div_sub_ok').show();
			$('.bgb').show();
			draw = false;
			
		}
	},'json');
});

$("#getOrderBag").click(function(){
	if(!draw){
		return false;
	}
	draw = false;
	var user_id = "<?php echo $_SESSION['user_id']?>"; //当前用户
	var get_id = "<?php echo $data['id']?>"; //当前记录id->修改get_course
	var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxGetPresentMbmber'));?>";
	$.post(url,{get_id:get_id,user_id:user_id},function(result){
		if(result.code != 200){
			alert(result.message);
			return false;
		}else{
			$("#getOrderBag").addClass('received');
			$("#getOrderBag>p>span").html('已领取');
            $("#getOrderBag>p>span").before('<img class="already_by" src="<?php echo ROOT_PATH;?>webStyle/images/ed.png" alt="">');
			$('#div_sub_ok').show();
			$('.bgb').show();
			draw = false;
		}
	},'json');
	
});

function sub_ok(){
	$('#div_sub_ok').hide();
	$('.bgb').hide();
	location.reload();
	
}

function send_sub_ok(){
	$('#send_sub_ok').hide();
}

function sendFriend(){
	$('#send_sub_ok').show();
}

//分享设置
</script>