<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<?php if($type == 1){?>
    <title>佣金充值</title>
<?php }else{?>
    <title>佣金提现</title>
<?php }?>
<style>
  body{
    padding-bottom: 30px;
    background-color: #f0f0f5;
    position: relative;
  }
</style>
<html>
<body>
  <div class="bgb" ></div>
  <div class="wallet">
    <div class="rechargeable">
      <?php if($type == 1){?>
        <p>请输入充值到钱包的金额</p>
        <?php }else{?>
          <p>请输入提现金额</p>
        <?php }?>
        <input type="text" class="custom_type" placeholder="输入金额(元)">
        <p style="margin-top: 1rem">当前佣金余额：￥<sapn class="b_price"><?php echo $user['brokerage']?></sapn>元&nbsp;&nbsp;&nbsp;&nbsp;
        <a style="color: #d7000f" href="javascript:;" onclick="allPrice()"><?php if($type == 1){?>全部充值<?php }else{?>全部提现<?php }?></a>
        </p>
    </div>
    <?php if($type == 1){?>
      <button id="recharge" class="recharge_btn"onclick="recharge(<?php echo $type;?>)">充值到钱包</button>
      <p class="recharge_info">佣金充值到钱包后，就可以用于支付课程和会员，学习更多
品牌智慧，但钱包余额不可提现。</p>
    <?php }else{?>
      <button id="recharge" class="recharge_btn" onclick="recharge(<?php echo $type;?>)">提现到微信</button>
      <div class="reacharge__attention">
        <p style="margin: 0.8rem 0">提现说明</p>
        <ul>
          <li>１、请确认是【一起聚餐】会员，即可进行提现操作。</li>
          <li>２、申请成功后，将通过【一起聚餐】公众号下发微信红包，请关注公众号并查收红包</li>
          <li>３、申请提现后，您将在２４小时内收到微信红包，领取即可。</li>
          <li>
            <p>４、如有任何疑问请联系客服</p>
            <p style="text-indent: 2.1rem">电话:１８９２８９２４２３４</p>
            <p style="text-indent: 2.1rem">微信号:ｊｎｘｔ００２</p>
          </li>
        </ul>
      </div>
    <?php }?>
  </div>
<!-- 支付成功 -->
  <div class="one_pay_success" id="one_pay_success" >
    <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
    <?php if($type == 1){?>
      <div>充值到钱包成功</div>
    <?php }else{?>
      <div>提现成功</div>
    <?php }?>
  </div>
 <!-- 试听结束 -->
 <!-- 验证码错误 -->
 <div class="verification_wrong" >
    <div id="contente">您输入的验证码有误！</div>
    <div>
      <ul>
        <li>
          <a href="javascript:(0);"  class="font_color_055773 verification_wrong_close">
            <p>确认</p>
          </a>
        </li>
      </ul>
    </div>
 </div>
 <!-- <div class="verification_choose" >
    <div id="contente2">您输入的验证码有误！</div>
    <div>
      <ul>
        <li class="cancel">
          <a href="javascript:(0);"  class=" verification_choose_close">取消
          </a>
        </li>
        <li class="sure">
          <a href="javascript:(0);"  class="font_color_055773 verification_choose_close">确认
          </a>
        </li>
      </ul>
    </div>
 </div> -->
</body>   
</html>
<script>
var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxRechargeWallet'));?>";
url = url + '/t' + <?php echo $type;?>;
function allPrice(){
    $('.custom_type').val($('.b_price').html())
}
function recharge(){
    var type = "<?php echo $type?>";
    var vip = "<?php echo $_SESSION['is_vip']?>";
    var price = parseFloat($('.custom_type').val());
    if(!price){
        $('.bgb').show();
        if(type == 1){
            $("#contente").html('充值到钱包的金额不能为空');
        }else{
            $("#contente").html('提现的金额不能为空');
        }
        $('.verification_wrong').show();
        return false;
    }
    if(type == 2){
        if(vip != 1){
            $('.bgb').show();
            $("#contente").html('会员才能够提现');
            $('.verification_wrong').show();
            return false;
        }
    }
    if(price > $('.b_price').html()){
        $('.bgb').show();
        if(type == 1){
            $("#contente").html('充值到钱包的金额大于佣金金额');
        }else{
            $("#contente").html('提现的金额大于佣金金额');
        }
        $('.verification_wrong').show();
        return false;
    }
	$.post(url,{price:price},function(result){
		if(result.code == 200){
            $("#one_pay_success").show();
            setTimeout("text()",2000);
        }else{
            $('.bgb').show();
            $("#contente").html(result.msg);
            $('.verification_wrong').show();
            return false;
		}
	},'json');
	
}

function text(){
	$('#one_pay_success').hide();
    location.reload();
}

$('.verification_wrong_close').click(function(){
    $('.verification_wrong').hide();
    $('.bgb').hide();
})

$('.verification_choose_close').click(function(){
    $('.verification_choose').hide();
    $('.bgb').hide();
})

$(document).ready(function(){
    bindKeyEvent($(".custom_type"));
});
function bindKeyEvent(obj){
    obj.keyup(function () {
        var reg = $(this).val().match(/\d+\.?\d{0,2}/);
        var txt = '';
        if (reg != null) {
            txt = reg[0];
        }
        $(this).val(txt);
    }).change(function () {
        $(this).keypress();
        var v = $(this).val();
        if (/\.$/.test(v))
        {
            $(this).val(v.substr(0, v.length - 1));
        }
    });
}

</script>


