<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<title>充值</title>
<style>
    body{
        padding-bottom: 30px;
        background-color: #f0f0f5; 
        position: relative;
    }

</style>
<html>
<body>
       <div class="wallet">
          <div class="head_portrait">
             <img src="<?php echo $user['img_path'] ? ROOT_PATH.UPLOAD_PATH.$user['img_path'] : $user['head_icon'];?>" alt="">
          </div>
          
           <div class="font_color_055773 name"><?php echo $top_up['top_content']?></div>
           <div class="rechargeable">
               <p>现有余额：￥<?php echo $user['amount']?></p>
               <?php if($moneys_array){?>
               <table cellspacing="0">
                <!-- class="on" -->
                   <tr>
                       <?php if($moneys_array[0]){?>
                         <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[0]?>)">￥<span><?php echo (float)$moneys_array[0]?></span></a></td>
                       <?php }?>
                       <?php if($moneys_array[1]){?>
                         <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[1]?>)">￥<span><?php echo (float)$moneys_array[1]?></span></a></td>
                       <?php }?>
                       
                       
                   </tr>
                   <tr>
                       <?php if($moneys_array[2]){?>
                         <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[2]?>)">￥<span><?php echo (float)$moneys_array[2]?></span></a></td>
                       <?php }?>
                       <?php if($moneys_array[3]){?>
                            <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[3]?>)">￥<span><?php echo (float)$moneys_array[3]?></span></a></td>
                        <?php }?>
                   </tr>
                   <tr>
                     <?php if($moneys_array[4]){?>
                       <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[4]?>)">￥<span><?php echo (float)$moneys_array[4]?></span></a></td>
                     <?php }?>
                     <?php if($moneys_array[5]){?>
                       <td><a href="javascript:(0)" onclick="recharge(<?php echo (float)$moneys_array[5]?>)">￥<span><?php echo (float)$moneys_array[5]?></span></a></td>
                     <?php }?>
                   </tr>
               </table>
               <?php }?>
               <input type="text" class="custom_sum" placeholder="其他整数金额(元)" maxlength="11" onkeyup="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" onafterpaste="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}">
               <a href="javascript:;" onclick="recharge(0)" class="sure_custom_sum">确定</a>
           </div>
           <div class="thank"><?php echo $top_up['bottom_content']?></div>
           <br>
           <!-- <button id="recharge" onclick="recharge()">充值</button>  -->
       </div>
      <!-- 支付成功 -->
        <div class="one_pay_success" id="one_pay_success" >
            <img src="<?php echo ROOT_PATH;?>webStyle/images/get_succeed_gray.png" alt="">
            <div>支付成功</div>
        </div>  
</body>   
</html>
<script>
var type = "<?php echo $type;?>"
var url = "<?php echo $url?>";
$("table td").on("click",function(){
    $(this).addClass('on').siblings().removeClass('on');
    $(this).parents().siblings().children().removeClass('on');
})
function recharge(price){
	if(price == 0){
		var price = $('.custom_sum').val();
	}

	var url = "<?php echo $this->url('web-common',array('controller' => 'User','action' => 'ajaxRecharge'));?>";
	$.post(url,{price:price},function(result){
		if(result.code == 200){
			if(result.is_debug == 1){
				  $("#one_pay_success").show();
				   setTimeout("text()",2000); 
			}else{
				WeixinJSBridge.invoke('getBrandWCPayRequest',result,function(res){
							WeixinJSBridge.log(res.err_msg);
							if (res.err_msg.indexOf("ok") != -1) {
                                $("#one_pay_success").show();
                                setTimeout("text()",2000); 
							}
						}
					);	
				return false;
			}
		}else{
// 			alert(result.message);
			return false;
		}
	},'json');
	
}
function text(){
	$('#one_pay_success').hide();
	var type = "<?php echo $type;?>"
    if(type == 1){
    	location.href = url;
    }else{
    	location.reload();
    }
}

wx.ready(function(){
   shareData = {title: '一起聚餐 | 中国5000万餐饮人的学习平台',desc: '学习改变命运 | 让餐饮赞美生命',imgUrl: '<?php echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>webStyle/images/nightbird_log.png'};
   share(shareData);
});



$(".custom_sum").keyup(function(){
  if($(".custom_sum").val()==""){
    $(".sure_custom_sum").hide();
       $(".custom_sum").css("font-size","1.4rem");
  }
  else{
    $(".sure_custom_sum").show();
       $(".custom_sum").css("font-size","2rem");
  }
});


</script>


