<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>

<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">

<title>地区</title>
<style>
    body{

        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="region">
        <div class="title">当前位置</div>
        <div class="bg_white site location" id="loca_name"><?php echo isset($_SESSION['location']) && $_SESSION['location'] ? $_SESSION['location'] : ""?></div>
        <div class="title">全部</div>
        <div class="bg_white site">
            <span>中国</span>
            <span style="color: black"></span>
            <span class="fr">已选地区</span>
        </div>
        <ul class="bg_white" id="bg_white">
        </ul>
    </div>
</body>   
</html>
<script>
var type = '<?php echo isset($type) ? $type : 0?>';
getRegion();
function getRegion(){
	var deep = 1;
    var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxGetRegion'))?>";
    $.post(url,{deep:deep},function(result) {
        var dom = $('#bg_white');
        var li = '';
        if(result.list.length > 0){
            $.each(result.list,function(i,v){
            	li += "<li class="+v.id+">"+v.name+"</li>"
            });
            dom.append(li);
            $("ul li").unbind("click").on("click",function(){
                var v=$(this).html();            
                $(".site span:nth-child(2)").html(v);
                var son_url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'sonRegion'))?>";
                id = $(this).attr('class');
                location.href = son_url+"?id="+id+"&type="+type;
            })
        }
    },'json');
}

var location_name = $('.location').html();
var id = 0;
$('#loca_name').click(function(){
	if(location_name == '定位失败'){
		return false;
	}
	var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAddRegion'))?>";
	var go_url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'userDetails','id'=>$_SESSION['user_id']))?>";
	$.post(url,{id:id,location_name:location_name},function(result) {
	   if(result.code == 200){    	        	
	   	var ua = navigator.userAgent.toLowerCase();	
		     	if (/iphone|ipad|ipod/.test(ua)) {
		   	     	location.href = go_url;
		     		$(function(){
		     		    pushHistory(); 
		     		    window.addEventListener("popstate", function(e) {
		     		    	location.href = go_url;      
		     		    }, false); 
		     		});
		     	} else if (/android/.test(ua)) {
		   	     	history.go(-1);
		     	}
	   }
	},'json');
});


</script>