<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>

<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">

<title>首页</title>
<style>
    body{

        background-color: #f0f0f5; 
    }
.toolbar{
    font-size: 1.2rem;
}
</style>
<html>
<body>
    <div class="signature">
        <textarea maxlength="30"><?php echo $data['signature'] ? $data['signature'] : ""?></textarea>
        <span>30</span>

        <button>保存</button>
    </div>
</body>   
</html>
<script>
    $(function(){
 	    pushHistory(); 
        window.addEventListener("popstate", function(e) {
        	var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'userDetails','id'=>$_SESSION['user_id']))?>";
        	location.href = url;      
        }, false); 
    });
    var t = $(".signature textarea").val().length;
    $(".signature span").text(30-t);
    //通知标题
    $(".signature textarea").on("input propertychange",function(){
        t = $(this).val().length;
        if(t>=30){
            t=30;
        }
        $(".signature span").text(30-t);
    })
    
    $("button").click(function(){
 	   var text = $(".signature textarea").val();
 	   if(!text){
 	 	   alert('签名不能为空');
 	 	   return false;
 	   }else{
 	 	  var id = "<?php echo $data->id?>";
          var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAmendUser'))?>";
      	   $.post(url,{id:id,text:text,type:4},function(data) {
          	   if(data.code == 200){
            		 history.go(-1);
            		
          	   }else{
              	   alert(data.message);
          	   }
      	   },'json');
 	   }
    });
</script>