<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jqsession.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">

<title>地区</title>
<style>
    body{

        background-color: #f0f0f5; 
    }

</style>
<html>
<body>
    <div class="region">
        <div class="title">当前位置</div>
        <div class="bg_white site location" id="loca_name"><?php echo isset($_SESSION['location']) && $_SESSION['location'] ? $_SESSION['location'] : ""?></div>
        <div class="title">全部</div>
        <div class="bg_white site">
            <span>中国</span>
            <span style="color: black"><?php echo $data['parent_name']?></span>
            <span style="color: black"></span>
            <span class="fr">已选地区</span>
        </div>
        <ul class="bg_white" id="bg_white">
            <?php foreach ($data['list'] as $v){?>
                <li class="<?php echo $v['id'];?>"><?php echo $v['name']?></li>
            <?php }?>
        </ul>
    </div>
</body>   
</html>
<script>

var type = '<?php echo isset($type) ? $type : 0?>';
$("ul li").unbind("click").on("click",function(){
    var v = $(this).html();            
    $(".site span:nth-child(3)").html(v);
   	var id = $(this).attr('class');
   	var region_name = $(".site span:nth-child(2)").html()+" "+$(".site span:nth-child(3)").html();
   	if(type == 1){
    	$.session.set('region_name', region_name);
    	$.session.set('region_id', id);
       	history.go(-2);
   	}else{
   		var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAddRegion'))?>";
   		var go_url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'userDetails'))?>";
   	    $.post(url,{id:id},function(result) {
   	        if(result.code == 200){    	        	
   	        	var ua = navigator.userAgent.toLowerCase();	
   	   	     	if (/iphone|ipad|ipod/.test(ua)) {
   	   	   	     	location.href = go_url;
   	   	     	} else if (/android/.test(ua)) {
   	   	   	     	history.go(-2);
   	   	     	}
   	        }
   	    },'json');
    }
})

$('#loca_name').click(function(){
	var location_name = $('.location').html();
	var id = 0;
	if(location_name == '定位失败'){
		return false;
	}
	var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAddRegion'))?>";
	var go_url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'userDetails','id'=>$_SESSION['user_id']))?>";
	$.post(url,{id:id,location_name:location_name},function(result) {
	   if(result.code == 200){    	        	
	   	var ua = navigator.userAgent.toLowerCase();	
		     	if (/iphone|ipad|ipod/.test(ua)) {
		   	     	location.href = go_url;
		     		$(function(){
		     		    pushHistory(); 
		     		    window.addEventListener("popstate", function(e) {
		     		    	location.href = go_url;      
		     		    }, false); 
		     		});
		     	} else if (/android/.test(ua)) {
		   	     	history.go(-2);
		     	}
	   }
	},'json');
});

</script>