<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<?php if($type == 1){?>
    <title>用户帮助</title>
<?php }else{?>
    <title>功能介绍</title>
<?php }?>
<style>
    body{
        padding-bottom: 90px;
        background-color: #f0f0f5; 
    }
    .about_nightbird{

    padding-top: 0px;
}
</style>
<html>
<body>
    <div class="about_nightbird">
        <div class="seek">
            <div class="issue_import">
                <div>
                    <input type="text" id="context" placeholder="请输入内容">
                    <img class="seek_empty" src="<?php echo ROOT_PATH;?>webStyle/images/seek_empty.png" alt="">
                </div> 
            </div>
        </div>
        <div class="enter_seek" style = "display:none">
            <ul class="bg_white" >
            </ul>
        </div>
        <div class="hot_issue">
            <p>热点问题</p>
            <ul class="bg_white">
               <?php if($data){?>
                    <?php foreach ($data as $v){?>
                         <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'introduce','type' => $type,'id'=> $v['id']));?>">
                            <li class="go">
                                <?php echo $v['title'];?>
                            </li>
                        </a>
                    <?php }?>
               <?php }?>
            </ul>
        </div>
    </div>
</body>   
</html>
<script>
$("input").keyup(function(){
   var content = $(this).val();
   var type = "<?php echo $type;?>"
   if(!content){
	   $('.enter_seek').hide();
		$(".hot_issue").show();
		return false;
   }else{
	   var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'userHelp'))?>";
	   $.post(url,{content:content,type:type},function(data) {
	      $('.enter_seek .bg_white a').remove();
		  var li = '';
		  var url = "<?php echo $this->url('web-common',array('controller' => 'user','action' => 'introduce','type' => $type));?>";
		  $.each(data.list,function(i,v){
			  li += '<a href="'+url+'?id='+v.id+'">';
			  li += ' <li class="go">'+v.title+'</li>';
			  li += '</a>';
		  });
		  $('.enter_seek').show();
		  $('.enter_seek .bg_white').append(li);
 	   },'json');
	   $(".hot_issue").hide();
   }
   
   
});

$(".seek_empty").click(function(){
	$("input").val('');
	$(".hot_issue").show();
	$('.enter_seek').hide();
});

</script>