<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/mobileBUGFix.mini.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/uploadImage.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/uploadPicture/exif.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jqsession.js"></script>
<title>个人信息</title>
<style>
    body{

        background-color: #f0f0f5; 
    }
.toolbar{
    font-size: 1.2rem;
}
</style>
<html>
<body>
    <div class="personal_information">
        <ul>
            <li>
                <a href="javascript:;">
                    <div>头像</div>
                    <div>
                        <span class="head_portrait_auto">
                            <img id="show_image_1" class="head_portrait" src="<?php echo  isset($data['head_icon']) && $data['head_icon'] ? $data['head_icon'] :'/images/portrait.png';?>" alt="">
                        </span>
                        
                        <div style="display: none;">
                        <input type="hidden" id="img_id_1" name="img_id" value="<?php if(isset($data['head_icon']) && $data['head_icon']){echo $data['head_icon'];} ?>" />
                        <input id="imgPath" type="hidden" name="img_path" value="<?php if(isset($data['head_icon']) && $data['head_icon']){echo $data['head_icon'];} ?>"/>
                        <input type="file" accept="image/*" id="uploadImage"
                            onchange="selectFileImage(this);" hidden />
                    </div>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'changeName','id' => $data['id']))?>">
                    <div>昵称</div>
                    <div>
                       <?php echo $data['name']?>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:(0);" id="showPicker">                    
                    <div>职位</div>
                    <div id="position">
                       <?php echo $data['position_name']?>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="javascript:(0);" id="sex">
                    <div>性别</div>
                    <div id="son_sex">
                         <?php if($data['sex'] == 1){?>男<?php }else{?>女<?php }?>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'region'))?>">
                    <div>地区</div>
                    <div>
                        <?php echo $data['region']?>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'changeName','id' => $data['id'],'type' => 2))?>">
                    <div>个性签名</div>
                    <div id="signature_omit">
                        <?php echo $data['signature'] ? $data['signature'] : "未填写"?>
                    </div>
                    <div>
                        <img class="more" src="<?php echo ROOT_PATH;?>webStyle/images/black_more.png" alt="">
                    </div>
                </a>
            </li>
        </ul>
    </div>
</body>   
</html>
<script>
    $(function(){
    	pushHistory();
        window.addEventListener("popstate", function(e) {
        	var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'index'))?>";
        	location.href = url;
        }, false); 
    });
    var id = "<?php echo $data['id']?>";
    var position = '<?php echo  isset($data['position']) && $data['position'] ? $data['position'] : ""?>'
    var content = '<?php echo $data['position_id'] ? $data['position_id'] : "";?>';
    var sex = '<?php echo $data['selset_sex'] ? $data['selset_sex'] : "";?>';
    position = JSON.parse(position);
    content = JSON.parse(content);
    sex = JSON.parse(sex);
    $('#showPicker').on('click', function () {
        weui.picker(position, {
            id: '#showPicker',
            defaultValue: [6],
            onChange: function (result) {
            	$(".picker_title").html("选择职位");            	
            },
            onConfirm: function (result) {
               var text = result[0];
               var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAmendUser'))?>";
          	   $.post(url,{id:id,text:text,type:1},function(data) {
              	   if(data.code == 200){
                  	   $("#position").html(content[text]);
              	   }else{
//                   	   alert(data.message);
              	   }
          	   },'json');
            }
        });
    });

    $('#sex').on('click', function () {
        weui.picker([{
            label: '男',
            value: 1
        }, {
            label: '女',
            value: 2
        }], {
            id: '#sex',
            defaultValue: [1],
            onChange: function (result) {
            	$(".picker_title").html("选择性别")
            	
            },
            onConfirm: function (result) {              
               var text = result[0];
               console.log(sex);
               var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAmendUser'))?>";
           	   $.post(url,{id:id,text:text,type:2},function(data) {
               	   if(data.code == 200){
                 		 $("#son_sex").html(sex[text]);
               	   }else{
//                    	   alert(data.message);
               	   }
           	   },'json');
            }
        });
    });
    
    var upload_url = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'uploadImage'));?>'; // uploadImage.js
    $("#show_image_1").click(function(){
       $("#uploadImage").click();
    });
    function uploadimages(num,path){
	  var url = "<?php echo $this->url('web-common', array('controller' => 'User', 'action' => 'ajaxAmendUser'))?>";
  	  $.post(url,{id:id,text:num,type:5,path:path},function(data) {
    	   if(data.code == 200){
        	   return;
    	   }else{
//         	   alert(data.message);
    	   }
        
	   },'json');
      show_image();

    }
    wx.ready(function(){
         getLocation();

    });
    function getLocation(){
        wx.getLocation({
            type: 'gcj02', // 默认为wgs84的gps坐标，如果要返回直接给openLocation用的火星坐标，可传入'gcj02'
            success: function (res) {
                var params = {};
                params.latitude = res.latitude; // 纬度，浮点数，范围为90 ~ -90
                params.longitude = res.longitude; // 经度，浮点数，范围为180 ~ -180。
                params.speed = res.speed; // 速度，以米/每秒计
                params.accuracy = res.accuracy; // 位置精度

                $.post('<?php echo $this->url('web-common',array('controller'=>'User','action' => 'getLocationInfo'))?>', params, function (data){
                    if(data.code == 200){
                        console.log(data.location);
                    }else{
                        console.log(data.location);
                    }
                },'json')
            }
        });
    }
    function show_image(){
        if($("#show_image_1").width()>$("#show_image_1").height()){
                $("#show_image_1").height(64);
                $("#show_image_1").css("width","auto");
                
        }
        else{
                $("#show_image_1").css("height","auto");
                $("#show_image_1").width(64);
        }
    }

</script>