<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/mine.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<title>我的钱包</title>
<style>
    body{
        padding-bottom: 60px;
        background-color: #f0f0f5; 
        position: relative;
    }

</style>
<html>
<body>
       <div class="wallet">
        <div class="head_portrait">
              <img src="<?php echo $data['img_path'] ? ROOT_PATH.UPLOAD_PATH.$data['img_path'] : $data['head_icon'];?>" alt="">
          </div>
         
           
               <div class="balance">￥<?php echo $data['amount']?></div>
               <button onclick=window.location.href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'rechargeIndex'))?>">充值</button>
                <div class="account_explain">
                    <div class="title">账户说明</div>
                    <div>
                      <?php echo $data['account_content'];?>
                    </div>
                </div>
               
           
       </div>
       <a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'finance'))?>" class="bill">账户明细</a>
</body>   
</html>