<link href="<?php echo $this->basePath() . '/adminStyle/css/basis.css'?>" rel="stylesheet" type="text/css">
<style type="text/css">
	.tab_menu li.on {
		background-color: #0099CC;
		color: #fff;
		border-color: #0099CC;
	}
	.tab_menu li.on a{
	   color: #fff;
	}
    #box{
    	border:0px;
    	width:100%;
    	height:900px;
    }
</style>
<body>
    <article class="manage-box">
    	<h1>内容列表</h1>
    	<header class="tab_menu">
    		<ul>
    		<?php $role = $_SESSION['role_nb_admin_manage'];
				if($role == 'all' || count(array_diff(array('ContentList-videoList'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'videoList'));?>" target="box"><li class="on">音频课程</a></li>
    			<?php } if($role == 'all' || count(array_diff(array('ContentList-videoList2'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'videoList2'));?>" target="box">视频课程</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('ContentList-coursesList'), $role)) < 1){?>	
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'coursesList'));?>" target="box">课程包</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('ContentList-teacherList'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'teacherList'));?>" target="box">觉鸟导师</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('Ads-relation'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'Ads', 'action' => 'relation'));?>" target="box">轮播图</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('Ads-todayAds'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'Ads', 'action' => 'todayAds'));?>" target="box">今日推荐</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('System-sendWord'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'System', 'action' => 'sendWord'));?>" target="box">用户寄语</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('ContentList-share'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'share'));?>" target="box">分享设置</a></li>
    			<?php  } if($role == 'all' || count(array_diff(array('ContentList-sensitiveWords'), $role)) < 1){?>
    				<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'sensitiveWords'));?>" target="box">敏感词管理</a></li>
    			<?php } if($role == 'all' || count(array_diff(array('ContentList-homePageSetting'), $role)) < 1){?>
					<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'homePageSetting'));?>" target="box">首页设置</a></li>
				<?php } if($role == 'all' || count(array_diff(array('ContentList-search'), $role)) < 1){?>
					<li><a href="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'search'));?>" target="box">搜索词配置</a></li>
				<?php }?>
    		</ul>
    	</header>
    </article>
    <div class="tab_box">
    	  <iframe src="<?php echo $this->url('admin', array('controller'=> 'ContentList', 'action' => 'videoList','a_type' => 1));?>" name="box" id="box">
    	  </iframe>
    </div>
</body>

<script type="text/javascript">
    var tourl = $.cookie("tourl");
    $.cookie('tourl', 'aqymarks' , { path: '/', expires: -1 }); 
    if(tourl=="aqymarks"){
		$(".tab_menu ul li:eq(1)").addClass("on").siblings().removeClass("on");  
		$(".tab_box > section").eq(1).show().siblings().hide();	
    }
	$(function(){
		$(".tab_menu ul li").click(function(){
			$(this).addClass("on").siblings().removeClass("on");  
			$(".tab_box > section").eq($(this).index()).show().siblings().hide(); 
		});
	});
	<?php if($id){?>
	var obj = $(".tab_menu ul li").eq(<?php echo $id?>).html();
	$(".tab_box iframe").attr('src',$(obj).attr('href'));
	$(".tab_menu ul li:eq("+'<?php echo $id?>'+")").addClass("on").siblings().removeClass("on");  
	<?php }?>
</script>