<?php
namespace Admin\Model;
/**
* 图片
*
* @author 系统生成
*
*/
class ImageGateway extends BaseGateway {
    /**
    *主键、自动增长
    */
    public $id;

    /**
     * 图片名称
     */
    public $name;

    /**
    *
    */
    public $md5;

    /**
    *文件名，时分秒_四位随机数（如：131452_1234.png）
    */
    public $filename;

    /**
    *目录，由日期组成（如：201305/20/）
    */
    public $path;

    /**
    *
    */
    public $width;

    /**
    *
    */
    public $height;

    /**
    *
    */
    public $count;

    /**
    *字段数组
    */
    protected $columns_array = ["id","md5","filename","path","width","height","count","delete","timestamp"];

    public $table = DB_PREFIX . 'image';

    public function addData()
    {
        return parent::addData(); // TODO: Change the autogenerated stub
    }

    /**
     * 通过MD5查询图片是否存在
     */
    public function getMd5()
    {
        $where = array("md5"=>$this->md5);
        return $this->getOne($where);
    }

    /**
     * 字段更新
     * @param number $id
     * @param number $income
     * @param string $key
     * @param float $value
     */
    public function updateKey($id, $income, $key, $value)
    {
        parent::updateKey($id, $income, $key, $value);
    }

}