<?php
namespace Admin\Model;
use Zend\Db\Sql\Where;

/**
* 短信验证码
*
* @author 系统生成
*
*/
class SmsCodeGateway extends BaseGateway {
    /**
    *主键、自动增长
    */
    public $id;

    /**
    *移动电话
    */
    public $mobile;

    /**
    *短信验证码（随机生成6位数字）
    */
    public $code;

    /**
    *ip地址
    */
    public $ip;

    /**
    *网页session或者移动端session
    */
    public $sessionId;

    /**
    *验证状态：0未验证；1已验证 2发送失败
    */
    public $status;

    /**
    *类型：1注册；2重新绑定手机；
    */
    public $type;

    /**
    *失效时间。默认+10分钟
    */
    public $expire;

    /**
    *短信下发次数统计
    */
    public $count;

    /**
    *会员id
    */
    public $userId;

    /**
    *字段数组
    */
    protected $columns_array = ["id","mobile","code","ip","session","status","type","expire","count","userId","delete","timestamp"];

    public $table = DB_PREFIX . 'sms_code';

    /**
     * @param $start_time
     * @param $end_time
     * @return mixed
     * 查询某段时间，同一IP/或同一sessionId发送验证码次数
     */
    public function getSendCount($start_time,$end_time)
    {
        $where = new Where();
        if($this->ip)
        {
            $where->equalTo('ip', $this->ip);
        }
        elseif($this->sessionId)
        {
            $where->equalTo('session_id',$this->sessionId);
        }

        $where->between('timestamp', $start_time, $end_time);
        $res = $this->fetchAll($where);
        return $res['total'];
    }

    /**
     * 获取某段时间内是否发送过短信及验证短信
     */
    public function getSendCode()
    {
        $where = array('mobile' => $this->mobile, 'type' => $this->type);
        if($this->status !== null){
            $where['status'] = $this->status;
        }
        return $this->getOne($where);
    }

    public function addData()
    {
        return parent::addData(); // TODO: Change the autogenerated stub
    }
}