<?php
use Core\System\WxApi\WxApi;
?>
<!DOCTYPE html>
    <html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">
    <?php //echo $this->headtitle();?>
</head>
<script>
    var user=(navigator.userAgent).toLocaleLowerCase(),isWeixin=false,ht="",hta="",addressObj,shareData,touchState=true;
    <?php
    if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger') && in_array(WX_IOSENV, array(1,2))) {
    @$jssdk = new WxApi();
    @$signPackage = $jssdk->wxJsapiPackage();
    ?>
</script>
    <script type="text/javascript" src="<?php echo $this->basepath()?>/webStyle/js/jweixin-1.2.0.js"></script>
    <script type="text/javascript" src="<?php echo $this->basepath()?>/webStyle/js/jquery.min.js"></script>
<script>
    /*使用微信*/
    var wx_WEIXIN_APP_ID="<?php echo $signPackage['appId'];?>";
    var wx_timestamp="<?php echo $signPackage['timestamp'];?>";
    var wx_nonceStr="<?php echo $signPackage['nonceStr'];?>";
    var wx_signature="<?php echo $signPackage['signature'];?>";
    var wx_num=0;
    /*shareData 下的参数*/
    $(document).ready(function() {
        getJssdk();

    });

    wx.ready(function(){
        shareData = {title: '一起聚餐丨凝聚餐饮品牌智慧',desc: '让品牌落地餐厅丨提升全员品牌素养，成为品牌代言人',imgUrl: '<?php echo 'http://'.$_SERVER['HTTP_HOST'].ROOT_PATH?>webStyle/images/nightbird_log.png'};
        share(shareData);
    });

    function getJssdk()
    {
        $('.notouchmove').bind({touchstart:function(e){touchState=true;},touchmove:function(e){touchState=false;}});
        /*判断是否在微信打开*/
        var user=(navigator.userAgent).toLocaleLowerCase(),isWeixin=false,ht="",hta="",addressObj,shareData,touchState=true;
        if(user.indexOf('micromessenger')!==-1)
        {
            isWeixin=true;
            wx.config({
                debug: false,
                appId: wx_WEIXIN_APP_ID,
                timestamp: wx_timestamp,
                nonceStr: wx_nonceStr,
                signature: wx_signature,
                jsApiList: [
                    'checkJsApi',
                    'onMenuShareTimeline',
                    'onMenuShareAppMessage',
                    'onMenuShareQQ',
                    'onMenuShareWeibo',
                    'openLocation',
                    'hideAllNonBaseMenuItem',
                    'hideMenuItems',
                    'previewImage',
                    'getLocation',
                    'startRecord',
                    'stopRecord',
                    'translateVoice',
                    'chooseWXPay',
                    'playVoice',
                    'uploadVoice',
                    'downloadVoice'
                ]
            });         
        }
        else{
            isWeixin=false;
            console.log("this isn't weixin");
        }
    }

    function share(shareData){
 	     wx.onMenuShareAppMessage(shareData);
	     wx.onMenuShareTimeline(shareData);
	     wx.onMenuShareQQ(shareData);
	     wx.onMenuShareWeibo(shareData);
    }

<?php }?>
</script>
<style>
    .more-img div,#autoInsertWapper_u2648773_1,#y_g_g {
        display:none;
    }
</style>
<?php echo $this->content;?>
<body>
    <div class="londing_gif" >
        <img src="<?php echo ROOT_PATH;?>webStyle/images/londing.gif" alt="">
    </div>
    <a href="<?php echo $this->url('web-common',array('controller' => 'index','action' => 'index'));?>" class="return_home">
        <img src="<?php echo ROOT_PATH;?>webStyle/images/return_home.png" alt="">
        <span>回到首页</span>
    </a>
</body>
</html>
<script>
     $(".londing_gif").show();
      window.onload=function(){
            $(".londing_gif").hide();
            // alert(1);

            if($(".portrait").width()>$(".portrait").height()){
                $(".portrait").height(75);
                $(".portrait").css("width","auto");
            }
            if($(".member_title .head_portrait img").width()>$(".member_title .head_portrait img").height()){
                $(".member_title .head_portrait img").height(80);
                $(".member_title .head_portrait img").css("width","auto");
            }
            if($(".wallet .head_portrait img").width()>$(".wallet .head_portrait img").height()){
                    $(".wallet .head_portrait img").height(80);
                    $(".wallet .head_portrait img").css("width","auto");
            }    
            if(typeof(show_image) == "function"){
                show_image();
            }
            
       }
       function head_portrait(){
            $(".other_information .comment .title .head_portrait_auto img").each(function(){
                if($(this).width()>$(this).height()){
                    $(this).height(40);
                    $(this).css("width","auto");
                }  
            }); 
        }   

       function pushHistory() { 
	        var state = { 
	            title: "title", 
	            url: "#"
	        }; 
	        window.history.pushState(state, "title", "#"); 
	    } 
</script>
