<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(PRODUCT_NAME . '管理'. $this->translate('后台'))->setSeparator(' - ')->setAutoEscape(false);?>
    <?php echo $this->headMeta()
        ->appendName('description', 'RemoteSystemsTempFiles')
        ->appendName('author', 'aiitec') ?>

    <!-- Le styles -->
    <?php // array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/adminStyle/img/favicon.ico')
    echo $this->headLink()
        ->appendStylesheet($this->basePath() . '/adminStyle/css/bootstrap-cerulean.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/bootstrap-responsive.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/charisma-app.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery-ui-1.8.21.custom.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/fullcalendar.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/fullcalendar.print.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/chosen.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/uniform.default.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/colorbox.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.cleditor.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.noty.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/noty_theme_default.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/elfinder.min.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/elfinder.theme.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/jquery.iphone.toggle.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/opa-icons.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/uploadify.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/template/css/date/jedate.css')
        ->appendStylesheet($this->basePath() . '/adminStyle/css/base.css')
    ?>
    <!--Date CSS-->
    <!-- The styles -->

    <style type="text/css">
        body{margin:0;padding:0}
        .sidebar-nav {
            padding: 9px 0;
        }
    </style>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Scripts -->
    <?php echo $this->headScript()->offsetSetFile(1,$this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->offsetSetFile(2,$this->basePath() . '/adminStyle/js/jquery-1.7.2.min.js')
        ->offsetSetFile(3,$this->basePath() . '/adminStyle/js/jquery.uploadify.js')
        ->offsetSetFile(4,$this->basePath() . '/adminStyle/js/swfobject.js')
        ->offsetSetFile(5,$this->basePath() . '/adminStyle/js/jquery-ui-1.8.21.custom.min.js')
        ->offsetSetFile(6,$this->basePath() . '/adminStyle/js/bootstrap-transition.js')
        ->offsetSetFile(7,$this->basePath() . '/adminStyle/js/bootstrap-alert.js')
        ->offsetSetFile(8,$this->basePath() . '/adminStyle/js/bootstrap-modal.js')
        ->offsetSetFile(9,$this->basePath() . '/adminStyle/js/bootstrap-dropdown.js')
        ->offsetSetFile(10,$this->basePath() . '/adminStyle/js/bootstrap-scrollspy.js')
        ->offsetSetFile(11,$this->basePath() . '/adminStyle/js/bootstrap-tab.js')
        ->offsetSetFile(12,$this->basePath() . '/adminStyle/js/bootstrap-tooltip.js')
        ->offsetSetFile(13,$this->basePath() . '/adminStyle/js/bootstrap-popover.js')
        ->offsetSetFile(14,$this->basePath() . '/adminStyle/js/bootstrap-button.js')
        ->offsetSetFile(15,$this->basePath() . '/adminStyle/js/bootstrap-typeahead.js')
        ->offsetSetFile(16,$this->basePath() . '/adminStyle/js/bootstrap-tour.js')
        ->offsetSetFile(17,$this->basePath() . '/adminStyle/js/jquery.cookie.js')
        ->offsetSetFile(18,$this->basePath() . '/adminStyle/js/fullcalendar.min.js')
        ->offsetSetFile(19,$this->basePath() . '/adminStyle/js/jquery.dataTables.min.js')

        ->offsetSetFile(20,$this->basePath() . '/adminStyle/js/jquery.chosen.min.js')
        ->offsetSetFile(21,$this->basePath() . '/adminStyle/js/jquery.uniform.min.js')
        ->offsetSetFile(22,$this->basePath() . '/adminStyle/js/jquery.colorbox.min.js')
        ->offsetSetFile(23,$this->basePath() . '/adminStyle/js/jquery.cleditor.min.js')
        ->offsetSetFile(24,$this->basePath() . '/adminStyle/js/jquery.noty.js')
        ->offsetSetFile(25,$this->basePath() . '/adminStyle/js/jquery.elfinder.min.js')
        ->offsetSetFile(26,$this->basePath() . '/adminStyle/js/jquery.raty.js')
        ->offsetSetFile(27,$this->basePath() . '/adminStyle/js/jquery.iphone.toggle.js')
        ->offsetSetFile(28,$this->basePath() . '/adminStyle/js/jquery.autogrow-textarea.js')
        //->appendFile($this->basePath() . '/adminStyle/js/jquery.uploadify-3.1.min.js')
        ->offsetSetFile(29,$this->basePath() . '/adminStyle/js/jquery.history.js')
        ->offsetSetFile(30,$this->basePath() . '/adminStyle/js/charisma.js')

        //公共js
        ->offsetSetFile(31,$this->basePath() . '/js/public.js')
    ?>

</head>
<body>
    <?php echo $this->content;?>
</body>
</html>
<!--Date JS-->
<script src="<?php echo ROOT_PATH."adminStyle/template/";?>js/date/jedate.min.js"></script>
<script>
    /**
     * Date part
     */
    jeDate({
        dateCell: '#inpo',
        format:"YYYY-MM-DD hh:mm",//YYYY-MM-DD hh:mm:ss
        minDate: '2016-01-01 00:00:00',
        maxDate: '2099-12-31 00:00:00',
        isTime:true,
    });
    var start = {
        dateCell: '#inpstart',
        format:"YYYY-MM-DD",
        minDate: '2013-01-01 00:00:00',
        festival:true,
        maxDate: jeDate.now(0),
        isTime: true,
        choosefun: function(datas){
            end.minDate = datas;
        }
    };
    var end = {
        dateCell: '#inpend',
        minDate: '2013-01-01 00:00:00',
        festival:true,
        format:"YYYY-MM-DD",
        isTime: true,
        choosefun: function(datas){
            start.maxDate = datas;
        }
    };
    jeDate(start);
    jeDate(end);

</script>