<style>
   .form-group label{
       width:100px;
    }
    .form-horizontal>div{
        margin-left: 22px !important;
    }
</style>
<div class="page-header">
    <h1>
        修改密码
    </h1>
</div>
<!-- div.table-responsive -->

<!-- div.dataTables_borderWrap -->
<div>
    <form class="form-horizontal" id="form" action="<?php echo $this->url('admin', ['action'=>'changePassword']) ?>" method="post">
        <div class="form-group">
            <label style="font-size: 16px;font-weight: bold;" class="col-sm-1 control-label"> 修改密码</label>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right"> 旧密码：</label>

            <div class="col-sm-9">
                <input type="password" name="oldpassword" required class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right"> 新密码：</label>

            <div class="col-sm-9">
                <input type="password" id="password" name="password" required class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label no-padding-right"> 确认密码：</label>

            <div class="col-sm-9">
                <input type="password" name="repassword" id="repassword" required class="col-xs-10 col-sm-5">
            </div>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
                <button class="btn btn-info" type="submit" name="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>

                &nbsp; &nbsp; &nbsp;
                <a class="btn" onclick="window.history.back()">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    取消
                </a>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('#form').submit(function (e) {
        var password = $('#password').val();
        var password2 = $('#repassword').val();
        if(password != password2){
            showMessage("两次密码输入不一致！",0);
            return false;
        }
        ajaxForm(e);
    })
</script>