<script src="<?php echo $this->basePath() . '/adminStyle/js/highcharts.js'?>"></script>
<script src="<?php echo $this->basePath() . '/adminStyle/js/exporting.js'?>"></script>
<script src="<?php echo $this->basePath() . '/adminStyle/js/highcharts-zh_CN.js'?>"></script>
<style>
select{width: 190px}
</style>

<div class="page-header">
    <h1>
        数据统计
    </h1>
</div>
<div class="row">
    <div style="margin-left: 30px;margin-bottom: 20px;font-weight: bold;font-size: 16px">统计范围</div>
</div>
<form action="">
    <div class="layui-form-item">
        <div class="layui-inline">
            <label class="layui-form-label" style="width:110px;">商家统计：</label>
            <div class="layui-input-inline">
                <select name="mType">
                    <option value="0">全部</option>
                    <option <?php if ($mType == 2) echo 'selected'?> value="2">自营商城</option>
                    <option <?php if ($mType == 1) echo 'selected'?> value="1">加盟商家</option>
                </select>
            </div>
            <div class="layui-input-inline">
                <select name="merchantId">
                    <option value="">全部商家</option>
                    <?php foreach ($merchantList as $v){?>
                        <option value="<?php echo $v->id?>" <?php if($v->id == $merchantId) echo 'selected' ?>><?php echo $v->name?></option>
                    <?php }?>
                </select>
            </div>
        </div>
        <div class="layui-inline">
            <label class="layui-form-label" style="width:110px;">社区统计：</label>
            <div class="layui-input-inline">
                <select name="province" id="province">

                </select>
            </div>
            <div class="layui-input-inline">
                <select name="city" onchange="AreaBind()" id="city">
                    <option value="">城市</option>
                </select>
            </div>
            <div class="layui-input-inline">
                <select name="area" id="area">
                    <option value="">社区</option>
                </select>
            </div>
        </div>
        <div class="layui-inline">
            <label class="layui-form-label" style="width:110px;">销售渠道：</label>
            <div class="layui-input-inline">
                <select name="from" >
                    <option value="0">全部销售渠道</option>
                    <option <?php if ($from == 1) echo 'selected'?> value="1">手机网站</option>
                    <option <?php if ($from == 2) echo 'selected'?> value="2">PC网站</option>
                    <option <?php if ($from == 3) echo 'selected'?> value="3">app</option>
                    <option <?php if ($from == 4) echo 'selected'?> value="4">微信端</option>
                </select>
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="space-6"></div>
    <div style="margin-left: 30px;margin-bottom: 20px;font-weight: bold;font-size: 16px">基本数据</div>
    <div class="col-sm-7 infobox-container" style="width: 100%">

        <div class="infobox infobox-green center" >
            <div class="infobox-data">
                <div class="infobox-content center">今日注册用户</div>
                <span class="infobox-data-number center"><?php echo $userTodayCount?></span>
            </div>
        </div>

        <div class="infobox infobox-blue center">
            <div class="infobox-data">
                <div class="infobox-content center">用户数</div>
                <span class="infobox-data-number center"><?php echo $userTotal?></span>
            </div>
        </div>

        <div class="infobox infobox-pink center">
            <div class="infobox-data">
                <div class="infobox-content center">今日认证业主</div>
                <span class="infobox-data-number center"><?php echo $mTodayCount?></span>
            </div>
        </div>

        <div class="infobox infobox-red center">
            <div class="infobox-data">
                <div class="infobox-content center">认证业主总数</div>
                <span class="infobox-data-number center"><?php echo $mTotal?></span>
            </div>
        </div>

        <div class="infobox infobox-orange2 center">
            <div class="infobox-data">
                <div class="infobox-content center">今日订单数</div>
                <span class="infobox-data-number center"><?php echo $oTodayCount?></span>
            </div>
        </div>

        <div class="infobox infobox-blue2 center">
            <div class="infobox-data">
                <div class="infobox-content center">本月订单总数</div>
                <span class="infobox-data-number center"><?php echo $oTotal?></span>
            </div>
        </div>

        <div class="infobox infobox-green center">
            <div class="infobox-data">
                <div class="infobox-content center">今日营业额</div>
                <span class="infobox-data-number center"><?php echo round($orderTodaySum,2)?></span>
            </div>
        </div>

        <div class="infobox infobox-green center">
            <div class="infobox-data">
                <div class="infobox-content center">本月营业总额</div>
                <span class="infobox-data-number center"><?php echo round($orderMonthSum,2)?></span>
            </div>
        </div>

        <div class="space-6"></div>
    </div>

</div><!-- /.row -->

<div class="hr hr32 hr-dotted"></div>

<div class="row">
    <div style="margin-left: 30px;margin-bottom: 20px;font-weight: bold;font-size: 16px">数据统计</div>
    <div class="col-sm-7" style="width: 100%">
        <div class="widget-box transparent">
            <div class="widget-body">
                <div class="widget-main padding-4">
                    <div id="container"></div>
                </div><!-- /.widget-main -->
            </div><!-- /.widget-body -->
        </div><!-- /.widget-box -->
    </div><!-- /.col -->
</div><!-- /.row -->
<script>
    var chart = new Highcharts.Chart('container', {
        title: {
            text: '营业额',
            x: -20
        },
        xAxis: {
            categories: <?php echo $data['category']?>
        },
        yAxis: {
            title: {
                text: '金额 (元)'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: '元'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: '营业额',
            data: [<?php echo $data['data']?>]
        }],
        credits:{
            enabled:false // 禁用版权信息
        }
    });
</script>
<script>
    var p = '<?php echo $province?>';
    var c = '<?php echo $city?>';
    var a = '<?php echo $area?>';
    $(function () {
        //默认绑定省
        ProviceBind();
        if(p){
            CityBind();
        }
        if(c){
            AreaBind();
        }
        //绑定事件
        $("#province").change( function () {
            var proId = $('#province').val();
            if(proId==820000){
                AreaBind();
            }else{
                CityBind();
            }
        });
    });
    function ProviceBind() {
        //清空下拉数据
        $("#province").html("");
        var str = "<option value=''>省份</option>";
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('platform-store',['action'=>'getAreaInfo'])?>",
            data: { "parentId": 1,"deep":1,"type":1},
            dataType: "JSON",
            async: false,
            success: function (data) {
                //console.log(typeof(data));return false;
                //从服务器获取数据进行绑定
                $.each(data, function (i, item) {
                    if(item.id == p){
                        str += "<option value='" + item.id + "' selected >" + item.name + "</option>";
                    }else{
                        str += "<option value='" + item.id + "'>" + item.name + "</option>";
                    }
                })
                //将数据添加到省份这个下拉框里面
                $('#province').append(str);
            },
            error: function (res) {
                console.log(res);
            }
        });
    }
    function CityBind() {
        var provice = $("#province").val();
        //判断省份这个下拉框选中的值是否为空
        if (provice == "") {
            $("#city").html("<option>城市</option>");
            $('#area').html('<option value="">社区</option>')
            return;
        }
        $("#city").html("<option value=''>城市</option>");
        var str = '';
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('platform-store',['action'=>'getAreaInfo'])?>",
            data: { "parentId": provice,"deep":2,"type":1 },
            dataType: "JSON",
            async: false,
            success: function (data) {
                //从服务器获取数据进行绑定
                if(data.total!=0){
                    $.each(data, function (i, item) {
                        if(item.id == c){
                            str += "<option value='" + item.id + "' selected >" + item.name + "</option>";
                        }else{
                            str += "<option value='" + item.id + "'>" + item.name + "</option>";
                        }
                    })
                    //将数据添加到省份这个下拉框里面
                    $("#city").append(str);
                }else{
                    $('#area').html('<option value="0">社区</option>');
                }
            },
            error: function (res) {
                alert('error');
                console.log(res);
            }
        });
    }
    function AreaBind() {
        var province = $('#province').val();
        var city = $("#city").val();
        if(province==820000){
            $("#city").html("<option value=''>城市</option>");
            city = province;
        }
        //判断市这个下拉框选中的值是否为空
        if (city == "") {
            $('#area').html('<option value="">社区</option>')
            return;
        }
        $('#area').html('<option value="">社区</option>')
        var str = '';
        //将市的ID拿到数据库进行查询，查询出他的下级进行绑定
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('platform-store',['action'=>'getAreaInfo'])?>",
            data: { "parentId": city, "deep": 4,"type":2 },
            dataType: "JSON",
            async: false,
            success: function (data) {
                //从服务器获取数据进行绑定
                if(data.total!=0){
                    $.each(data, function (i, item) {
                        if(item.id == a){
                            str += "<option value='" + item.id + "' selected >" + item.name + "</option>";
                        }else{
                            str += "<option value='" + item.id + "'>" + item.name + "</option>";
                        }
                    })
                    //将数据添加到省份这个下拉框里面
                    $("#area").append(str);
                }
            },
            error: function () { alert("Error"); }
        });
    }
    $('select').change(function () {
        var selName = $(this).attr('name');
        var mType = $('select[name="mType"]').val();
        if(selName == 'mType'){
            var merchantId = '';
        }else{
            var merchantId = $('select[name="merchantId"]').val();
        }
        var province = $('select[name="province"]').val();
        var city = province?$('select[name="city"]').val():'';
        var area = city?$('select[name="area"]').val():'';
        var from = $('select[name="from"]').val();
        var url = '<?php echo $this->url('platform',['action'=>'index']) ?>'
        window.location.href = url+'?mType='+mType+'&merchantId='+merchantId+'&province='+province+'&city='+city+'&area='+area+'&from='+from;
    })
</script>