<script src="<?php echo $this->basePath() . '/adminStyle/js/activity-pie.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/adminStyle/js/activity-pie2.js' ?>"></script>
<style>
    .select {
        border:1px solid #ccc;
        border-radius: 3px;
        width:115px;
    }
    .title-top div.con{
        border: 1px solid green;
        width: 16%;
        text-align: center;
        font-size: 22px;
        display: inline-block;
        margin-top: 15px;
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .title-top div.margin{
        margin-left:4.5%;
    }
    .select-top {
        border:1px solid #ccc;
        border-radius: 3px;
        width:115px;
    }
    .box-content span{line-height:25px;}

    .detail_href{
        float: right;
        font-size: 16px;
    }
    .detail_href a{
        color: #000000;
        cursor: hand;
        margin-right: 10px;
    }
</style>

<ul class="breadcrumb">
    <li><span>主页</span></li>
    <!--     <span class="divider">/</span><li> <a href="#">评论列表</a></li> -->
</ul>
<!--<select name="count_type" id="count_type">-->
<!--    <option value="1">用户统计</option>-->
<!--    <option value="2">财务统计</option>-->
<!--</select>-->
<div class="pannel-body" id="type_user">
    <div class="box-content">
        <legend class="lg_title">
            <span>今天实时 （更新时间：<?php echo date('Y-m-d H:i:s');?>）：</span>
            <span class="detail_href">
                <a href="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>?type=1">访客数详情</a>
                <a href="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>?type=2">浏览量详情</a>
                <a href="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>?type=3">下单用户详情</a>
                <a href="<?php echo $this->url('admin', array('controller' =>'Detail', 'action' => 'index'));?>?type=4">页面浏览总量</a>
            </span>
        </legend>
        <div class="title-top">
            <div class="con" ><div><?php echo $count['visitors'];?></div><br/><div style=" font-size: 14px;">今天访客数</div></div>
            <div class="con" ><div><?php echo $count['browse'];?></div><br/><div style=" font-size: 14px;">今天浏览量</div></div>
            <div class="con" ><div><?php echo $count['userCount'];?></div><br/><div style=" font-size: 14px;">今天下单用户</div></div>
            <div class="con" ><div><?php echo $count['user_total'];?></div><br/><div style=" font-size: 14px;">用户总数量</div></div>
            <div class="con" ><div>￥<?php echo $total['sum']?$total['sum'] : '0.00';?></div><br/><div style=" font-size: 14px;">今日收入（元）</div></div>
            <div class="con" ><div>￥<?php echo $total['sum_total']?$total['sum_total'] : '0.00';?></div><br/><div style=" font-size: 14px;">总收入（元）</div></div>
            <div class="con" ><div><?php echo $count['unbinding_browse'];?></div><br/><div style=" font-size: 14px;">浏览用户数(未绑定手机)</div></div>
            <div class="con" ><div><?php echo $count['user_vip_total'];?></div><br/><div style=" font-size: 14px;">用户数(已绑定手机)</div></div>
            <div class="con" ><div><?php echo $count['userCount'];?></div><br/><div style=" font-size: 14px;">消费用户</div></div>
            <div class="con" ><div><?php echo $count['user_vip'];?></div><br/><div style=" font-size: 14px;">会员数</div></div>
            <div class="con" ><div><?php echo $total['member_total_income']?$total['member_total_income']:0;?></div><br/><div style=" font-size: 14px;">会员贡献的收入</div></div>
            <div class="con" ><div><?php echo $total['user_total_come']?$total['user_total_come']:0;?></div><br/><div style=" font-size: 14px;">非会员贡献的收入</div></div>
            <div class="con" ><div><?php echo $total['member_class_consumption']?$total['member_class_consumption']:0;?></div><br/><div style=" font-size: 14px;">会员消费课程的金额</div></div>
            <div class="con" ><div><?php echo $total['consumption']?$total['consumption']:0;?></div><br/><div style=" font-size: 14px;">非会员消费课程的金额</div></div>
            <div class="con" ><div><?php echo $count['user_recom_total'] ? $count['user_recom_total']:0;;?></div><br/><div style=" font-size: 14px;">分销注册数</div></div>
            <div class="con" ><div><?php echo $count['user_recom_price'] ? $count['user_recom_price']:0;;?></div><br/><div style=" font-size: 14px;">分销总佣金</div></div>
        </div>
        <legend class="lg_title" style="margin-top: 27px;">
        </legend>
    </div>

    <div class="row">
        <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'Index', 'action' => 'index','types'=>$types));?>">
            <div class="pull-left ml8"  style="margin-left: 10%;width: 20%;">
                <div class="btn-group marginTB-xs form-remind" style="display:inline-block;margin-left: 15px;">
                    <select class="select-top"  name="cid" size="1" id="select" style="width: 100%;height: 30px;">
                        <option value="1" <?php echo $cid==1 ?'selected="selected"' : '';?>>浏览用户数(未绑定手机)</option>
                        <option value="2" <?php echo $cid==2 ?'selected="selected"' : '';?>>用户数(已绑定手机)</option>
                        <option value="3" <?php echo $cid==3 ?'selected="selected"' : '';?>>消费用户</option>
                        <option value="4" <?php echo $cid==4 ?'selected="selected"' : '';?>>会员数</option>
                        <option value="5" <?php echo $cid==5 ?'selected="selected"' : '';?>>会员贡献的收入</option>
                        <option value="6" <?php echo $cid==6 ?'selected="selected"' : '';?>>非会员贡献的收入</option>
                        <option value="7" <?php echo $cid==7 ?'selected="selected"' : '';?>>会员消费课程的金额</option>
                        <option value="8" <?php echo $cid==8 ?'selected="selected"' : '';?>>非会员消费课程的金额</option>
                        <option value="9" <?php echo $cid==9 ?'selected="selected"' : '';?>>分销注册统计</option>
                    </select>
                </div>
            </div>
            <div class="pull-left ml8">
                <span style="margin-left:20px;">查询日期：</span>
                <input type="text" id="inpstart" class="input-medium" name="start" value="<?php echo $start; ?>">&nbsp;至&nbsp;
                <input type="text" id="inpend" class="input-medium" name="end" value="<?php echo $end; ?>">
                <button type="submit" class="btn btn-info submit">统计</button>
            </div>
            <div class="pull-right">
                <div class="pull-left ml8" >
                    <a href="<?php echo $this->url('admin', array('controller' =>'Index', 'action' => 'index','cid'=>$cid,'types'=>24));?>" class="btn <?php echo $types==24?'btn-primary':'';?>">今天</a>
                    <a href="<?php echo $this->url('admin', array('controller' =>'Index', 'action' => 'index','cid'=>$cid,'types'=>7));?>" class="btn <?php echo $types==7?'btn-primary':'';?>">7天</a>
                    <a href="<?php echo $this->url('admin', array('controller' =>'Index', 'action' => 'index','cid'=>$cid,'types'=>30));?>" class="btn <?php echo $types==30?'btn-primary':'';?>">30天</a>
                </div>
            </div>
        </form>
        <!--     </div> -->
    </div>
    <div class="sortable row-fluid">

        <a data-rel="tooltip" class="well span12 top-block">
            <div id="add" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        </a>
    </div>
    <!--     			</div> -->
    <!-- 			</div> -->
</div>

<script type="text/javascript">
    $(".form-remind").change(function(){
        $(".form-horizontal").submit();
    });

    $('#count_type').change(function(){
        var countType= ($(this).children('option:selected').val());
        if(countType == 1){
            window.location.href="/admin/Index";
        }else{
            window.location.href="/admin/Count";
        }
    })

    $(function () {
        $(document).ready(function () {

            $('#add').highcharts({
                title: {
                    text: '统计图',
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: [<?php echo $data['data'];//$date = array();for($i = $types; $i >= 0; $i --){$date[] = date('m-d', strtotime('-'.$i.' day'));}echo "'".implode("','", $date)."'";?>]
                },
                yAxis: {
                    title: {
                        text: '数量 (<?php echo $title;?>)'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    valueSuffix: '<?php echo $title;?>'
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth:0
                },
                series: [{
                    name: '<?php echo $arr[$cid];?>',
//                     1,3,4,5,3,3,3
                    data: [<?php foreach ($data['array'] as $k=>$v) {echo isset($list[$v]) ? $list[$v].',' : 0 .',';}?>]
                }]
            });
        });
    });
</script>
