<style>
	.knowledge a{
		display: inline-block;
		width: 240px;
		height: 200px;
		border: 1px solid #ccc;
		margin: 0 10px;
		text-align: center;
		font-size: 16px;
		color: black;
	}
	.knowledge a img{
		margin-top: 50px;
		margin-bottom: 50px;
	}
	.knowledge .title{
		height: 50px;
		line-height: 50px;
		font-size: 16px;
	}
</style>


	<div id="content" class="span10">
	<!-- content starts -->		
		<div>
			<ul class="breadcrumb">
				<li>
					<span style="color:#369bd7;">新增内容</span>
				</li>
			</ul>
			<div class="knowledge">
				<div class="title">新增知识内容</div>
				<div>
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'addVideo', 'a_type'=>1, 'add'=>1));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/voice.png" alt="">
						<div>音频</div>
					</a>
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'addVideo', 'a_type'=>2, 'add'=>1));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/video.png" alt="">
						<div>视频</div>
					</a>
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'addCoures', 'add'=>1));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/course_packs.png" alt="">
						<div>课程包</div>
					</a>
					<a href="<?php echo $this->url('admin', array('controller' =>'ContentList', 'action' => 'teacherDetails', 'add'=>1));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/tutor.png" alt="">
						<div>觉鸟导师</div>
					</a>
				</div>
			</div>
			<div class="knowledge">
				<div class="title">新增运营内容</div>
				<div>
					<a href="<?php echo $this->url('admin', array('controller' =>'ads', 'action' => 'relationDetails', 'add'=>1));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/carousel.png" alt="">
						<div>轮播图</div>
					</a>
					<a href="<?php echo $this->url('admin', array('controller' =>'Manage', 'action' => 'contentList','types'=>6));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/wishes.png" alt="">
						<div>用户寄语</div>
					</a>
					<a href="<?php echo $this->url('admin', array('controller' =>'Manage', 'action' => 'contentList','types'=>7));?>">
						<img src="<?php echo $this->basepath();?>/adminStyle/images/share.png" alt="">
						<div>分享设置</div>
					</a>
	
				</div>
			</div>
		</div>
	</div>
			

			
			
			
			
			
			
			
			
			