<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>平台管理后台登录</title>

		<meta name="description" content="User login page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/adminStyle/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/adminStyle/font-awesome/4.5.0/css/font-awesome.min.css" />

		<!-- text fonts -->
		<link rel="stylesheet" href="/adminStyle/css/fonts.googleapis.com.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/adminStyle/css/ace.min.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/adminStyle/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="/adminStyle/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/adminStyle/css/ace-ie.min.css" />
		<![endif]-->

		<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/adminStyle/js/html5shiv.min.js"></script>
		<script src="/adminStyle/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body class="login-layout blur-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								<h1>
									<!-- <i class="ace-icon fa fa-leaf green"></i>
									<span class="red">2017</span> -->
									<span class="white" id="id-text2">平台管理后台登录</span>
								</h1>
								<h4 class="blue" id="id-company-text">&copy; 爱侗乡</h4>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="ace-icon fa fa-coffee green"></i>
												请输入您的用户名和密码
											</h4>

											<div class="space-6"></div>

											<form action="<?php echo $this->url('admin', ['action'=>'login']) ?>" method="post" id="form">
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="text" id="admin_name" name="name" value="<?php echo $adminName;?>" required class="form-control" placeholder="请输入登录账号" />
															<i class="ace-icon fa fa-user"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" name="password" required class="form-control" placeholder="请输入登录密码" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>
<!--                                                    --><?php //if(array_key_exists('login_error_time',$_SESSION)&& $_SESSION['login_error_time']>=3){?>
                                                    <label class="block clearfix">
														<span class="inline-block input-icon input-icon-right">
															<input type="text" id="checkCode" name="checkCode" required class="form-control" style="width:100%" placeholder="请输入图形验证码" />
														</span>
                                                        <img style="width:32%;height:35px;display: inline;" src="<?php echo $checkCode?>" alt="" onclick="changeCode()" id="checkCodeImage">
                                                    </label>
<!--                                                    --><?php //}?>
                                                    <label class="block clearfix" style="position: relative;">
														<span class="block input-icon input-icon-right">
                                                            <label class="inline">
                                                            <input type="checkbox" checked="checked" class="ace" name="remember" value="1"/>
                                                            <span class="lbl"> 记住用户名</span>
                                                        </label>
<!--                                                            <a href="--><?php //echo $this->url('admin', ['action'=>'passRetrieval']) ?><!--" class="text-right" style="position: absolute;right: 0;">忘记密码？</a>-->
														</span>
                                                    </label>

													<div class="clearfix">
														<button class="width-35 btn btn-sm btn-primary" style="margin-left: 35%;">
															<i class="ace-icon fa fa-key"></i>
															<span class="bigger-110">登录</span>
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form>
											<div class="space-6"></div>
										</div><!-- /.widget-main -->
									</div><!-- /.widget-body -->
								</div><!-- /.login-box -->
							</div><!-- /.position-relative -->

<!--							<div class="navbar-fixed-top align-right">-->
<!--								<br />-->
<!--								&nbsp;-->
<!--								<a id="btn-login-dark" href="#">Dark</a>-->
<!--								&nbsp;-->
<!--								<span class="blue">/</span>-->
<!--								&nbsp;-->
<!--								<a id="btn-login-blur" href="#">Blur</a>-->
<!--								&nbsp;-->
<!--								<span class="blue">/</span>-->
<!--								&nbsp;-->
<!--								<a id="btn-login-light" href="#">Light</a>-->
<!--								&nbsp; &nbsp; &nbsp;-->
<!--							</div>-->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script src="/adminStyle/js/jquery-2.1.4.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="/adminStyle/js/jquery-1.11.3.min.js"></script>
<![endif]-->
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='/adminStyle/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
        <script src="/plugins/layui/layui.js"></script>
        <script src="/plugins/layui/layui_component.js"></script>
        <script src="/js/ajaxSubmit.js"></script>
        <script>
            var err = 0;
            $('#form').submit(function (e) {
                e.preventDefault();
                var index = showLoad();
                var form = e.target;
                $(form).find('button[type="submit"]').attr('type', 'button');
                $.ajax({
                    url:form.action,
                    type:'post',
                    data:$(form).serializeArray(),
                    dataType:'json',
                    success: function (rs) {
                        if(rs.status == 0) {
                            err = err+1;
                            layer.close(index);
                            showMessage(rs.error_msg, 0);
                            $(form).find('button[type="button"]').attr('type', 'submit');
                            if(err > 2){
                                window.location.reload();
                            }
                            return;
                        }
                        if(rs.status == 1) {
                            layer.close(index);
                            if (rs.msg){
                                showMessage(rs.msg, 1);
                            }
                        }
                        if(rs.redirect) {
                            setTimeout(function () {
                                location.href = rs.redirect;
                            }, 700);
                        }
                    },
                    error: function () {
                        layer.close(index);
                        $(form).find('button[type="button"]').attr('type', 'submit');
                        showMessage('服务器请求错误', 2);
                    }
                });
            })
        </script>
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			jQuery(function($) {
			 $(document).on('click', '.toolbar a[data-target]', function(e) {
				e.preventDefault();
				var target = $(this).data('target');
				$('.widget-box.visible').removeClass('visible');//hide others
				$(target).addClass('visible');//show target
			 });
			});
			
			
			
			//you don't need this, just used for changing background
			jQuery(function($) {
			 $('#btn-login-dark').on('click', function(e) {
				$('body').attr('class', 'login-layout');
				$('#id-text2').attr('class', 'white');
				$('#id-company-text').attr('class', 'blue');
				
				e.preventDefault();
			 });
			 $('#btn-login-light').on('click', function(e) {
				$('body').attr('class', 'login-layout light-login');
				$('#id-text2').attr('class', 'grey');
				$('#id-company-text').attr('class', 'blue');
				
				e.preventDefault();
			 });
			 $('#btn-login-blur').on('click', function(e) {
				$('body').attr('class', 'login-layout blur-login');
				$('#id-text2').attr('class', 'white');
				$('#id-company-text').attr('class', 'light-blue');
				
				e.preventDefault();
			 });
			 
			});
            function changeCode(){
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->url('admin',['action'=>'getChechCode'])?>",
                    data: {"code":1},
                    dataType: "JSON",
                    async: false,
                    success: function (data) {
                        $('#checkCodeImage').attr('src',data);
                    },
                    error: function (res) {
                        //console.log(res);
                    }
                })
            }
		</script>
	</body>
</html>
