<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/TouchSlide.1.1.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/play-num-deal.js"></script>
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/api-request.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/common.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/audio.css">
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/nightbird.css">
<script type="text/javascript" src="<?php echo ROOT_PATH;?>webStyle/js/weui.min.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/weui.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<link rel="stylesheet" href="<?php echo ROOT_PATH;?>webStyle/css/jquery-weui.min.css">
<script src="<?php echo ROOT_PATH;?>webStyle/js/jquery-weui.min.js"></script>
<script src="<?php echo ROOT_PATH;?>webStyle/js/city-picker.js"></script>
<title>音频课程</title>
<style>
    body{
        padding-bottom: 60px;
    }
    .return_home{
	       display:none;
    }

</style>
<html>
<body>

    <div class="londing_gif1" >
        <img src="<?php echo ROOT_PATH;?>webStyle/images/londing.gif" alt="">
    </div>
    <div class="bgb"></div>
    <div class="voice_details">
        <div class="select_top">
            <?php foreach ($data as $k => $v){?>
                <a href="javascript:;" id="<?php echo  $v['id']?>" onclick="getCategory(<?php echo $v['id']?>,2);" <?php if($k==0){?>class="select_on"<?php }?> class=""><?php echo $v['name'];?></a>
            <?php }?>
        </div>
         <a class="goto_search" href="<?php echo $this->url('web-common',array('controller' => 'search','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/seek.png" alt="">更多品牌智慧</a>
        <div class="classify" id="classifys">
            <!-- <div> -->
            <!-- </div> -->
        </div>
        <div class="curriculums_table">课程列表</div>
        <div class="voice_curriculums_list" id="audio_curriculums_list">
            <ul>
            
            </ul>
        </div>
    </div>
    <input type="hidden" class="play" id="contrllor">
    <audio id="audio" -webkit-playsinline webkit-playsinline>
            <source src="" />
    </audio>
        <!-- 完善资料 -->
    <div class="perfect_data">
    	<div class="title">
    		可试听,请完善资料
    		<img class="close" src="<?php echo ROOT_PATH;?>webStyle/images/close_black.png" alt="">
    	</div>
    		<ul class="present_detail">
                <li>
                    <div>手机号码：<input id="mobile" type="text" placeholder="请输入您的手机号码" maxlength="11"></div>
                </li>
                <li>
                    <div>短信验证：<input id="captcha" type="text" placeholder="请输入短信验证码"><a href="javascript:(0);" class="gain_verification">获取验证码</a></div>


                </li>
                <li class="select">
                    <a href="javascript:(0);" id="showPicker">
                    <div>职位：
                    <span id='position' position_id="<?php echo $user['current_position_id'] ? $user['current_position_id'] : 0?>">
                      <?php echo $user['position_name']?>
                    </span></div></a>
                </li>
                <li class="select">
                    <div>地区：<input class="weui_input" type="text" value="<?php echo $user['region'] ? $user['region'] : '广东省 广州市';?>" id='region' style="text-align:right"/></div>
                </li>
            </ul>
            <div>
            <ul class="operation">

                <li><a href="javascript:(0);" class="affirm"><p>完成</p></a></li>
            </ul>
    		</div>
    </div>
    <!-- 验证码错误 -->
    <div class="verification_wrong" >
        <div>您输入的验证码有误！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 verification_wrong_close"><p>确认</p></a></li>
              
            </ul>
        </div>
    </div>
    <!-- 验证码错误 -->
    <div class="captcha_wrong" >
        <div id="comment">请输入正确的手机号！</div>
        <div>
            <ul>
                <li><a href="javascript:(0);"  class="font_color_055773 captcha_wrong_close"><p>确认</p></a></li>
            </ul>
        </div>
    </div>
    <footer class="home_footer">
        <ul>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'index','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/home.png" alt=""><p>首页</p></a></li>
            <li class=""><a href="javascript:void(0);"><img src="<?php echo ROOT_PATH;?>webStyle/images/voice_on.png" alt=""><p class="select_on">音频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'video','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/video.png" alt=""><p>视频</p></a></li>
            <li class=""><a href="<?php echo $this->url('web-common',array('controller' => 'user','action' => 'index'));?>"><img src="<?php echo ROOT_PATH;?>webStyle/images/mine.png" alt=""><p>我的</p></a></li>
        </ul> 
    </footer>
</body>   
</html>
<script>
var url_audio_list = sessionStorage.getItem('url_audio_list');
var audio_two_type = sessionStorage.getItem('audio_two_type');
var audio_one_type = sessionStorage.getItem('audio_one_type');
var url_name = "<?php echo $url_name?>";
// console.log(url_name);
if(url_audio_list == 2){
	 $('.voice_details .select_on').attr('class','');
	 $('.voice_details #'+audio_one_type).attr('class','select_on');
	 url_name = "";
}

if(url_name){
	$(".voice_details .select_top a").each(function(){
	    if($(this).html() == url_name){
		     url_id = $(this).attr('id');
	    	 $('.voice_details .select_on').attr('class','');
	    	 $('.voice_details #'+url_id).attr('class','select_on');
	    }
	});
}



$("#region").cityPicker({
   title: "选择省市",
   showDistrict: false,
 }); 
var is_perfect = '<?php echo $is_perfect?>';
var API_URL = '<?php echo API_URL?>';

document.ready = function () {
	if(is_perfect <= 0){
// 	    $('.perfect_data').show();
// 	    $('.bgb').show();
// 	    return false;
	}
}
var position = '<?php echo  isset($user['position']) && $user['position'] ? $user['position'] : ""?>'
var content = '<?php echo isset($user['position_id']) && $user['position_id'] ? $user['position_id'] : "";?>';
position = JSON.parse(position);
content = JSON.parse(content);
$('#showPicker').on('click', function () {
    weui.picker(position, {
        id: '#showPicker',
        defaultValue: [6],
        onChange: function (result) {
        	$(".picker_title").html("选择职位");            	
        },
        onConfirm: function (result) {
           var text = result[0];
           $("#position").html(content[text]);
           $("#position").attr('position_id',text);
        }
    });
});

$('.affirm').click(function(){
	var mobile = $('#mobile').val();
	var captcha = $('#captcha').val();
// 	var region_id = $('#region').attr('region_id');
	var region_id = $("#region").val();
	var position_id = $('#position').attr('position_id');
	if(!mobile){
		$('.captcha_wrong').show()
	    return false;
	}else{
	    if(!isMobile(mobile)){
	    	$('.captcha_wrong').show()
		    return false;
		}
	}
	if(!captcha){
		$("#comment").html('请输入短信验证码!');
		$('.captcha_wrong').show()
	    return false;
	}
	if(position_id == 0){
		$("#comment").html('请选择职位！');
		$('.captcha_wrong').show()
	    return false;
	}
	if(!region_id){
		$("#comment").html('请选择地区！');
		$('.captcha_wrong').show()
	    return false;
	}

	checkCaptcha();
});

var flat = true;
$(".gain_verification").on("click",function(){
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
// 	    alert('请输入正确的手机号码');
// 	    return;
		$('.captcha_wrong').show()
	    return false;
	}
// 	sendCaptcha();
// 	return false;
	if(flat){
    	sendCaptcha();
    	flat = false;
        var setTime;
        var time=60;
        $(".gain_verification").text('60s');
        $(".gain_verification").css("background-color","#cccccc");
        setTime=setInterval(function(){
            if(time<=0){
            	flat = true;
                clearInterval(setTime);
                 $(".gain_verification").text("获取验证码");
                $(".gain_verification").css("background-color","#d7000f");
                return;
            }
            time--;
            $(".gain_verification").text(time+'s');
//             $(".gain_verification").css("background-color","#cccccc");
        },1000);
    }
})

function sendCaptcha()
{
	var mobile = $('#mobile').val();
	if(!isMobile(mobile))
	{
// 	    alert('请输入正确的手机号码');
// 	    return false;
		$('.captcha_wrong').show()
	    return false;
	}
	var json = GetJson('SMSCode');
	json.q.a = 1;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
// 			$('#captcha').val(data.q.code);
// 			 var time=60;
// 		        setTime=setInterval(function(){
// 		            if(time<=0){
// 		            	flat = true;
// 		                clearInterval(setTime);
// 		                 $(".gain_verification").text("获取验证码");
// 		                $(".gain_verification").css("background-color","#d7000f");
// 		                return false;
// 		            }
// 		            time--;
// 		            $(".gain_verification").text(time+'s');
// 		            $(".gain_verification").css("background-color","#cccccc");
// 		        },1000);
		}
		else
		{
// 			alert(data.q.d);
			$("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}

function checkCaptcha(){
	var code = $('#captcha').val();
	if(!code){
	    alert("请输入验证码");
	    return false;
	}
	var json = GetJson('SMSCode');
	json.q.a = 2;
	json.q.type = 1;
	json.q.userId = '<?php echo $_SESSION['user_id']?>';
	json.q.mobile = $('#mobile').val();
	json.q.w = new Object();
	json.q.w.code = code;
	json.json = JSON.stringify(json);
	$.post(API_URL,json,function(data)
	{
		if(data.q.s == 0)
		{
			var mobile = $('#mobile').val();
// 			var region_id = $('#region').attr('region_id');
			var region_id = $("#region").val();
			var position_id = $('#position').attr('position_id');
			$.post("<?php echo $this->url('web-common',array('controller' => 'user','action' => 'ajaxUpdateUserInfo'));?>",{mobile : mobile,position_id:position_id,region_id:region_id},function(result){
				if(result.code == 200){
					$('.perfect_data').hide();
				    $('.bgb').hide();
				    window.location.href=window.location.href+"?id="+10000*Math.random();
				}else{
				    alert(result.message);
				}
			},'json');
		}else{
// 			if(data.q.s == "1003"){
// 				$('.verification_wrong').show()
// 			}
// 		    alert(data.q.d);
			$("#comment").html(data.q.d);
			$('.captcha_wrong').show()
		    return false;
		}
	},"json");
}

$('.captcha_wrong_close').click(function(){
    $('.captcha_wrong').hide();
})

$('.verification_wrong_close').click(function(){
    $('.verification_wrong').hide();
    $('.bgb').hide();
})

$('.close').click(function(){
    $('.bgb').hide();   
    $(".perfect_data").hide();

});


var play_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/player.png';
// console.log(play_img);
var pause_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/audio_pause_white.png';
var study_num_url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'ajaxAddStudyNum'));?>";
var one_category = $(".select_top a")[0].id;
var two_category = 0;
var page = 1;
var current_audio_id = 0;

if(url_name && url_id){
	getCategory(url_id);
}else if(url_audio_list == 2){
	getCategory(audio_one_type);
}else{
	getCategory(one_category);
}


// getAudioList(one_category,two_category,1);
$(".select_top a").on("click",function(){
	$(this).siblings().removeClass("select_on").end().addClass("select_on");
	one_category = $(this).attr('id');
	two_category = 0;
	getAudioList(one_category,two_category,1);
    $("#contrllor").addClass("play").removeClass("pause");
    audio.pause();
});

function getCategory(id,number_type){
	if(!number_type){
		number_type = 1;
	}
    $(".londing_gif1").show();
	$.post("<?php echo $this->url('web-common',array('controller' => 'Video','action' => 'getCategory'));?>",{id : id},function(result){
		$(".classify").html('');
		$(".classify").append("<span class='select_on' id="+0+" onclick='getAudioList("+id+','+0+','+1+")'>全部</span>");
		$.each(result,function(i,v){
		     $(".classify").append("<span id="+v.id+" onclick='getAudioList("+id+','+v.id+','+1+")'>"+v.name+"</span>");
		});
		$("#classifys span").on("click",function(){
			$(this).siblings().removeClass("select_on").end().addClass("select_on");
            $("#contrllor").addClass("play").removeClass("pause");
            audio.pause();

		});

// 		$(".classify").html('');
// 		$(".classify").append("<span class='select_on' id='0'>全部</span>");
// 		$.each(result,function(i,v){
// 		     $(".classify").append("<span id='"+v.id+"'>"+v.name+"</span>");
// 		});
// 		$(".classify span").on("click",function(){
// 			$(this).siblings().removeClass("select_on").end().addClass("select_on");
// // 			two_category = $(this).attr('id');
			
// 		});
	   if(number_type == 2){
		  url_audio_list = 0;
	   }
       if(url_audio_list == 2){
    	   getAudioList(audio_one_type,audio_two_type,1);
    	   $('#classifys .select_on').attr('class','');
    	   $('#classifys #'+audio_two_type).attr('class','select_on');
//     	   console.log(audio_one_type);
//     	   console.log(audio_two_type);
       }else{
    	   getAudioList(id,0,1);
       }
// 		console.log(audio_one_type);
// 		console.log(audio_two_type);
// 		console.log(url_audio_list);
	},'json');
}

var finished = false;
function getAudioList(one_category,two_category,type){
	sessionStorage.setItem('audio_one_type', one_category);
	sessionStorage.setItem('audio_two_type', two_category);
	if(one_category > 0){
    	 if (finished && type == 2) {
             return false;
         }
    	 $('.londing_gif').show();
         if(type == 1){
        	 page = 1;
         }
         finished = true;
         var url = "<?php echo $this->url('web-common', array('controller' => 'Audio', 'action' => 'getAudioList'))?>";
         $.post(url,
  	    	 {one_category:one_category,two_category:two_category,page:page},
  	    	 function(data){
  	    		 $('.londing_gif').hide();
  	  	    	 if(data.code == 200){
  	  	  	    	  var list = data.list;
   	  	    		  var dom = $("#audio_curriculums_list ul");
    	              var li = '';
    	                  if (list.length > 0) {
    	                      $.each(list,function(i,v){
    	                         var detail_img = "<?php echo ROOT_PATH;?>webStyle/images/gray_more.png";
    	                          if(v.type == 2){
    	                              var url = "<?php echo $this->url('web-common', array('controller' => 'audio', 'action' => 'details'))?>";
    	                              var ids = [v.id,2];
    	                              var image = "<?php echo ROOT_PATH.UPLOAD_PATH."/";?>"+v.image_path;
    	                              li += '<li>';
    	                              li += '<div class="cover"><img src="'+image+'" alt="">';
    	                              li += '<img audio_id='+v.first_audio_id+' class="player" onclick="play_audio(\''+v.full_path+'\','+v.time+',this)" src="'+play_img+'" alt="">';
    	                              li += '</div>';
                                      li += '<a href='+url+'?id='+ids+'&type='+2+'>';
    	                              li += '<div class="content">';
    	                              li += '<div>'+v.title+'</div>';
    	                              li += '<div class="teacher_name"></div>';
    	                              li += '<div class="information">';
    	                              li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
    	                              li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
    	                              li += '</div></div>';
    	                              li += '<div class="more">';
    	                              li += '<img src="'+detail_img+'" alt="">';
    	                              li += '</div></a></li>';
    	                          }else{
    	                        	 var video_view_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/video_view.png';
 	                                 var clock_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/clock.png';
 	                                 var date_img = "<?php echo ROOT_PATH;?>"+'webStyle/images/date.png';
    	                         	 var url = "<?php echo $this->url('web-common', array('controller' => 'audio', 'action' => 'details'))?>";
    	                         	 var time_img = '<?php echo ROOT_PATH;?>webStyle/images/clock.png';
    	                             var image = "<?php echo ROOT_PATH.UPLOAD_PATH."/";?>"+v.image_path;
    	                             var ids = [v.id,1];
    	                              li += '<li>';
    	                              li += '<div class="cover"><img src="'+image+'" alt="">';
    	                              li += '<img audio_id='+v.id+' class="player" onclick="play_audio(\''+v.full_path+'\','+v.time+',this)" src="'+play_img+'" alt="">';
    	                              li += '</div>';
                                      li += '<a href='+url+'?id='+ids+'&type='+1+'>';
    	                              li += '<div class="content">';
    	                              li += '<div>'+v.title+'</div>';
    	                              li += '<div class="teacher_name">'+v.teacher_name;
    	                              if(v.count != "0%"){
    	                                  if(v.count != "100%"){
    	                                 	 li += '<span class="ml40"><span>已播</span><span class=" font_color_055773">'+v.count+'</span></span>';
    	                                  }else{
    	                                 	 li += '<span class="ml40 ">已学完</span>';
    	                                  }
    	                              }
    	                              li += '</div>'
    	                              li += '<div class="information2">';
    	                              if(v.price == '仅限会员'){
    	                             	 li += '<div><span class="font_color_055773">'+v.price+'</span></div>';
    	                              }else{
    	                             	 li += '<div><span>非会员:</span><span>'+v.price+'</span></div>';
    	                              }
    	                              li += '<div class="counting"><span>会员:</span><span class="font_color_055773">'+v.original_price+'</span></div>';
    	                              li += '</div></div>';
    	                              li += '<div class="more">';
    	                              li += '<img src="'+detail_img+'" alt="">';
    	                              li += '</div></a></li>';
    	                          }
    	                      });
    	                      if(type == 1){
    	                     	 $('#audio_curriculums_list ul li').remove();
    	                      }  
    	                      $("#audio_curriculums_list ul").append(li);
    	                      finished = false;
    	                      page ++;
    	                  }else{
    	                	  if(type == 1){
 	    	                 	 $('#audio_curriculums_list ul li').remove();
 	    	                  }
        	              }
    	              }
    	              else {
    	                  if(type == 1){
    	                 	 $('#audio_curriculums_list ul li').remove();
    	                  }
    	              }
                      $(".londing_gif1").hide();  	  	  	     
         },'json');
	}
}

function play_audio(src,old_timem,obj){
    
	if(is_perfect <= 0){
	    $('.perfect_data').show();
	    $('.bgb').show();
	    return false;
	}
	var new_audio_id = $(obj).attr('audio_id');
	$('.player').attr('src',play_img);
    if(src){
    	var audio = document.getElementById("audio");
    	audio.currentTime=old_timem;

    	if(audio.src != src || new_audio_id != current_audio_id){
    		audio.src = src;
    		current_audio_id = new_audio_id;
            audio.currentTime=old_timem;
    		$("#contrllor").addClass("play");
        }
    	audio.loop = false; //歌曲循环
    	if ($("#contrllor").hasClass("play")) {
    		$("#contrllor").addClass("pause").removeClass("play");
    		audio.play();//开始播放
    		$(obj).attr('src',pause_img);
             $('.londing_gif1').show();
        }
    	else
    	{
    		$("#contrllor").addClass("play").removeClass("pause");
    	    audio.pause();
    	    $(obj).attr('src',play_img);
        }
    	play_num_deal(current_audio_id);//播放量处理
    }
}

var real_time;
audio.addEventListener("loadeddata", //歌曲一经完整的加载完毕( 也可以写成上面提到的那些事件类型)
    function() {
       var time = setInterval(function() {
        	var audio = document.getElementById("audio");
            var currentTime = audio.currentTime;  
            if(real_time < currentTime){
                $('.londing_gif1').hide();
            }/* else{
            	clearInterval(time);
            } */
//             console.log($('');
            real_time = audio.currentTime;
           
            
        }, 1000);
}, false);

setInterval("watchRecord(real_time,1)",3000);

var old_time;
function watchRecord(time,type){
	if(old_time == time){
		return false;
	}; 
	old_time = time;
	var url = "<?php echo $this->url('web-common', array('controller' => 'video', 'action' => 'ajaxWatchRecord'))?>";
	$.post(url,{id:current_audio_id,time:time,type:type},function(result) {
		if(result.code != 200){
			return false;
		}
	},'json');
}

function loadmore(obj){
    var scrollTop = $(obj).scrollTop();
    var scrollHeight = $(document).height();
    var windowHeight = window.innerHeight;
    if (scrollHeight - scrollTop - windowHeight<=50 ) {
    	one_category = $(".select_top .select_on")[0].id;
    	two_category = $("#classifys .select_on")[0].id
    	getAudioList(one_category,two_category,2);
    }
};

$(window).scroll(function (){
    if (loadmore) {
        loadmore($(this));
    }
});



$(document).ready(function(){ 
    var ua = navigator.userAgent.toLowerCase(); 
    if (/android/.test(ua)) {
        $(".home_footer ul li img").css({"margin-bottom":"4px"})
        $(".perfect_data").css("bottom","20%");
    }
    else{
        $(".perfect_data").css("top","50%");
    }

}); 



window.onload=function(){
    $(".londing_gif1").show();
    // alert(1);
}
</script>