<script src="<?php echo $this->basePath() . '/js/jedate.min.js'?>"  type="text/javascript"></script>
<link href="<?php echo $this->basePath() . '/css/jedate.css'?>" media="screen" rel="stylesheet" type="text/css">
<div class="page-header">
    <h1>
        财务列表
    </h1>
</div>

<div class="page-header">
    <form action="<?php echo $this->url('admin-finance', ['action' => 'index']) ?>">
    <!--        <a href="javascript:downloadUser();" class="btn btn-xs btn-primary">导出用户</a>-->
        <div style="float: right">
            交易方式：
            <select name="type">
                <option value="0">全部</option>
                <option value="1" <?php if ($type == 1) echo 'selected'; ?>>购买音频</option>
                <option value="2" <?php if ($type == 2) echo 'selected'; ?>>购买视频</option>
                <option value="3" <?php if ($type == 3) echo 'selected'; ?>>充值</option>
            </select>
            日期：
            <input class="date-icon" value="<?php echo $start_time?>" name="start_time" id="start_time" placeholder="开始日">
            <input class="date-icon" name="end_time" value="<?php echo $end_time?>" id="end_time" placeholder="截止日">
            搜索：
            <select name="search_type">
                <option value="1">交易流水号</option>
                <option value="2" <?php if ($search_type == 2) echo 'selected'; ?>>用户昵称</option>
            </select>
            <input type="text" name="keyword" value="<?php echo $keyword; ?>" placeholder="请输入关键字">
            <button class="btn btn-xs btn-primary" type="submit">搜索</button>
        </div>
    </form>
</div>

<!-- div.dataTables_borderWrap -->
<div>
    <table id="" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>时间</th>
                <th>金额</th>
                <th>用户手机</th>
                <th>用户昵称</th>
                <th>流水号</th>
                <th>财务类型</th>
                <th>交易方式</th>
                <th>支付方式</th>
            </tr>
        </thead>

        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $k =>$v) { ?>
                    <tr>
                        <input type="hidden" name="id<?php echo $k ?>" value="<?php echo $v->id ?>">
                        <td><?php echo $v->timestamp?></td>
                        <td><?php echo $v->cash ?></td>
                        <td><?php echo $v->mobile ?></td>
                        <td><?php echo $v->nick_name ?></td>
                        <td><?php echo $v->transfer_no ?></td>
                        <td><?php echo $v->income==1?"支出":"收入" ?></td>
                        <td>
                            <?php switch ($v->type){
                                case 1:
                                    echo "购买音频";
                                    break;
                                case 2:
                                    echo "购买视频";
                                    break;
                                case 3:
                                    echo "充值";
                                    break;
                                default:
                                    echo "";
                                    break;
                            } ?>
                        </td>
                        <td>
                            <?php switch ($v->payment_type){
                                case 1:
                                    echo "微信";
                                    break;
                                case 2:
                                    echo "支付宝";
                                    break;
                                default:
                                    echo "";
                                    break;
                            } ?>
                        </td>
                    </tr>
                <?php } ?>
            <?php endif; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <?php if(isset($where)){$condition['where'] = $where;} ?>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page', array('route' => 'admin-finance', 'condition' => $condition)); ?>
    </div>
</div>
</div>
</div>

<script type="text/javascript">
    var start ={
        dateCell:"#start_time",
        format:"YYYY-MM-DD",
        isinitVal:false,
        isTime:false, //isClear:false,
        maxDate:"",
        minDate:"",
        choosefun: function(datas){
            end.minDate = datas;
        }
    };
    jeDate(start);
    var end ={
        dateCell:"#end_time",
        format:"YYYY-MM-DD",
        isinitVal:false,
        isTime:false, //isClear:false,
        maxDate:"",
        minDate:"",
        choosefun: function(datas){
            start.maxDate = datas;
        }
    };
    jeDate(end);
</script>