<?php  $arr = $condition['where']; $type_arr = array('1'=>'音频', '2'=>'视频','3'=>'音频包','4'=>'视频包');?>
<style>
.select {
    border:1px solid #ccc;
    border-radius: 3px;
    width:115px;
}
.title-top div.con{
/*     border: 1px solid green; */
    width: 16%;
    text-align: center;
    font-size: 22px;
    display: inline-block;
}
.title-top div.margin{
    margin-left:4.5%;
}
</style>

<ul class="breadcrumb">
    <li><span>评论管理</span><span class="divider">/</span></li>
    <li> <a href="#">评论列表</a></li>
</ul>
<div class="pannel-body">
	<div class="box-content">
		<legend class="lg_title">
			<span>今天实时 （更新时间：<?php echo date('Y-m-d H:i:s');?>）：</span>
		</legend>
		<div class="title-top">
		  <div class="con" ><div><?php echo $today['count'];?></div><br/><div>今天评论数</div></div>
	      <div class="con margin" ><div><?php echo $today['user_count'];?></div><br/><div>今天评论用户数</div></div>
	      <div class="con margin" ><div><?php echo $today['admin_count'];?></div><br/><div>今天官方回复数</div></div>
	      <div class="con margin" ><div><?php echo $month['count'];?></div><br/><div>本月评论数</div></div>
	      <div class="con margin" ><div><?php echo $month['admin_count'];?></div><br/><div>本月官方回复</div></div>
		</div>
		<legend class="lg_title" style="margin-top: 27px;">
		</legend>
	</div>
<div class="pannel">
    <div class="row">
        <form class="form-horizontal" method="get" action="<?php echo $this->url('admin', array('controller' =>'Comment', 'action' => 'index'));?>">
            <div class="pull-right">
<!--             <div class="pull-left ml8" > -->
                <div class="btn-group marginTB-xs" style="display:inline-block;">
<!--                       <select name="teacher_id" size="1" class="select"> -->
<!--                         <option value="0" >全部所属老师</option> -->
                        <?php //if($teacher){foreach ($teacher as $v){?>
                     <!--     <option value="<?php //echo $v['id']?>" <?php //echo $arr['teacher_id']==$v['id']?'selected="selected"':''?>><?php //echo $v['name']?></option>
                        <?php// }}?>
                     </select> -->
<!--                 </div> -->
<!--             </div> -->
        <div class="pull-left ml8" >
                <div class="btn-group marginTB-xs" style="display:inline-block;margin:0 15px">
                  <select name="type" size="1" class="select">
                    <option value="0" >全部课程类型</option>
                    <option value="1" <?php echo $arr['type']==1?'selected="selected"':''?>>音频</option>
                    <option value="2" <?php echo $arr['type']==2?'selected="selected"':''?>>视频</option>
                     <option value="3" <?php echo $arr['type']==3?'selected="selected"':''?>>音频包</option>
                      <option value="4" <?php echo $arr['type']==4?'selected="selected"':''?>>视频包</option>
                  </select>
            </div>
        </div>
             <div class="pull-left ml8" style="position: relative">
                <input  style="width:160px;padding-left: 25px" name="keyword" type="text" class="input-small" placeholder="请输入课程名称" value="<?php echo $arr['keyword']?>">
                <i class="iconfont" style="position: absolute;top: 5px;left: 5px;">&#xe604;</i>
            </div>
        <div class="pull-left ml8" >
            <button type="submit" class="btn btn-info submit">搜索</button>
        </div>
        </div>
        </form>
    </div>
</div>
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-content">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>头像</th>
                <th>用户名</th>
                <th>课程类型</th>
                <th>课程名称</th>
                <th>所属老师</th>
                <th style="width:20%;">评论内容</th>
                <th>评论时间</th>
                <th>点赞数</th>
                <th>回复数</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
         <tbody>
            <?php foreach($list as $k=>$v){?>
            <tr>
                <th>
                    <img src="<?php echo $v['img_path']?($this->basepath().'/'.UPLOAD_PATH.'thumb/640X640X4/'.$v['img_path']):($v['head_icon']?$v['head_icon']:($this->basepath().'/images/portrait.png'));?>" width="100" height="100">
                </th>
                <th><?php echo$v['name'] ;?></th>
                <td><?php echo $v['type']?$type_arr[$v['type']]:'';?></td>
                <td><?php echo $v['type']>=3?$v['c_name']:$v['p_name'];?></td>
                <td><?php echo $v['t_name'];?></td>
                <td><?php echo $v['content'];?></td>
                <td><?php echo $v['timestamp'];?></td>
                <td><?php echo $v['praise_num'];?></td>
                <td><?php echo $v['comment_num'];?></td>
                <td id="statusDesc<?php echo $v['id'];?>"><?php echo $v['delete']==0?($v['is_top']==1?'置顶':'正常'):'隐藏';?></td>
                <td>
                     <a href="<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'details', 'id' => $v['id']));?>" class="btn btn-info">查看</a>
                     <input type="button" id="statusSwitch_<?php echo $v['id']?>" onclick="statusSwitch2('<?php echo $v['id']?>')"  class="btn <?php echo $v['is_top'] == 1 ? 'btn-warning' : 'btn-success';?>" value="<?php echo $v['is_top'] == 1 ? '取消置顶' : '置顶';?>" status="<?php echo $v['is_top'];?>" />
                     <input type="button" id="statusSwitch<?php echo $v['id']?>" onclick="statusSwitch('<?php echo $v['id']?>')"  class="btn <?php echo $v['delete'] == 1 ? 'btn-warning' : 'btn-success';?>" value="<?php echo $v['delete'] == 1 ? '显示' : '隐藏';?>" status="<?php echo $v['delete'];?>" />
                     <input type="button" class="btn btn-danger btn-sm"  onclick="submitDelete(<?php echo $v['id'];?>)" value="回复" />
                </td>
            </tr>
            <?php }?>
            </tbody>
        </table>
        <div class="page-control">
        <?php  echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin','condition'=>$condition));?>
       </div>
    </div>
      <!--/span-->
</div>
</div>
</div>
<div class="modal hide" id="myModal"  >
	<form action="<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'details','id'=>1));?>" method="post" id="abolish-family" class="form-horizontal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3 id="titles" style="text-align: center">回复评论</h3>
		</div>
	    <div class="">
            <div class="bootbox-body">
						<div style="float: left;width: 100%;">
							<div class="control-group">
    							<label class="control-label">评论时间：</label>
    							<div class="controls">
    								<label id="com_time"></label>
    							</div>
							</div>
							<div class="control-group">
    							<label class="control-label">用户名：</label>
    							<div class="controls">
    								<label  id="com_name"></label>
    							</div>
							</div>
							<div class="control-group">
								<label class="control-label">课程类型：</label>
								<div class="controls">
									<label id="com_type"></label>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">课程名称：</label>
								<div class="controls">
									<label id="com_pname"></label>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">评论内容：</label>
								<div class="controls">
									<label id="com_content"></label>
								</div>
							</div>
              <div class="control-group">
                  <label class="control-label">回复内容</label>
    			  <div class="controls">
                     <TEXTAREA rows="5" name="content" id="contents" style="width: 320px;" placeholder="回复内容" ></TEXTAREA>
                 </div>
<!-- 				<label id="conters"> 你确定要…？</label> -->
	    	</div>		
           </div>
        </div>
		<div class="modal-footer">
			<input type="hidden" name="id" value="" id ="shop_id">
			<input type="hidden" name="ajax" value="2017" >
			<a href="#" class="btn" data-dismiss="modal">取消</a>
<!-- 			onclick="submitDelete()" -->
			<input type="submit" name="s" class="btn btn-primary"   value="确定">
		</div>
	</form>
</div>
<script>
// function deleteModal(id){
// 	$('#shop_id').val(id);
// // 	$('#type').val(id);
// 	$('#myModal').modal('show');
// }

function submitDelete(id){
//    var id = $('#shop_id').val();
   var url = '<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'details2'));?>'+'/i'+id;
   $.post(url,{},function(data){
// 	   console.log(data.info.name);
	    if(data.code != 200){
// 	    	$('#myModal').modal('hide');
		    alert(data.msg);	return;
	    }else{
		    item = data.info;
		    $('#com_time').text(item.timestamp);
		    $('#com_name').text(item.name);
		    if(item.type == 1){
		    	 $('#com_type').text('音频');
		    }else if(item.type == 2){
		    	$('#com_type').text('视频');
		    }else if(item.type == 3){
		    	$('#com_type').text('音频包');
		    }else if(item.type == 4){
		    	$('#com_type').text('视频包');
		    }
		    if(item.type>=3){
		    	$('#com_pname').text(item.c_name);
		    }else{
		    	$('#com_pname').text(item.p_name);
		    }
		    $('#com_content').text(item.content);
		    $('#shop_id').val(id);
		    $('#myModal').modal('show');
// 	    	location.reload();
// 	        $('#s'+type+subscript).hide();
// 	        $('#shop'+type+shop_id).append('<td ></td>');
	    }
	   },'json');
}
</script>
<script>
var statusSwitchUrl2 = '<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'ajaxTop'));?>';
var lock = false;
function statusSwitch2(id) {
	if (lock) {
		return false;
	}
	lock = true;
	var dom = $("#statusSwitch_" + id);
	var status = dom.attr("status");
	var set_status = status == 1 ? 2 : 1;
	if (typeof(statusSwitchUrl2) != "undefined" && statusSwitchUrl2) {
		$.post(statusSwitchUrl2, {id: id, status: set_status}, function (data) {
		    if(data.code != 200){
		    	alert(data.message);return;
			}
			if (status == 2) {
				dom.attr("status", set_status);
				dom.val("取消置顶");
// 				dom.addClass("btn-success");
// 				dom.removeClass("btn-warning");
				dom.removeClass("btn-success");
				dom.addClass("btn-warning");
				if(data.status == 1){
				    $("#statusDesc" + id).text("隐藏");
				}else{
					 $("#statusDesc" + id).text("置顶");
				}
			}
			else {
				dom.attr("status", set_status);
				dom.val("置顶");
				dom.addClass("btn-success");
				dom.removeClass("btn-warning");
// 				dom.removeClass("btn-success");
// 				dom.addClass("btn-warning");
				if(data.status == 1){
				    $("#statusDesc" + id).text("隐藏");
				}else{
					 $("#statusDesc" + id).text("正常");
				}
// 				$("#statusDesc" + id).text("置顶");
			}
			lock = false;
		}, 'json');
	}
}
</script>
<script type="text/javascript">
var statusSwitchUrl = '<?php echo $this->url('admin', array('controller' => 'Comment', 'action' => 'ajaxDelete'));?>';
var lock = false;
function statusSwitch(id) {
	if (lock) {
		return false;
	}
	lock = true;
	var dom = $("#statusSwitch" + id);
	var status = dom.attr("status");
	var set_status = status == 1 ? 0 : 1;
	if (typeof(statusSwitchUrl) != "undefined" && statusSwitchUrl) {
		$.post(statusSwitchUrl, {id: id, status: set_status}, function (data) {
		    if(data.code != 200){
		    	alert(data.message);return;
			}
// 			console.log(set_status);
			if (set_status == 0) {
				dom.attr("status", set_status);
				dom.val("隐藏");
				dom.addClass("btn-success");
				dom.removeClass("btn-warning");
// 				dom.removeClass("btn-success");
// 				dom.addClass("btn-warning");
				if(data.is_top == 1){
				    $("#statusDesc" + id).text("置顶");
				}else{
					 $("#statusDesc" + id).text("正常");
				}
// 				$("#statusDesc" + id).text("显示");//"隐藏"
			}
			else {
				dom.attr("status", set_status);
				dom.val("显示");
				dom.removeClass("btn-success");
				dom.addClass("btn-warning");
// 				dom.addClass("btn-success");
// 				dom.removeClass("btn-warning");
				$("#statusDesc" + id).text("隐藏");
			}
			lock = false;
		}, 'json');
	}
}
</script>

<script type="text/javascript">
// function ajaxDelete(id,type){
//	var url = '<?php echo $this->url('admin', array('controller' => 'User', 'action' => 'ajaxDelete'));?>';
// 	$.post(url,{id:id,type:type},function(data){
// 	    if(data.code==200){
// 		    if(type ==1){//启用
// 		    	$('#id-'+id).html('禁用');
// 		    	$('#id-'+id).attr('onclick','ajaxDelete('+id+',2)');
// 		    	$('#id-'+id).attr('class','btn btn-warning');
// 		    }else{
// 		    	$('#id-'+id).html('启用');
// 		    	$('#id-'+id).attr('onclick','ajaxDelete('+id+',1)');
// 		    	$('#id-'+id).attr('class','btn btn-success');
// 		    }
// 		    return;
// 	    }
// 	    alert(data.message);return;
// 	},'json');
// }
// function deleteSocial(id){
// 	 $('#social_id').val(id);
// // 	$('#remark3').val(remark);
// 	$('#myModal').modal('show');
// }
// function submitDelete(){
// // 	$('#myModal').modal('hide');
//     $('#abolish-family').submit();
// 	$('#myModal').modal('toggle');
// }
</script>